monitoring/pom.xml
monitoring/src/main/java/CloudMonitoringAuthSample.java
monitoring/src/test/java/CloudMonitoringAuthSampleTest.java
pom.xml

Move java cloud monitoring sample into github.

---

bigquery/pom.xml
bigquery/src/main/java/com/google/cloud/bigquery/samples/ListDatasetsProjects.java
bigquery/src/test/java/com/google/cloud/bigquery/samples/test/ListDatasetsProjectsTest.java
monitoring/pom.xml
monitoring/src/test/java/CloudMonitoringAuthSampleTest.java
pom.xml

From this page: https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects

Move in bigquery quickstart sample.

---

cloud-storage/json-api/pom.xml
cloud-storage/json-api/src/main/java/StorageSample.java
cloud-storage/json-api/src/test/java/StorageSampleTest.java

Move in the sample from [its own repo](https://github.com/GoogleCloudPlatform/cloud-storage-docs-json-api-examples/tree/master/java-example), modify to use Application Default Credentials, and add samples for uploading and deleting objects

Add samples for cloud storage json api.

---

bigquery/src/main/java/com/google/cloud/bigquery/samples/GettingStarted.java
bigquery/src/test/java/com/google/cloud/bigquery/samples/test/GettingStartedTest.java

Also, tweak it so it's using ADC, and the synchronized query, since the doc says
it does.
This doc:
https://cloud.google.com/bigquery/bigquery-api-quickstart

Move test over from other repo.

---

pom.xml
storage/json-api/src/main/java/StorageSample.java

This is necessary when using a service account via setting the
GOOGLE_APPLICATION_CREDENTIALS environment variable.
Also - add a compiler target version, so that maven doesn't default to trying to compile against 1.3.

Add scopes if required.

---

appengine/appidentity/.gitignore
appengine/appidentity/README.md
appengine/appidentity/pom.xml
appengine/appidentity/src/main/java/com/example/appengine/appidentity/IdentityServlet.java
appengine/appidentity/src/main/webapp/WEB-INF/appengine-web.xml
appengine/appidentity/src/main/webapp/WEB-INF/web.xml
appengine/appidentity/src/test/java/com/example/appengine/appidentity/IdentityServletTest.java
pom.xml

This moves the first example from  https://cloud.google.com/appengine/docs/java/appidentity/ to GitHub.
I also add a simple unit test to at least make sure this code builds &
runs.  Since this sample just wraps:
ApiProxy.getCurrentEnvironment()
.getAttributes()
.get("com.google.appengine.runtime.default_version_hostname"))
there isn't really much more we can test in this example.
I will move the other examples from that page over in later PRs.

Add an App Identity example.

---

appengine/appidentity/README.md

The gcloud command was getting the project argument when I was passing
it in as -Dgcloud_project. After changing to -Dgcloud.gcloud_project it
now deploys to the project I specify there. I hadn't noticed this until
I had modified my gcloud config and deployments started going to the
wrong project.

Fix project parameter in App Identity README.

---

appengine/appidentity/pom.xml
appengine/appidentity/src/main/java/com/example/appengine/appidentity/UrlShortener.java
appengine/appidentity/src/main/java/com/example/appengine/appidentity/UrlShortenerServlet.java
appengine/appidentity/src/main/webapp/WEB-INF/web.xml

This sample is copied almost exactly from
https://cloud.google.com/appengine/docs/java/appidentity/#asserting_identity_to_google_apis
I also add a servlet for the sample code so that it can be more easily
demonstrated and manually tested.

Add App Identity example to assert identity to Google APIs.

---

appengine/mailgun/src/main/java/com/example/managedvms/mailgun/MailgunServlet.java
appengine/mailgun/src/main/webapp/index.html

Add a simple email example to Mailgun

Add a simple email example to Mailgun

---

appengine/appidentity/src/main/java/com/example/appengine/appidentity/IdentityServlet.java
appengine/appidentity/src/main/java/com/example/appengine/appidentity/UrlShortener.java
appengine/appidentity/src/main/java/com/example/appengine/appidentity/UrlShortenerServlet.java

I checked for style errors using the following command:
mvn checkstyle:checkstyle \
-Dcheckstyle.config.location=google_checks.xml \
-Dcheckstyle.consoleOutput=true

Fix style errors in the App Identity samples.

---

managedvms/sparkjava/pom.xml
managedvms/sparkjava/src/main/java/com/google/appengine/sparkdemo/Main.java
managedvms/sparkjava/src/main/java/com/google/appengine/sparkdemo/ResponseError.java
managedvms/sparkjava/src/main/java/com/google/appengine/sparkdemo/User.java
managedvms/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserController.java
managedvms/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserService.java

Fix checkstyle issues in SparkJava demo

---

managed_vms/cloudsql/src/main/java/com/example/managedvms/cloudsql/CloudSqlServlet.java
managed_vms/cloudstorage/src/main/java/com/example/managedvms/cloudstorage/UploadServlet.java
managed_vms/datastore/pom.xml
managed_vms/datastore/src/main/java/com/example/managedvms/datastore/DatastoreServlet.java

Add comments to datastore, and encrypt user ip
Add comments to cloudsql, and encrpyt user ip

Add comments to cloudstorage

---

managed_vms/sparkjava/src/main/java/com/google/appengine/sparkdemo/Main.java
managed_vms/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserService.java
managed_vms/sparkjava/src/test/java/com/google/appengine/sparkdemo/UserControllerTest.java
managed_vms/sparkjava/src/test/java/com/google/appengine/sparkdemo/UserServiceTest.java

Fixes #85 
Each run of the UserControllerTest now creates a unique kind so that multiple builds occurring at once won't cause the integration tests to fail.

Fix flaky test

---

managed_vms/sendgrid/pom.xml
managed_vms/sendgrid/src/main/java/com/example/managedvms/sendgrid/SendEmailServlet.java
managed_vms/twilio/pom.xml
managed_vms/twilio/src/main/java/com/example/managedvms/twilio/SendSmsServlet.java

Fix checkstyle in twilio and sendgrid samples.

---

datastore/README.md
datastore/pom.xml
datastore/src/main/java/com/google/datastore/snippets/Concepts.java
datastore/src/main/java/com/google/datastore/snippets/TaskList.java
pom.xml

Datastore Concepts snippets and Getting Started app

---

datastore/pom.xml
datastore/src/main/java/com/google/datastore/snippets/Concepts.java

Fixes #95 and also makes minor updates to use the latest gcloud-java features.
/cc @aozarov

Set source/target to jdk 1.7 and use latest gcloud-java release features

---

managed_vms/sparkjava/pom.xml
managed_vms/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserController.java
managed_vms/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserService.java
managed_vms/sparkjava/src/test/java/com/google/appengine/sparkdemo/UserControllerTest.java
managed_vms/sparkjava/src/test/java/com/google/appengine/sparkdemo/UserServiceTest.java

Consistency issues were likely involved with #85.
/cc @aozarov mind taking a look to check that consistency bugs are now fixed?

Fix consistency issue with sparkjava demo tests.

---

pom.xml

The `appengine.version` overrides the version tag for the instance
rather than the SDK version. Changing to `appengine.sdk.version` fixes
the errors we encounter when deploying.

Fix error deploying hello world.

---

appengine/helloworld/pom.xml
pom.xml
storage/xml-api/serviceaccount-appengine-sample/pom.xml
taskqueue/deferred/pom.xml
unittests/pom.xml

We don't have many samples that use the appengine-maven-plugin anymore, but those that do now should all inherit from the root pom.xml.
CC @ludoch @shun-fan

Update App Engine SDK version.

---

storage/json-api/pom.xml
storage/json-api/src/test/java/StorageSampleTest.java

Getting ready to use shared java-repo-tools configuration.
I also convert the assertions to use [truth](http://google.github.io/truth/).
Since I find it more readable to get a list of object names first
instead of manually looping through, I also update the sample to use
Java 8 lambdas to extract these object names. The sample is used here:
https://cloud.google.com/storage/docs/json_api/v1/json-api-java-samples
which does not indicate the required Java version.
Depends on https://github.com/GoogleCloudPlatform/java-docs-samples/pull/107

Checkstyle fixes in Cloud Storage JSON API tests.

---

monitoring/pom.xml
monitoring/src/test/java/CloudMonitoringAuthSampleTest.java

Changed to using Truth for assertions.

Checkstyle fixes for Cloud Monitoring sample tests.

---

appengine/.gitignore
appengine/mailgun/pom.xml
appengine/mailgun/src/main/java/com/example/appengine/mailgun/MailgunServlet.java
appengine/mailgun/src/main/webapp/WEB-INF/appengine-web.xml
appengine/mailgun/src/main/webapp/WEB-INF/web.xml
appengine/mailgun/src/main/webapp/index.html
pom.xml

Add gitignore for appengine dir

Add appengine mailgun sample

---

storage/storage-transfer/pom.xml
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/AwsRequesterTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/NearlineRequesterTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/RequestCheckerTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/TransferClientCreatorTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/TransferJobUtilsTest.java
storage/xml-api/cmdline-sample/pom.xml
storage/xml-api/cmdline-sample/src/test/java/StorageSampleTest.java

Depends on https://github.com/GoogleCloudPlatform/java-docs-samples/pull/110

Checkstyle fixes for Cloud Storage transfer sample.

---

datastore/pom.xml
managed_vms/cloudstorage/README.md
managed_vms/cloudstorage/src/main/java/com/example/managedvms/cloudstorage/UploadServlet.java
managed_vms/sparkjava/pom.xml

Updates the gcloud-java version in the remaining two gcloud-java samples.  Also cleans up the managed_vms/cloudstorage sample and docs.
I tested the cloudstorage sample manually both locally and in deployment.

Update gcloud-java version to 0.1.5 and clean up cloudstorage sample

---

unittests/src/test/java/com/google/appengine/samples/AuthenticationTest.java
unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
unittests/src/test/java/com/google/appengine/samples/LocalCustomPolicyHighRepDatastoreTest.java
unittests/src/test/java/com/google/appengine/samples/LocalDatastoreTest.java
unittests/src/test/java/com/google/appengine/samples/LocalHighRepDatastoreTest.java
unittests/src/test/java/com/google/appengine/samples/LocalMemcacheTest.java
unittests/src/test/java/com/google/appengine/samples/MyFirstTest.java
unittests/src/test/java/com/google/appengine/samples/OAuthTest.java
unittests/src/test/java/com/google/appengine/samples/ShortTest.java
unittests/src/test/java/com/google/appengine/samples/TaskQueueConfigTest.java
unittests/src/test/java/com/google/appengine/samples/TaskQueueTest.java

This requires an update to the documentation at https://cloud.google.com/appengine/docs/java/tools/localunittesting. I will ping a tech writer to restage after this merges.

Checkstyle fix for unittests samples.

---

.gitmodules
google-checks.xml
managed_vms/async-rest/pom.xml
managed_vms/async-rest/src/main/java/com/google/appengine/demos/DumpServlet.java
managed_vms/async-rest/src/main/java/com/google/appengine/demos/asyncrest/AbstractRestServlet.java
managed_vms/async-rest/src/main/java/com/google/appengine/demos/asyncrest/AsyncRestServlet.java
managed_vms/async-rest/src/main/java/com/google/appengine/demos/asyncrest/SerialRestServlet.java
pom.xml

Reverts GoogleCloudPlatform/java-docs-samples#119
Requiring `--recursive` to clone is no good. We reference a regular clone in many places in the docs.

Revert "Checkstyle fixes for async-rest sample."

---

google-checks.xml
monitoring/v3/README.md
monitoring/v3/pom.xml
monitoring/v3/src/test/java/CreateCustomMetricTest.java
monitoring/v3/src/test/java/ListResourcesTest.java
pom.xml
suppressions.xml

In this case rolling back (the git submodule which started applying checkstyle to test classes) was the correct fix for the build breakage, but I've also fixed the checkstyle issues.
CC @lesv

Fix checkstyle in monitoring v3 sample.

---

managed_vms/async-rest/pom.xml
managed_vms/async-rest/src/main/java/com/google/appengine/demos/DumpServlet.java
managed_vms/async-rest/src/main/java/com/google/appengine/demos/asyncrest/AbstractRestServlet.java
managed_vms/async-rest/src/main/java/com/google/appengine/demos/asyncrest/AsyncRestServlet.java
managed_vms/async-rest/src/main/java/com/google/appengine/demos/asyncrest/SerialRestServlet.java

Tested manually by deploying to http://async-rest-test-dot-java-docs-samples-swast-1.appspot.com/.
When doing so, I noticed that the `mvn gcloud:deploy` command would not run, so I updated the POM to the latest version of the gcloud maven plugin, too.
Just a cherry pick of https://github.com/GoogleCloudPlatform/java-docs-samples/pull/119, this time without the `git submodule` piece.

Checkstyle fixes for async-rest sample.

---

appengine/appidentity/pom.xml
managed_vms/analytics/pom.xml
managed_vms/async-rest/pom.xml
managed_vms/cloudstorage/pom.xml
managed_vms/datastore/pom.xml
managed_vms/disk/pom.xml
managed_vms/extending-runtime/pom.xml
managed_vms/helloworld/pom.xml
managed_vms/mailgun/pom.xml
managed_vms/memcache/pom.xml
managed_vms/sendgrid/pom.xml
managed_vms/sparkjava/pom.xml
managed_vms/static-files/pom.xml
managed_vms/twilio/pom.xml

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/126.
I used this script, slightly modified from one Shun sent out to work on my Linux workstation instead of Mac.
```
#!/bin/bash
#
#
#
echo 'new version is:'$1
echo "${@:2}"
for path in "${@:2}"
do
if [[ ! ( $path == */pom.xml ) ]] ; then
>&2 echo "$path is not a pom.xml file."
exit
fi
echo "Processing: $path"
lineOfArtifactId=`grep -n '<artifactId>gcloud-maven-plugin</artifactId>' $path | cut -f1 -d:`
echo $lineOfArtifactId
lineOfVersion=$(($lineOfArtifactId+1))
echo $lineOfVersion
sed -i "$lineOfVersion"'s:<version>.*</version>:<version>'"$1"'</version>:' $path
done
```
I used ZSH to get all the pom.xml files in subdirectories with`~/bin/update-gcloud.sh "2.0.9.101.v20160316" **/*/pom.xml`

Update gcloud Maven plugin.

---

storage/json-api/src/test/java/StorageSampleTest.java

The previous test bucket no longer seems to exist or is no longer
publicly accessible.
"mvn test" is currently broken. This change should fix that.

Change unit test bucket to "cloud-samples-test".

---

.travis.yml
monitoring/v3/README.md
monitoring/v3/src/main/java/CreateCustomMetric.java
monitoring/v3/src/main/java/ListResources.java
monitoring/v3/src/test/java/CreateCustomMetricTest.java
monitoring/v3/src/test/java/ListResourcesTest.java

Also fix error in README and change test project to this repo's project.

Fix style, Use Same Test Project

---

java-repo-tools/README.md
java-repo-tools/google-checks.xml

Sorry there's so many commits. I missed the step of merging histories (to avoid future conflicts when pulling down changes) when I first added the `java-repo-tools/` subtree.

Update java repo tools

---

storage/json-api/src/main/java/StorageSample.java
storage/json-api/src/test/java/StorageSampleTest.java

See [b/27498754](http://b/27498754)

Specify file length, for performance.

---

datastore/pom.xml
datastore/src/main/java/com/google/datastore/snippets/Concepts.java
datastore/src/main/java/com/google/datastore/snippets/TaskList.java

Note: this PR won't build until 0.1.7 is available on Maven.  I will rerun Travis once the artifacts are pushed.
/cc @aozarov

Changes for v1beta3

---

datastore/src/main/java/com/google/datastore/snippets/TaskList.java

Cleanup error handling/docs in TaskList

---

appengine/README.md
appengine/appidentity/README.md
appengine/helloworld/README.md
appengine/mailgun/README.md
appengine/sendgrid/README.md
appengine/twilio/README.md
managed_vms/README.md
managed_vms/sendgrid/README.md
managed_vms/twilio/README.md

These are linked to from https://cloud.google.com/java/, so we should
have a more welcoming landing page than the existing list of folders.
CC @lesv @shun-fan

Improve READMEs for App Engine samples.

---

managed_vms/sparkjava/README.md

Managed VMs is now App Engine flexible environment.
We should at least rename the header to reduce confusion when people arrive here from https://cloud.google.com/java/.

Rename mvm to flexible environment in SparkJava sample.

---

managed_vms/helloworld/pom.xml

This sample is linked to from https://cloud.google.com/java/ as "App Engine flexible environment for Java 7" https://cloud.google.com/appengine/docs/flexible/java/hello-world. We should make sure it really is compatible with Java 7 by making sure we use that compiler instead of Java 8.

Change Hello World compiler to Java 7.

---

datastore/pom.xml
datastore/src/main/java/com/google/datastore/snippets/Concepts.java
datastore/src/main/java/com/google/datastore/snippets/TaskList.java
managed_vms/cloudstorage/pom.xml
managed_vms/cloudstorage/src/main/java/com/example/managedvms/cloudstorage/UploadServlet.java
managed_vms/datastore/pom.xml
managed_vms/datastore/src/main/java/com/example/managedvms/datastore/DatastoreServlet.java
managed_vms/sparkjava/pom.xml
managed_vms/sparkjava/src/main/java/com/google/appengine/sparkdemo/Main.java
managed_vms/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserService.java
managed_vms/sparkjava/src/test/java/com/google/appengine/sparkdemo/UserServiceTest.java

Update gcloud-java dependency and imports

---

appengine/urlfetch/src/main/java/com/example/appengine/UrlFetchServlet.java
appengine/urlfetch/src/main/webapp/main.jsp

Add a more complex example as well.

---

.travis.yml

This will keep Travis from building twice for pull requests. (Currently
it builds once for the branch push and again for the pull request.)

Limit Travis to master branch.

---

compute/sendgrid/README.md
compute/sendgrid/pom.xml
compute/sendgrid/src/main/java/com/example/compute/sendgrid/SendEmailServlet.java

Add a compute engine sendgrid sample, with readme

Add compute sendgrid example

---

appengine/memcache/src/main/java/com/example/appengine/memcache/MemcacheServlet.java

Update memcache sample with code from https://cloud.google.com/appengine/articles/best-practices-for-app-engine-memcache

Update memcache with code from appengine documentation

---

appengine/logs/README.md
appengine/logs/pom.xml
appengine/logs/src/main/java/com/example/appengine/logs/LogsServlet.java
appengine/logs/src/main/webapp/WEB-INF/appengine-web.xml
appengine/logs/src/main/webapp/WEB-INF/logging.properties
appengine/logs/src/main/webapp/WEB-INF/web.xml
pom.xml

Example from Logs (https://cloud.google.com/appengine/docs/java/logs/) moved to Github.  No tests yet.

Moved Logs sample to Github

---

appengine/search/.gitignore
appengine/search/README.md
appengine/search/google-checks.xml
appengine/search/pom.xml
appengine/search/src/main/java/com/example/appengine/search/DeleteServlet.java
appengine/search/src/main/java/com/example/appengine/search/DocumentServlet.java
appengine/search/src/main/java/com/example/appengine/search/IndexServlet.java
appengine/search/src/main/java/com/example/appengine/search/SearchServlet.java
appengine/search/src/main/java/com/example/appengine/search/Utils.java
appengine/search/src/main/webapp/WEB-INF/appengine-web.xml
appengine/search/src/main/webapp/WEB-INF/web.xml
appengine/search/src/test/java/com/example/appengine/search/DeleteServletTest.java
appengine/search/src/test/java/com/example/appengine/search/DocumentServletTest.java
appengine/search/src/test/java/com/example/appengine/search/IndexServletTest.java
appengine/search/src/test/java/com/example/appengine/search/SearchServletTest.java
appengine/search/src/test/java/com/example/appengine/search/UtilsTest.java
appengine/search/suppressions.xml
pom.xml

This is the code snippet on:
https://cloud.google.com/appengine/docs/java/search/
I added actual retry code with simple exponential back-offs.
I needed to add `SuppressionCommentFilter` to the `Checker` and `FileContentsHolder` to the `TreeWalker` in order to suppress warnings for import ordering. It might be worth adding to java-repo-tools, but it's out of scope of this PR.
@tswast @lesv I'd appreciate it if you could take a look.

Adding Search API sample code.

---

appengine/datastore/README.md
appengine/datastore/pom.xml
appengine/datastore/src/main/java/com/example/appengine/AbstractGuestbook.java
appengine/datastore/src/main/java/com/example/appengine/AbstractGuestbookServlet.java
appengine/datastore/src/main/java/com/example/appengine/Greeting.java
appengine/datastore/src/main/java/com/example/appengine/Guestbook.java
appengine/datastore/src/main/java/com/example/appengine/GuestbookServlet.java
appengine/datastore/src/main/java/com/example/appengine/GuestbookStrong.java
appengine/datastore/src/main/java/com/example/appengine/GuestbookStrongServlet.java
appengine/datastore/src/main/java/com/example/appengine/ProjectionServlet.java
appengine/datastore/src/main/java/com/example/time/Clock.java
appengine/datastore/src/main/java/com/example/time/SystemClock.java
appengine/datastore/src/main/java/com/example/time/testing/FakeClock.java
appengine/datastore/src/main/webapp/WEB-INF/appengine-web.xml
appengine/datastore/src/main/webapp/WEB-INF/datastore-indexes.xml
appengine/datastore/src/main/webapp/WEB-INF/web.xml
appengine/datastore/src/main/webapp/guestbook.jsp
appengine/datastore/src/test/java/com/example/appengine/GuestbookStrongTest.java
appengine/datastore/src/test/java/com/example/appengine/GuestbookTest.java
appengine/datastore/src/test/java/com/example/appengine/ProjectionServletTest.java
pom.xml

These samples are pulled from the [projection query](https://cloud.google.com/appengine/docs/java/datastore/projectionqueries) and [structuring for strong consistency](https://cloud.google.com/appengine/docs/java/datastore/structuring_for_strong_consistency) pages.
I will add additional code to this sample as I convert the other pages.
@lesv PTAL.

Add App Engine Datastore raw APIs sample.

---

appengine/datastore/src/test/java/com/example/appengine/GuestbookStrongTest.java
appengine/datastore/src/test/java/com/example/appengine/GuestbookTest.java
appengine/datastore/src/test/java/com/example/appengine/ProjectionTest.java
java-repo-tools/google-checks.xml

Also update checkstyle to allow 1-letter variable names, since it
doesn't make sense to give long names to something like "arbitrary
column A that doesn't actually mean anything".

Add sample for App Engine  Datastore setDistinct projection queries.

---

appengine/datastore/src/test/java/com/example/appengine/ProjectionTest.java

The START_EXCLUDE wasn't working when I tried to embed the function. I'm reverting to region tags to just include the same code as used in the existing sample.

Add region tags for projection query sample.

---

appengine/memcache/src/main/java/com/example/appengine/memcache/MemcacheAsyncCacheServlet.java
appengine/memcache/src/main/java/com/example/appengine/memcache/MemcacheBestPracticeServlet.java
appengine/memcache/src/main/java/com/example/appengine/memcache/MemcacheConcurrentServlet.java
appengine/memcache/src/main/java/com/example/appengine/memcache/MemcacheSyncCacheServlet.java
appengine/memcache/src/main/webapp/WEB-INF/appengine-web.xml
appengine/memcache/src/main/webapp/WEB-INF/web.xml

Adding servlets for the different memcache samples here
https://cloud.google.com/appengine/docs/java/memcache/

Update memcache sample with code from docs pages

---

appengine/requests/pom.xml
appengine/requests/src/test/java/com/example/appengine/requests/LoggingServletTest.java
appengine/requests/src/test/java/com/example/appengine/requests/RequestsServletTest.java

Removed some nonessential dependencies.

Added files via upload

---

appengine/datastore/README.md
appengine/datastore/src/test/java/com/example/appengine/EntitiesTest.java

Pulls out all samples from https://cloud.google.com/appengine/docs/java/datastore/entities.
@laurieaw @lesv PTAL

Add App Engine raw Datastore API Entity samples.

---

appengine/xmpp/README.md
appengine/xmpp/pom.xml
appengine/xmpp/src/main/java/com/example/appengine/xmpp/ErrorServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/MessageReceiverServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/MessageSenderServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/PresenceServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/SubscriptionServlet.java
appengine/xmpp/src/main/webapp/WEB-INF/appengine-web.xml
appengine/xmpp/src/main/webapp/WEB-INF/web.xml

Added a number of Servlet based examples for XMPP

Added samples showcasing XMPP

---

.travis.yml
travis.sh

Decryption of the service key can fail if Travis is building from a fork instead of a branch.
This replaces https://github.com/GoogleCloudPlatform/java-docs-samples/pull/185.
This addresses the first two items in https://github.com/GoogleCloudPlatform/java-docs-samples/issues/117 (ignore decryption error and skip tests in that case).

Allow Travis to continue build if decryption fails.

---

appengine/datastore/src/test/java/com/example/appengine/EntitiesTest.java

Writers are using this snippet in a slightly different way, so it needs to include the key name instead of using the auto ID.

Use key name in Datastore snippet.

---

appengine/guestbook-objectify/pom.xml
appengine/guestbook-objectify/src/test/java/com/example/guestbook/GreetingTest.java
appengine/guestbook-objectify/src/test/java/com/example/guestbook/GuestbookTestUtilities.java
appengine/guestbook-objectify/src/test/java/com/example/guestbook/SignGuestbookServletTest.java

@tmatsuo asked for a few tests.  They are trivial.
@tswast PTAL

Some Trivial Tests

---

appengine/channel/pom.xml
appengine/channel/src/main/java/com/example/appengine/channel/Game.java
appengine/channel/src/main/java/com/example/appengine/channel/GetTokenServlet.java
appengine/channel/src/main/java/com/example/appengine/channel/MoveServlet.java
appengine/channel/src/main/java/com/example/appengine/channel/OfyHelper.java
appengine/channel/src/main/java/com/example/appengine/channel/OpenedServlet.java
appengine/channel/src/main/java/com/example/appengine/channel/TicTacToeServlet.java
appengine/channel/src/main/webapp/WEB-INF/appengine-web.xml
appengine/channel/src/main/webapp/WEB-INF/logging.properties
appengine/channel/src/main/webapp/WEB-INF/view/index.jsp
appengine/channel/src/main/webapp/WEB-INF/web.xml
pom.xml

This is adapted from https://code.google.com/archive/p/java-channel-tic-tac-toe/

AppEngine Channel Example with Tic Tac Toe + Java

---

appengine/channel/src/main/java/com/example/appengine/channel/ChannelPresenceServlet.java
appengine/channel/src/main/java/com/example/appengine/channel/Game.java
appengine/channel/src/main/java/com/example/appengine/channel/TicTacToeServlet.java
appengine/channel/src/main/webapp/WEB-INF/appengine-web.xml
appengine/channel/src/main/webapp/WEB-INF/view/index.jsp
appengine/channel/src/main/webapp/WEB-INF/web.xml

Added tags for docs, and added a channel presence example.

Channel Example - Added tags and channel presence

---

appengine/multitenancy/README.md
appengine/multitenancy/pom.xml
appengine/multitenancy/src/main/java/com/example/appengine/Greeting.java
appengine/multitenancy/src/main/java/com/example/appengine/Guestbook.java
appengine/multitenancy/src/main/java/com/example/appengine/MultitenancyServlet.java
appengine/multitenancy/src/main/java/com/example/appengine/NamespaceFilter.java
appengine/multitenancy/src/main/java/com/example/appengine/OfyHelper.java
appengine/multitenancy/src/main/java/com/example/appengine/SignGuestbookServlet.java
appengine/multitenancy/src/main/java/com/example/appengine/SomeRequestServlet.java
appengine/multitenancy/src/main/java/com/example/appengine/UpdateCountsServlet.java
appengine/multitenancy/src/main/webapp/WEB-INF/appengine-web.xml
appengine/multitenancy/src/main/webapp/WEB-INF/logging.properties
appengine/multitenancy/src/main/webapp/WEB-INF/web.xml
appengine/multitenancy/src/main/webapp/guestbook.jsp
appengine/multitenancy/src/main/webapp/stylesheets/main.css
appengine/multitenancy/src/test/java/com/example/appengine/GreetingTest.java
appengine/multitenancy/src/test/java/com/example/appengine/GuestbookTestUtilities.java
appengine/multitenancy/src/test/java/com/example/appengine/SignGuestbookServletTest.java
pom.xml

Needs more testing code, and to make a few things runnable, rather than just compilable.  I'm open to argument about committing this. I'm going to create a needs more work issue.

Multitenancy

---

.travis.yml
README.md
java-repo-tools/pom.xml

Hopefully this works more reliably than coveralls.

Use codecov for coverage.

---

appengine/datastore/src/test/java/com/example/appengine/QueriesTest.java

From https://cloud.google.com/appengine/docs/java/datastore/retrieving-query-results

Add Datastore retrieving query samples.

---

appengine/datastore/src/test/java/com/example/appengine/ReadPolicyTest.java

Moved from https://cloud.google.com/appengine/docs/java/datastore/data-consistency.

Datastore Read Consistency Policy sample.

---

appengine/requests/src/test/java/com/example/appengine/requests/LoggingServletTest.java
appengine/taskqueue-push/README.md
appengine/taskqueue-push/pom.xml
appengine/taskqueue-push/src/main/java/com/example/appengine/taskqueue/push/Enqueue.java
appengine/taskqueue-push/src/main/java/com/example/appengine/taskqueue/push/Worker.java
appengine/taskqueue-push/src/main/webapp/WEB-INF/appengine-web.xml
appengine/taskqueue-push/src/main/webapp/WEB-INF/web.xml
appengine/taskqueue-push/src/main/webapp/index.html
appengine/taskqueue-push/src/test/java/com/example/appengine/taskqueue/push/WorkerTest.java
pom.xml

@lesv, @tswast 
Moves files into Github for Java Taskqueue example. 
Some minor corrections to Requests testing and configuration.  This should replace [Pull Request 205](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/205).

Move Push Taskqueue sample program to Github

---

.travis.yml
appengine/datastore/indexes-exploding/pom.xml
appengine/datastore/indexes-exploding/src/main/java/com/example/appengine/IndexesServlet.java
appengine/datastore/indexes-exploding/src/main/webapp/WEB-INF/appengine-web.xml
appengine/datastore/indexes-exploding/src/main/webapp/WEB-INF/datastore-indexes.xml
appengine/datastore/indexes-exploding/src/main/webapp/WEB-INF/web.xml
appengine/datastore/indexes-exploding/src/test/java/com/example/appengine/IndexesServletTest.java
appengine/datastore/indexes-perfect/pom.xml
appengine/datastore/indexes-perfect/src/main/java/com/example/appengine/IndexesServlet.java
appengine/datastore/indexes-perfect/src/main/webapp/WEB-INF/appengine-web.xml
appengine/datastore/indexes-perfect/src/main/webapp/WEB-INF/datastore-indexes.xml
appengine/datastore/indexes-perfect/src/main/webapp/WEB-INF/web.xml
appengine/datastore/indexes-perfect/src/test/java/com/example/appengine/IndexesServletTest.java
appengine/datastore/indexes/pom.xml
appengine/datastore/indexes/src/main/java/com/example/appengine/IndexesServlet.java
appengine/datastore/indexes/src/main/webapp/WEB-INF/appengine-web.xml
appengine/datastore/indexes/src/main/webapp/WEB-INF/datastore-indexes.xml
appengine/datastore/indexes/src/main/webapp/WEB-INF/web.xml
appengine/datastore/indexes/src/test/java/com/example/appengine/IndexesServletTest.java
appengine/datastore/src/test/java/com/example/appengine/IndexesTest.java
java-repo-tools/test-devserver.sh
pom.xml
travis.sh

Samples are moved from:
https://cloud.google.com/appengine/docs/java/datastore/indexes
Note: I add a new script `test-devserver.sh` to the testing config. This
script runs the `mvn appengine:devserver` plugin, waits for it to start,
then verifies that it gets a non-error response from the `/` path. I use
this to verify that the `datastore-indexes.xml` files are correct (by
disabling autoGenerate, the local devserver throws an error when a query
is used without the correct index defined, just as production does).
We should probably add any "hello world" or other projects to this
check, as well. Anywhere we say to run `mvn appengine:devserver`, it
would be good to test that it is correct.
@shun-fan @tmatsuo FYI for testing-related script.

Add Datastore indexes samples.

---

appengine/datastore/indexes-exploding/src/main/webapp/WEB-INF/datastore-indexes.xml
appengine/datastore/indexes/src/main/webapp/WEB-INF/datastore-indexes.xml

Makes it easier to filter with regex, since we can't put a region tag before
the  definition.

Datastore Samples: Change comment format for XML license header.

---

appengine/datastore/src/test/java/com/example/appengine/MetadataEntityGroupTest.java
appengine/datastore/src/test/java/com/example/appengine/MetadataKindsTest.java
appengine/datastore/src/test/java/com/example/appengine/MetadataNamespacesTest.java
appengine/datastore/src/test/java/com/example/appengine/MetadataPropertiesTest.java

From https://cloud.google.com/appengine/docs/java/datastore/metadataqueries.
@shun-fan @lesv PTAL.

Add App Engine Cloud Datastore metadata queries samples.

---

travis.sh

This is the first step in e2e testing the user journey for the [App
Engine quickstart][ae-quickstart].
This will verify that the App Engine Maven plugin works in this sample.
[ae-quickstart]: https://cloud.google.com/appengine/docs/java/quickstart

Add App Engine Hello World to devserver tests.

---

compute/mailjet/README.md
compute/mailjet/pom.xml
compute/mailjet/src/main/java/com/example/compute/mailjet/MailjetSender.java
compute/mailjet/src/test/java/com/example/compute/mailjet/MailjetSenderTest.java
managed_vms/analytics/pom.xml
managed_vms/async-rest/pom.xml
managed_vms/cloudstorage/pom.xml
managed_vms/cron/pom.xml
managed_vms/datastore/pom.xml
managed_vms/disk/pom.xml
managed_vms/extending-runtime/pom.xml
managed_vms/helloworld/pom.xml
managed_vms/mailgun/pom.xml
managed_vms/memcache/pom.xml
managed_vms/sendgrid/pom.xml
managed_vms/sparkjava/pom.xml
managed_vms/static-files/pom.xml
managed_vms/twilio/pom.xml
pom.xml

Update maven gcloud plugin version for managed vm samples
Update master pom

Add compute mailjet sample

---

storage/json-api/src/main/java/StorageFactory.java

See:
https://github.com/GoogleCloudPlatform/java-docs-samples/commit/dceeb5f29b588ad26c0083af18a56f36b032c2b2#commitcomment-17458371
@lesv @BrandonY PTAL

Add missing Application Default Credentials region tags.

---

appengine/datastore/src/test/java/com/example/appengine/QueriesTest.java

We were setting the filter twice (overwriting the first) rather than
using a composite filter.  This was causing the query results to be even
more surprising than we intending.
PTAL @halgrimur @shun-fan

Fix "surprising queries" samples.

---

appengine/datastore/src/test/java/com/example/appengine/IndexesTest.java
appengine/datastore/src/test/java/com/example/appengine/QueriesTest.java

Also, update most queries to be `setKeysOnly()`. This is a good practice
when we don't care about the property values (more efficient queries).
And it also demonstrates that the equality matching for `Entity` objects
only checks the key values, not the property values.
In response to discussion here: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/242#discussion_r63552558
@aozarov PTAL.

ae/datastore: Remove unnecessary `getKeys()` calls.

---

speech/grpc/pom.xml
speech/grpc/src/main/java/com/google/cloud/speech/grpc/demos/AudioRequestFactory.java
speech/grpc/src/main/java/com/google/cloud/speech/grpc/demos/NonStreamingRecognizeClient.java
speech/grpc/src/main/proto/google/speech/v1/cloud-speech.proto
speech/grpc/src/test/java/com/google/cloud/speech/grpc/demos/AudioRequestFactoryTest.java

added gcs read for audio file

---

managed_vms/sparkjava/src/main/appengine/Dockerfile

Using the ENTRYPOINT directive here would override the settings from the base docker image, breaking the configuration of the cloud debugger. Instead, CMD is the proper directive to use here to specify runtime arguments.

 Used CMD instead of ENTRYPOINT to set default runtime args

---

java-repo-tools/README.md
java-repo-tools/scripts/test-localhost.sh
travis.sh

Use test-localhost.sh script, added in GoogleCloudPlatform/getting-started-java#92

Update to latest java-repo-tools.

---

appengine/analytics/pom.xml
appengine/mailgun/pom.xml
appengine/mailjet/pom.xml
appengine/memcache/pom.xml
appengine/remote/remote-server/pom.xml
appengine/sendgrid/pom.xml
appengine/sendgrid/src/main/java/com/example/appengine/sendgrid/SendEmailServlet.java
appengine/twilio/pom.xml
appengine/twilio/src/main/java/com/example/appengine/twilio/SendSmsServlet.java

According to:
https://cloud.google.com/appengine/docs/java/runtime#Java_Introduction
"App Engine uses the Java Servlet 2.5 standard for web applications."
This updates these samples to use version 2.5. Annotations are not
supported. I see that the SendGrid servlet already has a web.xml
defined, so the annotation were redundant, anyway (and not functional).

App Engine standard env uses Java Servlets 2.5.

---

.travis.yml
speech/grpc/bin/speech-sample-async.sh
speech/grpc/bin/speech-sample-streaming.sh
speech/grpc/bin/speech-sample-sync.sh
travis.sh

Add shellcheck to Travis tests and fix existing shell lint errors.

---

language/README.md
language/analysis/README.md
language/analysis/pom.xml
language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeIT.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeTest.java
pom.xml

This sample shows how to use the Cloud Natural Language API to do entity
recognition. The client libraries are vendored in while we are in alpha.

Add Cloud Natural Language API Java sample.

---

speech/grpc/bin/speech-sample-async.sh
speech/grpc/bin/speech-sample-streaming.sh
speech/grpc/bin/speech-sample-sync.sh
speech/grpc/pom.xml
speech/grpc/src/main/java/com/examples/cloud/speech/AsyncRecognizeClient.java

Also, fix shell-check warnings in scripts.
Switches to the auth library recommended in the grpc documentation.
There was an old version of Guava being included from this, which I had
to exclude from the pom.
FYI @puneith 
@lesv Please take a look.

Update dependencies for Speech sample.

---

datastore/src/main/java/com/google/datastore/snippets/Concepts.java

Uses 'category' instead of 'type' as a property name. 'type' could cause confusion with data type.

Changes property name

---

bigquery/README.md

Users probably don't want to run all the system tests to try out the BigQuery samples.

Don't recommend running the tests at package time.

---

appengine/analytics/pom.xml
appengine/appidentity/pom.xml
compute/error-reporting/pom.xml
compute/sendgrid/pom.xml
java-repo-tools/pom.xml
managed_vms/analytics/pom.xml
managed_vms/cloudsql/pom.xml
managed_vms/cloudstorage/pom.xml
managed_vms/cron/pom.xml
managed_vms/datastore/pom.xml
managed_vms/disk/pom.xml
managed_vms/extending-runtime/pom.xml
managed_vms/helloworld/pom.xml
managed_vms/mailgun/pom.xml
managed_vms/mailjet/pom.xml
managed_vms/memcache/pom.xml
managed_vms/sendgrid/pom.xml
managed_vms/static-files/pom.xml
managed_vms/twilio/pom.xml
monitoring/v3/pom.xml
speech/grpc/pom.xml
storage/xml-api/cmdline-sample/pom.xml
storage/xml-api/serviceaccount-appengine-sample/pom.xml
taskqueue/deferred/pom.xml
unittests/pom.xml
vision/face-detection/pom.xml
vision/label/pom.xml
vision/landmark-detection/pom.xml
vision/text/pom.xml

This a workaround for a missing feature in the codehaus versions maven
plugin where is cannot update plugins directly, but it can detect when
there are new plugins and update the related properties. https://github.com/mojohaus/versions-maven-plugin/issues/8#issuecomment-225593578
I don't actually update anything (or I tried not to, anyway). I'll get dpebot to do that.
@lesv

Move plugin version definitions to properties.

---

bigquery/README.md
bigquery/src/main/java/com/google/cloud/bigquery/samples/AsyncQuerySample.java
bigquery/src/main/java/com/google/cloud/bigquery/samples/SyncQuerySample.java
bigquery/src/test/java/com/google/cloud/bigquery/samples/test/AsyncQuerySampleTest.java
bigquery/src/test/java/com/google/cloud/bigquery/samples/test/SyncQuerySampleTest.java

Switches all parameters to be supplied by properties rather than standard in.
Adds a flag to switch between legacy and standard SQL syntax.
@lesv PTAL.

BigQuery query samples: command line parameters.

---

CONTRIBUTING.md

Also, add a link to google-java-format, which should help with keeping
samples within the style guidelines.
For internal bug 28395294.
@lesv PTAL

Add style guidelines to CONTRIBUTING file.

---

.travis.yml
travis.sh

Use APT Addon for Gradle.

---

appengine/endpoints-frameworks-v2/backend/README.md
appengine/endpoints-frameworks-v2/backend/pom.xml
appengine/endpoints-frameworks-v2/backend/src/main/java/com/example/echo/Echo.java
appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/appengine-web.xml
appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/web.xml

Adds service management and auth dependencies and filters.
Uses exec-maven-plugin to generate the swagger spec.
Updates README for swagger generation.

Updates Endpoints Frameworks v2 sample with service management.

---

speech/grpc/pom.xml
speech/grpc/src/main/java/com/examples/cloud/speech/AsyncRecognizeClient.java
speech/grpc/src/main/java/com/examples/cloud/speech/StreamingRecognizeClient.java
speech/grpc/src/main/java/com/examples/cloud/speech/SyncRecognizeClient.java

Also, remove references to `OptionBuilder` since it was deprecated in
favor of `Option.builder()`. (Ideally I'd update this to use properties
like our other samples, but I think that might require some docs
updates, too.)
@lesv @puneith PTAL

Update Speech sample to gRPC v1.0.

---

language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeIT.java

Comparing to 1.0 should have been accurate since it is accurately represented in base-2 floating point, but I think the method is deprecated to discourage depending on a fragile thing due to rounding issues.

The `.isEqualTo()` method is deprecated for doubles.

---

speech/grpc/src/main/java/com/examples/cloud/speech/AsyncRecognizeClient.java

Replaces https://github.com/GoogleCloudPlatform/java-docs-samples/pull/283.

Stop hardcoding Netty dependency so example works on Android.

---

datastore/src/main/java/com/google/datastore/snippets/Concepts.java

We should probably link to the docs where this is included in https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/datastore. We can do that using the Python team's tool to find where samples are referenced.
Fixes #325.

datastore: Remove broken link in Concepts.java

---

appengine/taskqueue/pull/src/main/webapp/WEB-INF/queue.xml

Make sure to terminate `<writer-email>` with `</writer-email>` instead of `</user-email>`.
Have not created an issue since the fix is trivial.

Typo fixes runtime error - user_email => writer_email

---

vision/label/src/main/java/com/google/cloud/vision/samples/label/LabelApp.java
vision/landmark-detection/src/main/java/com/google/cloud/vision/samples/landmarkdetection/DetectLandmark.java

This adds a workaround to the remaining samples for an issue where
requests over a certain size will "succeed" but return an empty response
from the vision API when gzipped.
The workaround is to disable gzip compression. Most images should be in
compressed formats anyway, so it's not like we are saving much bandwidth
with it.

vision: Got empty response when requests are gzipped.

---

translate/README.md
translate/pom.xml
translate/src/main/java/com/google/cloud/translate/samples/Translate.java
translate/src/main/java/com/google/cloud/translate/samples/TranslateText.java
translate/src/test/java/com/google/cloud/translate/samples/TranslateTextTest.java

@lesv @tswast Please review translate sample.

Translate sample

---

translate/README.md
translate/src/main/java/com/google/cloud/translate/samples/TranslateText.java
translate/src/test/java/com/google/cloud/translate/samples/TranslateTextTest.java

@tswast @lesv Added one more feature of target language for list of supported languages

added supportedd languages for target language

---

vision/label/src/test/java/com/google/cloud/vision/samples/label/LabelAppIT.java

They were brittle, since they were looking for a specific error message,
which changed in the service.
@jerjou @lesv PTAL.

Fix Vision tests.

---

monitoring/v3/src/test/java/ListResourcesTest.java

Look for a type instead of description, since that should be less likely
to change.
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/361.
@waprin PTAL.

Fix monitoring tests.

---

translate/README.md

Update Translate API README.md

---

appengine/firebase-tictactoe/README.md
appengine/firebase-tictactoe/pom.xml
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/DeleteServlet.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/FirebaseChannel.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/Game.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/MoveServlet.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/ObjectifyHelper.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/OpenedServlet.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/TicTacToeServlet.java
appengine/firebase-tictactoe/src/main/webapp/WEB-INF/appengine-web.xml
appengine/firebase-tictactoe/src/main/webapp/WEB-INF/logging.properties
appengine/firebase-tictactoe/src/main/webapp/WEB-INF/view/firebase_config.jspf
appengine/firebase-tictactoe/src/main/webapp/WEB-INF/view/index.jsp
appengine/firebase-tictactoe/src/main/webapp/WEB-INF/web.xml
appengine/firebase-tictactoe/src/main/webapp/static/main.css
appengine/firebase-tictactoe/src/main/webapp/static/main.js

This is my first pass at this. I copied the channel api sample to start, so there might be some vestigial stuff from that. I'm going to make another clean-up pass on this, but I figured I'd send it out sooner rather than later so you can start taking a look.
FYI this is on GAE standard, just 'cuz the channel api was on standard. Think it's worth it to put it on flex?

Add GAE standard + firebase tictactoe sample

---

appengine/taskqueue-push/pom.xml

This sample was breaking in the latest release due to this missing
dependency.
@lesv PTAL

Add appengine-api-1.0-sdk dependency to taskqueue sample.

---

appengine/taskqueue-push/pom.xml
appengine/users/pom.xml

dpebot found another one when I tried to re-run the dependency updater this morning.
The users sample and the taskqueue-push sample were depending on the
appengine-maven-plugin, which used to depend transitively on the
appengine-api-1.0-sdk package, but it does not in the latest version.
These samples should not have been using the plugin as a dependency,
anyway.
@lesv PTAL

Add appengine-api-1.0-sdk dep to users sample.

---

appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/FirebaseChannel.java
appengine/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/TicTacToeServlet.java
appengine/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java
unittests/pom.xml
unittests/src/test/java/com/google/appengine/samples/LocalUrlFetchTest.java

Also add example test for testing things that incorporate a urlfetch. (I hit a lot of dead-ends before I found the documentation for how to do this...)

Add test to Firebase TicTacToe sample

---

compute/mailjet/pom.xml
compute/mailjet/src/main/java/com/example/compute/mailjet/MailjetSender.java

Update the mailjet example in compute to the last version.
* add exceptions
* change the pom

update mailjet in compute to version 4.0.5

---

travis.sh

(work in progress. Will assign when ready)

Travis - Only run tests that have changed

---

bigquery/cloud-client/README.md
bigquery/cloud-client/src/main/java/com/example/bigquery/SimpleApp.java
bigquery/cloud-client/src/test/java/com/example/bigquery/SimpleAppIT.java

For using veneer at https://cloud.google.com/bigquery/create-simple-app-api
@lesv PTAL

Add shakespeare sample for BigQuery.

---

datastore/cloud-client/src/main/java/com/example/datastore/QuickstartSample.java

`defaultInstance()` and `service()` seem to be deprecated in favor of `getDefaultInstance()` and `getService()`

Use getters for DatastoreOptions and the Datastore service

---

.github/templates/README.md
.github/templates/appengine-flexible-before-you-begin.mdpp
.github/templates/appengine-flexible-deploy.mdpp
.github/templates/getting-sample-code.mdpp
flexible/README.md
flexible/README.mdpp

This uses https://github.com/jreese/markdown-pp to include markdown from
other files.  The templates in this repository can also be used in other
repositories with the `!INCLUDEURL` directive.
@lesv PTAL

Add templates for READMEs.

---

translate/src/main/java/com/google/cloud/translate/samples/TranslateText.java

@lesv @tswast @sgreenberg @gguuss Made changes to the sample so that it works for people without WL as well.

added function without and with model

---

language/analysis/README.md

Addresses comments missed in PR for adding GCS object support.

Improves style for shell examples

---

vision/text/pom.xml
vision/text/src/main/java/com/google/cloud/vision/samples/text/ImageText.java
vision/text/src/main/java/com/google/cloud/vision/samples/text/Index.java
vision/text/src/main/java/com/google/cloud/vision/samples/text/TextApp.java
vision/text/src/main/java/com/google/cloud/vision/samples/text/Word.java

AutoValue saves us from having to write boilerplate, but it only works
with Maven or Gradle. Those users using Eclipse and IntelliJ to compile
have been having difficulty.
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/252
@lesv PTAL

Remove dependency on AutoValue.

---

language/analysis/README.md
language/analysis/demo.cmd
language/analysis/demo.sh

Changes usage example in README and uses shell scripts to demonstrate comprehensive usage of the sample app.

Adds demo scripts and changes usage in README

---

bigquery/cloud-client/pom.xml
datastore/cloud-client/pom.xml
datastore/pom.xml
datastore/src/test/java/com/google/datastore/snippets/ConceptsTest.java
flexible/cloudstorage/pom.xml
flexible/datastore/pom.xml
language/cloud-client/pom.xml
logging/cloud-client/pom.xml
pom.xml
storage/cloud-client/pom.xml

Note this wasn't automatically done because dpebot currently skips beta
releases. We can look at how to add an exception for the
com.google.cloud libraries if they are going to stay beta a while.

Use latest (beta) versions of cloud client libraries.

---

appengine/endpoints-frameworks-v2/backend/pom.xml

Currently, mvn appengine:update fails because it compiles Java 8
bytecode. This forces the app code to Java 7.

enforce java 7 on Endpoints sample

---

appengine/endpoints-frameworks-v2/backend/pom.xml
appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/appengine-web.xml
appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/web.xml
endpoints/getting-started/pom.xml
endpoints/getting-started/src/main/appengine/app.yaml
endpoints/getting-started/src/main/appengine/openapi.yaml

1. Change default service names to the new cloud.goog format.
2. Change app.yaml beta_settings to endpoints_api_service.

Update Endpoints samples:

---

appengine/cloudsql/README.md
appengine/cloudsql/pom.xml
appengine/cloudsql/src/main/java/com/example/appengine/cloudsql/CloudSqlServlet.java

1. Not sure why this worked before, but this fixes it for good.

add war plugin

---

flexible/cloudsql/.gitignore
flexible/cloudsql/README.md
flexible/cloudsql/pom.xml
flexible/cloudsql/src/main/appengine/app.yaml
flexible/cloudsql/src/main/java/com/example/cloudsql/CloudSqlServlet.java
flexible/cloudsql/src/main/resources/config.properties

1. Fix Copyrights
2. Make work the same way that appengine standard works
3. move parameters to pom.xml -> resources/config.properties
4. Update README
5. Max instances = 2

CloudSql for Flexible update

---

bigquery/cloud-client/pom.xml
bigquery/cloud-client/src/main/java/com/example/bigquery/QueryParametersSample.java
bigquery/cloud-client/src/test/java/com/example/bigquery/QueryParametersSampleIT.java

Samples for:
- Named parameters with scalar values.
- Named parameters with array values.
- Named parameters with timestamp values.
Sample for structs is not present due to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1486

BigQuery: add samples for query parameters.

---

bigquery/cloud-client/src/main/java/com/example/bigquery/QueryParametersSample.java

That comment (about the format for timestamps) was copied from a raw API sample. It doesn't apply to the Java client library.

Remove extraneous comment about BigQuery timestamps.

---

appengine/endpoints-frameworks-v2/backend/.gitignore
appengine/endpoints-frameworks-v2/backend/README.md

The latest changes to the Framework generates an openapi.json rather
than a swagger.json.

Updates the Endpoints Java Framework sample README

---

vision/README.md

We got a question https://github.com/GoogleCloudPlatform/java-docs-samples/issues/469 about using this sample code in an Android application. We should mention the Android samples whereever we have them. (I think this will become even more important when we add Google Cloud client library samples since I don't think Android is supported for those libraries)

Add link to the Android sample.

---

speech/grpc/pom.xml
speech/grpc/src/main/java/com/examples/cloud/speech/StreamingRecognizeClient.java
speech/grpc/src/test/java/com/examples/cloud/speech/StreamingRecognizeClientTest.java

Stream audio from microphone for speech streaming

---

appengine/cloudsql/README.md
appengine/cloudsql/pom.xml

1. We want to use the Java SDK plugin for now

Use the Java SDK Plugin

---

appengine/endpoints-frameworks-v2/backend/pom.xml

* fix for character encoding issue
* fix local development server startup
Please don't merge this until January 25, 1.0.1 is currently being pushed to Maven right now.

bump API management version to 1.0.1

---

speech/grpc/README.md

--file flag is not defined in the example program. The program won't execute if not removed from the command

Enhanced streaming client example

---

.travis.yml
bigquery/pom.xml
bigquery/rest/README.md
bigquery/rest/pom.xml
bigquery/rest/src/main/java/com/example/bigquery/LabelsSample.java
bigquery/rest/src/test/java/com/example/bigquery/Constants.java
bigquery/rest/src/test/java/com/example/bigquery/LabelsSampleIT.java
pom.xml

These samples use the HTTP client library. Neither the Cloud nor API
client libraries support the table labeling feature yet.
The Cloud client library will not support it for a while, since this is
a beta feature. I made an agreement with the Cloud client libraries PM
that I can mix client libraries and raw HTTP samples.

BigQuery REST samples to label datasets and tables.

---

kms/README.md
kms/pom.xml
kms/src/main/java/com/example/CryptFile.java
kms/src/main/java/com/example/CryptFileCommands.java
kms/src/main/java/com/example/Quickstart.java
kms/src/main/java/com/example/SnippetCommands.java
kms/src/main/java/com/example/Snippets.java

Working on tests, but figured I'd send this out first to start the review.

Kms samples

---

.travis.yml
CONTRIBUTING.md
datastore/pom.xml
logging/pom.xml
monitoring/v2/pom.xml
pom.xml
spanner/cloud-client/pom.xml
spanner/cloud-client/src/main/java/com/example/spanner/QuickstartSample.java
spanner/cloud-client/src/test/java/com/example/spanner/QuickstartSampleIT.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
speech/grpc/pom.xml
speech/grpc/src/main/java/com/examples/cloud/speech/StreamingRecognizeClient.java
storage/storage-transfer/README.md
travis.sh

mvn verify
* Spanner Works
1. remove comments from pom.xml
2. explicitly pass the SystemPropertyValues in local pom — not sure how
it worked earlier.
3. Fix a comment in the QuickStart sample
4. Restore stdOut in both IT samples

Get full IT working again

---

pubsub/cloud-client/src/main/java/com/example/pubsub/QuickstartSample.java
pubsub/cloud-client/src/test/java/com/example/pubsub/QuickstartSampleIT.java

removing publisher use case from pubsub quickstart

removing publish from quickstart

---

storage/storage-transfer/README.md

@jerjou provided the suggestions.

Improve README

---

appengine/endpoints-frameworks-v2/backend/pom.xml

This clashes with the GetSwaggerDoc task, since the tool doesn't depend
on the -all dependency, so we revert it for now.

revert endpoints-framework-all dependency

---

language/README.md

Getting a 404. I think that's the new URL.
Thanks!

Fix Google Cloud Natural Language API link

---

jenkins.sh

* Fail when one of the tests fails
* Deploy to different app versions
* Clean up app versions in the background after each test

Fix jenkins script.

---

spanner/cloud-client/pom.xml

1. netty-tcnative-boringssl-static got upgraded by DPEBot to 2.0.0Beta6
which broke everything.  But it shouldn’t have been in the POM to begin
with.  The library includes all this.  Argh!

make it work again

---

flexible/analytics/src/main/appengine/app.yaml
flexible/async-rest/src/main/appengine/app.yaml
flexible/cloudsql/src/main/appengine/app.yaml
flexible/cloudstorage/src/main/appengine/app.yaml
flexible/cron/src/main/appengine/app.yaml
flexible/datastore/src/main/appengine/app.yaml
flexible/disk/src/main/appengine/app.yaml
flexible/endpoints/src/main/appengine/app.yaml
flexible/extending-runtime/src/main/appengine/app.yaml
flexible/helloworld/src/main/appengine/app.yaml
flexible/mailgun/src/main/appengine/app.yaml
flexible/mailjet/src/main/appengine/app.yaml
flexible/memcache/src/main/appengine/app.yaml
flexible/sendgrid/src/main/appengine/app.yaml
flexible/static-files/src/main/appengine/app.yaml
flexible/twilio/src/main/appengine/app.yaml

The "secure" directive is ignored in Flexible.

remove "secure: always" from Flexible samples.

---

jenkins.sh

Turns out GAE has a 63-character limit on subdomains.

Shorten version name to avoid 63-char limit.

---

datastore/README.md
datastore/src/main/java/com/google/datastore/snippets/TaskList.java
flexible/async-rest/README.md
flexible/sparkjava/README.md
storage/json-api/README.md

Pretty sure we always want the ADC command.

Replace all auth commands with ADC

---

appengine/endpoints-frameworks-v2/discovery/jenkins.sh
appengine/endpoints-frameworks-v2/discovery/src/main/java/com/example/helloendpoints/Greetings.java
flexible/sparkjava/jenkins.sh
jenkins.sh

Also, revert inadvertent commit -_-;

Save the output of commands that error.

---

monitoring/cloud-client/README.md
monitoring/cloud-client/pom.xml
monitoring/cloud-client/src/main/java/com/example/monitoring/QuickstartSample.java
monitoring/cloud-client/src/test/java/com/example/monitoring/QuickstartSampleIT.java
pom.xml

@jerjou Can you finish this? I'm not sure how to handle the inline `YOUR_PROJECT_ID` string so the tests will work.
Also, I wonder if the code can be cleaned up a bit, made to be less verbose.

Add Monitoring quickstart sample.

---

README.md
bigquery/src/test/java/com/google/cloud/bigquery/samples/test/Constants.java
bigquery/src/test/java/com/google/cloud/bigquery/samples/test/ListDatasetsProjectsTest.java
circle.yml
kms/src/test/java/com/example/SnippetsIT.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeIT.java
logging/src/test/java/ListLogsTest.java
monitoring/v2/src/test/java/CloudMonitoringAuthSampleTest.java
monitoring/v3/src/test/java/ListResourcesTest.java
pubsub/cloud-client/README.md
pubsub/cloud-client/pom.xml
speech/cloud-client/README.md
speech/cloud-client/src/test/java/com/example/speech/RecognizeIT.java
speech/grpc/src/test/java/com/examples/cloud/speech/RecognitionAudioFactoryTest.java
storage/json-api/src/test/java/StorageSampleTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/AwsRequesterTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/NearlineRequesterTest.java
storage/xml-api/cmdline-sample/src/test/java/StorageSampleTest.java
travis.sh
vision/cloud-client/src/test/java/com/example/vision/DetectIT.java
vision/landmark-detection/src/test/java/com/google/cloud/vision/samples/landmarkdetection/DetectLandmarkIT.java

Also, move all tests to use the project given in the environment variable, using buckets named after the project.

Setup circleci ADC

---

circle.yml
travis.sh

Remove chromedriver var, since it's in the path, don't print out the secrets, etc.

Testing tweaks

---

pubsub/cloud-client/pom.xml
pubsub/cloud-client/src/main/java/com/example/pubsub/QuickstartSample.java
pubsub/cloud-client/src/test/java/com/example/pubsub/QuickstartSampleIT.java

updating to v0.11.2-alpha

---

CONTRIBUTING.md

Use the `args` array, for simple arguments. Use Apache Commons CLI once you need options.

Document recommendations for command-line parsing.

---

speech/cloud-client/src/main/java/com/example/speech/Recognize.java

Removes commented out code snippet and adds note on async time limit for local files.

Speech cloud-client nits

---

bigquery/cloud-client/pom.xml
bigquery/cloud-client/src/main/java/com/example/bigquery/QueryParametersSample.java
bigquery/cloud-client/src/main/java/com/example/bigquery/QuerySample.java
bigquery/cloud-client/src/main/java/com/example/bigquery/SimpleApp.java

Manually fix some breaking changes caused by the PageImpl
iterator->iterable.
Manually applies the changes from https://github.com/GoogleCloudPlatform/java-docs-samples/pull/614

BigQuery update dependencies

---

README.md

1. Put an index up (Note that we have to GAE Standard samples at the top level)
2. Add some info about credentials.
@jabubake @tswast FYI

Add a bit more to the readme

---

language/analysis/README.md
language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java
language/analysis/src/main/java/com/google/cloud/language/samples/AnalyzeBeta.java
language/cloud-client/README.md
language/cloud-client/pom.xml

Updates readme instructions / changes execution for Quickstart

---

speech/cloud-client/README.md
speech/cloud-client/pom.xml
speech/cloud-client/src/main/java/com/example/speech/Recognize.java
vision/cloud-client/pom.xml
vision/cloud-client/src/main/java/com/example/vision/Detect.java

Upgrades speech and vision to google-cloud-java 0.17.1.

Vision speech upgrade

---

endpoints/getting-started/openapi.yaml
endpoints/getting-started/pom.xml
endpoints/getting-started/src/main/appengine/app.yaml
endpoints/getting-started/src/main/docker/Dockerfile
endpoints/multiple-versions/src/main/appengine/app.yaml

Adds the same updates in the comments in
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/627.
Also fixes the variables to replace in app.yaml.

Updates the Endpoints getting-started sample.

---

flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPublish.java

The removed region tag caused the sample to end too early. It should have the full function definition, but especially the end of the try block.

Remove extra end region tag.

---

appengine-java8/bigtable/build.gradle

Add pretty back in to give us variable substitution.
This is really overkill, but I don’t want to fix all the substitution
methods yet.

Fix variable substitution

---

README.md
appengine/iap/README.md
appengine/iap/pom.xml
appengine/iap/src/main/java/com/example/appengine/iap/JwtServlet.java
appengine/iap/src/main/webapp/WEB-INF/appengine-web.xml
appengine/iap/src/main/webapp/WEB-INF/web.xml
appengine/pom.xml
iap/README.md
iap/pom.xml
iap/src/main/java/com/example/iap/BuildIapRequest.java
iap/src/main/java/com/example/iap/VerifyIapRequestHeader.java
iap/src/test/java/com/example/iap/BuildAndVerifyIapRequestIT.java

Ported from python : 
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/iap

Cloud IAP samples

---

iap/README.md
iap/pom.xml
iap/src/main/java/com/example/iap/BuildIapRequest.java
iap/src/main/java/com/example/iap/VerifyIapRequestHeader.java
iap/src/test/java/com/example/iap/BuildAndVerifyIapRequestIT.java

Using jjwt instead of auth0 jwt library. Auth0 jwt library has intermittent token verification failures for IAP on OpenJDK.

Iap sample v2

---

appengine-java8/pom.xml
appengine-java8/spanner/README.md
appengine-java8/spanner/pom.xml
appengine-java8/spanner/src/main/java/com/example/appengine/spanner/SpannerClient.java
appengine-java8/spanner/src/main/java/com/example/appengine/spanner/SpannerTasks.java
appengine-java8/spanner/src/main/java/com/example/appengine/spanner/SpannerTasksServlet.java
appengine-java8/spanner/src/main/webapp/WEB-INF/appengine-web.xml

Spanner app engine sample.
FYI, @ludoch

adding java8 spanner sample

---

appengine-java8/spanner/src/main/java/com/example/appengine/spanner/SpannerClient.java
appengine-java8/spanner/src/main/java/com/example/appengine/spanner/SpannerTasks.java
appengine-java8/spanner/src/main/java/com/example/appengine/spanner/SpannerTasksServlet.java

Fixes Circle CI build failure.

Formatting fixes : appengine Java 8 spanner

---

appengine-java8/endpoints-v2-migration/README.md
appengine-java8/endpoints-v2-migration/build.gradle
appengine-java8/endpoints-v2-migration/pom.xml
appengine-java8/endpoints-v2-migration/src/main/webapp/WEB-INF/web.xml

This PR removes the Endpoints Frameworks v1 flow from Java 8 version of Endpoints Frameworks v2 migration sample.

Removing Endpoints v1 workflow from java8 samples

---

language/analysis/pom.xml
language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java
language/analysis/src/main/java/com/google/cloud/language/samples/AnalyzeBeta.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeBetaIT.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeIT.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeTest.java
language/cloud-client/pom.xml

Also fixes missing parent from language pom.xml and resolves the lint issues that appear in the tests.

Adds missing dependency until the language library is fixed.

---

flexible/postgres/.gitignore
flexible/postgres/README.md
flexible/postgres/pom.xml
flexible/postgres/src/main/appengine/app.yaml
flexible/postgres/src/main/java/com/example/postgres/PostgresSqlServlet.java
flexible/postgres/src/main/resources/config.properties
pom.xml

1. update cloudSql to latest plugin and make the sample a bit cleaner.
2. add postgresql sample.

Postgres & CloudSQL update for flex

---

appengine-java8/spanner/README.md
appengine-java8/spanner/src/main/webapp/WEB-INF/appengine-web.xml

cleaning up unused code, fixing bad link

minor fixes to App Engine Flex Spanner sample

---

iot/api-client/mqtt_example/src/main/java/com/google/cloud/iot/examples/MqttExample.java

Fixes [this issue](https://github.com/GoogleCloudPlatform/java-docs-samples/issues/734#event-1145055441).

Fixes RSA algo and uses .equals for string comparisons

---

appengine-java8/endpoints-v2-backend/build.gradle

also adopted the sourceCompatibility & targetCompatibility to 1.8

fix for #747, replaceProjectId wrong directory

---

endpoints/getting-started/openapi.yaml

In our sample, both api_key and the auth issuer are required, the config
should use "AND" semantics.

Fix an issue in openapi.yaml.

---

bigquery/cloud-client/.gitignore
bigquery/cloud-client/src/main/java/com/example/bigquery/AuthSnippets.java
bigquery/cloud-client/src/test/java/com/example/bigquery/AuthSnippetsIT.java

For inclusion in the BigQuery authentication docs: https://cloud.google.com/bigquery/authentication
I followed the Python example here: https://cloud.google.com/docs/authentication/production#auth-cloud-explicit-python

BigQuery: Add explicit service account key auth sample.

---

.travis.yml
dlp/pom.xml
dlp/src/main/java/com/example/dlp/Inspect.java

Note :the service account credentials used for tests need to have access to Datastore, Storage.

DLP dependency update, fix tests (still requires right service account credentials)

---

appengine-java8/guestbook-cloud-datastore/pom.xml
dlp/src/test/java/com/example/dlp/InspectIT.java
pom.xml
storage/storage-transfer/pom.xml
travis.sh
vision/cloud-client/pom.xml
vision/cloud-client/src/test/java/com/example/vision/DetectIT.java
vision/landmark-detection/src/test/java/com/google/cloud/vision/samples/landmarkdetection/DetectLandmarkIT.java

upgrade Guava

---

appengine-java8/analytics/src/main/java/com/example/appengine/analytics/AnalyticsServlet.java
appengine-java8/users/src/main/java/com/example/appengine/users/UsersServlet.java
appengine-java8/users/src/test/java/com/example/appengine/users/UsersServletTest.java
flexible/postgres/pom.xml

1. fix poster comment
2. run through google-java-format, (wasn’t totally happy)

fix a comment

---

appengine/mailjet/src/main/java/com/example/appengine/mailjet/MailjetServlet.java
compute/mailjet/src/main/java/com/example/compute/mailjet/MailjetSender.java
flexible/mailjet/src/main/java/com/example/mailjet/MailjetServlet.java

Mailjet Send API v3.1 is being released, so updating the code samples to match the new Send API v3.1 configuration. Reference can be found [here](https://dev.mailjet.com/beta/).

updating Mailjet code samples for Send API v3.1

---

kms/src/main/java/com/example/CryptFile.java
kms/src/main/java/com/example/CryptFileCommands.java
kms/src/main/java/com/example/Quickstart.java
kms/src/main/java/com/example/SnippetCommands.java
kms/src/main/java/com/example/Snippets.java
kms/src/test/java/com/example/QuickstartIT.java
kms/src/test/java/com/example/SnippetsIT.java

In particular:
* Define keyRingId and cryptoKeyId consistently with the API.
* Use locationId as an argument.
* Use the language "ciphertext" and "plaintext" to refer to encrypted and unencrypted data, respectively.
I opted to keep file I/O in the Command runner to keep the API
clean, especially when being rendered on
https://cloud.google.com/kms/docs/encrypt-decrypt.
Tracking bug: http://b/64758639

KMS: Make samples consistent with all languages.

---

kms/src/test/java/com/example/SnippetsIT.java

Fix the tests introduced in #816.
Some code was still calling encrypt(...) with a key version.

KMS: fixes the kms failing tests.

---

logging/cloud-client/src/main/java/com/example/logging/ListLogs.java
logging/jul/src/main/resources/logging.properties
logging/logback/src/main/resources/logback.xml

adding list logs snippet

---

appengine/datastore/README.md
appengine/endpoints-v1-helloworld/README.md
appengine/endpoints-v1-helloworld/pom.xml
appengine/endpoints-v1-helloworld/src/main/java/com/example/helloworld/Bar.java
appengine/endpoints-v1-helloworld/src/main/java/com/example/helloworld/BarTransformer.java
appengine/endpoints-v1-helloworld/src/main/java/com/example/helloworld/Constants.java
appengine/endpoints-v1-helloworld/src/main/java/com/example/helloworld/MyBean.java
appengine/endpoints-v1-helloworld/src/main/java/com/example/helloworld/RequestTimeoutException.java
appengine/endpoints-v1-helloworld/src/main/java/com/example/helloworld/YourFirstAPI.java
appengine/endpoints-v1-helloworld/src/main/webapp/WEB-INF/appengine-web.xml
appengine/endpoints-v1-helloworld/src/main/webapp/WEB-INF/logging.properties
appengine/endpoints-v1-helloworld/src/main/webapp/WEB-INF/web.xml
appengine/pom.xml

move appengine v1 sample here

---

pubsub/cloud-client/README.md

Patching Pub/Sub README variable name

---

appengine-java8/images/src/main/java/com/example/appengine/images/ImagesServlet.java

adding serving url sample

---

appengine-java8/endpoints-v2-backend/build.gradle
appengine-java8/endpoints-v2-backend/pom.xml
appengine-java8/endpoints-v2-backend/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/endpoints-v2-backend/src/main/webapp/WEB-INF/web.xml
appengine-java8/endpoints-v2-guice/build.gradle
appengine-java8/endpoints-v2-guice/pom.xml
appengine-java8/endpoints-v2-migration/build.gradle
appengine-java8/endpoints-v2-migration/pom.xml
appengine/endpoints-frameworks-v2/backend/build.gradle
appengine/endpoints-frameworks-v2/backend/pom.xml
appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/appengine-web.xml
appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/web.xml
appengine/endpoints-frameworks-v2/guice-example/build.gradle
appengine/endpoints-frameworks-v2/guice-example/pom.xml
appengine/endpoints-frameworks-v2/migration-example/build.gradle
appengine/endpoints-frameworks-v2/migration-example/pom.xml

This PR is to add region tags around the backend/ sample for use in documentation and update plugin versions. I'm not sure why they aren't getting picked up in dependency auto-update.

[Endpoints] Add region tags and update dependencies

---

kms/README.md
kms/src/main/java/com/example/SnippetCommands.java
kms/src/main/java/com/example/Snippets.java
kms/src/test/java/com/example/SnippetsIT.java

New snippet to use at https://cloud.google.com/kms/docs/destroy-restore.

Adds snippet for restoring a crypto key version

---

.kokoro/continuous.cfg
.kokoro/periodic.cfg
.kokoro/presubmit.cfg
.kokoro/tests/run_tests.sh

This PR setups up the build configs for Kokoro to do CI and presubmit testing.

Configured kokoro tests for CI and presubmit testing.

---

logging/cloud-client/src/main/java/com/example/logging/ListLogs.java
logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java

Increase the stability of the Logging tests.
@lesv - FYI

Increase Logging Testing stability

---

appengine-java8/endpoints-v2-backend/README.md
appengine-java8/endpoints-v2-backend/jenkins.sh
appengine-java8/endpoints-v2-guice/README.md
appengine/endpoints-frameworks-v2/backend/README.md
appengine/endpoints-frameworks-v2/backend/jenkins.sh
appengine/endpoints-frameworks-v2/guice-example/README.md
appengine/endpoints-frameworks-v2/guice-example/jenkins.sh
endpoints/getting-started-grpc/README.md
endpoints/getting-started/src/main/appengine/app.yaml
endpoints/multiple-versions/src/main/appengine/app.yaml

@inklesspen
- `gcloud service-management deploy` becomes `gcloud endpoints deploy`
- `gcloud service-management configs` becomes `gcloud endpoints configs`

Update deprecated commands for `gcloud service-management`

---

appengine-java8/endpoints-v2-guice/README.md
appengine-java8/endpoints-v2-guice/build.gradle
appengine-java8/endpoints-v2-guice/pom.xml
appengine-java8/endpoints-v2-guice/src/main/java/com/example/echo/EchoGuiceListener.java
appengine-java8/endpoints-v2-guice/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/endpoints-v2-guice/src/main/webapp/WEB-INF/web.xml
appengine/endpoints-frameworks-v2/guice-example/src/main/webapp/WEB-INF/appengine-web.xml
appengine/endpoints-frameworks-v2/guice-example/src/main/webapp/WEB-INF/web.xml

There exists a bug with the DevAppServer and Guice + Basic Scaling that causes the main serving port 8080 to 404 when accessing the sample API endpoint, but works from an instance port when this isn't the correct way to access the API endpoint.
Reported here: b/68948960

[Endpoints] Fix local development for Guice sample.

---

appengine-java8/endpoints-v2-skeleton/build.gradle
appengine-java8/endpoints-v2-skeleton/pom.xml

This PR updates region tags for used by Endpoints Framework for Java documentation.

[Endpoints] Region tag changes

---

firestore/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java

This adds blocking to the initial transaction done in the returnInfoFromTransaction to ensure the transaction is completed before the retrieval that follows it. 
@lesv, @jabubake - FYI

Firebase Sample test fix.

---

flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPublish.java
pubsub/cloud-client/src/main/java/com/example/pubsub/CreatePullSubscriptionExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/PublisherExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/SubscriberExample.java
pubsub/cloud-client/src/test/java/com/example/pubsub/QuickStartIT.java

Updating w surface changes
adding exception handling and asynchronous callback

updating pub/sub samples

---

bigquery/cloud-client/pom.xml
translate/cloud-client/pom.xml
vision/README.md

Add 'dependencies' tag to bigquery/cloud-client/pom.xml and translate/cloud-client/pom.xml.
Fix broken link to 'vision/face-detection' in vision/README.md.

Add 'dependencies' tags & fix broken vision link.

---

cloud-tasks/README.md
cloud-tasks/pom.xml
cloud-tasks/src/main/java/com.example.cloudtasks/PullQueue.java
cloud-tasks/src/test/java/com/example/cloudtasks/PullQueueIT.java
flexible/cloud-tasks/README.md
flexible/cloud-tasks/pom.xml
flexible/cloud-tasks/src/main/appengine/app.yaml
flexible/cloud-tasks/src/main/java/com/example/cloudtasks/CreateTaskServlet.java
flexible/cloud-tasks/src/main/java/com/example/cloudtasks/HelloServlet.java
flexible/cloud-tasks/src/main/java/com/example/cloudtasks/LogPayloadServlet.java
flexible/pom.xml

This PR adds two new samples pertaining to the Cloud Samples API.
The first is a command line application that shows how to create, pull, and acknowledge cloud tasks.
The second is an AppEngine App to showcase how to create a Cloud Task with an AppEngine endpoint as it's target. 
FYI @lesv, @jabubake

Add Cloud Tasks Samples

---

appengine-java8/datastore/src/test/java/com/example/appengine/TransactionsTest.java

1. An example that shows queue add w/ transactions should actually use
the transaction.

Transaction Sample update

---

bigquery/cloud-client/src/main/java/com/example/bigquery/SimpleApp.java
bigquery/cloud-client/src/test/java/com/example/bigquery/SimpleAppIT.java

- Add region tags for needed dependencies.
- Use more relevant query from public datasets.

BigQuery: rewrite simple app tutorial.

---

endpoints/getting-started/deployment.yaml

For better readability, let's use the long options for the ESP config. Here's the doc: https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options

Use long options for ESP config

---

endpoints/getting-started-grpc/README.md
endpoints/getting-started-grpc/deployment.yaml
endpoints/getting-started/deployment.yaml
endpoints/multiple-versions/container-engine.yaml

Prevents common mistake between -p and -P.
@navinger @p-buse

Use long-flags everywhere, for readability.

---

vision/beta/cloud-client/src/test/java/com/example/vision/DetectIT.java

This generalizes the test for testDetectWebEntitiesIncludeGeoResults. Currently the test is failing because the expected label for the picture is not present in the results. Since the API is still in beta, the labels returned from images change over time. Instead of just updating the label each time it changes, the test has been changed to fail if an error has occurred. 
@lesv - FYI

Fix for VisionBetaTest reliability 

---

mlengine/online-prediction/README.md
mlengine/online-prediction/pom.xml
monitoring/cloud-client/README.md
monitoring/cloud-client/pom.xml
monitoring/cloud-client/src/main/java/com/example/monitoring/QuickstartSample.java
monitoring/cloud-client/src/main/java/com/example/monitoring/Snippets.java
monitoring/cloud-client/src/test/java/com/example/monitoring/QuickstartSampleIT.java
monitoring/cloud-client/src/test/java/com/example/monitoring/SnippetsIT.java
pom.xml
pubsub/cloud-client/README.md
pubsub/cloud-client/pom.xml
pubsub/cloud-client/src/main/java/com/example/pubsub/CreatePullSubscriptionExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/PublisherExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/SubscriberExample.java
pubsub/cloud-client/src/test/java/com/example/pubsub/QuickStartIT.java
spanner/cloud-client/README.md
spanner/cloud-client/pom.xml
spanner/cloud-client/src/main/java/com/example/spanner/QuickstartSample.java
spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
spanner/cloud-client/src/test/java/com/example/spanner/QuickstartSampleIT.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
speech/README.md
speech/cloud-client/README.md
speech/cloud-client/pom.xml
speech/cloud-client/src/main/java/com/example/speech/QuickstartSample.java
speech/cloud-client/src/main/java/com/example/speech/Recognize.java
speech/cloud-client/src/test/java/com/example/speech/QuickstartSampleIT.java
speech/cloud-client/src/test/java/com/example/speech/RecognizeIT.java

Updated parent poms and added Cloud Shell Button.

Updated mlengine, monitoring, pubsub, spanner, and speech.

---

appengine-java8/translate-pubsub/README.md
appengine-java8/translate-pubsub/pom.xml
appengine-java8/translate-pubsub/sample_message.json
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/Message.java
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/MessageRepository.java
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/MessageRepositoryImpl.java
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/PubSubHome.java
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/PubSubPublish.java
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/PubSubPush.java
appengine-java8/translate-pubsub/src/main/java/com/example/appengine/translatepubsub/Translate.java
appengine-java8/translate-pubsub/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/translate-pubsub/src/main/webapp/index.jsp

Moving translate-pubsub sample from [GoogleCloudPlatform/getting-started-java](https://github.com/GoogleCloudPlatform/getting-started-java) to [GoogleCloudPlatform/java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples).
Only changes from that project's version are updates to the pom.xml & README.md where appropriate, and fixing a typo in index.jsp (importing translate_pubsub.PubSubHome instead of translatepubsub.PubSubHome).

Moving translate-pubsub

---

vision/cloud-client/README.md
vision/cloud-client/pom.xml
vision/cloud-client/src/main/java/com/example/vision/Detect.java
vision/cloud-client/src/main/java/com/example/vision/QuickstartSample.java
vision/cloud-client/src/test/java/com/example/vision/DetectIT.java
vision/face-detection/README.md
vision/face-detection/pom.xml
vision/face-detection/src/main/java/com/google/cloud/vision/samples/facedetect/FaceDetectApp.java
vision/face-detection/src/test/java/com/google/cloud/vision/samples/facedetect/FaceDetectAppIT.java
vision/face-detection/src/test/java/com/google/cloud/vision/samples/facedetect/FaceDetectAppTest.java
vision/label/README.md
vision/label/pom.xml
vision/label/src/main/java/com/google/cloud/vision/samples/label/LabelApp.java
vision/label/src/test/java/com/google/cloud/vision/samples/label/LabelAppIT.java
vision/label/src/test/java/com/google/cloud/vision/samples/label/LabelAppTest.java
vision/landmark-detection/README.md
vision/landmark-detection/pom.xml
vision/landmark-detection/src/main/java/com/google/cloud/vision/samples/landmarkdetection/DetectLandmark.java
vision/landmark-detection/src/test/java/com/google/cloud/vision/samples/landmarkdetection/DetectLandmarkIT.java
vision/text/README.md
vision/text/pom.xml
vision/text/src/main/java/com/google/cloud/vision/samples/text/ImageText.java
vision/text/src/main/java/com/google/cloud/vision/samples/text/Index.java
vision/text/src/main/java/com/google/cloud/vision/samples/text/TextApp.java
vision/text/src/test/java/com/google/cloud/vision/samples/text/TextAppIT.java
vision/text/src/test/java/com/google/cloud/vision/samples/text/TextAppTest.java

This updates the parent pom, checkstyle violations, and cloud shell buttons for the vision folder.

Update vision folder.

---

appengine-java8/bigquery/README.md
appengine-java8/bigquery/pom.xml
appengine-java8/bigquery/src/main/java/com/example/appengine/bigquerylogging/BigQueryHome.java
appengine-java8/bigquery/src/main/java/com/example/appengine/bigquerylogging/BigQueryRun.java
appengine-java8/bigquery/src/main/java/com/example/appengine/bigquerylogging/BigQueryRunner.java
appengine-java8/bigquery/src/main/java/com/example/appengine/bigquerylogging/TimeSeriesSummary.java
appengine-java8/bigquery/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/bigquery/src/main/webapp/index.jsp
appengine-java8/bigquery/src/test/java/com/example/appengine/bigquerylogging/BigQueryRunnerTest.java
appengine-java8/pom.xml

After running some queries on the most often paired API's, I found that bigquery-json and monitoring are among the top paired in java projects. This version of the API showcase includes aspects of both the bigquery SimpleApp and the monitoring QuickStart, demonstrating how to incorporate both into a single project.
In this case, after making the call to BigQuery, the app adds metrics about how long it took the query to process, and the number of rows returned.
This tutorial will be linked to as the second part of the new [/java/docs](https://cloud.google.com/java/docs) page, after a similar link to the Spring Boot on AppEngine Standard tutorial.

Adding BigQuery + StackDriver Monitoring API Showcase sample.

---

.kokoro/tests/run_tests.sh
pom.xml

This tidies up and condenses the test script used to trigger Kokoro tests.
It removes some unused variables, directs output from tests themselves into a file, and removes the clutter from 'downloading....' for all the dependencies.

Consolidate and cleanup Kokoro test script. 

---

.kokoro/presubmit.cfg
.kokoro/tests/diff_tests.sh

This enables Kokoro presubmit tests to run only on projects that contain changes from the master branch. It does this by finding all pom.xmls in the project, and checking the folder of each one to determine if any changes have occurred. If so, it runs the `mvn verify` command on the folder. 
Given the current structure of our folders, changes to projects under sub-projects will trigger twice (changes to appengine/project will trigger a build for project and appengine) however this is still faster than waiting for the entire project to run.

Only run presubmit tests for projects containing changes. 

---

cloud-tasks/src/main/java/com.example.cloudtasks/PullQueue.java

One for create task and one for lease and acknowledge task

Add region tags

---

cloud-tasks/src/main/java/com.example.cloudtasks/PullQueue.java
flexible/cloud-tasks/README.md

Update Lease Task Request to retrieve entire response and makes some minor changes to the wiki since the endpoints were changed.

Minor Fixes for Cloud Tasks Sample

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java

Related:
* ~~googleapis/nodejs-spanner#136~~ merged
* GoogleCloudPlatform/ruby-docs-samples#244
* GoogleCloudPlatform/python-docs-samples#1376
* GoogleCloudPlatform/dotnet-docs-samples#454
* GoogleCloudPlatform/php-docs-samples#562
* GoogleCloudPlatform/golang-samples#403

Clean up Spanner region tags.

---

dlp/pom.xml
dlp/src/main/java/com/example/dlp/DeIdentification.java
dlp/src/main/java/com/example/dlp/Metadata.java
dlp/src/main/java/com/example/dlp/RiskAnalysis.java

Related:
* googleapis/nodejs-dlp#26
* GoogleCloudPlatform/php-docs-samples#568

Clean up DLP region tags.

---

monitoring/v3/src/main/java/AlertSample.java

Adds region tags to AlertSample.java, for extraction of doc samples without resorting to regexps.

Adds region tags to Java alerting sample

---

appengine-java8/cloudsql-postgres/README.md
appengine-java8/cloudsql-postgres/pom.xml
appengine-java8/cloudsql-postgres/src/main/java/com/example/appengine/postgresql/PostgreSqlServlet.java
appengine-java8/cloudsql-postgres/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/cloudsql/README.md
appengine-java8/cloudsql/pom.xml
appengine-java8/cloudsql/src/main/java/com/example/appengine/cloudsql/CloudSqlServlet.java
appengine-java8/cloudsql/src/main/webapp/WEB-INF/appengine-web.xml

Updates for the AppEngine Standard samples to use a single jdbc url, remove references to v6 connector, and other minor text fixes. 
FYI - @piaxc

Update CloudSQL Samples

---

container-registry/container-analysis/src/main/java/com/example/containeranalysis/Samples.java
container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTests.java

The Container Analysis tests are currently failing, due to conflicts with dependencies after an update from the DPE bot (b/78643399). After discussing how to resolve the issue, we decided the best option is to temporarily disable the tests until the official release of the client libraries into the maven repo. 
This PR **removes the container analysis project from the pom file to disable the automated tests**. It also adds in some miscellaneous minor fixes for the container analysis samples (primarily typos and variable changes)

Disable Container Analysis 

---

dlp/src/main/java/com/example/dlp/DeIdentification.java

Fix the end tag deIdentifyWithMask to match the start tag which is dlp_deidentify_masking.

Fix documentation for deIdentifyWithMask

---

datastore/pom.xml
datastore/src/main/java/com/google/datastore/snippets/TaskList.java
datastore/src/test/java/com/google/datastore/snippets/ConceptsTest.java

These samples/region tags aren't used on cloud.google.com, so I'm deleting them.
Related:
- GoogleCloudPlatform/python-docs-samples#1531
- googleapis/nodejs-datastore#110
- GoogleCloudPlatform/php-docs-samples#631
- GoogleCloudPlatform/dotnet-docs-samples#569
- GoogleCloudPlatform/ruby-docs-samples#292
- GoogleCloudPlatform/golang-samples#516

Delete unused Datastore region tags / samples.

---

dataflow/transforms/README.md

Short PR to fix errors in the README.md.

[Dataflow] Fix errors in README.md

---

appengine-java8/tasks/pom.xml
appengine-java8/tasks/src/main/java/com/example/task/CreateTask.java
appengine-java8/tasks/src/main/java/com/example/task/TaskServlet.java
appengine-java8/tasks/src/main/webapp/WEB-INF/appengine-web.xml
tasks/pom.xml
tasks/src/main/java/com/example/Quickstart.java
tasks/src/test/java/com/example/QuickstartIT.java

Still working on the appengine version, but thought I would create the pull request now so reviews can start, since we were wanting this done by EOD.
I do not have a README currently because the content seems copied from the documentation at https://cloud.google.com/tasks/docs/quickstart-pull, which someone else will be working on this weekend. I will grab it from there and pull it down when it is done.

Add task create & lease/acknowledge sample.

---

monitoring/v3/manage_alerts_sample.sh
monitoring/v3/pom.xml
monitoring/v3/src/main/java/com/example/AlertSample.java
monitoring/v3/src/main/java/com/example/UptimeSample.java
monitoring/v3/src/test/java/com/example/AlertIT.java
monitoring/v3/src/test/java/com/example/UptimeIT.java

Also organize the existing alert samples in a traditional directory, and clean up the code a bit.
The cleanup to AlertSample is just using a try() block to create the AlertPolicyClient or NotificationChannelServiceClient as needed instead of creating them for an instance of the AlertSample.

Create monitoring uptime check config samples.

---

dlp/README.md

These were removed when the API went GA. Also fix a couple typos, we refer to "info types" as InfoTypes in all formal documentation.

Remove deprecated references to categories and fix paths.

---

vision/beta/cloud-client/src/main/java/com/example/vision/Detect.java
vision/cloud-client/src/main/java/com/example/vision/Detect.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ImportProductSets.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ProductInProductSetManagement.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ProductManagement.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSearch.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSetManagement.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ReferenceImageManagement.java

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

Vision region tag update

---

vision/beta/cloud-client/src/main/java/com/example/vision/Detect.java

These samples need to be tracked separately from GA, so we are changing the tags

Udpate Beta Vision samples to use beta tags

---

speech/cloud-client/README.md
speech/cloud-client/src/main/java/com/example/speech/Recognize.java

[DO_NOT_MERGE] Microphone streaming with a 1 minute duration.

---

speech/cloud-client/pom.xml
speech/cloud-client/src/main/java/com/example/speech/Recognize.java

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

Speech region tag update

---

language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

Natural Language region tag update

---

texttospeech/beta/src/main/java/com/example/texttospeech/SynthesizeText.java

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

TTS region tag update

---

vision/product-search/cloud-client/src/main/java/com/example/vision/ProductInProductSetManagement.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ProductManagement.java
vision/product-search/cloud-client/src/main/java/com/example/vision/ProductSetManagement.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ImportProductSetsIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ProductInProductSetManagementIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ProductManagementIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSetManagementIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ReferenceImageManagementIT.java

@nnegrey Please review.
Apart from the tests, cleaned up the main files as well.
Currently missing the tests for ProductSearch.java file. Working on fixing some issues with the src and test files.

Adding the Product Search tests.

---

bigquery/cloud-client/pom.xml
bigquery/datatransfer/cloud-client/pom.xml
language/analysis/pom.xml
language/automl/pom.xml
pubsub/cloud-client/pom.xml
texttospeech/beta/pom.xml
texttospeech/cloud-client/pom.xml
translate/automl/pom.xml
translate/cloud-client/pom.xml
vision/automl/pom.xml
vision/beta/cloud-client/pom.xml
vision/cloud-client/pom.xml
vision/face-detection/pom.xml
vision/product-search/cloud-client/pom.xml

The goal with sample region tags is to have a globally unique tag for each sample. The "dependencies" tag is used throughout the java-docs-samples repo, which goes against best practices. This PR accomplishes the following:
+ For region tags that are not used on cloud.google.com, remove the region tag
+ For region tags that are used on cloud.google.com, add a prefix of product_java_ (ex. bigquery_java_dependencies)
Note that this PR does not include all products, only ones that I am responsible for adding to the sample tracker. Others will be performing this update for the remaining products.

Remove unused dependency region tags and update used region tags

---

appengine-java8/cloudsql-postgres/pom.xml
appengine-java8/cloudsql-postgres/src/main/webapp/WEB-INF/appengine-web.xml

The JDBC SocketFactory is deprecating 'socketFactoryArg' in favor of 'cloudSqlInstance'. This updates the Postgres example with that change.

Update Appengine example for updated Postgres JDBC SocketFactory.

---

appengine-java8/README.md

Hello World URL was invalid, fixed URL to point to https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/helloworld
Resolves #1148

Fix Url & Issue #1148

---

dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java

Make the test less flaky

---

opencensus/pom.xml
opencensus/src/main/java/com/example/opencensus/Quickstart.java
pom.xml

Java version of https://github.com/GoogleCloudPlatform/golang-samples/pull/646/files.

Add OpenCensus sample code.

---

opencensus/pom.xml
opencensus/src/main/java/com/example/opencensus/Quickstart.java

OpenCensus rep tried running the sample and had some feedback.
1. Removed "_4" from metric group name.
1. Added a print message before thread sleep notifying user why the thread is waiting to complete.
1. Re-added "cleanupDaemonThreads" flag in `pom.xml` - without it, the program does not end gracefully.
1. Removed [example_code] tag, no need for it when we don't separate other sections (like the imports).

Fix OpenCensus thread cleanup error and other issues.

---

firestore/pom.xml
firestore/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
firestore/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java

Add Java snippets for the [Paginating Data with Query Cursors](https://cloud.google.com/firestore/docs/query-data/query-cursors) query.

[Firestore] Snippets for document snapshots and paginated queries. 

---

cloud-sql/mysql/servlet/pom.xml
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
cloud-sql/postgres/servlet/README.md
cloud-sql/postgres/servlet/pom.xml
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/Vote.java
cloud-sql/postgres/servlet/src/main/webapp/WEB-INF/appengine-web.xml
cloud-sql/postgres/servlet/src/main/webapp/index.jsp
pom.xml

Same as #1231, but for PostgreSQL.
Corrects some of the region tags to be MySQL-specific (these are pretty much the same for Java, but vary in some languages so separate region tags are needed).

Add Cloud SQL Postgres connectivity sample for servlets. 

---

bigquery/cloud-client/pom.xml

Oracle no longer posts updated of Java 7. Updated to Java 8. See: https://java.com/en/download/faq/java_7.xml

Updated to java version 8

---

logging/cloud-client/src/main/java/com/example/logging/ListLogs.java

Updating so that https://cloud.google.com/logging/docs/api/tasks/creating-logs#logging-list-entries-java can point to this sample in java-docs-samples instead of google-cloud-java.
Searched CS to confirm no reference to "listlogs" region tag anywhere.

Update list logs region tag.

---

errorreporting/src/main/java/com/example/errorreporting/QuickStart.java

Also hit "format file" while I was in there.

Add correct region tag for error_reporting_quickstart.

---

errorreporting/src/main/java/com/example/errorreporting/QuickStart.java
flexible/errorreporting/src/main/java/com/example/flexible/errorreporting/ErrorReportingExample.java

As with `error_reporting_quickstart`, I can remove the old tag `flex_error_reporting` once the docs change is pushed.

Add updated region tags for error_reporting_setup_java[_appengine_flex].

---

dlp/README.md
dlp/src/main/java/com/example/dlp/DeIdentification.java
dlp/src/test/java/com/example/dlp/DeIdentificationIT.java

The DLP team is in the process of expanding code samples to include features that we have launched since the initial samples were written.
This pull request adds code samples for transformations that replace pieces of sensitive info with their info types. It also updates the README to bring the CLI usage info and flags up to date.

Add  DLP replace with info type transformation examples, and update DLP README

---

.github/CODEOWNERS

Anyone else who should be added to particular sub projects is welcome to add their names as well, using other CODEOWNERS files as [examples](https://github.com/googleapis/google-cloud-python/blob/master/.github/CODEOWNERS)

Add CODEOWNERS file to automatically assign reviews to dzlier.

---

vision/label/src/test/java/com/google/cloud/vision/samples/label/LabelAppIT.java

Missed this as I was focused on the detect samples, and missed this
additional failure in labeling.

vision: relax another case comparison in vision (labels).

---

speech/cloud-client/src/main/java/com/example/speech/Recognize.java
speech/cloud-client/src/test/java/com/example/speech/RecognizeIT.java

Added the GA sample for multi-channel speech - to - text recognition.

Speech multi-channel GA

---

opencensus/src/main/java/com/example/opencensus/Quickstart.java

OpenCensus Stackdriver exporter exports every 60s by default, we need make sure main thread is running for longer than that.

OpenCensus: Update EXPORT interval

---

.kokoro/tests/diff_tests.sh
.kokoro/tests/run_tests.sh

Not all of the pom.xml are structured in the same way; therefore creating a bug to make the version consistent and adding a `version == ""` check.

[Kokoro] Update version check

---

firestore/pom.xml
firestore/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
firestore/src/main/java/com/example/firestore/snippets/model/City.java

* Bump `com.google.cloud:google-cloud-firestore` to `1.2.0` which
includes the new functionality
Currently blocked waiting on the merge and release of https://github.com/googleapis/google-cloud-java/pull/4652

Add snippet for Collection Group Query

---

container-registry/container-analysis/src/main/java/com/example/containeranalysis/PollDiscoveryOccurrenceFinished.java
container-registry/container-analysis/src/main/java/com/example/containeranalysis/Subscriptions.java
container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

Two small fixes:
- I changed the filter string that is exposed in the docs to be more precise, but used region tags to invisibly fall back to the original filter since the new one can't be easily tested
- I renamed PubSub.java to Subscriptions.java. It seems PubSub was causing warnings in the docs CLs, since the proper name is Pub/Sub

Container analysis filter

---

spanner/cloud-client/pom.xml

Right now, the Cloud Spanner docs go stale whenever we upgrade the parent to a new version. The docs are stale right now, in fact; they say `1.0.10`, but the current version is `1.0.11` ([example](https://cloud.google.com/spanner/docs/getting-started/java/)).
With this change, we can update the docs to tell customers to run something like `mvn package -Drevision=0.1.0-SNAPSHOT`, and then use `0.1.0-SNAPSHOT` throughout the examples.

Cloud Spanner: Specify the name for packaging the JAR

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

The `writeWithTransactionUsingDml` method moved $200,000 from Album1 to Album2. However, Album1 is initialized with a budget of $100,000. As a result, you couldn't work through the [getting started doc](https://cloud.google.com/spanner/docs/getting-started/java/) from start to finish.
Also, there were some unnecessary inconsistencies between `writeWithTransaction` and `writeWithTransactionUsingDml`, and neither method explicitly compared the transfer amount with the source album's existing balance.
I changed the methods so they both transfer $200,000 from Album2 to Album1. I also added explicit checks against the existing balance, and I updated the tests as needed.
(This is an updated version of #1432. @jsimonweb, PTAL.)

Cloud Spanner: Fix samples that transfer money between albums

---

appengine-java8/datastore-schedule-export/src/main/webapp/WEB-INF/web.xml

Restrict the export URL according to https://cloud.google.com/appengine/docs/standard/java/config/webxml#security-auth

Restrict the export url to admins and cron jobs

---

pubsub/cloud-client/src/main/java/com/example/pubsub/CreatePullSubscriptionExample.java
pubsub/cloud-client/src/main/java/com/example/pubsub/CreateTopicExample.java

"Subscription/topic created" messages were being printed even during failure cases. Move inside try block to fix
Fixes minor issue reported by #1419

PubSub: move topic/subscription success statement to inside try block

---

vision/beta/cloud-client/src/main/java/com/example/vision/AsyncBatchAnnotateImagesGcs.java
vision/beta/cloud-client/src/test/java/com/example/vision/DetectIT.java
vision/cloud-client/src/test/java/com/example/vision/DetectIT.java

Multiple tests in the vision suite write output to GCS.  Sadly, all wrote to the
same output prefix in a nondeterministic order, which can cause issues.  This change does two things:
1) ensures each test run uses a unique prefix
2) makes the prefix clearer to disambiguate output from the cloud_client and the beta samples.
I suspect the beta samples should be cleaned up, but it appears there's still linkages into cloud docs which is a more involved change.  This should get the
tests green once more.

vision: address flakes due to collisions.

---

vision/automl/README.md
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/DatasetApi.java
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ModelApi.java
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/PredictionApi.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/DatasetApiIT.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/PredictionApiIT.java

Fixes: 
- https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1451
- https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1452

Clean up the code and fix the sample tests

---

dataflow/templates/README.md
dataflow/templates/WordCount_metadata
dataflow/templates/pom.xml
dataflow/templates/src/main/java/com/example/dataflow/templates/WordCount.java

Code sample for the [Creating templates](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates) page.

Add WordCount template sample

---

healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java

Updating region tag names and disabling test. Filed internal bug to track broken test.

Ignore FHIR resource conditional patch test while java 8 is broken.

---

datastore/src/test/java/com/google/datastore/snippets/ConceptsTest.java

Rather than using the overloaded method that implicitly creates a
ListValue, this sample has been updated to explicitly use the ListValue.
The advantage here is that ListValue has a factory method that can take
a java.util.List.

Add explicit ListValue to datastore_array_value

---

.kvgbot.yml

Little bot that assigns issues or PRs to folks when opened if they don't already have an assignee. 
May still be a little rough around the edges.

Add config for auto-assigning issues and PRs to folks. 

---

container-registry/container-analysis/src/main/java/com/example/containeranalysis/Subscriptions.java
container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

updated the pub/sub topic to use the v1 topic id

ContainerAnalysis: Update topic id

---

speech/cloud-client/src/main/java/com/example/speech/Recognize.java

Looks like this line accidentally got removed awhile back. Putting it back in so the program properly terminates.

Add back missing break statement

---

firestore/README.md
firestore/pom.xml

When exec-maven-plugin runs the `exec:java` goal, it executes the java
program in the maven process (there currently isn't an option to fork
instead of running it in process). As a side effect of this, shutdown
hooks are not run when the program has completed running. In the case
of our Quickstart that means the daemon thread for grpc and gax do not
shutdown when the program has completed running, resulting in maven
listing all the threads that are still running and showing a stacktrace.
This change uses `exec:exec` and manually builds the java command to be
run, thereby forcing the program to be ran in a forked process and able
to use the normal shutdown process.
Attached are a logs showing the following
* Errors printed by maven when using `exec:java`
* A thread dump of the maven …

Update Firestore Quickstart to use exec:exec

---

appengine-java8/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/EchoServlet.java
appengine-java8/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/SendServlet.java
appengine-java8/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/ServerSocket.java

+ Eliminate reliance on SimpleContainerScope (it is deprecated
and has already been removed in Jetty 10).
+ Use HttpClient properly instead of SimpleContainerScope.
+ SslContextFactory belongs to HttpClient.
+ WebSocketClient uses HttpClient (recommended if you need/want SSL).
+ Use WebSocket Endpoint Annotations, not Adapter (this is also Jetty 10 compatible).
+ Use WebSocketCreator, not raw registered classes (this is also Jetty 10 compatible).
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

Saner Jetty native WebSocket usage

---

dialogflow/cloud-client/src/test/java/com/example/dialogflow/KnowledgeBaseManagementIT.java

This is mostly just an FYI to all of you, but I've changed the rouge SA role to Project Viewer, in case someone complains. This should be the final time I have to do this fix (I hope).
Otherwise, if Dialogflow is failing again, it is likely that the Test Knowledge Base was deleted and needs to be re-created and these IDs have to be updated each time.

Update KnowledgeBaseId and update rouge SA roles

---

vision/spring-framework/pom.xml

Removes an unnecessary dependency from the Spring Framework Vision sample.
This is helpful to making the documentation code fragment more accurate.

Remove extra dependency from Spring Vision Sample

---

speech/beta/pom.xml
speech/beta/src/main/java/com/example/speech/Recognize.java
speech/beta/src/test/java/com/example/speech/RecognizeIT.java

https://groups.google.com/forum/#!topic/cloud-speech-discuss/gHj5KJMH4TM

Due to API backend changes, update the samples to match

---

speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java

Staging for viewing in tutorial

refactored and added tags to infinite speech streaming sample

---

appengine-java8/analytics/README.md
appengine-java8/analytics/src/main/java/com/example/appengine/analytics/AnalyticsServlet.java
appengine-java8/analytics/src/main/webapp/WEB-INF/appengine-web.xml

Add region tags and readme for Google Analytics

---

iam/api-client/src/main/java/com/google/iam/snippets/TestPermissions.java

Changing region tag so that it uses underscores instead of hyphens

IAM: fix region tag syntax

---

run/hello-broken/src/main/java/com/example/cloudrun/App.java

Need to exclude the "fixed" version of the code from the `run_broken_service` region tag.

run/broken: exclude "improved" route from run_broken_service

---

.kokoro/tests/build_cloud_run.sh

quiet: Disable all interactive prompts when running gcloud commands
no-user-output-enabled: doesn't print the output

Quiet Kokoro build steps

---

firestore/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
firestore/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java

New samples:
* `fs_query_filter_in`
* `fs_query_filter_in_with_array`
* `fs_query_filter_array_contains_any`
Bump google-cloud-firestore to v1.29.0
Fixes b/141194359

firestore: add snipped for IN & ARRAY_CONTAINS_ANY

---

iot/api-client/manager/README.md

The readme mentions that the project ID `blue-jet-123` is in `asia-east1` but then it forgets to pass the `cloud_region` parameter which results in a `Not authorized to connect (5)` exception since the default region is `us-central1`.

Fixed missing cloud_region in MQTT example

---

automl/cloud-client/src/main/java/com/example/automl/DeleteModel.java
automl/cloud-client/src/main/java/com/example/automl/DeployModel.java
automl/cloud-client/src/main/java/com/example/automl/ImportDataset.java
automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationCreateDataset.java
automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationCreateModel.java
automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationPredict.java
automl/cloud-client/src/main/java/com/example/automl/ListModelEvaluations.java
automl/cloud-client/src/main/java/com/example/automl/TranslateCreateDataset.java
automl/cloud-client/src/main/java/com/example/automl/TranslateCreateModel.java
automl/cloud-client/src/main/java/com/example/automl/TranslatePredict.java
automl/cloud-client/src/main/java/com/example/automl/VisionClassificationCreateDataset.java
automl/cloud-client/src/main/java/com/example/automl/VisionClassificationCreateModel.java
automl/cloud-client/src/main/java/com/example/automl/VisionClassificationPredict.java

Relevant tutorial pages:
- https://cloud.google.com/translate/automl/docs/tutorial
- https://cloud.google.com/natural-language/automl/docs/tutorial
- https://cloud.google.com/vision/automl/docs/tutorial
Note: this does not update all snippet files only those in the main method, if for consistency I should update all snippets, let me know.

Rename overloaded functions to main functions for use in tutorial pages

---

kms/pom.xml

fix compile by inheriting version of compiler plugin from parent

---

bigtable/snippets/pom.xml
bigtable/snippets/src/main/java/com/example/bigtable/Filters.java
bigtable/snippets/src/main/java/com/example/bigtable/Reads.java
bigtable/snippets/src/main/java/com/example/bigtable/WriteConditionally.java
bigtable/snippets/src/main/java/com/example/bigtable/WriteIncrement.java
bigtable/snippets/src/main/java/com/example/bigtable/WriteSimple.java
bigtable/snippets/src/test/java/com/example/bigtable/FiltersTest.java
bigtable/snippets/src/test/java/com/example/bigtable/ReadsTest.java
bigtable/snippets/src/test/java/com/example/bigtable/WritesTest.java

Snippets for reading and filtering data from cloud bigtable

Read and Filter Snippets 

---

kms/README.md

added info about environment variables and enabling the API to the KMS README

KMS: update README.md

---

translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryAndModelTests.java
translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithGlossaryTests.java
translate/cloud-client/src/test/java/com/example/translate/BatchTranslateTextWithModelTests.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1950

translate: bump batch request timeouts

---

iam/api-client/pom.xml

The client library dependency in the IAM docs is currently hard-coded [1], so it won't stay up-to-date. Adding these region tags will let us insert the dependency as a GitHub include, so it will stay up-to-date automatically.
[1] https://cloud.google.com/iam/docs/quickstart-client-libraries#client-libraries-install-java

IAM: Add region tags for IAM dependency

---

vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ClassificationDeployModel.java
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ClassificationDeployModelNodeCount.java
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ClassificationUndeployModel.java
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/ObjectDetectionDeployModelNodeCount.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ClassificationDeployModelIT.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ObjectDetectionDeployModelNodeCountIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1992
Use fake model Ids and just catch the error. 
Can't yet remove the snippets as a large number of localization docs rely on these.

automl: fix old beta snippet tests

---

dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java

Potential fix for: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1991
I was unable to reproduce the flakiness locally. But based on the test being run and the error code, I think it has to do with a request timeout. So I'm adding that in and setting it to 2 minutes though it should never take that long in case that is the issue.

dialogflow: add and increase timeout to document creation for tests

---

dataproc/pom.xml
dataproc/src/main/java/Quickstart.java
dataproc/src/test/java/QuickstartTest.java
flexible/helloworld/src/main/java/com/example/flexible/helloworld/HelloServlet.java

I made the Dataproc quickstart runnable and provided instructions on how to run it with maven.

feat: add cli functionality to dataproc quickstart

---

healthcare/v1beta1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java

The tests didn't catch this because the tests use their own resource path, not the path used in HL7v2MessageList.java.

Heathcare API: fix resource path and console output for HL7v2MessageList

---

dataflow/spanner-io/pom.xml
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerGroupWriteIT.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerWriteIT.java

Updates the Spanner example to Beam 2.18. This requires the BigTable client to be excluded, as it brings in a version of OpenCensus that is incompatible with Spanner. See also https://issues.apache.org/jira/browse/BEAM-9304.
Fixes #2025

deps: update to Beam 2.18

---

bigquery/bigquerystorage/pom.xml

The arrow (de)serialization library requires a netty java property
to be set per guidance in
https://github.com/apache/arrow/tree/master/java#java-properties
Fixes: #2162

fix: bigquery/bigquerystorage needs a java property set

---

bigquery/rest/pom.xml
compute/cmdline/pom.xml
endpoints/getting-started/clients/pom.xml
endpoints/getting-started/pom.xml
flexible/cloudsql/pom.xml
flexible/postgres/pom.xml
healthcare/v1beta1/pom.xml
iot/api-client/codelab/manager/pom.xml
iot/api-client/codelab/manager/src/main/java/com/example/cloud/iot/examples/MqttExampleOptions.java
iot/api-client/end-to-end-example/pom.xml
iot/api-client/manager/pom.xml
mlengine/online-prediction/pom.xml
vision/face-detection/pom.xml

1. Update to Java 11
2. Get rid of Findbugs (no longer supported)
3. WAR's should use the latest war plugin.
4. Remvoe a bad / wrong import in MqttExampleOptions
PR replaces #2070 which was broken.

Renovate/com.google.api client google api client 1.x

---

renovate.json

"rebaseStalePrs" has been deprecated:
https://docs.renovatebot.com/configuration-options/#rebasewhen

Update renovate to use new "rebaseWhen" flag.

---

dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
dlp/src/main/java/dlp/snippets/InspectGcsFile.java

Increased the timeout period for the sample from 10 to 15 min, to resolve #2302 , #2303 , and #2317. Also refactored the Pub/Sub code in the samples to be more consistent with other samples.

Fix flaky DLP inspect tests

---

vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSetManagementIT.java
vision/product-search/cloud-client/src/test/java/vision/snippets/ProductInProductSetManagementTests.java
vision/product-search/cloud-client/src/test/java/vision/snippets/ProductManagementTests.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2355

vision: update product search tests

---

securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/CreateNotificationConfigSnippets.java
securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/DeleteNotificationConfigSnippets.java
securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/GetNotificationConfigSnippets.java
securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/ListNotificationConfigSnippets.java
securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/NotificationReceiver.java
securitycenter/src/main/java/com/google/cloud/examples/securitycenter/snippets/UpdateNotificationConfigSnippets.java

Notification feature work has been merged into v1, so we need to update the samples to match the updated version.

docs: Update securitycenter samples to v1

---

jobs/v3/src/test/java/SampleTests.java

Fixing this issue: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2261
Since there is Thread.sleep(10000) in the main, the problem is that JUnit needs to wait until the whole thing is finished.

fix: SampleTests: customAttributeSampleTest

---

dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes: #2302, #2303, #2317 
The tests keep timing out, so I followed the pattern implemented in the corresponding python samples to create a job and immediately cancel it.

Fix Flaky DLP tests

---

functions/snippets/src/main/java/com/example/functions/SlackSlashCommand.java

Forgot these in #2394 - cc @averikitsch @grant as FYI.

GCF Slack: add javadoc + region tags

---

video/beta/src/test/java/com/example/video/DetectIT.java
video/cloud-client/src/test/java/com/example/video/DetectIT.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2545
- [ x] Tests pass
- [ x] Appropriate changes to README are included in PR
- [ x] API's need to be enabled to test (tell us)
- [ x] Environment Variables need to be set (ask us to set them)

video: update .mp4 file used in test

---

functions/snippets/src/main/java/com/example/functions/BearerTokenHttp.java

**N.B:** I did *not* include tests as this is a fairly simple sample that is, at best, somewhat difficult to properly test (since it deals with GCF internals).
@kurtisvg LMK if I should change that.

Add HTTP bearer token sample

---

functions/slack/pom.xml
functions/slack/src/main/java/functions/SlackSlashCommand.java
functions/slack/src/test/java/functions/SlackSlashCommandTest.java

**N.B:** the `Slack` tutorial was only one function, so no splitting was involved.

GCF file split (munge): Slack

---

healthcare/v1/pom.xml
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetCreate.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetDeIdentify.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetDelete.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetGet.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetGetIamPolicy.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetList.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetPatch.java
healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetSetIamPolicy.java
healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java

NOTE: This PR is fundamentally a branch of https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/healthcare/v1beta1 to v1. The code has been previously reviewed in this repository.
Updates for fhir/, dicom/, and hl7v2/ are coming but I wanted to keep the PRs separate.
After all healthcare/v1 samples are approved, I'll delete the existing v1beta1/ directory.

healthcare API: update datasets/ samples from v1beta1 to v1

---

dataflow/flex-templates/streaming_beam_sql/pom.xml

Hello,
I tried to run the example and unfortunately, there were problems with them. I got the following exception:
```
Executing: java -cp /template/pipeline.jar org.apache.beam.samples.StreamingBeamSQL --region=us-central1 --inputSubscription=ratings --project=polidea-airflow --serviceAccount=198907790164-compute@developer.gserviceaccount.com --templateLocation=gs://dataflow-staging-us-central1-198907790164/staging/template_launches/2020-04-20_14_05_05-10138518335536770368/job_object --tempLocation=gs://dataflow-staging-us-central1-198907790164/tmp --stagingLocation=gs://dataflow-staging-us-central1-198907790164/staging --outputTable=polidea-airflow:beam_samples.streaming_beam_sql --runner=DataflowRunner --jobName=streaming-beam-sql-20200420-230503
Error: A JNI error has occurred, please …
```

Remove signatures from UberJAR for Beam SQL

---

spanner/cloud-client/pom.xml

Use the libraries-bom for the Spanner cloud client samples.
Fixes #2718

fix: use libraries-bom

---

jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java

Meant to reduce this before submitting https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2721. I had one test at 5 seconds and the rest at 1 second, just to see if it made a difference when the tests ran, but 1 second is enough.

Reduce wait on CommuteSearchSample to 1 second from 5.

---

functions/http/http-form-data/pom.xml
functions/http/http-form-data/src/main/java/functions/HttpFormData.java
functions/http/http-form-data/src/test/java/functions/HttpFormDataTest.java
functions/http/http-form-data/src/test/java/functions/MockHttpPart.java

* Remove unused dependencies from `pom.xml`.
* Remove `@MultipartConfig`, an attempted workaround for a bug in multipart handling that unfortunately doesn't help.
* Use conventional spelling for `logger` field. It is not a constant so it should not be spelled `LOGGER`.
* Use `Map.forEach` to iterate over a map.
* Use `List.of(...)` and `Map.of(...)` instead of constructing lists and maps with statements.
* Remove unnecessary `throws IOException`.
Multipart handling is currently broken on GCF. A fix has been prepared but will not be active until it is rolled out. This sample won't work on GCF until that happens.

Simplify the `http-form-data` sample and use Java 11 features.

---

functions/http/send-http-request/src/main/java/functions/SendHttpRequest.java

The Apache `httpclient` offers a more configurable implementation, but `java.net.httpClient` seems to [support connection pooling as well.](https://stackoverflow.com/questions/53617574/how-to-keep-connection-alive-in-java-11-http-client)
I suspect this simpler, automatic implementation is fine for our docs - but I'll let @kurtisvg and @labtopia be the judges of that.

Add connection pooling comment + region tag

---

kms/src/main/java/kms/GetKeyVersionAttestation.java
kms/src/main/java/kms/UpdateKeyRemoveRotation.java
kms/src/test/java/kms/SnippetsIT.java

Add two new samples: get attestation on an hsm key, remove rotation schedule from an existing key.

kms: add attestation and rotation schedule sample

---

spanner/cloud-client/pom.xml
spanner/jdbc/pom.xml
spanner/leaderboard/complete/pom.xml
spanner/leaderboard/step4/pom.xml
spanner/leaderboard/step5/pom.xml
spanner/leaderboard/step6/pom.xml

As noted in #2748, the Spanner samples should use the `libraries-bom:5.2.0` to import dependencies.

deps: use libraries bom for dependencies

---

appengine-java11/spanner/pom.xml
appengine-java8/spanner/pom.xml

Changes the appengine examples to use the latest version of the libraries-bom.

deps: use libraries bom for spanner on appengine

---

functions/concepts/file-system/src/main/java/functions/FileSystem.java

Otherwise we have to call String.format. This also fixes a place where
we weren't in fact calling String.format even though we were using the
%n format specifier.

Use a PrintWriter to make printf available.

---

functions/firebase/firestore/pom.xml
functions/helloworld/helloworld/pom.xml

functions: shrink example pom sample

---

functions/helloworld/kotlin-helloworld/pom.xml

@saturnism FYI - hopefully I got everything here?
(The removed section seemed a bit small. 🙂 )

functions: shrink Kotlin example POM

---

functions/concepts/scopes/src/main/java/functions/Scopes.java

[functions/scopes]: use CONSTANT_CASE for variable

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDelete.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDeletePurge.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGet.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetPatientEverything.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceListHistory.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourcePatch.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchPost.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java

Fixes b/155972712
Also:
* Removed skip from FhirResourcePatch test because it now works
* Changed instances of "fhir-id" comment to "resource-id" for clarity
* Changed some outputs for clarity/correctness
* Changed patientType to resourceType in tests for correctness
* Add a new resourcePath variable to tests for search GET/POST
* Remove 404 check for delete resource--server returns 200 even on deleted resources and never returns 404

healthcare API: add resource types to remaining FHIR resource code

---

.kokoro/tests/run_tests.sh
firestore/README.md
firestore/src/test/java/com/example/firestore/BaseIntegrationTest.java

fix: firestore projectId is hardcoded in the tests

---

jobs/v4/cts_v4_secrets.txt
jobs/v4/pom.xml
jobs/v4/src/main/java/com/example/jobs/CommuteSearchJobs.java
jobs/v4/src/main/java/com/example/jobs/CustomRankingSearchJobs.java
jobs/v4/src/main/java/com/example/jobs/HistogramSearchJobs.java
jobs/v4/src/main/java/com/example/jobs/JobSearchAutoCompleteJobTitle.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateClientEvent.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateCompany.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJobCustomAttributes.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateTenant.java
jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteCompany.java
jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteJob.java
jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteTenant.java
jobs/v4/src/main/java/com/example/jobs/JobSearchGetCompany.java
jobs/v4/src/main/java/com/example/jobs/JobSearchGetJob.java
jobs/v4/src/main/java/com/example/jobs/JobSearchGetTenant.java
jobs/v4/src/main/java/com/example/jobs/JobSearchListCompanies.java
jobs/v4/src/main/java/com/example/jobs/JobSearchListJobs.java
jobs/v4/src/main/java/com/example/jobs/JobSearchListTenants.java

Fixes #2970
Looks like job posting by default was expired and deleted in 30 days.
That's why this happens once in a month.
I found out that I can customize the expiration date in job posting, and created one job for testing that expires in 40 years from now.

fix: talent solution v4 samples tests

---

appengine-java11/README.md
appengine-java11/http-server/README.md
appengine-java11/kotlin-ktor/README.md
appengine-java11/micronaut-helloworld/README.md
appengine-java11/quarkus-helloworld/README.md
appengine-java11/sparkjava-helloworld/README.md
appengine-java11/springboot-helloworld/README.md
appengine-java11/tasks/README.md
appengine-java11/vertx-helloworld/README.md

Modifies the deployment methods to the new source deploy functionality
for those applications that do not have a dependency on the
appengine-simple-jetty-main artifact.
The public GAE documentation reference these samples and will reflect these changes as well.

Update READMEs with source deploy functionality

---

bigtable/cassandra-migration-codelab/pom.xml
bigtable/hbase/snippets/pom.xml
bigtable/pom.xml
bigtable/snippets/pom.xml

Upgraded bigtable to 1.13.0 and reordered pom files to have test dependencies last
Opening in favor of #2901

chore(deps): upgrade bigtable dep to 1.13.0 and reorganize dependencies

---

dlp/README.md
dlp/pom.xml
dlp/src/main/java/dlp/snippets/InfoTypesList.java
dlp/src/main/java/dlp/snippets/QuickStart.java
dlp/src/main/java/dlp/snippets/RedactImageFile.java
dlp/src/test/java/dlp/snippets/RedactTests.java

Fixes some problems with the DLP readme and the examples referenced from it.
* Fix `pom.xml` so we produce the expected jar with dependencies. 
* Fix package names in CLI examples to match what actually exists.
* Add notes to README reminding users they need to replace the projectId vars in the samples before running
* Make InfoTypesList example runnable
* Fix RedactImageFile example to use an existing image file by default, update the readme to match the sample code that exists. 
Internal bug: b/156125412

Fix issues with DLP readme and samples used in it

---

vision/automl/pom.xml
vision/automl/src/main/java/com/google/cloud/vision/samples/automl/DatasetApi.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/DatasetApiIT.java

bug: fix importData sample in order to bump libraries-bom version

---

dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
dlp/src/test/java/dlp/snippets/InspectTests.java

https://cloud.google.com/dlp/docs/concepts-infotypes
Fixes <no github issue associated>
- [yes, except where consistency made more sense] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [yes] Appropriate changes to README are included in PR
- [yes] Tests pass (`mvn -P lint clean verify`)
- [yes] Please **merge** this PR for me once it is approved.

Add Java code sample for concepts-infotypes

---

dlp/src/main/java/dlp/snippets/DeIdentifyWithDateShift.java
dlp/src/main/java/dlp/snippets/DeIdentifyWithFpe.java
dlp/src/main/java/dlp/snippets/DeIdentifyWithMasking.java
dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
dlp/src/main/java/dlp/snippets/InspectGcsFile.java
dlp/src/main/java/dlp/snippets/InspectImageFile.java
dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
dlp/src/main/java/dlp/snippets/InspectString.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
dlp/src/main/java/dlp/snippets/InspectTextFile.java
dlp/src/main/java/dlp/snippets/JobsCreate.java
dlp/src/main/java/dlp/snippets/JobsList.java
dlp/src/main/java/dlp/snippets/QuickStart.java
dlp/src/main/java/dlp/snippets/ReIdentifyWithFpe.java
dlp/src/main/java/dlp/snippets/RedactImageFile.java
dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
dlp/src/main/java/dlp/snippets/TemplatesCreate.java
dlp/src/main/java/dlp/snippets/TemplatesList.java
dlp/src/main/java/dlp/snippets/TriggersCreate.java
dlp/src/main/java/dlp/snippets/TriggersList.java
dlp/src/test/java/dlp/snippets/JobsTests.java
dlp/src/test/java/dlp/snippets/TemplatesTests.java
dlp/src/test/java/dlp/snippets/TriggersTests.java

Adds "locations/global" to the parent field specified when calling DLP api. This makes the job name produced consistent with the internal usage and, importantly to these samples, consistent with the job name used in the pubsub message indicating that the job is complete. This should fix certain tests timing out after 15 minutes waiting for the wrong pubsub message.
fixes internal bug b/158100365 (partially: only for Java samples)
Also see internal bug b/158026949 for more context.

Include locations/global in parent field to fix samples

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java

fix: include different ways to delete data in sample

---

dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156971890

create Java code sample for omit email with specific domain

---

dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156966396

Create Java code sample for omit finding with substring

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java

Currently the [public docs](https://cloud.google.com/spanner/docs/use-oss-jdbc) don't point to the samples on GitHub so adding the relevant region tags here to enable the docs to point to these samples.
Also made changes to the following samples to match those of the existing samples:
- InsertDataExample.java to use autocommit to be equivalent to [existing sample](https://cloud.google.com/spanner/docs/use-oss-jdbc#use_a_transaction_in_autocommit_mode_to_add_and_delete_rows).
- BatchDmlExample.java to turn off autocommit to be equivalent to [existing sample](https://cloud.google.com/spanner/docs/use-oss-jdbc#use_a_batch_transaction_to_add_and_delete_rows).
If the changes in 3d5e6158e81de4ffce786e5699f1817eaf2cf168 don't make sense, happy to revert.

chore: add region tags for Spanner JDBC samples

---

dlp/src/test/java/dlp/snippets/InspectTests.java

Update DLP inspect tests to fail properly, instead of timing out after 15 minutes and passing. 
Also remove some broken code that tried to cancel early. 
Fixes internal bug b/158026949

Fix DLP inspect tests to fail on timeout

---

dlp/README.md

Fixes b/144646990 - minor documentation fix.

fix Gandalf phone number - valid phone numbers cannot start with 1.

---

dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156969706

Create Java code sample for omit names that are also an email

---

dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156972858

Create Java code sample for omit domain names that are an email

---

dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
dlp/src/main/java/dlp/snippets/InspectGcsFile.java
dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
dlp/src/test/java/dlp/snippets/InspectTests.java
dlp/src/test/java/dlp/snippets/RiskAnalysisTests.java

Fixes internal bug b/158322296
1. Update DLP java tests to use unique topic/subscription for each test. This should help avoid flakes caused by concurrent test runs competing for resources. The PUBSUB_ env vars are still required, but used as a prefix instead of as a shared single topic/sub. 
2. Properly close the subscription in each sample before returning. This avoids a race condition with topic/subscription cleanup, in addition to being good hygiene. 

Fix pubsub handling for DLP samples and tests

---

.kokoro/lint/common.cfg
.kokoro/lint/presubmit.cfg
.kokoro/static_analysis/common.cfg
.kokoro/static_analysis/presubmit.cfg
.kokoro/tests/run_lint.sh
.kokoro/tests/run_static_analysis.sh

Adds two checks - "lint" that runs checkstyle, and "static analysis" that runs spotbugs and pmd
Fixes #2790

Add separate lint and static anaylsis tests for presubmits.

---

firestore/src/main/java/com/example/firestore/Quickstart.java
firestore/src/test/java/com/example/firestore/BaseIntegrationTest.java

These lines of code are referenced in this quickstart guide:
https://cloud.google.com/firestore/docs/quickstart-servers#java_1
The docs suggest that the credentials file will be read from the env variable, but that doesn't seem to be the case.  This change sets the credentials in the builder, using a Google credential utility to read it from the file specified by the env variable.

Fix java quickstart

---

dlp/src/main/java/dlp/snippets/InspectImageFileAllInfoTypes.java
dlp/src/main/java/dlp/snippets/InspectImageFileListedInfoTypes.java
dlp/src/test/java/dlp/snippets/InspectTests.java

To be linked from https://cloud.google.com/dlp/docs/inspecting-images
Fixes #issue
- [yes] Tests pass (`mvn -P lint clean verify`)
- [yes] Please **merge** this PR for me once it is approved.

Add Java code samples for image inspection

---

dlp/src/main/java/dlp/snippets/DeIdentifyWithSimpleWordList.java
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java

To be linked from https://cloud.google.com/dlp/docs/creating-custom-infotypes-dictionary#simple_word_list
Fixes #issue
It's a good idea to open an issue first for discussion.
[yes] I have followed Sample Format Guide
[yes] pom.xml parent set to latest shared-configuration
[nothing new] Appropriate changes to README are included in PR
[nothing new] API's need to be enabled to test (tell us)
[nothing new] Environment Variables need to be set (ask us to set them)
[yes] Tests pass (mvn -P lint clean verify)
(Note- Checkstyle passing is required; Spotbugs, ErrorProne, PMD, etc. ERROR's are advisory only)
[yes] Please merge this PR for me once it is approved.

Create Java code sample for wordList example

---

dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java
dlp/src/test/java/dlp/snippets/InspectTests.java

To be linked from https://cloud.google.com/dlp/docs/creating-custom-infotypes-regex#regex-example
Fixes #issue
It's a good idea to open an issue first for discussion.
[yes] I have followed Sample Format Guide
[yes] pom.xml parent set to latest shared-configuration
[nothing new] Appropriate changes to README are included in PR
[nothing new] API's need to be enabled to test (tell us)
[nothing new] Environment Variables need to be set (ask us to set them)
[yes] Tests pass (mvn -P lint clean verify)
(Note- Checkstyle passing is required; Spotbugs, ErrorProne, PMD, etc. ERROR's are advisory only)
[yes] Please merge this PR for me once it is approved.

 Create Java code sample for custom regex 

---

.kokoro/tests/run_static_analysis.sh
.kokoro/tests/run_tests.sh

- Adds "compile" for errorprone + spotbugs to work.
- Removes lint profile from main tests
FYI: Spotbugs will show errors, but will continue to pass until java-repo-tools is updated.

Add "compile" goal to static check

---

dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
dlp/src/main/java/dlp/snippets/InspectGcsFile.java
dlp/src/main/java/dlp/snippets/InspectImageFile.java
dlp/src/main/java/dlp/snippets/InspectImageFileListedInfoTypes.java
dlp/src/main/java/dlp/snippets/InspectString.java
dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
dlp/src/main/java/dlp/snippets/InspectStringCustomHotword.java
dlp/src/main/java/dlp/snippets/InspectStringCustomOmitOverlap.java
dlp/src/main/java/dlp/snippets/InspectStringMultipleRules.java
dlp/src/main/java/dlp/snippets/InspectStringOmitOverlap.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
dlp/src/main/java/dlp/snippets/InspectStringWithoutOverlap.java
dlp/src/main/java/dlp/snippets/InspectTextFile.java
dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java

Fix some minor formatting inconsistencies across my last several commits and other samples in the same group.

Formatting consistency pass for DLP Inspect* samples

---

dlp/src/main/java/dlp/snippets/DeIdentifyTableWithFpe.java
dlp/src/main/java/dlp/snippets/DeIdentifyTextWithFpe.java
dlp/src/main/java/dlp/snippets/ReIdentifyTableWithFpe.java
dlp/src/main/java/dlp/snippets/ReIdentifyTextWithFpe.java
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java

To be linked from https://cloud.google.com/dlp/docs/pseudonymization
Fixes #issue
- [yes] Tests pass (`mvn -P lint clean verify`)
- [yes] Please **merge** this PR for me once it is approved.

Add Java code samples for fpe

---

dlp/src/main/java/dlp/snippets/InspectWithHotwordRules.java
dlp/src/test/java/dlp/snippets/InspectTests.java

To be linked from https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood#hotword_example_match_medical_record_numbers
Fixes #issue
It's a good idea to open an issue first for discussion.
[yes] I have followed Sample Format Guide
[yes] pom.xml parent set to latest shared-configuration
[nothing new] Appropriate changes to README are included in PR
[nothing new] API's need to be enabled to test (tell us)
[nothing new] Environment Variables need to be set (ask us to set them)
[yes] Tests pass (mvn -P lint clean verify)
(Note- Checkstyle passing is required; Spotbugs, ErrorProne, PMD, etc. ERROR's are advisory only)
[yes] Please merge this PR for me once it is approved.

 Create Java code sample for custom infotype likelihood

---

dlp/src/main/java/dlp/snippets/InspectGcsFile.java
dlp/src/main/java/dlp/snippets/InspectGcsFileWithSampling.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/157050959

Inspect gcs sample b 157050959

---

monitoring/cloud-client/src/main/java/com/example/monitoring/QuickstartSample.java

- Change the quick start metric to `custom.googleapis.com/my_metric`
- Change the type to "gce_instance".
Justification: Cloud monitoring api team discourage using "global" resource type for custom metric, and to align the sample, I change the metric type also.

fix-it(Cloud Monitoring Api): Change the quick start documentation.

---

appengine-java8/bigquery/README.md

The enablement link appears to be no longer necessary and has been broken for quite some time.
Fixes product names and broken link in the README
- [ NA] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ NA] `pom.xml` parent set to latest `shared-configuration`
- [ NA] Appropriate changes to README are included in PR
- [ NA] API's need to be enabled to test (tell us)
- [ NA] Environment Variables need to be set (ask us to set them)
- [ NA] **Tests** pass:   `mvn clean verify` **required**
- [ NA] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ NA] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ X] Please **merge** this PR for me once it is …

Fixes product names and a link reference

---

dlp/src/main/java/dlp/snippets/DeIdentifyWithInfoType.java
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java

To be linked from https://cloud.google.com/dlp/docs/redacting-sensitive-data
Fixes #issue
- [yes] **Tests** pass:   `mvn clean verify` **required**
- [yes] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [fails] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [yes] Please …

Add Java code samples for replacement with infotype

---

dlp/src/main/java/dlp/snippets/DeIdentifyWithExceptionList.java
dlp/src/main/java/dlp/snippets/DeIdentifyWithSimpleWordList.java
dlp/src/main/java/dlp/snippets/InspectWithCustomRegex.java
dlp/src/main/java/dlp/snippets/InspectWithHotwordRules.java

Clean up some samples that got added with the old way of setting the parent field. See internal bug b/158100365 for context.

Clean up some ProjectName uses in DLP

---

dlp/src/main/java/dlp/snippets/DeIdentifyTableBucketing.java
dlp/src/main/java/dlp/snippets/DeIdentifyTableConditionInfoTypes.java
dlp/src/main/java/dlp/snippets/DeIdentifyTableConditionMasking.java
dlp/src/main/java/dlp/snippets/DeIdentifyTableInfoTypes.java
dlp/src/main/java/dlp/snippets/DeIdentifyTableRowSuppress.java
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java

To be linked from https://cloud.google.com/dlp/docs/examples-deid-tables
Fixes #issue
- [yes] **Tests** pass:   `mvn clean verify` **required**
- [yes] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [fails] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [yes] Please **merge** …

Add Java code samples for de-id tabular data

---

asset/cloud-client/pom.xml
asset/cloud-client/src/main/java/com/example/asset/SearchAllIamPoliciesExample.java
asset/cloud-client/src/main/java/com/example/asset/SearchAllResourcesExample.java
asset/cloud-client/src/test/java/com/example/asset/Search.java

[asset] feat: add samples for SearchAllResources and SearchAllIamPolicies

---

.kokoro/lint/common.cfg

Update lint check to use Java 11 image.

---

appengine-java11/guestbook-cloud-firestore/pom.xml

@lesv since these are separate projects in the same repo, more granular PRs will help isolate issues

update to BOM 7

---

functions/slack/pom.xml
functions/slack/src/main/java/functions/SlackSlashCommand.java
functions/slack/src/test/java/functions/SlackSlashCommandTest.java

Cherry-picked and rebased from @eamonnmcmanus's https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2854
Instead of using Whitebox, use package-private constructor overloads
to supply the values needed by the test.

Remove PowerMock from the Slack GCF sample.

---

jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
jobs/v4/src/test/java/JobSearchCreateTenantTest.java
jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
jobs/v4/src/test/java/JobSearchDeleteTenantTest.java

Fixes the concurrency error which mentioned in #3206

samples: added UUID to prevent concurreny errors

---

tasks/src/main/java/com/example/task/CreateHttpTask.java
tasks/src/main/java/com/example/task/CreateHttpTaskWithToken.java
tasks/src/main/java/com/example/task/CreateQueue.java
tasks/src/main/java/com/example/task/DeleteQueue.java
tasks/src/main/java/com/example/task/ListQueues.java
tasks/src/test/java/com/example/task/CreateHttpTaskIT.java
tasks/src/test/java/com/example/task/CreateQueueIT.java
tasks/src/test/java/com/example/task/DeleteQueueIT.java
tasks/src/test/java/com/example/task/ListQueuesIT.java

Environment Variables need to be set:
- GOOGLE_CLOUD_PROJECT to the project id

add Java snippets for creating, listing, and deleting queues

---

iap/src/main/java/com/example/iap/BuildIapRequest.java
iap/src/test/java/com/example/iap/BuildAndVerifyIapRequestIT.java

chore(iap): cleanup spotbugs warnings

---

healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java

healthcare API: simplify response for HL7v2MessageList

---

dataproc/src/main/java/CreateClusterWithAutoscaling.java
dataproc/src/main/java/SubmitHadoopFsJob.java
dataproc/src/test/java/CreateClusterWithAutoscalingTest.java
dataproc/src/test/java/InstantiateInlineWorkflowTemplateTest.java
dataproc/src/test/java/SubmitHadoopFsJobTest.java

Adding a sample + test for submitting a HadoopFS command using the Java client library.
Adding a sample + test for creating a Dataproc cluster with autoscaling configured.
Follow-up to #2949

feat: adding hadoopfs and autoscaling samples

---

automl/cloud-client/src/main/java/com/example/automl/LanguageEntityExtractionPredict.java
automl/cloud-client/src/main/java/com/example/automl/LanguageSentimentAnalysisPredict.java
automl/cloud-client/src/main/java/com/example/automl/LanguageTextClassificationPredict.java

samples:added docs links to predict samples

---

dialogflow/cloud-client/pom.xml
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentAudio.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentKnowledge.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentStream.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentTexts.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithSentimentAnalysis.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentWithTextToSpeechResponse.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/DocumentManagement.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/IntentManagement.java
dialogflow/cloud-client/src/main/java/com/example/dialogflow/KnowledgeBaseManagement.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateDocumentTest.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/CreateKnowledgeBaseTest.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentKnowledgeTest.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentStreamIT.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithAudioTest.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/DetectIntentWithSentimentAndTextToSpeechIT.java
dialogflow/cloud-client/src/test/java/com/example/dialogflow/IntentManagementIT.java

Fixes #3207 
I will refactor IntentMgmt.java and break them down into individual files in different PR.

samples: refactor dialogflow for 2.1.0

---

vision/automl/src/test/java/com/google/cloud/vision/samples/automl/PredictionApiIT.java

Fixes #2469 
I was able to reproduce the error with the following steps:
1. undeploy model
2. run predict the test --> which will go into setup of the test (tries to deploy the model again) and since deploying model takes 5-30 min. 
Then, the actual test runs while the deployment is not finished.

samples: increased wait time for undeployed model prediction

---

language/cloud-client/README.md

When run with the existing command it returns an error:
```
Error: Could not find or load main class com.example.language.QuickstartSample
```

Use correct java flag for Language API readme

---

automl/beta/src/test/java/com/example/automl/CancelOperationTest.java

samples: fixed automl cancel operation bug

---

functions/helloworld/hello-http-gradle/build.gradle
functions/helloworld/hello-http-gradle/src/main/java/functions/HelloHttp.java

Include the `package` declaration in the Java file,
and exclude the copyright notice in `build.gradle`.

Adjust region tags for Gradle functions sample.

---

run/markdown-preview/editor/pom.xml
run/markdown-preview/editor/src/main/java/com/example/cloudrun/RenderController.java

Update token creation for Cloud Run Markdown sample

---

asset/cloud-client/src/main/java/com/example/asset/ListAssetsExample.java
asset/cloud-client/src/test/java/com/example/asset/ListAssets.java

Add sample code for Cloud Assets Inventory ListAssets v1p5beta1 APIs.

---

video/beta/src/main/java/com/example/video/StreamingAutoMlClassification.java
video/beta/src/main/java/com/example/video/TextDetection.java
video/beta/src/test/java/com/example/video/DetectIT.java
video/beta/src/test/java/com/example/video/StreamingAutoMlClassificationIT.java

Fixes #3427 
Video StreamingAutoMlClassification sample sporadically fails due to Bad Gateway error from server side.
It is also known issue in python. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/4a251779251da3f1a114318c374b1458f6479025/video/cloud-client/analyze/beta_snippets_test.py#L164
I tried to use same approach on this flaky test.
Video Text Detection sometimes throws TimeoutException 
```
com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture@52500920[status=PENDING, info=[inputFuture=[com.google.api.core.ApiFutureToListenableFuture@117e0fe5], function=[com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction@18a3962d]]]
``` 
it is also related to server side issue that I do not know of. In that case, I added try/catch to catch specific …

samples: fix flaky video stream and text Detection tests

---

spanner/cloud-client/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java

Adds an example for how to set custom timeout and retry settings for the Spanner client.

docs: add sample for setting timeout and retry settings

---

logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java

I was able to reproduce Linked bug's error by running loggingIT test multiples times. 
Looks like timeout 30000 might be short for this test.
Average time took to run LoggingIT ~ about 20sec
Longest was 35 sec. 
I think increasing to 45 secs should fix this problem otherwise increase to 60sec.

samples: fixed flaky test of logging

---

dataflow/flex-templates/streaming_beam_sql/metadata.json

The service uses RE2 and doesn't support negative lookaheads

dataflow: removed negative lookahead

---

run/authentication/src/main/java/com/example/cloudrun/Authentication.java

This change sets up the Cloud Run sample to be reused for Cloud Functions. Cross-product reuse on identity token minting has been done along these lines for Node.js and Golang and is in progress for Python.
Once documentation is updated the intention is to delete the current Functions sample, this is planned for August/Early September.

refactor(run): use the Cloud Run authentication sample for Cloud Functions

---

spanner/cloud-client/pom.xml
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

The database restore operation could be given up by the test if it fails too many times with an error indicating that too many restore operations are running. The test for listing database operations would still be executed and would then look for the optimize operation of the previous restore. This operation would not be found, as the restore operation was skipped.
Fixes #3541

fix: only run test if restore succeeded

---

dataflow/flex-templates/kafka_to_bigquery/metadata.json
dataflow/flex-templates/streaming_beam_sql/metadata.json
dataflow/templates/WordCount_metadata

Fixes #3514 -- making parameters consistent (camelCase for Java, and snake_case for Python).
Both snake_case and camelCase names are supported.

dataflow: have consistent metadata names in camelCase

---

iam/api-client/src/main/java/iam/snippets/QuickstartV2.java

Saying "member:user@example.com" isn't helpful, since the prefix needs to be "user", "serviceAccount", or "group", not "member'"
Since this is a quickstart, we should just pick one type and stick with that. "user" is a good way to demonstrate core functionality, so I picked that type.

Specify member type

---

iam/api-client/pom.xml

This region tag will be used in the Java install section of the new [IAM quickstart](https://cloud.devsite.corp.google.com/iam/docs/quickstart-client-libraries?nocache=717387#client-libraries-install-java).

Add region tag for Quickstart dependencies

---

run/helloworld/.dockerignore
run/helloworld/Dockerfile

The docs will be showing both Jib and Dockerfile builds. 

Add Dockerfile for Cloud Run quickstart

---

functions/firebase/firestore-reactive/src/main/java/functions/FirebaseFirestoreReactive.java
functions/firebase/firestore-reactive/src/test/java/functions/FirebaseFirestoreReactiveTest.java

As requested by @jskeet
(N.B: this isn't _actually_ broken on Cloud Functions itself, but it depends on undocumented behavior.)

chore(functions/firebase): Add infinite-loop guard + test

---

functions/slack/pom.xml
functions/slack/src/main/java/functions/SlackSlashCommand.java
functions/slack/src/test/java/functions/SlackSlashCommandTest.java

- Use URL encoding instead of JSON for incoming (from Slack) requests
- Fix improperly formatted outgoing (to Slack) JSON response
- Move to official (and largely identical) Slack API package
cc @jskeet as FYI

chore(functions/slack): update Slack sample

---

spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java

Replaces the reference to the deprecated `SpannerPool#closeSpannerPool()` method with the equal in behavior `ConnectionOptions#closeSpanner()` method.

chore: remove reference to deprecated class

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopUsingOnlyJdbcExample.java

The current transaction should be explicitly rollbacked after an Aborted error to ensure that the connection will start a new transaction on the next statement.
The current version of the JDBC driver does not require the user to rollback the transaction after an `Aborted` error, but it is customary to do so. Future versions of the JDBC driver might also require a `rollback()` call after an `Aborted` error.

fix: explicitly rollback transaction after abort

---

.kokoro/static_analysis/common.cfg

Update static analysis image to include java 8 and 11 runtimes.

---

flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPublish.java
flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPush.java

These two samples aren't published on any Pub/Sub page, so their region tags should lead with `gae_`. 
Page they appear: https://cloud.google.com/appengine/docs/flexible/java/writing-and-responding-to-pub-sub-messages
Will submit (cl/333179348) to update docs when this is merged.

gae: lead with gae_ in region tags

---

dataflow/README.md
dataflow/encryption-keys/README.md
dataflow/flex-templates/README.md
dataflow/flex-templates/kafka_to_bigquery/README.md
dataflow/flex-templates/streaming_beam_sql/README.md
dataflow/templates/README.md

Updating the "Open in Cloud Shell" links to clone the repo and open the correct README file

dataflow: update "Open in Cloud Shell" links

---

spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

Temporarily skip `listBackupOperations` test.
Fixes #3817

fix: skip listBackupOperations test

---

spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

Close the `Spanner` instance after all tests have been executed. This ensures that all sessions that have been opened by the tests will be deleted on the backend.

fix: close Spanner instance after tests

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

Adds samples for the new `NUMERIC` data type in Cloud Spanner.

docs: add numeric samples for Spanner

---

pubsub/spring/src/main/java/demo/PubSubApplication.java

Use a more generic name for the message channel because it's used for both inbound and outbound communication in the sample. These were the choices I considered.

Pub/Sub: rename input Spring message channel and lint

---

appengine-java8/bigtable/pom.xml

Addresses issue as described here: https://github.com/googleapis/java-bigtable-hbase/issues/2039

Update POM to use smaller Bigtable dependency

---

.github/CODEOWNERS

cDPE Observability team owns logging and error reporting APIs and samples
Fixes #4011

chore: add observability team to codeowners

---

.github/blunderbuss.yml

Update blunderbuss to use java-samples-reviewers team

---

SAMPLE_FORMAT.md

@lesv  Most notably, Java has "method arguments" instead of "function parameters", but overall good advice.

clean up grammar and spelling

---

functions/spanner/src/test/java/functions/HelloSpannerTest.java

`MockitoAnnotations.initMocks(Object)` is deprecated and should be replaced with `openMocks(Object)` and a call to `close()` on the returned `AutoClosable`.

chore: remove call to deprecated method

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
spanner/cloud-client/src/test/java/com/example/spanner/AsyncExamplesIT.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java

The Spanner client has the option to automatically throttle the number of administrative requests that are generated in order to avoid hitting the [hard limit that Spanner has of max 5 admin requests per second](https://cloud.google.com/spanner/quotas#administrative_limits).
Updates #4144

test: auto-throttle admin requests

---

spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java

Delete stale test databases that have the same name as those being created by this test.
Fixes #4103

test: delete stale test databases

---

cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java

- Added example connection URL to SQL Server sample
- Added instructions for forcing connection with Private IP to MySQL and Postgres samples
- Updated renovate.json to only update driver if new jre8 versions are released.

chore: updates to Cloud SQL samples

---

bigtable/spark/build.sbt
renovate.json

We are pinning versions to dataproc 1.4, so do not automatically update deps.
Updated config following: https://docs.renovatebot.com/configuration-options/#enabled

chore(bigtable_spark): rollback scala update and update renovate config

---

functions/helloworld/helloworld-gradle/build.gradle

The current ones don't match the commands in the docs; this fixes that.
This fixes **b/177219806**.

chore(functions): use correct Gradle argument names

---

pubsub/spring/pom.xml

The dependency bot is not pulling in the .RELEASE version for the samples in `pubsub/spring`. This PR temporarily fixes the dependency until the bot is updated. 
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies

chore(deps): update spring boot to v2.3.8.RELEASE

---

cloud-sql/r2dbc/pom.xml

The PR replaces the dependencies on `spring-data-r2dbc` and `r2dbc-pool` with `spring-boot-starter-data-r2dbc` (already version managed by Spring Boot), which includes those dependencies.
This PR also removes other version numbers for dependencies which are already version managed via Spring Boot to simplify and future-proof the `pom.xml` file.

Use spring-boot-starter-data-r2dbc and version manage as little dependencies as possible

---

.github/stale.yml
.kokoro/tests/run_tests.sh

buildcop => flakybot

---

pubsub/spring/pom.xml

See https://cloud.google.com/pubsub/docs/spring#install-spring-integration-channel-adapters-for-pubsub. 
We are missing an opening `<dependencies>`.
Fixing internal b/178796972

fix: region tag open and close

---

eventarc/README.md
eventarc/audit-storage/src/main/java/com/example/cloudrun/EventController.java

Uses "Cloud Storage" instead of "GCS" for Eventarc Audit quickstart per branding guidelines.
See internal b/180109929

fix: update eventarc storage name

---

bigtable/cassandra-migration-codelab/pom.xml
bigtable/hbase/snippets/pom.xml
bigtable/memorystore/pom.xml

not sure why renovate didn't update the rest in the previous PR, updating manually

deps: update bigtable to 1.21.0

---

cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/CloudKmsEnvelopeAead.java

@thaidn mentioned that there's a plan to deprecate the API we're using for envelope encryption in our Java sample. Updating this with the new, preferred method
- [x ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [x ] `pom.xml` parent set to latest `shared-configuration`
- [x ] Appropriate changes to README are included in PR

fix: replace deprecated envelope encryption method in Tink sample

---

storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/CreateTransferClient.java
storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RetryHttpInitializerWrapper.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/CheckLatestTransferOperationTest.java
storage/storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/CheckTransferJobTest.java

Although they won't be used as a dependency for the other samples anymore, these samples are still needed on the [Creating a Client](https://cloud.google.com/storage-transfer/docs/create-client) page, so I've restored them, this time with proper region tags (i added them to the tracker).

restore transfer service initializer samples with proper region tags

---

cloud-sql/mysql/client-side-encryption/example.envrc
cloud-sql/mysql/client-side-encryption/pom.xml
cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/CloudKmsEnvelopeAead.java
cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
cloud-sql/postgres/client-side-encryption/README.md
cloud-sql/postgres/client-side-encryption/example.envrc
cloud-sql/postgres/client-side-encryption/pom.xml
cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/CloudKmsEnvelopeAead.java
cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/CloudSqlConnectionPool.java
cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
cloud-sql/postgres/client-side-encryption/src/test/java/cloudsql/tink/EncryptInsertDataIT.java
cloud-sql/postgres/client-side-encryption/src/test/java/cloudsql/tink/QueryDecryptDataIT.java
cloud-sql/postgres/servlet/pom.xml
cloud-sql/sqlserver/client-side-encryption/README.md
cloud-sql/sqlserver/client-side-encryption/example.envrc
cloud-sql/sqlserver/client-side-encryption/pom.xml
cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/CloudKmsEnvelopeAead.java
cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/CloudSqlConnectionPool.java
cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
cloud-sql/sqlserver/client-side-encryption/src/test/java/cloudsql/tink/EncryptInsertDataIT.java
cloud-sql/sqlserver/client-side-encryption/src/test/java/cloudsql/tink/QueryDecryptDataIT.java

These are mostly copied from the MySQL samples, but with the SQL statements changed to work with the other DB engines.

feat: add client-side encryption samples for Postgres and SQL Server

---

media/transcoder/src/main/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheet.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheet.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheetTest.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheetTest.java

feat: add spritesheet samples and tests

---

eventarc/README.md
eventarc/audit-storage/README.md
eventarc/audit-storage/pom.xml
eventarc/audit-storage/src/main/java/com/example/cloudrun/Application.java
eventarc/audit-storage/src/main/java/com/example/cloudrun/EventController.java
eventarc/generic/README.md
eventarc/generic/pom.xml
eventarc/pubsub/README.md

- Updates Eventarc naming style
- Removes leftover traces of Anthos in the `eventarc/` directory
- Updates region tags
- Updates `gcloud` commands (although these may be removed completely at some point when docs are ready)

docs: update eventarc docs and region tags

---

run/idp-sql/README.md

Naming fix (secrets manager -> secret manager)

Naming fix (secrets manager -> secret manager)

---

appengine-java8/pubsub/src/main/java/com/example/appengine/pubsub/PubSubAuthenticatedPush.java

This snippet is used in the Cloud Pub/Sub docs (https://cloud.google.com/pubsub/docs/push#validating_tokens) and many users are not aware that signature verification of the token is not enough, the claim needs to be validated also.
See similar change in the nodejs repo: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2222.

Add comment about authenticated push JWT token validation.

---

pubsublite/streaming-analytics/README.md
pubsublite/streaming-analytics/pom.xml
pubsublite/streaming-analytics/src/main/java/PubsubliteToGcs.java
pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java
pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java

This is a planned sample (See internal b/186049986), to be published as an official quickstart as well. It uses PubsubLiteIO+Dataflow to read from Pub/Sub Lite (a streaming source), group messages by fixed windows, and write them to  Cloud Storage. 
1. When run on Dataflow, this I/O connector will generate a lot of `java.lang.RuntimeException: ManagedChannel allocation site` errors due to improper channel shutdown, but this doesn't seem to negatively affect performance. Also tracked in https://github.com/googleapis/java-pubsublite/issues/548 and see the maintainer's [comment](https://github.com/googleapis/java-pubsublite/issues/548#issuecomment-801437469).
> ![Screen Shot 2021-04-21 at 4 32 22 PM](https://user-images.githubusercontent.com/9518298/115634813-35ccce80-a2bf-11eb-96cf-89bf240fc …

Add sample for Pub/Sub Lite I/O Connector for Beam

---

pubsublite/streaming-analytics/pom.xml
pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java
pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java

Fixes #5113 
This test will add another 10 minutes to the tests 😖   
The tricky bit is canceling the Dataflow job using the Discovery API (apiary client) for Dataflow, which uses a different auth method: https://github.com/googleapis/google-auth-library-java#using-credentials-with-google-http-client
A permanent Pub/Sub Lite topic has been created for this test. This Lite topic has some messages already published to it. Every time the test runs, a new Lite subscription is created for the topic and is configured to read all the messages in the topic. The Dataflow job, when run correctly, shall window the messages based on some logic defined by the windowing function and then write three files to Cloud Storage. The test checks for those files and passes when their content match the desired …

test: update IT to run Pub/Sub Lite I/O sample on GCP

---

pubsub/streaming-analytics/pom.xml
pubsublite/streaming-analytics/pom.xml

This should unblock #5117
https://mvnrepository.com/artifact/org.apache.beam/beam-examples-java/2.29.0
The convenience method I'm using is still being released in `2.29.0`: 
https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/common/WriteOneFilePerWindow.java

fix(deps): use beam-examples-java

---

renovate.json

See #5131
See https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5131#issuecomment-827754518

Update renovate.json to ignore google-api-services-dataflow

---

pubsublite/streaming-analytics/README.md
pubsublite/streaming-analytics/metadata.json
pubsublite/streaming-analytics/pom.xml
pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java
pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java

Add instructions for turning a Dataflow pipeline into a [Dataflow flex template](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates), which can be run with different input parameters via gcloud as well as in Cloud Console.
- updated README to include instructions.
- `metadata.json` is a required file for creating a flex template.
- the Dataflow Discovery API dependencies have to be given the scope `runtime` for flex templates.
- Flex templates don't allow `pipeline.run().waitUntilFinish()`. Removed `waitUntilFisnish()` from sample.
- used a blocking call to wait 10 minutes in test instead.

feat: add instructions for flex templates

---

appengine-java11/quarkus-helloworld/src/main/resources/application.properties

I have noticed that Quarkus GAE "hello world" example doesn't work, as uber JAR is not produced. To rectify this, it is necessary to add 
```
quarkus.package.type=uber-jar
```
to ```applications.properties```, as per [documentation](https://quarkus.io/guides/deploying-to-google-cloud)

Set up application to be packaged as an uber-jar via application.properties

---

renovate.json

Fixes #1727
JSON requires the backslash itself to be escaped, so that it can be a single backslash-escape in the regex.

chore: escape the escape character in renovate.json

---

renovate.json

Fixes #1727
Looks like a match rule is required. Docs for change: https://docs.renovatebot.com/configuration-options/#matchpackageprefixes

chore(renovate): add required match section to package rules

---

spanner/r2dbc/README.md
spanner/r2dbc/pom.xml
spanner/r2dbc/src/main/java/com/example/spanner/r2dbc/Name.java
spanner/r2dbc/src/main/java/com/example/spanner/r2dbc/R2dbcSampleApplication.java
spanner/r2dbc/src/main/java/com/example/spanner/r2dbc/WebController.java
spanner/r2dbc/src/main/resources/application.properties
spanner/r2dbc/src/main/resources/static/index.html
spanner/r2dbc/src/test/java/com/example/spanner/r2dbc/R2dbcSampleApplicationIT.java

This sample uses the already-enabled Cloud Spanner API. This PR does not include an integration test, but if we add one, the environment variables will also be reused from the client library/JDBC Cloud Spanner examples.
PMD reporting Spring Endpoints as a potential security issue. For a sample application, it is surely not.

Add a Cloud Spanner with Spring Data R2DBC sample app

---

storage/s3-sdk/src/main/java/storage/s3sdk/ListGcsBuckets.java
storage/s3-sdk/src/main/java/storage/s3sdk/ListGcsObjects.java
storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsBucketsTest.java
storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsObjectsTest.java

This will allow better reporting for storage test failures. In order
to avoid breaking docs links, I'm first going to copy the files
and then delete the originals in a separate PR.

chore(storage): move storage/s3-sdk into a package

---

.kokoro/tests/run_tests.sh
storage/s3-sdk/README.md
storage/s3-sdk/pom.xml
storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsBucketsTest.java
storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsObjectsTest.java
storage/s3-sdk/src/test/java/storage/s3sdk/TestHmacKeyRule.java

Update S3 SDK Tests to create and use HMAC credentials in the test rather than depending on external credentials.
Test has been updated to rely on a Service Account to generate the necessary HMAC credentials.
Fixes #5374
Fixes #5375
port of https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6074

test(storage): fix S3 SDK tests

---

renovate.json

Fixes #4579
Followed [this](https://docs.renovatebot.com/configuration-options/#matchcurrentversion) example which enforces only 1.* versions will be used

chore: only use release version of spring-boot-dependencies

---

.kokoro/tests/run_tests.sh

Bumps btlr to the newest version. The new version prints logs as each command is completed.

chore(ci): bump btlr version

---

dataflow/transforms/src/main/java/com/example/AvroToCsv.java

I opened an issue on this topic #5560 and finally found the solution myself. I wanted to share this because it allows the user to read avro files with nulls in them. This change worked for me and the pipeline returns the intended csv.
Fixes #5560
- [ x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ x] `pom.xml` parent set to latest `shared-configuration`
- [ x] Appropriate changes to README are included in PR
- [ x] API's need to be enabled to test (tell us)
- [ x] Environment Variables need to be set (ask us to set them)
- [ x] **Tests** pass:   `mvn clean verify` **required**
- [ x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [x …

Added "union" to accepted types in the avro schema

---

run/markdown-preview/editor/src/main/resources/templates/index.html

This is a fix propagating from https://github.com/GoogleCloudPlatform/golang-samples/pull/2149
* Pin material to v11
* Use new fullwidth guide "width: 100%"

fix(run/markdown-preview): full width input form

---

unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java

fix: extend timeout for flaky test

---

auth/README.md
auth/pom.xml
auth/src/main/java/com/google/cloud/auth/samples/DownscopingExample.java
auth/src/test/java/com/google/cloud/auth/samples/DownscopingExampleIT.java

Adds a sample to illustrate token broker and token consumer functionality for downscoping with CAB.
This includes samples on:
- How to initialize the CAB rules.
- How to initialize the downscoped credentials.
- How to inject the downscoped credentials in the token consumer.
The samples also include a test that verifies readonly access to a temporary
object.

feat: adds downscoping with Credential Access Boundaries samples

---

endpoints/getting-started/clients/src/main/java/com/example/app/GoogleJwtClient.java

Only removes two characters in a comment, from `expirary` to `expiry`.

Fix minor typo

---

workflows/cloud-client/src/main/java/com/example/workflows/WorkflowsQuickstart.java

Workflows Quickstart: enable env vars so docs can use this format.
---
Tested locally. Examples:
```
GOOGLE_CLOUD_PROJECT=serverless-com-demo mvn compile exec:java -Dexec.mainClass=com.example.workflows.WorkflowsQuickstart
GOOGLE_CLOUD_PROJECT=serverless-com-demo LOCATION=us-central1 WORKFLOW=myFirstWorkflow mvn compile exec:java -Dexec.mainClass=com.example.workflows.WorkflowsQuickstart
GOOGLE_CLOUD_PROJECT=serverless-com-demo mvn clean verify
```

fix: update workflows quickstart to use env vars for config

---

dataflow/templates/pom.xml
pubsub/streaming-analytics/pom.xml
pubsublite/streaming-analytics/pom.xml

Beam 2.34.0 doesn't depend on log4j-api but 2.31.0 does.
Go into each project and do with 2.31.0 vs. 2.34.0.
`mvn dependency:tree | grep log4j`

chore(deps): update beam to 2.34.0 for pub/sub and dataflow

---

dataflow/encryption-keys/pom.xml
dataflow/flex-templates/kafka_to_bigquery/pom.xml
dataflow/flex-templates/streaming_beam_sql/pom.xml
dataflow/spanner-io/pom.xml
dataflow/templates/pom.xml

Fixes log4j security vulnerability
https://logging.apache.org/log4j/2.x/security.html
Uses log4j 2.15 explicitly (where the vulnerability has been fixed) instead of slf4j.

dataflow: use log4j 2.15 to patch security bug

---

pubsub/streaming-analytics/README.md
pubsub/streaming-analytics/build.gradle
pubsub/streaming-analytics/pom.xml
pubsublite/streaming-analytics/README.md
pubsublite/streaming-analytics/build.gradle
pubsublite/streaming-analytics/pom.xml

Beam has moved on from Maven to Gradle as its [default build](https://beam.apache.org/get-started/quickstart-java/). Add gradle build scripts to all the Pub/Sub and Pub/Sub Lite Dataflow tutorials.
And other nits.
I didn't add the following Gradle files because one can build them from `build.gradle` with `gradle build`. 
- gradle/
- gradlew
- gradlew.bat
- settings.gradle

feat: add gradle build scripts to pubsub and pubsublite tutorials for beam

---

dataflow/encryption-keys/pom.xml
dataflow/flex-templates/kafka_to_bigquery/pom.xml
dataflow/flex-templates/streaming_beam_sql/pom.xml
dataflow/spanner-io/pom.xml
dataflow/templates/pom.xml

Related to #6588 and #6587 
As recently reported on [apache.org](https://logging.apache.org/log4j/2.x/security.html)
Apache Log4j2 versions 2.0-alpha1 through 2.16.0 did not protect from uncontrolled recursion from self-referential lookups. When the logging configuration uses a non-default Pattern Layout with a Context Lookup (for example, $${ctx:loginId}), attackers with control over Thread Context Map (MDC) input data can craft malicious input data that contains a recursive lookup, resulting in a StackOverflowError that will terminate the process. This is also known as a DOS (Denial of Service) attack.

dataflow: update log4j to 2.17.0

---

.github/CODEOWNERS

Include everyone in https://github.com/orgs/GoogleCloudPlatform/teams/api-pubsub-and-pubsublite/members for Pub/Sub and Pub/Sub Lite code reviews. 
Note that this group is a GitHub TeamSync Team and maps to an internal group. Ask @anguillanneuf about this internal group. 
@brijk7 You have been added and can review PRs that have `api-pubsub-and-pubsublite` assigned as Reviewers in java-docs-samples.

chore: add more pubsub and pubsublite codeowners

---

pubsub/spring/README.md
pubsub/spring/build.gradle
pubsub/spring/pom.xml

User request to add gradle build script to the Spring project.
I didn't add the following Gradle files because one can build them from `build.gradle` with `gradle build`. 
- gradle/
- gradlew
- gradlew.bat
- settings.gradle
Remind ourselves to update to Spring v2.5.8 when Dec 23 comes around.

feat: add gradle build script to pubsub/spring tutorial

---

dataflow/encryption-keys/pom.xml
dataflow/flex-templates/kafka_to_bigquery/pom.xml
dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
dataflow/flex-templates/streaming_beam_sql/pom.xml
dataflow/flex-templates/streaming_beam_sql/src/main/java/org/apache/beam/samples/StreamingBeamSql.java
dataflow/spanner-io/pom.xml
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
dataflow/templates/pom.xml

Remove any direct dependencies of log4j and use slf4j instead, as recommended by the [documentation](https://cloud.google.com/dataflow/docs/guides/logging#java_1), and update to Beam 2.34 which doesn't depend on log4j.
Confirmed with `mvn dependency:tree | grep log4j-api` that there are no direct or indirect dependency instances of log4j on any sample by doing this.

dataflow: avoid importing log4j at all

---

eventarc/generic/pom.xml
eventarc/pubsub/pom.xml
flexible/helloworld-springboot/pom.xml
pubsub/spring/pom.xml
run/helloworld/pom.xml
run/image-processing/pom.xml
run/markdown-preview/editor/pom.xml
spanner/r2dbc/pom.xml
spanner/r2dbc/src/test/java/com/example/spanner/r2dbc/R2dbcSampleApplicationIT.java

The latest Spring Boot release was yesterday; it upgrades log4j-api to 2.17.0.
Do you know why renovate bot does not get to these dependencies?
I also had to upgrade the R2DBC test to JUnit5 -- at some point when spring-boot-test dependency got upgraded to 2.5.x, the test got silently ignored.
- [x ] **Tests** pass:   `mvn clean verify` **required**
- [x ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**

Update Spring Boot dependencies to 2.5.8

---

pubsub/spring/pom.xml
run/idp-sql/pom.xml
run/image-processing/pom.xml
spanner/spring-data/pom.xml

Spring Cloud GCP 2.0.7 is released. It includes a transitive dependency on the latest Spring Boot in 2.5.x train.
I also found a couple of Spring Boot versions I missed in #6600.
- [x ] **Tests** pass:   `mvn clean verify` **required**
- [ x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ x] Please **merge** this PR for me once it is approved.

Upgrade Spring Cloud GCP and remaining Spring Boot versions

---

bigtable/beam/workload-generator/README.md

Fix parameter mismatch.
Also, the command `gcloud dataflow jobs cancel $JOB_NAME` gives me error
```
Could not cancel workflow; user does not have sufficient permissions on project: autonomous-mote-782, or the job does not exist in the project. Please ensure you have permission to access the job and the `--region` flag, us-central1, matches the job's region.
```
Any thoughts?

docs: Update README.md

---

compute/cloud-client/src/test/java/compute/SnippetsIT.java

fix(compute-samples): fixed flaky firewall rule deletion

---

.kokoro/java11/common.cfg
.kokoro/java8/common.cfg
.kokoro/tests/run_tests.sh

Updating to get latest version secrets from secret manager so we don't need to update secrets in bucket

chore: migrate to secretmanager

---

compute/cloud-client/pom.xml
compute/cloud-client/src/main/java/compute/customhostname/CreateInstanceWithCustomHostname.java
compute/cloud-client/src/main/java/compute/customhostname/GetInstanceHostname.java
compute/cloud-client/src/test/java/compute/customhostname/CustomHostnameInstanceIT.java

Added samples for instance creation with custom hostname.

docs(compute-samples): init add samples for custom hostname

---

pubsublite/streaming-analytics/pom.xml
pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java

By default, `FixedWindows` are triggered by event time (if no trigger is specified), which is the publish timestamp of a message. 
The example was using the processing time trigger because the PubsubLiteIO at one time had a bug. 
The bug has since been fixed (b/186174854), so we no longer need to demonstrate how to use processing time triggers for the sample to work. 
The `pom.xml` changes are required for running the sample via command line - I had previously thought they were required by the test only. Without them as compile dependencies, the following error will be thrown:
```
An exception occured while executing the Java class. com/google/api/services/dataflow/Dataflow: com.google.api.services.dataflow.Dataflow
```

fix(pubsublite): remove processing time trigger

---

bigtable/spark/build.sbt

Reverts GoogleCloudPlatform/java-docs-samples#6747
This sample should pin the hbase version, which I will update the renovate config to do separately. There's also a bug with renovate bot where it also updated the `sparkVersion` as part of this PR, thinking it was an hbase dependency.

Revert "chore(deps): update hbaseversion for org.apache.hbase to v2.4.9"

---

spanner/changestreams/README.md
spanner/changestreams/pom.xml
spanner/changestreams/src/main/java/com/example/spanner/changestreams/ChangeStreamRecordMapper.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/ChangeStreamSample.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ChangeStreamRecord.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ChildPartition.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ChildPartitionsRecord.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ColumnType.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/DataChangeRecord.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/HeartbeatRecord.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/Mod.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ModType.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/TypeCode.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/ValueCaptureType.java
spanner/changestreams/src/main/java/com/example/spanner/changestreams/model/package-info.java
spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java

The followings are included:
* Sample code for creating change stream.
* Sample code for querying change stream, basically it does an change stream initial query to get a list of partition tokens, and then use the partition tokens to query the data change records for each partition.
* Sample code for dropping change stream.
* ChangeStreamRecordMapper and models, these are the files that help change stream users understand how to model change stream records after receiving them from API, they are copied from org.apache.beam.sdk.io.gcp.spanner.changestreams.* with unused code being removed.
* README for how to run the sample code and tests.

feat: add cloud spanner change streams samples

---

run/jobs/src/test/java/com/example/JobsIntegrationTests.java

chore: update job tests with retries

---

compute/cloud-client/src/test/java/compute/SnippetsIT.java

This is already tested in the test setup.
Fixes: #6828.

test: remove flaky unnecessary testCreateFirewallRule

---

spanner/changestreams/src/main/java/com/example/spanner/changestreams/ChangeStreamSample.java
spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java

Fix and add logging to com.example.spanner.changestreams.ChangeStreamSampleIT: testChangeStreamSample
In my local testing, sometimes the test failed with timeout executing DDL, so I increased the timeout from 2 minutes to 15 minutes. After the fix, I run the test 100 times locally and all of them passed.
I am not sure if this will fix the problem since the test was failed at a different place in Sponge, but I cannot repro it locally and I cannot see the logging since the standard output was hidden, so I also print the standard output and hopefully we will see some logging to debug if it fails another time.
Fixes #6831

Fix and add logging to com.example.spanner.changestreams.ChangeStreamSampleIT: testChangeStreamSample

---

bigtable/spark/build.sbt

https://spark.apache.org/news/ shows 2.4.9 was not released. The robot accidentally upgraded it in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/6847

Use latest 2.4 Spark version 2.4.8

---

secretmanager/pom.xml
secretmanager/src/main/java/secretmanager/AccessSecretVersion.java
secretmanager/src/main/java/secretmanager/AddSecretVersion.java

Adds checksum-usage snippets to SecretManager samples.

chore(secret-manager): add checksum-usage to snippets

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchPost.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java

Part of fix for b/221324824. Our client libraries do not allow for FHIR GET/POST search requests to be set in the HTTP request path, which is required by the FHIR specification. Due to a bug, you can send search requests by specifying a resource type in the request body, but this is an anti-pattern. Until we fix the issue with the client library, we need to use the Apache HTTP client to explicitly make GET/POST requests and not use the client library.

healthcare API: do not use client library for FHIR search requests

---

iam/api-client/pom.xml

Editing the dependency for the Troubleshooter API to use the Cloud Client library instead of the Google API client library.
Cloud Client libraries are generally preferred. I'll use this sample on 

Use Cloud Client library for Troubleshooter

---

appengine-java11/springboot-helloworld/pom.xml
appengine-java11/tasks-handler/pom.xml
appengine-java8/springboot-helloworld/pom.xml
cloud-sql/r2dbc/pom.xml
eventarc/audit-storage/pom.xml
eventarc/generic/pom.xml
eventarc/pubsub/pom.xml
flexible/helloworld-springboot/pom.xml
pubsub/spring/pom.xml
run/endpoints-v2-backend/pom.xml
run/filesystem/pom.xml
run/helloworld/pom.xml
run/idp-sql/pom.xml
run/image-processing/pom.xml
run/markdown-preview/editor/pom.xml
run/markdown-preview/renderer/pom.xml
run/pubsub/pom.xml
spanner/r2dbc/pom.xml
spanner/spring-data/pom.xml

Addresses [CVE-2022-22965](https://tanzu.vmware.com/security/cve-2022-22965).
See [blog post](https://spring.io/blog/2022/03/31/spring-boot-2-6-6-available-now) for details.
I manually tested `appengine-java8/springboot-helloworld`, as the pom file requested.

Update versions to latest Spring Boot and Spring Cloud GCP

---

renovate.json

Fixes #6955 
Spring boot does not use RELEASE to signify GA releases on Maven Central. Therefore this update rejects SNAPSHOTs and M releases that are not GA.

fix: update renovate spring boot version matcher

---

run/jobs/src/main/java/com/example/JobsExample.java
run/jobs/src/test/java/com/example/JobsIntegrationTests.java

fix: Update env var and log filter

---

spanner/jdbc/pom.xml

Use the versions from the `libraries-bom` instead of specific versions for the Spanner JDBC driver samples.
Replaces #6844

deps: use libraries bom for Spanner JDBC samples

---

appengine-java11-bundled-services/README.md

Since most users looking to access bundled services will want to use the App Engine APIs directly, I think it makes sense to include steps to add the required dependency.
Fixes #issue

docs(bundled services): Include instructions to add bundled services JAR

---

pubsub/spring/src/main/resources/application.properties

pubsub(fix): avoid default port in spring app

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/HelloWorld.java
bigtable/hbase/snippets/src/test/java/com/example/bigtable/HelloWorldTest.java

Moving: https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/main/java/hello-world
Fixes #issue

bigtable: migrate HelloWorld sample from cloud-bigtable-examples

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/BigtableConnect.java
bigtable/hbase/snippets/src/test/java/com/example/bigtable/BigtableConnectTest.java

Moving: https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/main/java/connect to java-docs-samples

bigtable: migrate BigtableConnect sample from cloud-bigtable-examples

---

pubsublite/streaming-analytics/pom.xml
pubsublite/streaming-analytics/src/test/java/PubsubliteToGcsIT.java

The sample test as it was written should have failed for the last Beam version bump. 
There's a known issue with PubsubLiteIO in Beam==2.38.0: https://github.com/apache/beam/issues/21703
Need to bump Beam version to the latest and our libraries-bom together. 
TL;DR - PubsubLiteIO for Beam==2.39 [requires](https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-io-google-cloud-platform/2.39.0) google-cloud-pubsublite==1.5.0-1.6.0. [libraries-bom==25.0.0](https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/25.0.0/libraries-bom-25.0.0.pom) uses [google-cloud-bom==0.171.0](https://repo1.maven.org/maven2/com/google/cloud/google-cloud-bom/0.171.0/google-cloud-bom-0.171.0.pom), which pulls in an older version of google-cloud-pubsublite.

pubsublite: rewrite test and bump versions

---

dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerGroupWrite.java
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerRead.java
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadAll.java
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadApi.java
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
dataflow/spanner-io/src/main/java/com/example/dataflow/TransactionalRead.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java

Adds PostgreSQL-specific samples for read and query operations using `SpannerIO`:
* Cloud Spanner GoogleSQL column names use camel case.
* Cloud Spanner PostgreSQL column names all lowercase with underscores to separate words. This because PostgreSQL automatically folds identifiers to lowercase.
All `Pipeline` variables that were named `p` are renamed to `pipeline` for better readability in the documentation that imports the code samples here: https://cloud.google.com/spanner/docs/dataflow-connector#read-without
Fixes b/232995390

docs: add PostgreSQL read and query samples for SpannerIO

---

flexible/pubsub/pom.xml
iot/api-client/codelab/manager/pom.xml
iot/api-client/end-to-end-example/pom.xml

#7231 is failing due to 1 of the 4 updates. Pulling 3 of the 4 updates into a seperate PR.

fix(deps): manual update dependency com.google.cloud:google-cloud-pubsub to v1.120.3

---

media/stitcher/pom.xml
media/stitcher/src/test/java/com/example/stitcher/CreateLiveSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/CreateSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/DeleteSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/GetLiveAdTagDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/GetLiveSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/GetSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/ListLiveAdTagDetailsTest.java
media/stitcher/src/test/java/com/example/stitcher/ListSlatesTest.java
media/stitcher/src/test/java/com/example/stitcher/TestUtils.java
media/stitcher/src/test/java/com/example/stitcher/UpdateSlateTest.java

The project has run out of quota on slates (3), most likely due to b:246797639. This PR adds a mechanism to name test slates with a creation timestamp since the API does not reveal creation time.  Before applicable test runs, test slates more than 3 hours old are deleted.
This first commit deletes **all** old test slates, even those that have not been named with a creation timestamp. A subsequent commit will enable the timestamp naming and selective deletion.

fix(samples): Clean up stale Video Stitcher slates

---

unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java

There have been several solutions to #5588, but the flaky test is still occurring occasionally. This fix should reduce the probability of it reoccurring by introducing retries.
Fixes #5588

test: add retries for flaky GAE test

---

trace/pom.xml

By using `cloud-libraries-bom` for dependency management, we can simplify `pom.xml` to use the latest recommended library dependencies. This should make the failed renovate PR #6452 unnecessary.

chore(deps): cleanup trace dependencies

---

iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

Some of the tests, but not all, had try/finally blocks to delete resources at the end. This fix applies that logic consistently to catch most of the issues.
More robust error-handling could be added later to handle ignore `AlreadyExistsException` or to deal with resources individually rather than in bulk within each test function.
Fixes #7330
Fixes #7331 
Fixes #7322

test: Address IOT flaky tests

---

README.md

* Adds badges for Java 8, 11, and 17 periodic builds
* Updates copyright header template to 2022

chore: Update README.md with nightly build status

---

spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java

Adds the actual change text that was received to the assertion message
so the log will contain a hint as to why the test seems to be flaky.
cc @Neenu1995 @haikuo-google 
Updates #7165

test: add got to assertion message

---

compute/cloud-client/src/main/java/compute/disks/DeleteSnapshotsByFilter.java
compute/cloud-client/src/main/java/compute/disks/GetSnapshot.java
compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
compute/cloud-client/src/test/java/compute/disks/SnapshotsIT.java

Improving the code snippets for disk snapshots, so they can be used on this page: [Create and manage disk snapshots](https://cloud.google.com/compute/docs/disks/create-snapshots)

docs(compute-samples): improving snapshot samples

---

iot/api-client/codelab/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

This PR address a failing dependency PR #6766. One of the IoT tests runs a Java applet, which fails in the build environment due to `/dev/tty (No such device or address)`. 
This PR catches the expected exception and logs it. I verified that this test continues to run all the way through locally with the try/catch block added. FYI: [IoT Core is being retired](https://cloud.google.com/iot-core).

test: handle expected exception when running IoT GUI test

---

storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferFromAws.java
storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/apiary/TransferFromAwsApiary.java
storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/ITStoragetransferSamplesTest.java

Use AWS creds from environment variable directly in sample instead of passing them in via program args

fix(storagetransfer):use AWS creds from environment variable directly in sample

---

iot/api-client/codelab/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

#7349 was too specific, as it handled the `FileNotFoundException` but not its superclass `IOException`. The build for #6766 is still failing:
```
java.io.IOException: Cannot run program "/bin/stty": /dev/tty (No such device or address)
at cloudiot.manager.demo@1.0/com.example.cloud.iot.examples.ManagerIT.testTerminal(ManagerIT.java:61)
Caused by: java.io.FileNotFoundException: /dev/tty (No such device or address)
at cloudiot.manager.demo@1.0/com.example.cloud.iot.examples.ManagerIT.testTerminal(ManagerIT.java:61)
```

test: handle expected exception in GUI test

---

functions/v2/ocr/ocr-process-image/pom.xml
functions/v2/ocr/ocr-process-image/src/main/java/functions/OcrProcessImage.java
functions/v2/ocr/ocr-process-image/src/main/java/functions/OcrTranslateApiMessage.java
functions/v2/ocr/ocr-process-image/src/main/java/functions/eventpojos/CustomerEncryption.java
functions/v2/ocr/ocr-process-image/src/main/java/functions/eventpojos/StorageObjectData.java
functions/v2/ocr/ocr-process-image/src/test/java/functions/OcrProcessImageTest.java
functions/v2/ocr/ocr-save-result/pom.xml
functions/v2/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
functions/v2/ocr/ocr-save-result/src/main/java/functions/OcrTranslateApiMessage.java
functions/v2/ocr/ocr-save-result/src/main/java/functions/eventpojos/Message.java
functions/v2/ocr/ocr-save-result/src/main/java/functions/eventpojos/MessagePublishedData.java
functions/v2/ocr/ocr-save-result/src/test/java/functions/OcrSaveResultTest.java
functions/v2/ocr/ocr-translate-text/pom.xml
functions/v2/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateApiMessage.java
functions/v2/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateText.java
functions/v2/ocr/ocr-translate-text/src/main/java/functions/eventpojos/Message.java
functions/v2/ocr/ocr-translate-text/src/main/java/functions/eventpojos/MessagePublishedData.java
functions/v2/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java

add 2nd gen GCF OCR sample

---

compute/cloud-client/src/main/java/compute/windows/osimage/CreateImage.java
compute/cloud-client/src/main/java/compute/windows/osimage/DeleteImage.java
compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java

Samples to create and delete images. The compute_windows_image_create region is here to match https://github.com/googleapis/nodejs-compute/pull/703/files
Changes:
1. Create sample: added second region tag and made changes to comments.
2. Added a new delete sample
3. Modified test file to include the delete sample

docs(compute-samples): add samples for image creation and deletion

---

optimization/snippets/pom.xml
optimization/snippets/resources/sync_request.textproto
optimization/snippets/src/main/java/com/example/optimizationai/AsyncApi.java
optimization/snippets/src/main/java/com/example/optimizationai/GetOperation.java
optimization/snippets/src/main/java/com/example/optimizationai/SyncApi.java
optimization/snippets/src/main/java/com/example/optimizationai/SyncApiWithLongTimeout.java
optimization/snippets/src/test/java/com/example/optimizationai/AsyncApiTest.java
optimization/snippets/src/test/java/com/example/optimizationai/GetOperationTest.java
optimization/snippets/src/test/java/com/example/optimizationai/SyncApiTest.java
optimization/snippets/src/test/java/com/example/optimizationai/SyncApiWithLongTimeoutTest.java

- feat: initial generation
- test(deps): update dependency com.google.truth:truth to v1.1.3 (#11)
- test(deps): update dependency junit:junit to v4.13.2 (#5)
- chore(deps): update dependency com.google.cloud.samples:shared-configuration to v1.2.0 (#10)
- chore(deps): update dependency com.google.cloud:google-cloud-optimization to v0.1.0 (#15)
- chore(deps): update dependency com.google.cloud:google-cloud-optimization to v0.1.1 (#22)
- docs: add async api code snippet (#25)
- docs: add a code snippet for the sync api (#24)
- samples: add long timeout sample (#27)
- docs: add get operation code snippet (#28)
- chore(deps): update dependency com.google.cloud:google-cloud-optimization to v0.1.2 (#32)
- chore(deps): update dependency com.google.cloud:libraries-bom to v25.2.0 (#37)
- …

migrate code from googleapis/java-optimization

---

webrisk/pom.xml
webrisk/src/main/java/webrisk/SearchUriExample.java
webrisk/src/main/java/webrisk/SubmitUriExample.java
webrisk/src/test/java/webrisk/SearchUriExampleTest.java
webrisk/src/test/java/webrisk/SubmitUriExampleTest.java

- samples: scaffold pom.xml files (#88)
- chore(deps): update dependency com.google.cloud:libraries-bom to v4.3.0 (#96)
- deps: update dependency com.google.cloud.samples:shared-configuration to v1.0.13 (#101)
- chore(deps): update dependency com.google.cloud.samples:shared-configuration to v1.0.14 (#105)
- chore(deps): update dependency com.google.cloud:libraries-bom to v4.4.0 (#106)
- chore(deps): update dependency com.google.cloud.samples:shared-configuration to v1.0.15 (#110)
- chore(deps): update dependency com.google.cloud:libraries-bom to v4.4.1 (#111)
- chore(deps): update dependency com.google.cloud:libraries-bom to v5 (#122)
- chore(deps): update dependency com.google.cloud.samples:shared-configuration to v1.0.16 (#127)
- chore(deps): update dependency …

migrate code from googleapis/java-webrisk

---

vision/spring-framework/README.md

Removing the conflicting README in preparation for the [java-vision](https://github.com/googleapis/java-vision/tree/main/samples/spring-framework) samples migration

chore: remove conflicting README

---

bigtable/spark/README.md

update readme spark version to match spark version the example refers to with [2.4.8](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/bigtable/spark/build.sbt#L24)

fix: bump spark version in readme

---

.kokoro/tests/run_tests.sh
security-command-center/snippets/pom.xml
security-command-center/snippets/src/main/java/NotificationReceiver.java
security-command-center/snippets/src/main/java/bigqueryexport/CreateBigQueryExport.java
security-command-center/snippets/src/main/java/bigqueryexport/DeleteBigQueryExport.java
security-command-center/snippets/src/main/java/bigqueryexport/GetBigQueryExport.java
security-command-center/snippets/src/main/java/bigqueryexport/ListBigQueryExports.java
security-command-center/snippets/src/main/java/bigqueryexport/UpdateBigQueryExport.java
security-command-center/snippets/src/main/java/muteconfig/BulkMuteFindings.java
security-command-center/snippets/src/main/java/muteconfig/CreateMuteRule.java
security-command-center/snippets/src/main/java/muteconfig/DeleteMuteRule.java
security-command-center/snippets/src/main/java/muteconfig/GetMuteRule.java
security-command-center/snippets/src/main/java/muteconfig/ListMuteRules.java
security-command-center/snippets/src/main/java/muteconfig/SetMuteFinding.java
security-command-center/snippets/src/main/java/muteconfig/SetUnmuteFinding.java
security-command-center/snippets/src/main/java/muteconfig/UpdateMuteRule.java
security-command-center/snippets/src/test/java/BigQueryExportIT.java
security-command-center/snippets/src/test/java/MuteFindingIT.java

Manual updation due to merge conflicts. No critical history has been omitted for the samples.

chore: migrate samples from googleapis/java-securitycenter

---

jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java

Adds "dual-homed" region tags with product prefix to enable better sample tracking. Will send a CL to update relevant docs and then remove the obsolete region tags in a separate PR.

chore(jobs): add normalized region tags with product prefix

---

jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java

cl/490049441 removed usage in documentation; this can be merged once snippet-bot is happy (since that means the changes will have been successfully published/indexed).

chore: remove obsolete region tags

---

dialogflow/snippets/src/main/java/com/example/dialogflow/ConversationManagement.java
dialogflow/snippets/src/main/java/com/example/dialogflow/ConversationProfileManagement.java
dialogflow/snippets/src/main/java/com/example/dialogflow/ParticipantManagement.java
dialogflow/snippets/src/test/java/com/example/dialogflow/CreateConversationProfileTest.java
dialogflow/snippets/src/test/java/com/example/dialogflow/CreateConversationTest.java
dialogflow/snippets/src/test/java/com/example/dialogflow/CreateParticipantTest.java

---
- During the initial migration of the samples from the client repo some samples were left out since they were not being referenced anywhere in the documentation.
- However, in later discussions with the Eng Team and DEE Team for dialogflow, it was deemed that some of these samples have to be migrated and used in documentation

chore: migrated left out samples

---

.kokoro/tests/run_test_java.sh
asset/src/test/java/com/example/asset/QuickStartIT.java
automl/src/test/java/beta/automl/TablesCreateModelTest.java
automl/src/test/java/beta/automl/TablesPredictTest.java
automl/src/test/java/com/example/automl/LanguageTextClassificationCreateModelTest.java

- Asset/AutoML: Adds retries to failing tests
- Asset: 
- Updates timeout from 5->10 min (later we could apply a filter on asset type to speed up test)
- Refactors dataset creation to occur in helper method
- Dataset creation fails sometimes and should be included when retrying
Fixes #7463, Fixes #7456, Fixes #7446

test: increased timeout and added retries to flaky tests

---

appengine-java8/springboot-helloworld/.gitignore

Issue #7503 was raised about including maven-wrapper.jar. @ludoch helpfully pointed out https://maven.apache.org/wrapper/; effectively we can remove the .jar, it makes using the sample a little more difficult, but with the rule to not include binary artifacts into our source code, seems like the right thing to do
@averikitsch if you can take a look

fix: Update .gitignore so that .jar file isn't included

---

asset/src/main/java/com/example/asset/ExportAssetsBigqueryExample.java
asset/src/main/java/com/example/asset/ExportAssetsExample.java
asset/src/test/java/com/example/asset/QuickStartIT.java

#7446 has continued to flake after retries were added.  The following updates were made in this PR:
- Tests will use a different Dataset ID or GCS path each retry. Whenever a timeout flake occurred, retries immediately failed with an `INVALID_ARGUMENT` exception. I believe that was because the resources were still in use. 
- A new, optional sample parameter for exporting specific asset types was introduced. This should hopefully reduce the export time, and therefore reduce the chance of timeouts. The tests now only export the Disk asset type.
Fixes #7446
Fixes #7456
Fixes #7476

test: fix flaky asset tests

---

unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java

This test has flaked occasionally because `tearDown()` takes > 10 minutes.
Previous fixes have tried to address the issue by catching the timeout exception in `tearDown()`, but the exception is still being thrown.
This fix attempts to solve the problem by adding an `expectedException` parameter to the flaky test, expecting the test to timeout. This parameter is mandatory, and there is no option to make it optional (i.e. it will fail if the test does not timeout).
So, the only work-around I could find is to throw a timeout exception at the end to cover both success and timed-out scenarios. A comment was added to clarify this behavior.
I ran tests 3 times across 3 Java versions - no failures. Hopefully that continues and the flaky behavior goes away. Fixes #5588

test: handle flaky timeout in GAE task test

---

aiplatform/src/test/java/aiplatform/FeatureValuesSamplesTest.java
aiplatform/src/test/java/aiplatform/FeaturestoreSamplesTest.java

This fix reduces the chance of flakiness, but doesn't eliminate it. 
* Extended timeout in a few operations (reusing existing TIMEOUT constant)
* Added retries to the FeatureStore test classes
If we see continued errors, we should consider:
* Removing the assertion in the tearDown() method
* Refactoring the deletion steps into a test method that can be retried.
Fixes #7538 
Fixes #7530

test: update aiplatform FeatureStore timeout + add retries

---

.kokoro/tests/run_tests.sh
storage-transfer/pom.xml
storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/QuickstartSample.java
storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferFromAzure.java
storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/ITStoragetransferSamplesTest.java

Adds a sample for transferring data from Azure

STS Azure sample

---

recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/AccountDefenderAssessment.java
recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/SearchRelatedAccountGroupMemberships.java
recaptcha_enterprise/snippets/src/test/java/app/SnippetsIT.java

Update Create account defender assessment sample to use HMAC SHA 256.
Update SearchRelatedAccountGroupMemberships to reflect API changes. (setParent to setProject)

docs(recaptcha-samples): update account defender samples

---

session-handling/src/main/java/com/example/gettingstarted/actions/HelloWorldServlet.java
session-handling/src/main/java/com/example/gettingstarted/util/FirestoreSessionFilter.java

This sample is currently not associated with a product, but it used in this [tutorial](https://cloud.google.com/java/getting-started/session-handling-with-firestore): "This tutorial shows how to handle sessions on [Cloud Run](https://cloud.google.com/run).
Will create a matching doc CL. Once that is approved, we can remove the "Do not merge" label and merge both the PR and CL.

chore: update region tags on session-handling sample

---

appengine-java11/gaeinfo/pom.xml
appengine-java11/gaeinfo/src/main/java/com/example/appengine/standard/GaeInfoServlet.java
appengine-java8/gaeinfo/pom.xml
appengine-java8/gaeinfo/src/main/java/com/example/appengine/standard/GaeInfoServlet.java
appengine-java8/metadata/pom.xml
appengine-java8/metadata/src/main/java/com/example/appengine/standard/MetadataServlet.java
flexible/gaeinfo/pom.xml
flexible/gaeinfo/src/main/java/com/example/appengine/flex_compat/GaeInfoServlet.java

Migrated GAE samples using Thyme to 3.1. (Migration guide in section 2 [here](https://www.thymeleaf.org/doc/articles/thymeleaf31whatsnew.html)).
This includes the dependency updates in #7634 plus the necessary code changes.
Samples were manually tested.  Deprecated usage of JsonParser was updated, too.

fix: migrate GAE samples to thymeleaf 3.1

---

aiplatform/src/test/java/aiplatform/FeatureValuesSamplesTest.java
aiplatform/src/test/java/aiplatform/FeaturestoreSamplesTest.java

Ignores failing FeatureStore tests which are blocking other PRs.
The tests should be enabled with #7642 and #7651.

test: temporarily ignore failing featurestore tests

---

aiplatform/src/main/java/aiplatform/PredictTextSentimentAnalysisSample.java

Updates a code sample to have safe serialization of input which may come unsanitized. 
I was referred here by @kweinmeister as I'm told this is the new house of what used to live at https://github.com/googleapis/java-aiplatform.
This PR is duplicate of one there: https://github.com/googleapis/java-aiplatform/pull/1098
Fixes #7561 ☕️

docs: improve `PredictTextSentimentAnalysisSample`

---

aiplatform/src/main/java/aiplatform/CreateFeaturestoreFixedNodesSample.java
aiplatform/src/test/java/aiplatform/FeaturestoreSamplesTest.java

Fixes #7679
1. Increased the featurestore tests timeout from 900 to 1800 seconds. This is to handle the intermittent timeouts in featurestore tests. 
2. Removed the temporary fix for #[7682](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7682)

test: Increased the featurestore tests timeout

---

recaptcha_enterprise/demosite/docker-compose.yaml
recaptcha_enterprise/demosite/src/main/resources/static/scripts/component.js

- Specify a container_name to simplify docker operations
- Remove unhelpful invalidReason from the response. null is not a valid value.

Demosite app recaptcha changes

---

.github/CODEOWNERS

DLP is self-service. Added the product team and java reviewers to CODEOWNERS.
b/269596305

chore: add CODEOWNERS for DLP samples

---

compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java

Fix: b/269415403
Custom Machine type instances were not being cleaned up because of a typo in one of the instance names.

fix: gce machine type name for auto-deletion

---

.github/auto-label.yaml
.github/blunderbuss.yml

Adding self-service DLP team to labels and blunderbuss

chore: Adding self-service DLP team to labels and blunderbuss

---

cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java

Cloud CDN Snippets are missing product's specific region tags. In this PR, we are only adding region tags. No code changes. For more details, refer to [b/264905390](b/264905390).
Fixes #issue

fix: Add missing product region tags for Cloud CDN snippets

---

.kokoro/tests/run_tests.sh

Recaptcha tests require chrome and chromedriver for executing tests. Adding the installation to the script.
The installation is not part of the docker image because it might slow down the build for all other tests.

chore: install chrome and driver for recaptcha tests

---

healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java

Fixes de-identified datasets created during tests not being deleted.

fix(healthcare-api): clean up de-identified dataset after tests

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/SetQueryOptionsExample.java

This snippet is used for the Cloud Spanner documentation on a page that covers both GoogleSQL and PostgreSQL. We therefore need a small comment on how the syntax looks in both dialects.

docs: add a comment for using optimizer_version with PG

---

storage/cloud-client/README.md
storage/cloud-client/pom.xml
storage/s3-sdk/README.md
storage/s3-sdk/pom.xml
storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsBucketsTest.java
storage/s3-sdk/src/test/java/storage/s3sdk/ListGcsObjectsTest.java
storage/xml-api/cmdline-sample/README.md
storage/xml-api/cmdline-sample/pom.xml
storage/xml-api/serviceaccount-appengine-sample/README.md
storage/xml-api/serviceaccount-appengine-sample/pom.xml

Cleaned up `/storage` samples, including:
- fixing deprecation warnings
- simplifying `pom.xml` with use of libraries bom
- lint markdown (including line length)

fix: cleanup storage deprecations

---

.github/CODEOWNERS

updating App Engine sample directories to be serverless-runtimes team ownership; leaving functions framework for flex as it was listed there previously. unittests is an app engine sample, moving over to serverless-runtimes as well.

Chore: Cleanup CODEOWNERS for App Engine samples

---

iot/README.md

- Cloud IoT Core will be deprecated on Aug 16 2023
- The Core team has no specific commitment to the samples anymore
- Hence, adding an archived note to the samples directory
- https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7833 tracks the eventual removal of the samples.

chore: add deprecation notice for iot samples

---

dlp/snippets/src/main/java/dlp/snippets/DeIdenitfyWithDeterministicEncryption.java
dlp/snippets/src/test/java/dlp/snippets/DeIdentificationTests.java

Added a sample for [De-identify content through deterministic encryption](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-deterministic)

[DLP] Implemented sample for DeIdenitfy With Deterministic Encryption

---

datalabeling/snippets/pom.xml

fix: restore pom.xml for datalabeling

---

monitoring/v3/src/main/java/com/example/monitoring/CreateAlertPolicy.java
monitoring/v3/src/main/java/com/example/monitoring/DeleteNotificationChannel.java
monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java
monitoring/v3/src/test/java/com/example/monitoring/DeleteNotificationChannelIT.java
monitoring/v3/src/test/java/com/example/monitoring/ListAlertPolicyIT.java

fixes #7916
fixes #7915
fixes #7914
fixes #7913
fixes #7912
i see other badly written tests in this /monitoring directory that will need a larger scale rewrite
- inconsistent use of resource id versus resource names
- not all samples have tests
- unnecessary ITs for each sample, with this type of admin ops, ITs can be combined into a single IT
- repeated use of functions like `requireEnvVar` in each IT and can be extracted instead
- the `java-pubsub` samples repo have some really good examples that can be ref'ed
for now, i've done a few things while being aware that there's a 500 hard limit on alerting policies per google cloud project. these include:
- create test resources for each IT run (of the ITs i touched) and clean them up 
- use consistent naming for resource ids versus names
- …

fix(monitoring): refactor a few monitoring ITs

---

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyWithMasking.java

Code sample DeidentifyWithMasking was using replacement instead of masking. Correcting PrimitiveTransformation to include CharacterMaskConfig instead of ReplaceWithInfoTypeConfig.
Fixes #7935

Deidentify with masking

---

recaptcha_enterprise/demosite/pom.xml
recaptcha_enterprise/demosite/src/main/resources/application.properties

We also need to restore the spring-boot-devtools dependency removed by 
https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7927/files#diff-8244e1351f473dc033a31c273f3c5999a07b1cdb678725da1338908330a30393

Fix live reload of HTML files.

---

dlp/snippets/src/main/java/dlp/snippets/InspectGcsFileSendToScc.java
dlp/snippets/src/test/java/dlp/snippets/JobsTests.java

Implemented [Inspect Gcs File and Send findings to SCC](https://cloud.google.com/dlp/docs/sending-results-to-scc.md?g=0&l=416#cloud-storage-data)

[DLP] Implemented Inspect Gcs File and Send findings to SCC

---

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableWithCryptoHash.java
dlp/snippets/src/test/java/dlp/snippets/DeIdentificationTests.java

Implemented [deidentify data using a cryptographic hash transformation](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_using_a_cryptographic_hash_transformation)

[DLP] Implemented deidentify data using a cryptographic hash transformation

---

appengine-java11-bundled-services/datastore/pom.xml
appengine-java17-bundled-services/datastore/pom.xml
appengine-java8/datastore/pom.xml
appengine-java8/datastore/src/main/java/com/example/appengine/AbstractGuestbook.java
appengine-java8/datastore/src/main/java/com/example/appengine/Greeting.java
appengine-java8/datastore/src/main/java/com/example/time/Clock.java
appengine-java8/datastore/src/main/java/com/example/time/SystemClock.java
appengine-java8/datastore/src/main/java/com/example/time/testing/FakeClock.java
appengine-java8/datastore/src/test/java/com/example/appengine/GuestbookStrongTest.java
iot/api-client/codelab/manager/pom.xml
iot/api-client/codelab/manager/src/main/java/com/example/cloud/iot/examples/MqttCommandsDemo.java
iot/api-client/end-to-end-example/pom.xml
iot/api-client/end-to-end-example/src/main/java/com/example/cloud/iot/endtoend/CloudiotPubsubExampleMqttDevice.java
iot/api-client/manager/pom.xml
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
trace/pom.xml
trace/src/main/java/com/example/trace/TraceSample.java

Migrate from the Joda time library to the standard java.time classes introduced in Java 8. 
More info: https://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html

chore: migrate org.joda.time to java.time (JSR310)

---

dlp/snippets/src/main/java/dlp/snippets/InspectTableWithCustomHotword.java
dlp/snippets/src/test/java/dlp/snippets/InspectTests.java

Implemented [Inspect Table With Custom Hotword ](https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-column-values)

[DLP] Implemented Inspect Table With Custom Hotword

---

dlp/snippets/src/main/java/dlp/snippets/TriggersPatch.java
dlp/snippets/src/test/java/dlp/snippets/TriggersTests.java

Implementation of [Updating an existing job trigger](https://cloud.google.com/dlp/docs/creating-job-triggers#update_an_existing_job_trigger)

[DLP] Update an existing job trigger

---

renovate.json

This will group 3+ SLF4J dependency updates that have a matching version number.

chore: group SLF4J dependency updates

---

secretmanager/pom.xml
secretmanager/src/main/java/secretmanager/ConsumeEventNotification.java
secretmanager/src/test/java/secretmanager/SnippetsIT.java

Bug: b/281694482 
Doc update: cl/533479206

feat: add secretmanager sample for ConsumeEventNotification

---

renovate.json

Grouping Bigtable updates to reduce clutter and ensure consistency. This covers 4 currently open updates, all on 2.8.1.

chore: group Bigtable dependency updates

---

content-warehouse/src/test/java/contentwarehouse/v1/QuickStartTest.java

fix: add multiple retries to Content Warehouse sample

---

aiplatform/src/main/java/aiplatform/CreateCustomJobSample.java
aiplatform/src/test/java/aiplatform/CreateCustomJobSampleTest.java

Fixes #281693980
Added missing Java sample for aiplatform_create_custom_job_sample

fixit: create new Java sample for aiplatform_create_custom_job_sample

---

recaptcha_enterprise/demosite/src/main/java/app/MainController.java

The previous code showed the SCORE_LESS_THAN_THRESHOLD message for invalid tokens.
This matches Javascript and Python samples

Use 'else if' to avoid re-classifying an interaction.

---

dlp/snippets/src/main/java/dlp/snippets/RiskAnalysisKAnonymityWithEntityId.java
dlp/snippets/src/test/java/dlp/snippets/RiskAnalysisTests.java

Implementation of [computing K Anonymity With EntityId.](https://cloud.google.com/dlp/docs/visualizing_re-id_risk.md?g=0&l=119#step_1_calculate_k-anonymity_on_the_dataset)

[DLP] Implementation of computing K Anonymity With EntityId

---

renovate.json

To keep `com.fasterxml.jackson.core:*` dependencies on a consistent version

chore: group jackson.core dependencies

---

spanner/r2dbc/src/test/java/com/example/spanner/r2dbc/R2dbcSampleApplicationIT.java

Fixes #8214 
- The test failed with “Timeout on blocking read” exceptions. The commit ([1e02bf3](https://github.com/GoogleCloudPlatform/java-docs-samples/commit/1e02bf3f2a9c76ff047f87650058475a30738d59)) itself did not change anything about this sample. And this flake looks like a one-off at this point.
- The test already acknowledged this by setting a longer timeout [here](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/43e27985e5ec060081541887974718040adb3c1f/spanner/r2dbc/src/test/java/com/example/spanner/r2dbc/R2dbcSampleApplicationIT.java#L92-L93) (this was recently extended to 120s in change [here](https://github.com/GoogleCloudPlatform/java-docs-samples/commit/57f0927b72843ef50f8199e20cd6e3dcc3c998ee#diff-992d3859c0c34ca26a5093720d94c57d9192210b5fbc25abce465533ceef1506 …

chore(test): extend max timeout to avoid 'Timeout on blocking read'

---

aiplatform/src/main/java/aiplatform/PredictTextSummarizationSample.java
aiplatform/src/test/java/aiplatform/PredictTextSummarizationSampleTest.java

Fixes b/281562687
Add a text summarization sample for Vertex LLMs.

feat: text summarization sample for Vertex LLMs

---

aiplatform/src/main/java/aiplatform/PredictTextPromptSample.java
aiplatform/src/test/java/aiplatform/PredictTextPromptSampleTest.java

Fixes b/281562687
Add a text prompt sample for Vertex LLMs.

feat: text prompt sample for Vertex LLMs

---

appengine-java8/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java

This fix aims to avoid concurrency issues seen in issue 8175, by creating a unique `LocalServiceTestHelper` instance in each process.

fix: experimental fix for 8175

---

aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSample.java
aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java

Fixes b281562687
Added a text embeddings sample with Vertex Gen AI.

feat: text embeddings sample with Vertex Gen AI

---

dialogflow/snippets/src/test/java/com/example/dialogflow/CreateDocumentTest.java

Fixes #8180
Increase the max retries to handle a flaky test.
The flakiness happened but was not often.

fix(dialogflow): increase max retries to handle flaky test

---

aiplatform/src/main/java/aiplatform/CreatePipelineJobModelTuningSample.java
aiplatform/src/test/java/aiplatform/CreatePipelineJobModelTuningSampleTest.java

Fixes b281562687
Add a tune model sample for Vertex LLMs.
Public doc: https://cloud.google.com/vertex-ai/docs/generative-ai/models/tune-models

feat(aiplatform): add tune model sample for Vertex LLMs

---

aiplatform/src/main/java/aiplatform/ListTunedModelsSample.java
aiplatform/src/test/java/aiplatform/ListTunedModelsSampleTest.java

Fixes b281562687
Add a list tuned models sample for Vertex LLMs.
Public doc: https://cloud.google.com/vertex-ai/docs/generative-ai/models/tune-models#view_a_list_of_tuned_models

feat(aiplatform): add the code sample for list the tuned models of the Vertex LLMs

---

renovate.json

The GRPC dependency group currently misses [protoc-gen-grpc-java](https://mvnrepository.com/artifact/io.grpc/protoc-gen-grpc-java), which follows the same versioning scheme.

chore: update grpc dependency group

---

appengine-java8/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java

New retry logic in #8253 is working, but a subsequent assert needs to be updated. This PR updates the assert to check that the method was called at least once, rather than only once.
Error:
```
Wanted 1 time:
-> at com.example.appengine.firetactoe.TicTacToeServletTest.doGetNoGameKey(TicTacToeServletTest.java:183)
But was 2 times:
-> at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:889)
-> at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:889)
at com.example.appengine.firetactoe.TicTacToeServletTest.doGetNoGameKey(TicTacToeServletTest.java:183)
```

fix: address tictactoe test failure

---

aiplatform/src/test/java/aiplatform/FeaturestoreSamplesTest.java

When the creation step fails, the Featurestore sample test throws an NPE during teardown when the creation step fails. This can lead to more confusion when debugging. See below.
Teardown is now updated to delete the featurestore if the feature was actually created.
```
[ERROR]   Run 1: FeaturestoreSamplesTest.testCreateFeaturestoreSample:97 » Cancellation Task wa...
[ERROR]   Run 2: FeaturestoreSamplesTest.tearDown:81 » NullPointer
[ERROR]   Run 3: FeaturestoreSamplesTest.testCreateFeaturestoreSample:97 » Cancellation Task wa...
[ERROR]   Run 4: FeaturestoreSamplesTest.tearDown:81 » NullPointer
[ERROR]   Run 5: FeaturestoreSamplesTest.testCreateFeaturestoreSample:97 » Cancellation Task wa...
[ERROR]   Run 6: FeaturestoreSamplesTest.tearDown:81 » NullPointer
```

chore: cleanup featurestore test teardown

---

dlp/snippets/src/main/java/dlp/snippets/InspectWithStoredInfotype.java
dlp/snippets/src/test/java/dlp/snippets/InfoTypesTests.java
dlp/snippets/src/test/java/dlp/snippets/InspectTests.java

Checked the logs and the issue is that we can't create more than 30 storedInfoTypes. For unit test cases, all the objects are deleted but perhaps because of parallel processing storedInfoType count have exceeded 30. To fix such issues, we have considered mock approach here
Fixes #8342, #8343, #8344

fix: Implemented mock mechanism for the flaky test cases

---

appengine-java8/firebase-tictactoe/src/main/java/com/example/appengine/firetactoe/Game.java
appengine-java8/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java

Hopefully, this fix should resolve the issue once-and-for-all.
It adds a new created date field to the Game object. That enables the test to retrieve the Game with the most recently created date in one query. It avoids more complex logic that was leading to occasional race conditions.
Fixes #8175

fix: flaky tictactoe test

---

aiplatform/src/main/java/aiplatform/PredictImageFromImageAndTextSample.java
aiplatform/src/test/java/aiplatform/PredictImageFromImageAndTextSampleTest.java

Fixes b/288242440
Add code sample to demo how to edit an image using text prompts using image models
Docs: https://cloud.google.com/vertex-ai/docs/generative-ai/image/edit-images

feat(aiplatform): add code sample to update an image using text prompts

---

aiplatform/src/main/java/aiplatform/PredictImageFromTextSample.java
aiplatform/src/test/java/aiplatform/PredictImageFromTextSampleTest.java

Fixes b/288242440
Add code sample to demo how to generate images from text prompts using image models
Doc: https://cloud.google.com/vertex-ai/docs/generative-ai/image/generate-images

feat(aiplataform): add code sample for generating images from text prompts

---

renovate.json

Reduces PRs and keeps versions consistent. See #8367 and #8368

chore: combine io.quarkus dependencies

---

monitoring/v3/src/test/java/com/example/monitoring/ListAlertPolicyIT.java
privateca/snippets/src/main/java/privateca/MonitorCertificateAuthority.java
privateca/snippets/src/test/java/privateca/SnippetsIT.java

Performs cleanup for the `testMonitorCertificateAuthority()` by deleting an alert policy that is created by `createCaMonitoringPolicy()`.
Fixes #8320

fix: cleanup testMonitorCertificateAuthority() test

---

privateca/snippets/README.md
privateca/snippets/src/test/java/privateca/SnippetsIT.java
privateca/snippets/src/test/java/privateca/Util.java

The `privateca` tests regularly hit a create certificate quota limit. This PR adds a utility function which enables distributing the tests across multiple regions to reduce the pressure on quota.
It also fixes existing Java warnings, and lints the README.

fix: address quota warnings for privateca

---

batch/snippets/src/main/java/com/example/batch/CreateWithContainerNoMounting.java
batch/snippets/src/main/java/com/example/batch/CreateWithMountedBucket.java
batch/snippets/src/main/java/com/example/batch/CreateWithScriptNoMounting.java
batch/snippets/src/main/java/com/example/batch/CreateWithTemplate.java
batch/snippets/src/main/java/com/example/batch/DeleteJob.java
batch/snippets/src/main/java/com/example/batch/GetJob.java
batch/snippets/src/main/java/com/example/batch/GetTask.java
batch/snippets/src/main/java/com/example/batch/ListJobs.java
batch/snippets/src/main/java/com/example/batch/ListTasks.java
batch/snippets/src/main/java/com/example/batch/ReadJobLogs.java
batch/snippets/src/test/java/com/example/batch/BatchBasicIT.java
batch/snippets/src/test/java/com/example/batch/BatchBucketIT.java
batch/snippets/src/test/java/com/example/batch/BatchTemplateIT.java
batch/snippets/src/test/java/com/example/batch/Util.java

Change region to `us-central1` to address CPU quota alerts.
Also, addressed code warnings that added `com.example.batch` package and disposed of resources.

fix: update batch region to address quota alerts

---

mediatranslation/README.md
mediatranslation/src/test/java/com/example/mediatranslation/TranslateFromFileTest.java

Updates README file with the deprecation notice.
Marks all tests to be ignored.
Fixes #8393

chore(cleanup): retire media translate samples

---

compute/cloud-client/src/test/java/compute/FirewallIT.java
compute/cloud-client/src/test/java/compute/InstanceOperationsIT.java
compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
compute/cloud-client/src/test/java/compute/InstancesAdvancedIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java
compute/cloud-client/src/test/java/compute/Util.java
compute/cloud-client/src/test/java/compute/customhostname/CustomHostnameInstanceIT.java
compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java
compute/cloud-client/src/test/java/compute/custommachinetype/HelperIT.java
compute/cloud-client/src/test/java/compute/deleteprotection/DeleteProtectionIT.java
compute/cloud-client/src/test/java/compute/disks/DisksFromSourceIT.java
compute/cloud-client/src/test/java/compute/disks/DisksIT.java
compute/cloud-client/src/test/java/compute/disks/SnapshotsIT.java
compute/cloud-client/src/test/java/compute/preemptible/PreemptibleIT.java
compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java
compute/cloud-client/src/test/java/compute/windows/windowsinstances/CreatingManagingWindowsInstancesIT.java

Fixes #8319 and #8384
1. Caught `Assertion Error` in FirewallsIT: Firewall rules are deleted by GCEEnforcer hence leading to flaky assertion.
2. Created a Util method to return random zones for tests. This avoids quota issues.

fix(compute): fix flaky issues in firewall and cmt

---

cdn/signed-urls/src/main/java/com/google/cdn/SignedCookies.java
cdn/signed-urls/src/main/java/com/google/cdn/SignedUrlWithPrefix.java
cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java
cdn/signed-urls/src/test/java/com/google/cdn/SignedCookiesTest.java
cdn/signed-urls/src/test/java/com/google/cdn/SignedUrlWithPrefixTest.java
cdn/signed-urls/src/test/java/com/google/cdn/SignedUrlsTest.java

The Cloud CDN Signed URLs and Signed Cookies features expect signatures to be created with the HMAC-SHA1 algorithm; Google's servers validate signatures using this algorithm. PRs #8103, #8136, and #8183 updated the Java code samples to use HMAC-SHA256 instead, based on the argument that according to GCP's KMS docs on choosing a good algorithm, HMAC-SHA256 is recommended.
While it may be a better algorithm to use when designing a new system, it is not the algorithm used by the Signed URLs and Signed Cookies feature, so these code samples are currently 100% wrong and do not actually work to implement URL/cookie signing! (Fortunately the non-Java code samples are still correct.)
This PR reverts changes made in the above PRs to use the correct HMAC-SHA1 algorithm.
Fixes #8418
Note: Before …

cdn/signed-urls: use correct HMac algorithm

---

.kokoro/tests/run_tests.sh
bigquery/bigqueryconnection/snippets/pom.xml
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/CreateAwsConnection.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/CreateConnection.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/DeleteConnection.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/GetConnection.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/ListConnections.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/QuickstartSample.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/ShareConnection.java
bigquery/bigqueryconnection/snippets/src/main/java/com/example/bigqueryconnection/UpdateConnection.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/CreateAwsConnectionIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/CreateConnectionIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/DeleteConnectionIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/GetConnectionIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/ListConnectionsIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/QuickstartSampleIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/ShareConnectionIT.java
bigquery/bigqueryconnection/snippets/src/test/java/com/example/bigqueryconnection/UpdateConnectionIT.java

Migrating the snippet from googleapis/java-bigqueryconnection https://github.com/googleapis/java-bigqueryconnection/tree/8e1577003242eb019fb07be51fc7b874613e9d3b/samples/snippets
These tests ran fine in https://source.cloud.google.com/results/invocations/bef3f8f1-575b-49e6-979c-cf69c91505f4/targets (May)

feat: migrating java-bigqueryconnection snippet

---

bigtable/beam/change-streams/pom.xml
bigtable/beam/change-streams/src/main/java/SongRank.java

The `withHeartbeatDuration()` method was [removed](https://github.com/apache/beam/pull/27249) in the 2.49.0 Beam release, causing this sample to no longer compile with 2.49.0. The sample will now use the default value of 5 seconds.

fix: remove deprecated method from bigtable change-streams sample

---

bigquery/bigqueryreservation/snippets/pom.xml
bigquery/bigqueryreservation/snippets/src/main/java/com/example/bigqueryreservation/QuickstartSample.java
bigquery/bigqueryreservation/snippets/src/test/java/com/example/bigqueryreservation/QuickstartSampleIT.java

Moving the snippet from https://github.com/googleapis/java-bigqueryreservation/tree/68cf1f5/samples/snippets
The test was succeeding in the old repository https://source.cloud.google.com/results/invocations/31176557-31be-4e48-9539-228a2ea65948.

feat: adding bigqueryreservation snippets

---

bigtable/hbase/snippets/src/test/java/com/example/bigtable/FiltersTest.java

Fixes #7963 
Fixes #7964 
Fixes #7965 
Fixes #7966 
Fixes #7967 

chore: add multiple attempts on bigtable sample

---

aiplatform/src/main/java/aiplatform/UndeployModelSample.java

Fixes b/293345808
We should not to specify trafficSplit when un-deploying a model,  otherwise error ""The following DeployedModel ID(s) [0] do not exist." occurs.

fix(aiplatform): not to set trafficSplit when undeploying model

---

dataflow/snippets/src/main/java/com/example/dataflow/BigQueryStreamExactlyOnce.java
dataflow/snippets/src/test/java/com/example/dataflow/BigQueryWriteIT.java

Adds error handling to show the [dead-letter pattern](https://beam.apache.org/documentation/patterns/bigqueryio/#bigqueryio-deadletter-pattern).
Also removes the call to withNumStorageWriteApiStreams, because this setting now [defaults to autosharding](https://beam.apache.org/documentation/io/built-in/google-bigquery/#exactly-once-semantics), so there is no need to explicitly set a value.

docs(samples): Add error handling for BigQueryIO streaming example

---

.gitignore
accessapproval/snippets/pom.xml
aiplatform/pom.xml
flexible/java-11/analytics/pom.xml
flexible/java-11/cloudstorage/pom.xml
flexible/java-11/datastore/pom.xml
flexible/java-11/pubsub/pom.xml
flexible/java-11/static-files/pom.xml
flexible/java-8/pubsub/pom.xml

Updated `pom.xml` where we are overriding/duplicating the managed versions. This keeps our dependencies in sync within a sample, and also reduces dependency PRs.
Also, added a couple `.gitignore` entries with this PR.

chore: use managed dependencies

---

bigtable/hbase/snippets/src/test/java/com/example/bigtable/FiltersTest.java

Updated the table creation to remove any garbage collection. Default for most Bigtable clients is none, but for HBase client it was 1 max version for consistency with HBase API.
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7963
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7964
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7965
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7966
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7967

docs: fix Bigtable flakey filters test

---

aiplatform/src/main/java/aiplatform/DeployModelSample.java

Fixes b/281672516
Correct the timeout setting for the endpoint service. It should use the deployModelOperationSettings instead of the createEndpointOperationSettings.

fix(aiplatform): correct the timeout setting for the endpoint service

---

storageinsights/pom.xml
storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples/CreateInventoryReportConfig.java
storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples/DeleteInventoryReportConfig.java
storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples/EditInventoryReportConfig.java
storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples/GetInventoryReportNames.java
storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples/ListInventoryReportConfigs.java
storageinsights/src/test/java/com/google/cloud/storage/storageinsights/samples/test/ITStorageinsightsSamplesTest.java

Adds samples for storage insights, intended for this page: https://cloud.google.com/storage/docs/insights/using-inventory-reports

Add storage insights samples

---

storageinsights/src/test/java/com/google/cloud/storage/storageinsights/samples/test/ITStorageinsightsSamplesTest.java

Replaces the sleep in the storageinsights tests with a retry rule, so that delays only happen as much as is needed
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/8534

fix(storageinsights): Replace sleep with retry rule

---

workflows/cloud-client/src/main/java/com/example/workflows/WorkflowsQuickstart.java

This PR adds 2 region tags to the Workflows quickstart sample for planned updates to documentation [here](https://cloud.google.com/workflows/docs/executing-workflow).

chore: add region tags to workflows quickstart

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java

Updates the BatchDML example to use PreparedStatement instead of Statemnet. PreparedStatement has a lower latency when the same SQL string is repeatedly executed multiple times, and we should encourage our users to prefer PreparedStatements whenever possible.

docs: update Batch DML sample to use PreparedStatement

---

aiplatform/src/test/java/aiplatform/FeaturestoreSamplesTest.java

Fixes #8620
Re-add featurestore tests back to the integration tests as the stability issue has been resolved b/290339336.

chore(aiplatform): re-add skipped tests back to the integration

---

video/src/main/java/video/LogoDetectionGcs.java

Fixes #8611
Increase the timeout from 300s to 600s to avoid flaky test. 
The operation can take from 40s to 400s to complete.

fix(video): increase timeout to avoid flaky test

---

discoveryengine/src/main/java/discoveryengine/v1/Search.java
discoveryengine/src/test/java/discoveryengine/v1/SearchTest.java

- Change `searchEngineId` to `dataStoreId`
- Add Endpoint for non-global data stores.
Fixes Internal ticket 300400448

fix: Updates to Vertex AI Search samples after GA

---

compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java

combine image creation and deletion into the one test. assert that image is created before deleting it.
Combines tests for create and delete image code samples in the single test.
Assert that the image is eventually created (READY) before deleting it.
Fixes #8730

chore(fix): refactor image create/delete test

---

aiplatform/src/main/java/aiplatform/CreateTrainingPipelineCustomJobSample.java

Fixes b/305782039
Clarify that argument model_dir is specific to the custom job referred in this sample but not a general argument for all of the container images. This is because we don't use model_dir or model-dir consistently.

chore(aiplatform): clarify argument model_dir

---

run/filesystem/gcsfuse.Dockerfile

The URL for packages.cloud.google.com should be https instead of http.

Fix URL for GCS fuse example.

---

monitoring/cloud-client/src/main/java/com/example/monitoring/Snippets.java
monitoring/cloud-client/src/test/java/com/example/monitoring/SnippetsIT.java

Fixes the code sample tagged  `monitoring_get_descriptor` that is supposed to show the code to get
a custom metric descriptor info.
The current version of the code is a replica of the code sample tagged `monitoring_get_resource`.
Modify the IT method that validates this code sample.
Fixes b/286036224 (feedback report)

fix: update code sample of metric descriptor info

---

run/idp-sql/pom.xml
run/idp-sql/src/main/resources/application.properties
run/idp-sql/src/test/resources/application.properties

Fixes b/302827133
The `spring.datasource.*` properties were deprecated in a previous version of Spring Boot, meaning this sample didn't initialise the database, and the sample wouldn't operate correctly when deployed. 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#SQL-Script-DataSource-Initialization
Fix: update the settings to the new configurations. Manual debug and testing results in bug above. 
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts

fix: update sql initialisation properties

---

pubsublite/streaming-analytics/src/test/java/examples/PubsubliteToGcsIT.java

Fixes #8772
This flaky issue has existed for some time, and retries have not helped.
This change catches an exception when creating the topic and it already exists. That should allow the test to continue. Also, a catch statement has been added to the teardown method when the topic has already been deleted.

fix: catch timing issue on pubsublitetogcs test

---

compute/cloud-client/src/test/java/compute/SnippetsIT.java

Skipping `testSetUsageBucketExportCustomPrefix`. Flaky issue needs to be resolved later.

chore(compute): skipping flaky setUsageBucket test

---

asset/src/test/java/com/example/asset/QuickStartIT.java
asset/src/test/java/com/example/asset/SearchIT.java

Adding an `@Ignore` annotation to a test that consistently fails, blocking other PRs. Will add a comment to the existing issue #8798  to remove this when the issue is resolved.
Also:
* Addressed style warning (`final` unnecessary if `private`)
* Selected a different resource type with fewer instances (to address a timeout in another test)

fix: add skip to test blocked on #8798

---

aiplatform/src/main/java/aiplatform/CreatePipelineJobModelTuningSample.java

Fixes b/306723063
New optional accelerator_type = "GPU/TPU" parameter for tuning pipeline.
Public docs: https://cloud.devsite.corp.google.com/vertex-ai/docs/generative-ai/models/tune-text-models-supervised#generative-ai-tune-model-nodejs

feat: add new optional accelerator_type parameter

---

Makefile

This is a work in progress.
The goal is to provide a consistent way for contributors to built, test, and
lint their samples, regardless of the language repo they are working in.
(Similar PRs are open in other language repos)

feat: Add Makefile for constistent sample interface

---

bigtable/beam/change-streams/src/test/java/ChangeStreamsHelloWorldTest.java

bigtable (docs): add multiple attempts for change stream test

---

dataflow/flex-templates/getting_started/README.md
dataflow/flex-templates/getting_started/metadata.json
dataflow/flex-templates/getting_started/pom.xml
dataflow/flex-templates/getting_started/src/main/java/com/example/dataflow/FlexTemplateGettingStarted.java
dataflow/flex-templates/getting_started/src/test/java/com/example/dataflow/FlexTemplateGettingStartedIT.java

Add a basic flex template sample. This will enable simplifying / streamlining the tutorial [Use Flex Template](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates) in the Dataflow documentation.
Doc bugs: b/309158338, b/309159028

docs(samples): Add Dataflow "Getting started" flex template

---

recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/AccountDefenderAssessment.java
recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/AnnotateAccountDefenderAssessment.java
recaptcha_enterprise/snippets/src/test/java/app/SnippetsIT.java

The new recommended way to provide the user identifier is through the `userInfo.accountId` field in the assessment's `event`.
Change-Id: Icd7bdecb8a783e9a148db2f2b50d1df3d222347c

fix: update references to deprecated `hashed_account_id`

---

.github/renovate.json5
README.md

Remove Java8 badge and add section "Supported Java runtimes" to the root README.
Exclude code samples designated to run under Java 8 runtime from the renovate analysis.
This change is a part of the process described in #8935.
Excluding dependency updates for Java 8 code samples will allow to reduce a number of flaky tests in each renovate PR.

chore(proc): prevent dependency upgrades for java8 code samples

---

vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java

Fixes internal bug tracked as b/316922981
Favor putting images first, prompt second, in multimodal queries.

Use image first in prompts

---

media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/CreateCdnKeyAkamai.java
media/stitcher/src/main/java/com/example/stitcher/CreateLiveConfig.java
media/stitcher/src/main/java/com/example/stitcher/CreateLiveSession.java
media/stitcher/src/main/java/com/example/stitcher/CreateSlate.java
media/stitcher/src/main/java/com/example/stitcher/CreateVodSession.java
media/stitcher/src/main/java/com/example/stitcher/DeleteCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/DeleteLiveConfig.java
media/stitcher/src/main/java/com/example/stitcher/DeleteSlate.java
media/stitcher/src/main/java/com/example/stitcher/GetCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveAdTagDetail.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveConfig.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveSession.java
media/stitcher/src/main/java/com/example/stitcher/GetSlate.java
media/stitcher/src/main/java/com/example/stitcher/GetVodAdTagDetail.java
media/stitcher/src/main/java/com/example/stitcher/GetVodSession.java
media/stitcher/src/main/java/com/example/stitcher/GetVodStitchDetail.java
media/stitcher/src/main/java/com/example/stitcher/ListCdnKeys.java
media/stitcher/src/main/java/com/example/stitcher/ListLiveAdTagDetails.java
media/stitcher/src/main/java/com/example/stitcher/ListLiveConfigs.java
media/stitcher/src/main/java/com/example/stitcher/ListSlates.java
media/stitcher/src/main/java/com/example/stitcher/ListVodAdTagDetails.java
media/stitcher/src/main/java/com/example/stitcher/ListVodStitchDetails.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKeyAkamai.java
media/stitcher/src/main/java/com/example/stitcher/UpdateSlate.java

Remove try block for LROs and call close on the client per https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8494#pullrequestreview-1561456858. Also, update comments on non-LROs that you don't need to call close when using try-with-resources.

feat: update samples with LROs to not use a try block

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgAutoPartitionModeExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgDataBoostExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgPartitionQueryExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/PgRunPartitionedQueryExample.java
spanner/jdbc/src/test/java/com/example/spanner/jdbc/BaseJdbcPgExamplesIT.java
spanner/jdbc/src/test/java/com/example/spanner/jdbc/PgPartitionedQueryIT.java

Adds samples for running partitioned queries with the Spanner JDBC driver on PostgreSQL-dialect databases.

feat: samples for partitioned queries on Spanner with PostgreSQL

---

recaptcha_enterprise/snippets/src/main/java/recaptcha/account_defender/SearchRelatedAccountGroupMemberships.java
recaptcha_enterprise/snippets/src/test/java/app/SnippetsIT.java

This is the leftover from https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8844.

fix: update references to deprecated hashed_account_id

---

.kokoro/tests/run_test_java.sh

feat(testing): convert CI to use Makefile for testing

---

.kokoro/tests/run_test_java.sh

Change Kokoro test script execution to exclude running [flakybot] on the test results of Java8 tests.
We run tests on Java 8 runtime for the reference only since Java 8 runtime support is deprecated.

chore: exclude flakybot to run on Java8 tests

---

README.md

Versions:
Java 8 : badge removed as this version is in maintenance mode for existing samples.
Java 11 and 17: badge supported as periodic builds reflect health of the samples against these versions
Java 21: badge added to reflect nightly build results

chore: update workflow badges

---

aiplatform/src/main/java/aiplatform/UndeployModelSample.java

fix: use model id instead of model name in undeployModelAsync

---

aiplatform/src/main/java/aiplatform/PredictImageFromImageAndTextSample.java
aiplatform/src/main/java/aiplatform/PredictImageFromTextSample.java
aiplatform/src/test/java/aiplatform/PredictImageFromImageAndTextSampleTest.java
aiplatform/src/test/java/aiplatform/PredictImageFromTextSampleTest.java

Reverts GoogleCloudPlatform/java-docs-samples#8391
The samples can be republished as the underlying features become publicly available.

chore(aiplatform): Revert "chore(aiplatform): temporarily remove unready samples"

---

aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSample.java
aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSamplePreview.java
aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java

feat: Elastic Text-Embedding demo.

---

healthcare/v1/src/test/java/snippets/healthcare/DicomWebTests.java

Only store DICOM instance once for all DICOMweb tests. Previously, storing a duplicate instance returned a 200, but it now returns a 409, causing tests to fail.
The JUnit4 MethodSorters (https://junit.org/junit4/javadoc/4.12/org/junit/runners/MethodSorters.html) functionality is also incorrectly running the DicomWebDeleteStudy test too early, even though its name was modified so that it ran last in the NAME_ASCENDING order, so update each test's name to ensure that they run in order.
Fixes
* #9266
* #9265 
* #9264 
* #9263 
* #9262 
* #9261 
- [] Appropriate changes to README are included in PR

fix(healthcare): don't store DICOM instance before each DICOMweb test

---

storageinsights/src/main/java/com/google/cloud/storage/storageinsights/samples/EditInventoryReportConfig.java
storageinsights/src/test/java/com/google/cloud/storage/storageinsights/samples/test/ITStorageinsightsSamplesTest.java

In storageinsights, you need to set the field mask in order to update an inventory report config. This fixes the sample so that it takes this into account, and fixes the test to catch it.

storageinsights: update edit inventory report config sample

---

iam/api-client/pom.xml
iam/api-client/src/main/java/iam/snippets/CreateServiceAccount.java
iam/api-client/src/main/java/iam/snippets/DeleteServiceAccount.java
iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java

refactor(iam): update service account samples to use GAPIC library

---

compute/cloud-client/src/test/java/compute/SnippetsIT.java

Unignore SnippetsIT.testSetUsageBucketExportCustomPrefix cause can't reproduce flaky test, rerun 20 times during 2 days 
Fixes #8855

compute: testSetUsageBucketExportCustomPrefix Flaky test should be handled

---

asset/src/test/java/com/example/asset/SearchIT.java

Unignore SearchIT.testSearchAllResourcesExample cause problems with the dataset are fixed, and the test working 
Fixes #8798

Asset inventory: searchAllResources sample not working for Bigquery Dataset #8798

---

vertexai/snippets/src/main/java/vertexai/gemini/TextInput.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

feat: add gemini code sample and test for text-only input

---

aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSample.java
aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java

feat: Text Embedding Sample override 003 model to 004

---

run/hello-broken/src/main/java/com/example/cloudrun/App.java
run/image-processing/src/main/java/com/example/cloudrun/ImageMagick.java
run/image-processing/src/main/java/com/example/cloudrun/PubSubController.java
run/logging-manual/pom.xml
run/logging-manual/src/main/java/com/example/cloudrun/App.java
run/pubsub/src/main/java/com/example/cloudrun/PubSubApplication.java
run/pubsub/src/main/java/com/example/cloudrun/PubSubController.java

Manually searched docs and confirmed no references remain. Only removed comments, no code changes.
Removed these tags:
run_broken_service_upgrade
run_broken_service_problem
run_broken_service
run_pubsub_server
run_pubsub_handler
run_manual_logging
run_imageproc_controller
run_imageproc_handler_setup
run_imageproc_handler_blur
run_imageproc_handler_analyze
These tags are referenced in docs at all, so removed both variations: run_manual_logging_dep
cloudrun_manual_logging_dep
run_manual_logging_jib
cloudrun_manual_logging_jib

chore(fixit): remove redundant region tags

---

functions/concepts/lazy-fields/src/main/java/functions/LazyFields.java
functions/concepts/scopes/src/main/java/functions/Scopes.java
run/helloworld/src/main/java/com/example/helloworld/HelloworldApplication.java
run/markdown-preview/editor/src/main/java/com/example/cloudrun/RenderController.java
run/system-package/src/main/java/com/example/cloudrun/App.java

Remove redundant region tags: 
run_helloworld_service
run_secure_request
run_secure_request_do
run_system_package_exec
run_system_package_handler
run_tips_global_lazy
run_tips_global_scope
(Some tags remain in XML files (and also in java files if also in those XML files)

fixit: remove redundant region tags

---

compute/cloud-client/src/test/java/compute/InstancesAdvancedIT.java
compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java

unignore tests, rerun 5 times without failings
Fixes #8965

compute/cloud-client test(s) are failing #8965

---

spanner/r2dbc/src/test/java/com/example/spanner/r2dbc/R2dbcSampleApplicationIT.java

added creation of the instance and only then the creation of database, added after block to close delete an instance, db and close all connections
Fixes #8978

spanner/r2dbc test(s) are failing #8978

---

run/logging-manual/src/main/java/com/example/cloudrun/App.java

This App.java is referenced in https://cloud.google.com/run/docs/samples/cloudrun-manual-logging#cloudrun_manual_logging-java. But the document does not explain how to instantiate and configure the logger variable.
https://cloud.google.com/run/docs/logging#run_manual_logging-java has the answer. So let's add the explanation in the source code comment.

chore: comment about how to instantiate logger variable in Cloud Run

---

eventarc/pubsub/Dockerfile

Removes unused region tag:
-  eventarc_pubsub_dockerfile

fix: remove unused region tag eventarc_pubsub_dockerfile

---

security-command-center/snippets/src/main/java/vtwo/findings/ListAllFindings.java
security-command-center/snippets/src/main/java/vtwo/source/GetSource.java
security-command-center/snippets/src/main/java/vtwo/source/ListSources.java
security-command-center/snippets/src/main/java/vtwo/source/UpdateFindingSource.java
security-command-center/snippets/src/main/java/vtwo/source/UpdateSource.java
security-command-center/snippets/src/test/java/vtwo/SourceIT.java

feat: Adding API v2 Source samples

---

aiplatform/src/main/java/aiplatform/CreateBatchPredictionJobSample.java
aiplatform/src/main/java/aiplatform/CreateCustomJobSample.java
aiplatform/src/main/java/aiplatform/CreateHyperparameterTuningJobPythonPackageSample.java
aiplatform/src/main/java/aiplatform/CreateHyperparameterTuningJobSample.java

Updating NVIDIA_TESLA_K80 to NVIDIA_TESLA_T4, as the former has reached End of Life support (https://cloud.google.com/compute/docs/eol/k80-eol)

fix(aiplatform): Update NVIDIA_TESLA_K80 to NVIDIA_TESLA_T4

---

aiplatform/src/main/java/aiplatform/EmbeddingModelTuningSample.java
aiplatform/src/test/java/aiplatform/EmbeddingModelTuningSampleTest.java

Update embedding tuning sample to use the v1.1.3 pipeline.
Also remove some extra `[START aiplatform_sdk_embedding_model_tuning]` tags that led to incorrect display in docs
BUG=b/340594864

feat: Update embedding tuning sample to use the v1.1.3 pipeline.

---

aiplatform/src/test/java/aiplatform/EmbeddingModelTuningSampleTest.java

fix: Use Alphabet 10k sample dataset.

---

.kokoro/prptst/common.cfg
.kokoro/prptst/periodic.cfg
.kokoro/prptst/run_tests.sh

Adds kokoro configuration files (SCM side) to support testing a subset of the tests on PRPTST universe.
The new configuration is copied from java17 config files and modified to do the following:
* Reduce the timeout
* Use "local" bash script
* Execute testing using PRPTST project `java-docs-samples-testing` with the service account created in that project
* Retrieve the key from the "original" (on GDU) `java-docs-samples-testing` project
* Remove all unused commands and instructions
* Remove use of `btlr`

chore(proc): add periodic test config for TPC testing

---

.github/CODEOWNERS

docs: add greater pubsub org as owners of managedkafka directory

---

.kokoro/prptst/run_tests.sh

Fix the name of the project sa key.
Set up the names of the compute zones to the list supported by PRPTST.
Set up the project ID that is used for compute images tests to be real project. Note that the test will still fail because expected images aren't there yet.

chore(proc): Update TPC test config

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergRead.java
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergWrite.java
dataflow/snippets/src/test/java/com/example/dataflow/ApacheIcebergIT.java

Add code snippets for reading and writing to Apache Iceberg using the Dataflow managed I/O transform.
Fixes doc bug: b/341806230 (part of the work for b/338063763)

docs(samples): Add snippets for Apache Iceberg using Managed I/O

---

appengine-java8/datastore/src/test/java/com/example/appengine/QueriesTest.java

The sample with region tag `gae_java8_datastore_inequality_filters_sort_orders_valid` is no longer used.
Removing the region tag. Since there are other region tags in the file that could be disrupted, I am not deleting the code now. Code cleanup will be handled with last dependents on the code are removed.

chore(appengine-java8): remove unused gae_java8_datastore_inequality_filters_sort_orders_valid

---

jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java

The region tag custom_attribute_filter_multi_attributes in the file jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java is being migrated adding a correct "job_" prefix to the region. After merging the old region will be deprecated and removed from the documents.
Internal: b/347826138

Added modified region tag for migration

---

appengine-java8/appidentity/src/main/java/com/example/appengine/appidentity/IdentityServlet.java

This sample is no longer deployable, removing region tag. Once the last region tag is ready to be removed from this sample app the whole directory can be deleted.

chore(appengine-java8): Remove region tag gae_java8_app_identity_versioned_hostnames

---

jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java

The new region tag has been previously added and updated in the documentation. 
The old region tag can be now removed.
bug 347826138

bug 347826138 clean up the deprecated region attribute custom_attribte_filter_multi_attributes

---

.kokoro/tests/run_prptst_tests.sh

After provisioning secrets to the shared location, the script is updated to use the same secret reading mechanism as in run_tests.sh.

chore: modify secret management

---

.kokoro/tests/run_prptst_tests.sh

Remove redundant `fi` in `run_prptst_tests.sh` after previous refactoring.

chore: remove redundant fi

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergRead.java
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergWrite.java
dataflow/snippets/src/main/java/com/example/dataflow/PubSubWriteWithAttributes.java

- Bump Apache Beam version
- Update Iceberg snippets to latest API
- Minor fixes to comments

docs(samples): Update Dataflow snippets to Beam 2.57

---

.github/CODEOWNERS

Add `GoogleCloudPlatform/gcp-security-command-center` team as codeowners for Security Command Center samples.

chore: update CODEOWNERS to add SCC team

---

bigtable/beam/batch-write-flow-control-example/README.md
bigtable/beam/batch-write-flow-control-example/pom.xml
bigtable/beam/batch-write-flow-control-example/src/main/java/bigtable/BatchWriteFlowControlExample.java
bigtable/beam/batch-write-flow-control-example/src/test/java/bigtable/BatchWriteFlowControlExampleTest.java

Add a batch write flow control example for Bigtable
- [] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample

Add a batch write flow control example for Bigtable

---

aiplatform/src/main/java/aiplatform/CreatePipelineJobModelTuningSample.java
aiplatform/src/main/java/aiplatform/EmbeddingModelTuningSample.java
aiplatform/src/main/java/aiplatform/PredictChatPromptSample.java
aiplatform/src/main/java/aiplatform/PredictCodeChatSample.java
aiplatform/src/main/java/aiplatform/PredictCodeCompletionCommentSample.java
aiplatform/src/main/java/aiplatform/PredictCodeGenerationFunctionSample.java
aiplatform/src/main/java/aiplatform/PredictImageFromImageAndTextSample.java
aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSample.java
aiplatform/src/main/java/aiplatform/PredictTextPromptSample.java
vertexai/snippets/src/main/java/vertexai/gemini/GetTokenCount.java

Adding `generativeaionvertexai_` region tags to replace old `aiplatform_`
In near future GenAI code samples, will only use `generativeaionvertexai_` region tag prefix.
Fixes: [b/350918509](b/350918509)

docs(generativeai): add region tags for code samples

---

vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

fix: generativeaionvertexai_gemini_get_started

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergRead.java
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergWrite.java

Beam 2.58.0 introduced breaking changes in the configuration parameters for the Apache Iceberg I/O connector. This PR updates the corresponding Dataflow snippets.
Doc bug: b/353519510

docs(samples): Update Dataflow Iceberg samples for Beam 2.58.0

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/KafkaRead.java
dataflow/snippets/src/test/java/com/example/dataflow/KafkaReadIT.java

Add code snippets for reading from Kafka using the Dataflow managed I/O transform.
Doc bugs:
- b/338063763: Managed I/O documentation [includes Kafka support]
- b/342015050: Document best practices for using Kafka with Dataflow
-

docs(samples): Add Kafka to Dataflow snippet

---

.github/CODEOWNERS

add GoogleCloudPlatform/teams/text-embedding to CODEOWNERS of `aiplatform` samples

chore: add GoogleCloudPlatform/text-embedding to CODEOWNERS

---

vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
vertexai/snippets/src/main/java/vertexai/gemini/FunctionCalling.java
vertexai/snippets/src/main/java/vertexai/gemini/GetTokenCount.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalMultiImage.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalQuery.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalVideoInput.java
vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java

No code change. Goal of this PR is to remove unsed `aiplatform_` region tags
I have added `generativeaionvertexai_` region tags to replace old `aiplatform_`; In near future GenAI code samples, will only use `generativeaionvertexai_` region tag prefix.
In Cloud documentation, all samples using `aiplatform_` are cleared. Any pending Samples browser page, will be update automatically after this PR.
Fixes b/355202776

docs(generativeai): clear unused region tags for code samples

---

.github/CODEOWNERS

* Fix syntax error (missing space between two team names)
* Remove empty @GoogleCloudPlatform/functions-framework-google
* Remove empty (and redundant) @GoogleCloudPlatform/cloud-asset-platform-team
* Remove defunct torus-dpe, dee-platform-ops, and dee-data-ai teams

chore: Refresh CODEOWNERS

---

iam/snippets/src/main/java/DeleteServiceAccountKey.java
iam/snippets/src/main/java/DisableServiceAccountKey.java
iam/snippets/src/main/java/EnableServiceAccountKey.java
iam/snippets/src/main/java/GetServiceAccountPolicy.java
iam/snippets/src/main/java/Quickstart.java
iam/snippets/src/main/java/SetServiceAccountPolicy.java

Fixes the following issues with the code comments:
- Removes query string that forces documentation links to go to the English version of the page (?hl=en)
- Updates text to correctly indicate what each service account is for (several pages incorrectly said that the service accounts were to specify which key should be deleted)

Update comments for IAM samples

---

aiplatform/pom.xml
aiplatform/src/main/java/aiplatform/BatchTextPredictionSample.java
aiplatform/src/test/java/aiplatform/BatchTextPredictionSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextClassificationSampleTest.java

This sample was done for Python - https://github.com/GoogleCloudPlatform/python-docs-samples/blob/3d6340881961a238b2ecc3a0028a02aa2ee9d944/generative_ai/batch_predict/batch_text_predict.py

feat(aiplatform): add batch text predict sample

---

SAMPLE_FORMAT.md

Modify snippet method's return value guidelines to enable more robust testing.
Fix markdown lint warning for the modified section of the document.

chore(docs): change guidelines for snippet return values

---

dataplex/snippets/src/main/java/dataplex/CreateEntryGroup.java
dataplex/snippets/src/main/java/dataplex/DeleteEntryGroup.java
dataplex/snippets/src/main/java/dataplex/GetEntryGroup.java
dataplex/snippets/src/main/java/dataplex/ListEntryGroups.java
dataplex/snippets/src/main/java/dataplex/UpdateEntryGroup.java
dataplex/snippets/src/test/java/dataplex/EntryGroupIT.java

feat(dataplex): add code samples for Entry Group

---

dataplex/snippets/src/main/java/dataplex/CreateEntryType.java
dataplex/snippets/src/main/java/dataplex/DeleteEntryType.java
dataplex/snippets/src/main/java/dataplex/GetEntryType.java
dataplex/snippets/src/main/java/dataplex/ListEntryTypes.java
dataplex/snippets/src/main/java/dataplex/UpdateEntryType.java
dataplex/snippets/src/test/java/dataplex/EntryTypeIT.java

feat(dataplex): add code samples for Entry Type

---

flexible/java-17/cloudstorage/README.md
flexible/java-17/cloudstorage/pom.xml
flexible/java-17/cloudstorage/src/main/appengine/app.yaml
flexible/java-17/cloudstorage/src/main/java/com/example/cloudstorage/Main.java
flexible/java-17/cloudstorage/src/main/java/com/example/cloudstorage/UploadServlet.java
flexible/java-17/cloudstorage/src/main/webapp/index.html
flexible/java-17/cloudstorage/src/test/java/com/example/cloudstorage/UploadServletTest.java
flexible/java-17/datastore/README.md
flexible/java-17/datastore/pom.xml
flexible/java-17/datastore/src/main/appengine/app.yaml
flexible/java-17/datastore/src/main/java/com/example/datastore/DatastoreServlet.java
flexible/java-17/datastore/src/main/java/com/example/datastore/Main.java
flexible/java-17/datastore/src/test/java/com/example/datastore/DatastoreServletTest.java
flexible/java-17/websocket-jetty/README.md
flexible/java-17/websocket-jetty/pom.xml
flexible/java-17/websocket-jetty/src/main/appengine/app.yaml
flexible/java-17/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/ClientSocket.java
flexible/java-17/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/EchoServlet.java
flexible/java-17/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/Main.java
flexible/java-17/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/SendServlet.java
flexible/java-17/websocket-jetty/src/main/java/com/example/flexible/websocket/jettynative/ServerSocket.java
flexible/java-17/websocket-jetty/src/main/webapp/WEB-INF/index.jsp
flexible/java-17/websocket-jetty/src/main/webapp/WEB-INF/jetty-web.xml
flexible/java-17/websocket-jetty/src/main/webapp/WEB-INF/js_client.jsp
flexible/java-17/websocket-jetty/src/test/java/com/example/flexible/websocket/jettynative/ClientSocketTest.java
flexible/java-17/websocket-jetty/src/test/java/com/example/flexible/websocket/jettynative/SendServletTest.java

Migrate java-11 cloudstorage, websocket-jetty, datastore sample app to use Java 17 (and later). 
Java 20+ might have warning at compile but the app runs as expected

Migrate java-11 sample app to use Java17

---

aiplatform/src/main/java/aiplatform/EmbeddingBatchSample.java
aiplatform/src/main/java/aiplatform/EmbeddingModelTuningSample.java
aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSample.java
aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSamplePreview.java
aiplatform/src/test/java/aiplatform/EmbeddingBatchSampleTest.java
aiplatform/src/test/java/aiplatform/EmbeddingModelTuningSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java

Fixes: b/366507572: Getting embeddings using text-embedding-005

feat: Getting embeddings using text-embedding-005.

---

dataflow/snippets/src/main/java/com/example/dataflow/ReadFromStorage.java
dataflow/snippets/src/test/java/com/example/dataflow/ApacheIcebergIT.java
dataflow/snippets/src/test/java/com/example/dataflow/BigQueryWriteIT.java
dataflow/snippets/src/test/java/com/example/dataflow/BiqQueryReadIT.java
dataflow/snippets/src/test/java/com/example/dataflow/PubSubWriteIT.java
dataflow/snippets/src/test/java/com/example/dataflow/ReadFromStorageIT.java

Adds a snippet that shows how to read from a Cloud Storage file into Dataflow.
Also fixed some integration tests that were failing due to setting System.out to null.
Snippet bug: b/340947448
Related doc bug: b/337851367
I structured this snippet similarly to the KafkaRead sample: The snippet includes the code to create the pipeline, but leaves out the options class and the code to run the pipeline.

docs(samples): Add Dataflow snippet for reading from Cloud Storage

---

auth/src/main/java/UndeleteApiKey.java
auth/src/test/java/ApiKeySnippetsIT.java

Documentation - https://cloud.google.com/docs/authentication/api-keys#java_6

feat(auth): add apikeys undelete api key sample.

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/KafkaReadTopics.java
dataflow/snippets/src/test/java/com/example/dataflow/KafkaReadIT.java

Add a code snippet that shows how to read from multiple Kafka topics in a Dataflow pipeline. This snippet shows a recommended pattern for handling messages from several Kafka topics within the same pipeline. This snippet will appear in a doc that outlines best practices for reading Kafka in Dataflow. 
- Snippet bug: b/362324327
- Related doc bug: b/342015050 
A Python version of this snippet is here: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12530

docs(samples): Read multiple Kafka topics from Dataflow

---

dataplex/snippets/src/main/java/dataplex/SearchEntries.java
dataplex/snippets/src/test/java/dataplex/SearchEntriesIT.java

feat(dataplex): add code samples for search Entries

---

dataplex/quickstart/pom.xml
dataplex/quickstart/src/main/java/dataplex/Quickstart.java
dataplex/quickstart/src/test/java/dataplex/QuickstartIT.java

feat(dataplex): add quickstart for dataplex

---

spanner/opentelemetry/pom.xml
spanner/opentelemetry/src/main/java/com/example/spanner/OpenTelemetryUsage.java

This PR fixes the OpenTelemetry metrics documentation to include the bom details and add meterProvider.close() in the sample [here](https://cloud.google.com/spanner/docs/capture-custom-metrics-opentelemetry#before-you-begin)

fix(spanner): opentelemetry metrics documentation

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/ResourceCollector.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Verify.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallLabels.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/ProxyHandler.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Metrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/NoopMetrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Tracer.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeMetricsTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/core/CallLabelsTest.java

CallLabels apply to more than just metrics, this is the first part of generalizing them.

chore: bigtable-proxy move CallLabels to core

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallLabels.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Metrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/NoopMetrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Tracer.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeMetricsTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/core/CallLabelsTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImplTest.java

NOTE: this is depends on and includes #9746
Metric labels are derived from CallLabels, but they are not the same thing

chore: decouple Otel from CallLabels

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/ResourceCollector.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallLabels.java

NOTE: this depends on and includes #9747
Derive a PrimingKey from CallLabels. PrimingKeys are now collected by ResourceCollector instead of raw PingAndWarmRequests. This will allow us to capture more RLS headers in PingAndWarm in the future.

chore: introduce PrimingKey to encapsulate PingAndWarm request & metadata

---

eventarc/storage-handler/src/main/java/com/example/cloudrun/CloudEventController.java
functions/v2/firebase/firestore-reactive/src/main/java/functions/FirebaseFirestoreReactive.java
functions/v2/firebase/firestore/src/main/java/functions/FirebaseFirestore.java
functions/v2/hello-gcs/src/main/java/functions/HelloGcs.java
functions/v2/imagemagick/src/main/java/functions/ImageMagick.java
functions/v2/ocr/ocr-process-image/src/main/java/functions/OcrProcessImage.java

This PR sets all of the calls to protojson.Unmarshal() to DiscardUnknown fields. This will reduce the likelihood of customers encountering errors in their deployed functions. This PR also adds a comment explaining the usage of the DiscardUnknown field.

fix(eventarc): sets protojson to ignoreUnknownFields

---

managedkafka/examples/pom.xml
managedkafka/examples/src/main/java/examples/CreateCluster.java
managedkafka/examples/src/main/java/examples/DeleteCluster.java
managedkafka/examples/src/main/java/examples/UpdateCluster.java
managedkafka/examples/src/test/java/examples/ClustersTest.java

* feat(managedkafka): increase timeouts to 1 hour for Create/Update/Delete cluster 
* feat(managedkafka): added code sample for polling logs in CreateCluster

feat(managedkafka): increase LRO timeout to 1 hour in client samples

---

jobs/v4/pom.xml

Delete sample or region tag: jobs_java_dependencies_beta at jobs/v4/pom.xml
Fixes Internal: b/347352230
Note for the reviewer: See the Issue for detail on the strategy followed.

chore(job): delete sample jobs_java_dependencies_beta

---

iam/snippets/src/main/java/AddMember.java

Includes changing "member" to "principal" and linking to principal identifiers page instead of specifying recommended format.

Update AddMember.java comments

---

security-command-center/snippets/src/main/java/management/api/CreateEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/DeleteEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/GetEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/ListEventThreatDetectionCustomModules.java
security-command-center/snippets/src/test/java/management/api/EventThreatDetectionCustomModuleTest.java

Fixes # b/347346890, b/347346971, b/347346892, b/347346464
Reference to b/347346890, b/347346971, b/347346892, b/347346464
This PR adds SCC Managament API Org Event Threat Detection Custom Module Code Samples for Create, Delete, List & Get.

feat(securitycenter): Add Resource SCC Management API Org ETD Custom Module code samples (Create, Delete, List, Get)

---

storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/util/TransferJobUtils.java

Migrate old region all to storagetransfer_transfer_all to associate it with official product and function
Fixes [b/347826316](https://b.corp.google.com/issues/347826316)

fix(storage): migrate old region all to storagetransfer_transfer_all step 1

---

jobs/v3/src/main/java/com/google/samples/BasicJobSample.java

Delete old region tag create_job
Fixes 
[b/347826077](https://b.corp.google.com/issues/347826077)

fix(job): remove old region create_job

---

jobs/v3/src/main/java/com/google/samples/BasicJobSample.java

Delete old region tag "update_job_with_field_mask"
Fixes [b/347826098](https://b.corp.google.com/issues/347826098)

fix(job): delete old region tag update_job_with_field_mask

---

jobs/v3/src/main/java/com/google/samples/BasicCompanySample.java

Adding new region tag as first step
Internal
b/347826075
b/347826038
b/347826042
b/347826020

feat(job): migrate region tags to include product prefix

---

endpoints/getting-started/k8s/esp_echo_http.yaml

Add "endpoints_" and "_java" suffix to all regions, also replace "-" character to underscore
Fixes [b/347825448](https://b.corp.google.com/issues/347825448)

fix(endpoints): migrate all regions

---

.kokoro/tests/run_prptst_tests.sh
.kokoro/tests/run_test_java.sh

Disable lingering flakybot reporting on periodic builds. Flakybot was disabled for this repo several months ago.

fix: disable flakybot reporting

---

jobs/v3/src/main/java/com/google/samples/BasicCompanySample.java

Delete unused region tags from migration and deletion processes related with BasicCompanySample.java
Fixes 
Internal
b/347826075
b/347826038
b/347826042
b/347826020
b/347351874
b/347351606
b/347351980

chore(job): remove unused region tags

---

security-command-center/snippets/src/main/java/management/api/CreateEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/DeleteEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/GetEffectiveEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/GetEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/ListDescendantEventThreatDetectionCustomModules.java
security-command-center/snippets/src/main/java/management/api/ListEffectiveEventThreatDetectionCustomModules.java
security-command-center/snippets/src/main/java/management/api/ListEventThreatDetectionCustomModules.java
security-command-center/snippets/src/main/java/management/api/UpdateEventThreatDetectionCustomModule.java
security-command-center/snippets/src/main/java/management/api/ValidateEventThreatDetectionCustomModule.java
security-command-center/snippets/src/test/java/management/api/EventThreatDetectionCustomModuleTest.java

Fixes # b/347346777, b/347346891, b/347346970, b/347346994, b/347346149
This PR adds SCC Managament API Org Event Threat Detection Custom Module Code Samples for Update, Get Effective, List Effective, List Descendant and Validate.

feat(securitycenter): Add Resource SCC Management API Org ETD Custom Module code samples (Update, Get Eff, List Eff, List Desc, Validate)

---

endpoints/getting-started/k8s/esp_echo_http.yaml

Fixes [b/347825448](https://b.corp.google.com/issues/347825448)

fix(endpoints): update new regions adding _yaml_

---

storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/util/TransferJobUtils.java

Delete old region tag "all"
Fixes [b/347826316](https://b.corp.google.com/issues/347826316)

fix(storagetransfer): deleted old region tags (all)

---

compute/sendgrid/pom.xml
compute/sendgrid/src/main/java/com/example/compute/sendgrid/SendEmailServlet.java

Migrate old 'example' region to 'compute_sendgrid' to officially associate it with a product.
Fixes [b/386956670](https://b.corp.google.com/issues/386956670)

fix(compute): migrate region 'example' to 'compute_sendgrid'

---

endpoints/getting-started/k8s/esp_echo_http.yaml

Delete old region tags
secret-1
service
secret-2
Fixes [b/347825448](https://b.corp.google.com/issues/347825448)

fix(endpoints): remove old region tags

---

jobs/v3/src/main/java/com/google/samples/LocationSearchSample.java

Fixes 
[b/347826159](https://b.corp.google.com/issues/347826159)
basic_location_search -> job_basic_location_search 
[b/347826166](https://b.corp.google.com/issues/347826166)
keyword_location_search -> job_keyword_location_search
[b/347826161](https://b.corp.google.com/issues/347826161)
city_location_search -> job_city_location_search
[b/347826174](https://b.corp.google.com/issues/347826174)
multi_locations_search -> job_multi_locations_search
[b/384049653](https://b.corp.google.com/issues/384049653)
broadening_location_search -> job_broadening_location_search

chore(job): delete old region tags from LocationSearchSample.java

---

jobs/v3/src/main/java/com/google/samples/AutoCompleteSample.java

chore(job): delete unused region tag after migration

---

security-command-center/snippets/src/main/java/management/api/GetSecurityCenterService.java
security-command-center/snippets/src/main/java/management/api/ListSecurityCenterServices.java
security-command-center/snippets/src/main/java/management/api/UpdateSecurityCenterService.java
security-command-center/snippets/src/test/java/management/api/SecurityCenterServiceTest.java

Fixes # b/347346449, b/347346682, b/347346802
This PR adds SCC Managament API Org Security Center Service Custom Module Samples for Get, List and Update.

feat(securitycenter): Add Resource SCC Management API Org Security Center Service Custom Module samples (Get, List, Update)

---

recaptcha_enterprise/snippets/src/main/java/recaptcha/CreateAssessment.java

Add ja4 to CreateAssessment code snippet used in recaptcha docs

docs: add ja4 to CreateAssessment code snippet used in recaptcha docs

---

appengine-java21/helloworld/build.gradle

This build.gradle file will be referenced in https://cloud.google.com/appengine/docs/standard/java-gen2/using-gradle#linuxmacos (which currently references outdated Java 8 build.gradle settings)

chore: add region tags to appengine java 21 gradle file

---

compute/sendgrid/pom.xml

Delete old region to 'compute_sendgrid_dependencies_java' to officially associate it with a product.
Fixes b/347825311

chore(compute): delete old region "compute_sendgrid_dependendies_java"

---

cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectorConnectionPoolFactory.java
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectorIamAuthnConnectionPoolFactory.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectorConnectionPoolFactory.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectorIamAuthnConnectionPoolFactory.java
cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectorConnectionPoolFactory.java

Fixes #388034268
Enabled lazy refresh for the Java Cloud SQL connector (Postgres, MySQL, and SQL Server).

feat(cloud sql): add lazy refresh property for postgres, sql server and mysql

---

compute/error-reporting/pom.xml
compute/error-reporting/src/main/java/com/example/compute/errorreporting/ExceptionUtil.java

Fixes 
Internal
b/347825209
b/347825167

chore(compute): delete old unused region tags after migration

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadFromQuery.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadWithProjectionAndFiltering.java

Update two Dataflow snippets to use [Managed I/O for BigQuery](https://cloud.google.com/dataflow/docs/guides/managed-io-bigquery). 
doc bug: b/398001369

feat(dataflow):  Update BigQuery read samples to use Managed I/O

---

bigquery/cloud-client/snippets/pom.xml
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/CreateDataset.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/CreateTable.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/CreateView.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/DeleteDataset.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/DeleteTable.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/CreateDatasetIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/CreateTableIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/CreateViewIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/DeleteDatasetIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/DeleteTableIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/Util.java

Part of internal b/394478489
(**https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10034**, https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10035, https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10036)
**Create[Dataset,Table,View]** and **Delete[Dataset,Table]** are required for testing the following samples (samples will be added in part 2 and 3).
1. [bigquery_view_dataset_access policy](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#view_the_access_policy_of_a_dataset)
2. [bigquery_view_table_or_view_access_policy](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#view_the_access_policy_of_a_table_or_view)
3. [bigquery_grant_access_to_dataset](https://cloud.google.com/bigquery/docs/control-access-to-resou …

feat(bigquery): add helper classes for cloud-client testing (1/3)

---

bigquery/cloud-client/snippets/pom.xml
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/GetTableOrViewAccessPolicy.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/GrantAccessToTableOrView.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/RevokeAccessToTableOrView.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/GetTableOrViewAccessPolicyIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/GrantAccessToTableOrViewIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/RevokeAccessToTableOrViewIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/Util.java

Part of internal b/394478489
(https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10034, https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10035, **https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10036**)
This part adds samples 2, 4 and 6 from the following list:
1. [bigquery_view_dataset_access policy](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#view_the_access_policy_of_a_dataset)
2. [bigquery_view_table_or_view_access_policy](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#view_the_access_policy_of_a_table_or_view)
3. [bigquery_grant_access_to_dataset](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#grant_access_to_a_dataset)
4. …

feat(bigquery): add table/view samples to cloud-client (3/3)

---

bigquery/cloud-client/snippets/pom.xml
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/GetDatasetAccessPolicy.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/GrantAccessToDataset.java
bigquery/cloud-client/snippets/src/main/java/com/example/bigquery/RevokeDatasetAccess.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/GetDatasetAccessPolicyIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/GrantAccessToDatasetIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/RevokeDatasetAccessIT.java
bigquery/cloud-client/snippets/src/test/java/com/example/bigquery/Util.java

Part of internal b/394478489
(https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10034, **https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10035**, https://github.com/GoogleCloudPlatform/java-docs-samples/pull/10036)
This part adds samples 1, 3 and 5 from the following list:
1. [bigquery_view_dataset_access policy](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#view_the_access_policy_of_a_dataset)
2. [bigquery_view_table_or_view_access_policy](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#view_the_access_policy_of_a_table_or_view)
3. [bigquery_grant_access_to_dataset](https://cloud.google.com/bigquery/docs/control-access-to-resources-iam#grant_access_to_a_dataset)
4. …

feat(bigquery): add dataset samples to cloud-client (2/3)

---

jobs/v3/pom.xml
jobs/v3/src/main/java/com/google/samples/BasicJobSample.java

Fixes Internal:
b/347351978 delete_job
b/347351397 basic_job
b/399887278 create_job
b/347826078 get_job
b/347825450 dependencies

chore(job): delete invalid region tags in v3

---

compute/cmdline/src/main/java/ComputeEngineSample.java

Fixes internal
b/347824910
b/347825073
b/347351936
b/348423500

chore(compute): remove unused region tags

---

parametermanager/src/main/java/parametermanager/regionalsamples/GetRegionalParam.java
parametermanager/src/main/java/parametermanager/regionalsamples/GetRegionalParamVersion.java
parametermanager/src/main/java/parametermanager/regionalsamples/ListRegionalParamVersions.java
parametermanager/src/main/java/parametermanager/regionalsamples/ListRegionalParams.java
parametermanager/src/main/java/parametermanager/regionalsamples/RenderRegionalParamVersion.java
parametermanager/src/test/java/parametermanager/regionalsamples/SnippetsIT.java

Added samples for viewing, listing and rendering parameter and parameter versions using Parameter Manager SDK
1. [list-all-parameters](https://cloud.google.com/secret-manager/parameter-manager/docs/list-parameter#list-all-parameters)
2. [view-parameter-details](https://cloud.google.com/secret-manager/parameter-manager/docs/view-parameter-details#view-parameter-details)
3. [list-all-parameters-versions](https://cloud.google.com/secret-manager/parameter-manager/docs/list-parameter-versions#list-all-parameters-versions)
4. [view-parameter-version-details](https://cloud.google.com/secret-manager/parameter-manager/docs/view-parameter-version-details#view-parameter-version-details)
5. [render-secret-parameter-version](https://cloud.google.com/secret-manager/parameter-manager/docs/render-paramete …

feat(parametermanager): Added samples for get, list and render regional parameter & parameter version

---

parametermanager/src/main/java/parametermanager/DeleteParam.java
parametermanager/src/main/java/parametermanager/DeleteParamVersion.java
parametermanager/src/main/java/parametermanager/DisableParamVersion.java
parametermanager/src/main/java/parametermanager/EnableParamVersion.java
parametermanager/src/test/java/parametermanager/SnippetsIT.java

Added samples for deleting parameter, enabling, disabling and deleting parameter version using Parameter manager SDK
1. [delete-parameter](https://cloud.google.com/secret-manager/parameter-manager/docs/delete-parameters#list-all-parameters)
2. [disable-parameters-version](https://cloud.google.com/secret-manager/parameter-manager/docs/disable-parameter-versions#disable-parameters-version)
3. [enable-disabled-parameters-version](https://cloud.google.com/secret-manager/parameter-manager/docs/enable-disabled-versions#enable-disabled-parameters-version)
4. [delete-parameter-version](https://cloud.google.com/secret-manager/parameter-manager/docs/delete-parameter-version#list-all-parameters)
Added required tests for it.

feat(parametermanager): Added samples for delete, enable and disable parameter & parameter version

---

.github/header-checker-lint.yml

existing copyright headers should be maintained; we often shift code from one place to another and it can appear as if the file is a new file which requires current year which is incorrect. this fixes this problem.

fix: sync setting for Java header check

---

auth/src/test/java/com/google/cloud/auth/samples/AuthExampleIT.java

There can be a delay after creating an API key where its not available yet, so in the case the operation fails with API authentication issue, retry operation again with a delay 5.x
Fixes #10023 

fix(auth): AuthExampleIT flaky test

---

jobs/v3/src/main/java/com/google/samples/AutoCompleteSample.java

chore(job): delete unused region tag

---

modelarmor/pom.xml
modelarmor/src/main/java/modelarmor/CreateTemplateWithAdvancedSdp.java
modelarmor/src/test/java/modelarmor/SnippetsIT.java

Added sample for creating template with Advanced SDP settings

feat(modelarmor): Added sample for creating template with Advanced SDP settings

---

retail/interactive-tutorials/src/main/java/product/AddFulfillmentPlaces.java

chore: add back region tags for sample browser

---

parametermanager/pom.xml
parametermanager/src/main/java/parametermanager/regionalsamples/CreateRegionalParamWithKmsKey.java
parametermanager/src/main/java/parametermanager/regionalsamples/RemoveRegionalParamKmsKey.java
parametermanager/src/main/java/parametermanager/regionalsamples/UpdateRegionalParamKmsKey.java
parametermanager/src/test/java/parametermanager/regionalsamples/SnippetsIT.java

Added samples for kms_key field in regional parameter using Parameter manager SDK
1. create_regional_param_with_kms_key
2. update_regional_param_kms_key
3. remove_regional_param_kms_key
Added required Tests for the same.

feat(parametermanager): Added samples for kms_key field in regional parameter

---

parametermanager/pom.xml
parametermanager/src/main/java/parametermanager/CreateParamWithKmsKey.java
parametermanager/src/main/java/parametermanager/RemoveParamKmsKey.java
parametermanager/src/main/java/parametermanager/UpdateParamKmsKey.java
parametermanager/src/test/java/parametermanager/SnippetsIT.java
parametermanager/src/test/java/parametermanager/regionalsamples/SnippetsIT.java

Added samples for kms_key field in global parameter using Parameter manager SDK
1. create_param_with_kms_key
2. update_param_kms_key
3. remove_param_kms_key
Added required tests for the same.

feat(parametermanager): Added samples for kms_key field in global parameter

---

iam/snippets/src/main/java/AddBinding.java
iam/snippets/src/main/java/AddMember.java
iam/snippets/src/main/java/Quickstart.java
iam/snippets/src/main/java/RemoveMember.java

Includes changing "member" to "principal" and linking to principal identifiers page instead of specifying recommended format.
I left "member" when it referred to the field in the role binding, since that field is still called "members."
Please **merge** this PR for me once it is approved

docs(iam): Update comments and terminology in IAM samples

---

.kokoro/tests/run_tests.sh
modelarmor/pom.xml
modelarmor/src/main/java/modelarmor/GetFolderFloorSetting.java
modelarmor/src/test/java/modelarmor/SnippetsIT.java

Added Floor settings tests in model armor as issue b/424365799 is fixed.

chore(modelarmor): Added floor settings tests

---

dlp/snippets/pom.xml
dlp/snippets/src/main/java/dlp/snippets/ProcessInspectFindingsSavedToGcs.java
dlp/snippets/src/test/java/dlp/snippets/InspectTests.java
dlp/snippets/src/test/resources/save_to_gcs_findings.txt

Add SaveFindingsToGcs output proto conversion sample for DLP
