GoogleCloudPlatform/java-docs-samples

appengine/helloworld/pom.xml
appengine/helloworld/src/main/java/com/example/appengine/gettingstartedjava/helloworld/HelloServlet.java
appengine/helloworld/src/main/webapp/WEB-INF/appengine-web.xml

Per request from tech writing team to release simple appengine helloworld app on github

Add appengine helloworld sample

---

appengine/analytics/pom.xml
appengine/cloudsql/pom.xml
appengine/cloudstorage/pom.xml
appengine/datastore/pom.xml
appengine/disk/pom.xml
appengine/extending-runtime/pom.xml
appengine/helloworld-mvm/pom.xml
appengine/mailgun/pom.xml
appengine/mailgun/src/main/java/com/example/managedvms/mailgun/MailgunServlet.java
appengine/memcache/pom.xml
appengine/sendgrid/pom.xml
appengine/static-files/pom.xml
appengine/twilio/pom.xml
appengine/websockets/pom.xml

Update maven plugin version

---

managed_vms/helloworld/README.md

Update readme for mvms

---

managed_vms/helloworld/README.md
managed_vms/helloworld/pom.xml
managed_vms/helloworld/src/main/appengine/app.yaml
managed_vms/helloworld/src/main/webapp/WEB-INF/appengine-web.xml
managed_vms/helloworld/src/main/webapp/WEB-INF/web.xml

1. make sure it really runs on MVM
2. Fix read Me to use jetty:run
3. get rid of appengine-web.xml use app.yam
4. improved security constraint.
I need this to stage some docs, likely to get replaced by Shun later
today.

Fix helloWorld

---

managedvms/sparkjava/pom.xml

Also bump the version of gcloud-java

Get the right tagging this time

---

bigquery/pom.xml

Update maven dependencies in bigquery

---

appengine/appidentity/pom.xml
appengine/appidentity/src/test/java/com/example/appengine/appidentity/IdentityServletTest.java
appengine/appidentity/src/test/java/com/example/appengine/appidentity/SignForAppServletTest.java

Getting ready to use shared java-repo-tools configuration.

Checkstyle fixes for App Identity sample.

---

managed_vms/sparkjava/src/main/appengine/Dockerfile

I had to make this change for the sample to work. 
Seems like the projectname was updated and didn't reflect here.

Fix jar filename in Dockerfile

---

managed_vms/cloudstorage/pom.xml
managed_vms/datastore/pom.xml
managed_vms/sparkjava/pom.xml

/cc @shun-fan 
Also, do you think a README should be added to managed_vms/datastore detailing how to run it and what it does?

Update gcloud-java version in samples

---

compute/cmdline/ComputeEngineSample.launch
compute/cmdline/README.md
compute/cmdline/logging.properties
compute/cmdline/pom.xml
compute/cmdline/src/main/java/ComputeEngineSample.java
pom.xml

Only made minimal changes to follow style guide and update links.
PTAL @jsimonweb @lesv

Migrate sample from compute-getting-started-java repo.

---

compute/sendgrid/README.md

Update readme for compute sendgrid

---

appengine/xmpp/src/main/java/com/example/appengine/xmpp/ErrorServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/MessageReceiverServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/MessageSenderServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/PresenceServlet.java
appengine/xmpp/src/main/java/com/example/appengine/xmpp/SubscriptionServlet.java
pom.xml

Add XMPP sample to Travis build, added in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/182.

Fix checkstyle errors in XMPP sample.

---

appengine/remote/remote-client/pom.xml
appengine/remote/remote-server/src/main/webapp/WEB-INF/web.xml

update web.xml with include tags for easier incorporation into docs

Update web.xml with include tags

---

appengine/datastore/src/test/java/com/example/appengine/QueriesTest.java

From Query concepts and restrictions pages.

Add Datastore query examples.

---

appengine/datastore/src/main/java/com/example/appengine/ListPeopleServlet.java
appengine/datastore/src/main/java/com/example/appengine/StartupServlet.java
appengine/datastore/src/main/webapp/WEB-INF/web.xml
appengine/datastore/src/test/java/com/example/appengine/ListPeopleServletTest.java
appengine/datastore/src/test/java/com/example/appengine/StartupServletTest.java

Moved from
https://cloud.google.com/appengine/docs/java/datastore/query-cursors#query_cursor_example

Add Query Cursor Datastore sample.

---

appengine/datastore/indexes-exploding/pom.xml
appengine/datastore/indexes-perfect/pom.xml
appengine/datastore/indexes/pom.xml
appengine/datastore/pom.xml

Re: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/214/files#r61533229

Add whitespace to Datastore samples' pom.xml files.

---

appengine/mail/src/main/java/com/example/appengine/mail/BounceHandlerServlet.java
appengine/mail/src/main/java/com/example/appengine/mail/HandleDiscussionEmail.java

Fixed some stray tabs that should be spaces.

Stray tabs to spaces

---

appengine/datastore/src/main/java/com/example/appengine/StatsServlet.java
appengine/datastore/src/main/webapp/WEB-INF/web.xml

Stats queries aren't supported on the local server for unit testing, so
no tests. :-(
@shun-fan @lesv PTAL

Add App Engine Datastore stats sample.

---

appengine/datastore/src/test/java/com/example/appengine/TransactionsTest.java

From:
https://cloud.google.com/appengine/docs/java/datastore/transactions
@lesv @shun-fan PTAL.

Add AE Datastore transactions samples.

---

appengine/images/src/main/java/com/example/appengine/images/ImagesServlet.java

Change for Paul

---

appengine/datastore/geo/pom.xml
appengine/datastore/geo/src/main/java/com/example/appengine/GeoServlet.java
appengine/datastore/geo/src/main/java/com/example/appengine/StartupServlet.java
appengine/datastore/geo/src/main/webapp/WEB-INF/appengine-web.xml
appengine/datastore/geo/src/main/webapp/WEB-INF/datastore-indexes.xml
appengine/datastore/geo/src/main/webapp/WEB-INF/web.xml
appengine/datastore/geo/src/test/java/com/example/appengine/GeoServletTest.java
appengine/datastore/geo/src/test/java/com/example/appengine/StartupServletTest.java
pom.xml
travis.sh

Samples moved from:
https://cloud.google.com/appengine/docs/java/datastore/geosearch

Add AE Datastore geo query sample.

---

appengine/images/pom.xml

See: https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/127925475

Fix broken appengine-gcs-client dependency.

---

appengine/firebase-event-proxy/gae-firebase-event-proxy/pom.xml
appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java
appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/ServletContextListenerImpl.java
appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/webapp/WEB-INF/appengine-web.xml
appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/webapp/WEB-INF/web.xml
pom.xml

Updating firebase-event-proxy/pom.xml so that it is more like other pom's and references the parent pom.xml. Adding firebase-event-proxy to parent pom.xml.
Will work on tests next.

Updating firebase-event-proxy/pom.xml and parent pom.xml.

---

pom.xml

Update App Engine SDK to v1.9.38.

---

java-repo-tools/README.md
java-repo-tools/codecov.yml
java-repo-tools/pom.xml
java-repo-tools/test/pom.xml
java-repo-tools/test/src/main/java/com/google/cloud/samples/test/App.java
java-repo-tools/test/src/test/java/com/google/cloud/samples/test/AppTest.java

Adds [versions plugin](http://www.mojohaus.org/versions-maven-plugin/) so that we can automatically update dependencies.
@lesv @shun-fan PTAL

update java repo tools

---

datastore/src/main/java/com/google/datastore/snippets/Concepts.java

Excluded a property from the index

---

pom.xml

Sparkjava has been flaky, disable testing, while I figure out why.

Disable testing for a bit

---

appengine/helloworld-new-plugins/build.gradle
appengine/helloworld-new-plugins/pom.xml

1. tags for compiler properties
2. gradle comment

Add tags for compiler properties

---

bigquery/cloud-client/README.md
bigquery/cloud-client/pom.xml
bigquery/cloud-client/src/main/java/com/example/bigquery/SyncQuerySample.java
bigquery/cloud-client/src/test/java/com/example/bigquery/SyncQuerySampleTest.java

This loosely follows the Python sample here:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/sync_query.py
@lesv PTAL

Add gcloud-java sample for BigQuery synchronous querying.

---

appengine/helloworld-new-plugins/build.gradle
appengine/helloworld-new-plugins/pom.xml
managed_vms/helloworld/build.gradle

1. Remove the model component for Gradle
2. update to latest maven plugin as well.

No model for Gradle

---

vision/face-detection/src/test/java/com/google/cloud/vision/samples/facedetect/FaceDetectAppIT.java

One more vision API test to fix.

---

bigquery/cloud-client/README.md
bigquery/cloud-client/pom.xml
datastore/pom.xml
datastore/src/test/java/com/google/datastore/snippets/ConceptsTest.java
flexible/cloudstorage/pom.xml
flexible/datastore/pom.xml
flexible/sparkjava/README.md
flexible/sparkjava/pom.xml
flexible/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserController.java
flexible/sparkjava/src/main/java/com/google/appengine/sparkdemo/UserService.java
speech/grpc/src/main/java/com/examples/cloud/speech/StreamingRecognizeClient.java

We were still using the old artifactId in some pom.xml files, so dpebot
could not update these.  Also, some READMEs needed updating from my grep
search.
@lesv ptal

Remove references to gcloud-java.

---

vision/landmark-detection/src/test/java/com/google/cloud/vision/samples/landmarkdetection/DetectLandmarkIT.java

Fix vision integration test to match latest error messages.

---

.gitmodules
travis.sh

Remove java-repo-tools submodule.

---

endpoints/getting-started/src/main/appengine/openapi.yaml

Add region tags to openapi.yaml

---

datastore/cloud-client/src/main/java/com/example/datastore/QuickstartSample.java
datastore/cloud-client/src/test/java/com/example/datastore/QuickstartSampleIT.java
datastore/pom.xml

Library version upgrade, Adding retrieve entity snippet to quick start.

Upgrading library to 0.9.2-beta, adding retrieve entity to quickstart

---

kms/pom.xml
kms/src/main/java/com/example/CryptFile.java
kms/src/main/java/com/example/Quickstart.java
kms/src/main/java/com/example/SnippetCommands.java
kms/src/main/java/com/example/Snippets.java

Updates Cloud-KMS sample code to use V1 libraries.

Updates Cloud-KMS sample code to use V1 libraries.

---

monitoring/cloud-client/src/main/java/com/example/monitoring/Snippets.java
monitoring/cloud-client/src/test/java/com/example/monitoring/SnippetsIT.java

Monitoring VTK snippets

---

appengine/mail/src/main/java/com/example/appengine/mail/MailServlet.java

Without this line the code does not work.

Add missing email content

---

language/analysis/src/main/java/com/google/cloud/language/samples/AnalyzeBeta.java

as NL does autodetect of language

no need to test lang

---

language/analysis/README.md

missing instructions to run the new method entity sentiment analysis

add missing instructions for NL v1.1beta

---

flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPublish.java
flexible/pubsub/src/main/java/com/example/flexible/pubsub/PubSubPush.java

Please do not merge, coordinating with doc updates to avoid broken links.

standardizing pubsub doc tags

---

appengine-java8/cloudsql/pom.xml
appengine-java8/cloudsql/src/main/webapp/WEB-INF/appengine-web.xml

1. No longer use the Google Connector/j

Use the socketFactory everywhere

---

iap/README.md
iap/src/main/java/com/example/iap/BuildIapRequest.java
iap/src/test/java/com/example/iap/BuildAndVerifyIapRequestIT.java

@matthewg PTAL
Clone of https://github.com/GoogleCloudPlatform/java-docs-samples/pull/699 with updated tests, README.

updating audience from baseUrl to clientId

---

appengine/iap/src/main/java/com/example/appengine/iap/JwtServlet.java
iap/README.md
iap/src/main/java/com/example/iap/VerifyIapRequestHeader.java
iap/src/test/java/com/example/iap/BuildAndVerifyIapRequestIT.java
pom.xml

FYI, @matthewg
Closing : https://github.com/GoogleCloudPlatform/java-docs-samples/pull/756

IAP sample update : new JWT header

---

appengine-java8/gaeinfo/src/main/java/com/example/appengine/standard/GaeInfoServlet.java

Tokens are a risk to display on an unprotected system

---

monitoring/cloud-client/pom.xml
vision/cloud-client/pom.xml

auth library workaround

---

vision/cloud-client/src/test/java/com/example/vision/DetectIT.java

Vision is moving back and forth between knowing the image and thinking
it’s in Ancient Rome.  Let’s not test such things.

Don't check for location

---

appengine/mailjet/pom.xml
compute/mailjet/pom.xml
flexible/mailjet/pom.xml

Mailjet java version 4.1.1 released today, updating pom.xml files to match

updating Mailjet java version in pom.xml files

---

compute/pom.xml
compute/signed-metadata/README.md
compute/signed-metadata/pom.xml
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/App.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/GCPInstance.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/VerifyingInstance.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/DecodedGoogleJWTWrapper.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/Downloader.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/GoogleRSAKeyProvider.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/TokenDownloader.java
compute/signed-metadata/src/main/java/com/example/compute/signedmetadata/token/TokenVerifier.java

* https://cloud.google.com/compute/docs/instances/verifying-instance-identity
requires Java example

Add signed-metadata example

---

storage/json-api/src/main/java/StorageSample.java

Fix suggested change

---

appengine-java8/endpoints-v2-backend/pom.xml
appengine/endpoints-frameworks-v2/backend/pom.xml

- Update version for Endpoints Framework
Fixes #847

[Endpoints] Update endpoints framework maven plugin version

---

iot/api-client/README.md

1. gcloud alpha should be gcloud beta
2. --pubsub-topic should be --event-pubsub-topic
3. Updated the link to the docs
4. Added info about the Publisher role for the Pub/Sub topic

Small fixes to README.md

---

bigquery/cloud-client/src/main/java/com/example/bigquery/SimpleApp.java

The old dataset name is not valid anymore and causes an iternal error

Update the Public data set name

---

appengine/endpoints-frameworks-v2/backend/src/main/webapp/WEB-INF/web.xml

fix api_management tag boundary

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java

This PR updates the SpannerSample to highlight the usage of bound parameters.

Updated SpannerSample to highlight bound parameters.

---

appengine-java8/endpoints-v2-guice/build.gradle
appengine/endpoints-frameworks-v2/guice-example/build.gradle

This PR is to primarily fix a typo in Guice + Endpoints Gradle script.

[Endpoints] Fix a typo in the Gradle script and update versions.

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

At the request of the spanner team.

Bump spanner stale read from 10 to 15 seconds.

---

appengine-java8/endpoints-v2-migration/build.gradle
appengine-java8/endpoints-v2-migration/pom.xml
appengine/endpoints-frameworks-v2/migration-example/build.gradle
appengine/endpoints-frameworks-v2/migration-example/pom.xml

Short PR to move around region tags in the migration example.

[Endpoints] Update region tags

---

pubsub/cloud-client/pom.xml

For use in new java landing page samples section.

Add section_id 'dependencies' around pubsub dependencies in pubsub/cloud-client/pom.xml.

---

appengine-java8/endpoints-v2-migration/build.gradle
appengine/endpoints-frameworks-v2/migration-example/build.gradle

This is a PR to fix an error made in gradle buildscript files.

[Endpoints] Fix endpoints versions in Migration sample Gradle files

---

endpoints/getting-started/src/main/appengine/app.yaml

I want to use a docwidget to display the section that needs to be configured in the docs.

Update comment and use region tags

---

firestore/src/main/java/com/example/firestore/snippets/References.java

This is a quick fix to Issue #991

Fix typo in comment

---

appengine-java8/cloudsql-postgres/pom.xml
appengine-java8/cloudsql/pom.xml
flexible/cloudsql/src/main/resources/config.properties

Add some anchors to allow sections to be linked to in the docs

Add tags to CloudSQL samples

---

logging/jul/src/main/java/com/example/logging/jul/Quickstart.java
logging/jul/src/main/resources/logging.properties
logging/logback/src/main/java/com/example/logging/logback/Quickstart.java
logging/logback/src/main/resources/logback.xml

**Do not merge** until all relevant region tags have been updated

Update region tags

---

datastore/pom.xml
datastore/src/main/java/com/google/datastore/snippets/TaskList.java
datastore/src/test/java/com/google/datastore/snippets/ConceptsTest.java

Updating all the region tags to have a prefix of datastore

[DO NOT MERGE] Updating all the region tags to have a prefix of datastore

---

memorystore/redis/gke_deployment/visit-counter.yaml
memorystore/redis/src/main/java/com/example/redis/AppServletContextListener.java
memorystore/redis/src/main/java/com/example/redis/VisitCounterServlet.java
memorystore/redis/src/main/resources/application.properties

Updating region tags
GKE deployment: removing use of config map

Patch memorystore samples

---

vision/beta/cloud-client/pom.xml
vision/beta/cloud-client/src/test/java/com/example/vision/DetectIT.java
vision/cloud-client/pom.xml
vision/cloud-client/src/test/java/com/example/vision/DetectIT.java

Also add "sponge_log" to end of failsafe error reports so they show up in fusion.

dpebot dependency updates + test fixes.

---

vision/cloud-client/README.md
vision/cloud-client/pom.xml
vision/cloud-client/src/main/java/com/example/vision/Detect.java
vision/cloud-client/src/test/java/com/example/vision/DetectIT.java

Move samples from beta folder to cloud-client folder.

Update OCR sample from beta to ga

---

pubsub/cloud-client/README.md

Code expects arg[0] and arg[1]. README only provided arg[0].

Modified publish message command line arg

---

memorystore/redis/pom.xml

Update pom.xml region tags

---

speech/cloud-client/src/main/java/com/example/speech/Recognize.java

Updates region tag per feedback

Updates word time offsets region tag

---

language/analysis/src/main/java/com/google/cloud/language/samples/Analyze.java

Updates region tags from _file_gcs to _gcs

NL region tag update

---

kms/pom.xml
kms/src/main/java/com/example/Asymmetric.java
kms/src/test/java/com/example/AsymmetricIT.java

Added samples for the KMS Asymmetric Keys launch

added samples for KMS Asymmetric Keys

---

endpoints/getting-started/k8s/esp_echo_http.yaml

Copied the k8s config file used in the Endpoints Kubernetes tutorial from the endpoints-samples repo. This way the sample code and the config files are all in the same repo.

Copied config file from endpoints-samples/k8s

---

appengine-java8/endpoints-v2-backend/src/main/webapp/WEB-INF/web.xml

Moved the api_management region tag to include the filter that fetches the service config from service management.

Moved api_managment region tag

---

appengine-java8/urlfetch/src/main/java/com/example/appengine/UrlFetchServlet.java
appengine-java8/urlfetch/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/urlfetch/src/main/webapp/urlfetchresult.jsp

Fixes Issue #1225
* Fixed validation for id
* Updated HTTP content type
* Add url stream handler to pom

Update UrlFetch sample

---

vision/face-detection/pom.xml

Going too fast, forgot the brackets.

Correct dependency tag syntax.

---

cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/IndexServlet.java

Updating region tags and fixing environment variable to match docs.

Update cloud-sql sample region tags. 

---

appengine-java8/mail/pom.xml
appengine-java8/mail/src/main/java/com/example/appengine/mail/BounceHandlerServlet.java
appengine-java8/mail/src/main/java/com/example/appengine/mail/HandleDiscussionEmail.java
appengine-java8/mail/src/main/java/com/example/appengine/mail/MailHandlerBase.java
appengine-java8/mail/src/main/java/com/example/appengine/mail/MailHandlerServlet.java
appengine-java8/mail/src/main/java/com/example/appengine/mail/MailServlet.java
appengine-java8/mail/src/main/webapp/WEB-INF/web.xml
appengine-java8/pom.xml

Fixes the issue mentioned in #1242.

Correct parent in appengine-java8/mail.

---

appengine-java8/datastore-schedule-export/src/main/java/com/example/datastore/DatastoreExportServlet.java

Use kindsJson for the entity filter.

---

bigquery/bigquerystorage/README.md
bigquery/bigquerystorage/pom.xml
bigquery/bigquerystorage/src/main/java/com/example/bigquerystorage/StorageSample.java
bigquery/bigquerystorage/src/test/java/com/example/bigquerystorage/QuickstartSampleIT.java
pom.xml

Adds a sample for demonstrating how to invoke the BQ Storage API.

BigQuery: add sample for bigquerystorage API.

---

firestore/pom.xml
firestore/src/test/java/com/example/firestore/snippets/ManageDataSnippetsIT.java

Update google-cloud-firestore dependency to 0.81.0-beta

---

speech/cloud-client/src/main/java/com/example/speech/Recognize.java

/cc @telpirion @GoogleCloudPlatform/ml-apis

Data logging opt-in is no longer required for enhanced models

---

CONTRIBUTING.md
SAMPLE_FORMAT.md

Add a document summarizing some java-specific requirements for the new sample format.

Add new Sample Format guidelines. 

---

appengine-java8/pubsub/README.md

Fix readme link in appengine pubsub

Fix readme link in appengine pubsub

---

endpoints/getting-started/pom.xml

Update parent in pom.xml

---

spanner/spring-data/pom.xml

Adding POM markers for the devsite page to include the snippet:
https://cloud.google.com/spanner/docs/adding-spring-data

Spring Data Spanner POM region markers

---

speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java

forgot to change default val to param

---

pubsub/cloud-client/src/main/java/com/example/pubsub/SubscriberExample.java

Address #1531 by acking only after processing a message.

Make Pub/Sub subscriber example simpler and more idiomatic

---

container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

fixing https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1532

Container Analysis exception fix

---

functions/snippets/src/main/java/HelloBackground.java
functions/snippets/src/test/java/SnippetsTests.java

Adds bg functions snippet
https://devrel.corp.google.com/samples/82

Feat: Adds functions_helloworld_background

---

dataflow/README.md
dataflow/encryption-keys/README.md
dataflow/encryption-keys/pom.xml
dataflow/encryption-keys/src/main/java/com/example/dataflow/cmek/BigQueryKmsKey.java
dataflow/templates/README.md
dataflow/templates/pom.xml
dataflow/templates/src/main/java/com/example/dataflow/templates/WordCount.java

Creating a Dataflow sample to show how to use Customer-Managed Encryption Keys (CMEK) for the [Using customer-managed encryption keys](https://cloud.google.com/dataflow/docs/guides/customer-managed-encryption-keys) docs page.
Also updating the templates README for consistency.

Add BigQueryKmsKey Dataflow sample

---

functions/snippets/src/main/java/HelloWorld.java
functions/snippets/src/test/java/SnippetsTests.java

Adds the basic `Hello, World` function.
`devrel/samples/304`

feat: Adds functions_helloworld_get

---

iam/api-client/src/main/java/com/google/iam/snippets/DisableServiceAccount.java
iam/api-client/src/main/java/com/google/iam/snippets/EnableServiceAccount.java
iam/api-client/src/test/java/com/google/iam/snippets/ServiceAccountTests.java

Adding service account enable/disable snippets to go along with this doc addition: https://critique.corp.google.com/#review/267282634

Add service account enable/disable snippets

---

appengine-java11/appengine-simple-jetty-main/src/main/java/com/example/appengine/demo/jettymain/Main.java
appengine-java11/quarkus-helloworld/pom.xml
appengine-java11/quarkus-helloworld/src/main/resources/application.properties
appengine-java11/vertx-helloworld/src/main/java/com/example/appengine/vertxhello/Application.java

Make sure Java 11 samples listen to PORT env var

---

appengine-java8/endpoints-v2-backend/pom.xml

The new version of the library was released earlier this week: 1.0.12.

Upgrade the version of Endpoints Management Framework to 1.0.12

---

bigtable/cassandra-migration-codelab/pom.xml
bigtable/cassandra-migration-codelab/src/main/java/CassandraMigrationCodelab.java
bigtable/cassandra-migration-codelab/src/test/java/CassandraMigrationCodelabTest.java

This code will be used with a codelab and shouldn't be used much outside of that

Creating codelab for Cassandra migration queries

---

appengine-java11/appengine-simple-jetty-main/README.md
appengine-java11/cloudsql/app.yaml
appengine-java11/gaeinfo/src/main/appengine/app.yaml
appengine-java11/guestbook-cloud-firestore/src/main/appengine/app.yaml
appengine-java11/helloworld-servlet/README.md
appengine-java11/helloworld-servlet/src/main/appengine/app.yaml
appengine-java11/kotlin-ktor/app.yaml
appengine-java11/micronaut-helloworld/src/main/appengine/app.yaml
appengine-java11/oauth2/src/main/appengine/app.yaml
appengine-java11/spanner/src/main/appengine/app.yaml
appengine-java11/sparkjava-helloworld/src/main/appengine/app.yaml
appengine-java11/springboot-helloworld/src/main/appengine/app.yaml

Java 11 apps can now use a smaller instance size.

Reduce instance size for Java 11 apps.

---

appengine-java11/appengine-simple-jetty-main/README.md
appengine-java11/cloudsql/app.yaml
appengine-java11/gaeinfo/src/main/appengine/app.yaml
appengine-java11/guestbook-cloud-firestore/src/main/appengine/app.yaml
appengine-java11/helloworld-servlet/README.md
appengine-java11/helloworld-servlet/src/main/appengine/app.yaml
appengine-java11/oauth2/src/main/appengine/app.yaml
appengine-java11/spanner/src/main/appengine/app.yaml

update classpath for java11 samples

---

firestore/pom.xml

Bump firestore samples to latest library version

---

renovate.json

Fix typo in renovate.json

---

kms/pom.xml

Update to Truth 1.0 and downgrade to non-beta JUnit

---

kms/pom.xml
kms/src/main/java/com/example/Asymmetric.java
kms/src/test/java/com/example/AsymmetricIT.java

addresses https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1762

KMS: update package version

---

firestore/src/main/java/com/example/firestore/snippets/ManageDataSnippets.java

This PR follows up on #1752 
Now the `firestore` transactions are done using lambda. This makes the code short, brief and less verbose.

Firestore: refactor transactions to use lambda instead of anonymous class

---

appengine-java11/guestbook-cloud-firestore/pom.xml
appengine-java11/tasks/pom.xml
appengine-java8/pubsub/pom.xml
appengine-java8/translate-pubsub/pom.xml
asset/cloud-client/pom.xml
auth/pom.xml
automl/beta/pom.xml
automl/cloud-client/pom.xml
bigquery/cloud-client/pom.xml
bigquery/datatransfer/cloud-client/pom.xml

Towards #1761 - breaking up into small PRs for easier reviewing

Use libraries-bom for snippets - part 1

---

texttospeech/cloud-client/pom.xml
translate/automl/pom.xml
translate/cloud-client/pom.xml
video/beta/pom.xml
vision/automl/pom.xml
vision/beta/cloud-client/pom.xml
vision/cloud-client/pom.xml
vision/product-search/cloud-client/pom.xml

Use libraries-bom for snippets - part 3

---

language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeBetaIT.java
language/analysis/src/test/java/com/google/cloud/language/samples/AnalyzeIT.java

GCS files no longer exist, updated to general GCS location and updated tests accordingly

Update tests with broken GCS links

---

language/analysis/pom.xml

Update language samples to use libraries-bom

---

SAMPLE_FORMAT.md

Mention Streams and Lambda's

---

automl/cloud-client/src/main/java/com/example/automl/ListDatasets.java

Remove the filter as this should

hotfix: Update ListDatasets.java

---

renovate.json

Let's do this manually for a while.

Ask renovate bot to stop rebasing PR's

---

renovate.json

Revert commit until we have a chance to discuss.

Revert "Only run on weekdays; limit to 2/h"

---

renovate.json

(We should probably wait until Tuesday to kick this off)

Remove PR limit.

---

dlp/src/main/java/dlp/snippets/DeIdentifyWithDateShift.java
dlp/src/main/java/dlp/snippets/DeIdentifyWithFpe.java
dlp/src/main/java/dlp/snippets/DeIdentifyWithMasking.java
dlp/src/main/java/dlp/snippets/InfoTypesList.java
dlp/src/main/java/dlp/snippets/JobsDelete.java
dlp/src/main/java/dlp/snippets/JobsList.java
dlp/src/main/java/dlp/snippets/ReIdentifyWithFpe.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
dlp/src/main/java/dlp/snippets/TemplatesCreate.java
dlp/src/main/java/dlp/snippets/TemplatesDelete.java
dlp/src/main/java/dlp/snippets/TemplatesList.java
dlp/src/main/java/dlp/snippets/TriggersCreate.java
dlp/src/main/java/dlp/snippets/TriggersDelete.java
dlp/src/main/java/dlp/snippets/TriggersList.java
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
dlp/src/test/java/dlp/snippets/InfoTypesTests.java
dlp/src/test/java/dlp/snippets/InspectTests.java
dlp/src/test/java/dlp/snippets/JobsTests.java
dlp/src/test/java/dlp/snippets/QuickstartTests.java
dlp/src/test/java/dlp/snippets/RedactTests.java
dlp/src/test/java/dlp/snippets/TemplatesTests.java
dlp/src/test/java/dlp/snippets/TriggersTests.java

Fixes linting errors. Will rebase this once #2069 is merged in.

Fix Checkstyle errors for DLP Snippets and Tests

---

.kokoro/tests/run_tests.sh

* Also, fix some comments that were stale
* and add some shellcheck comments

For Java 11, skip appengine-java8 & flexible

---

vision/cloud-client/src/test/java/com/example/vision/DetectIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2240
Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2241
Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2242

vision: change flaky tests to be more fuzzy

---

speech/beta/src/test/java/com/example/speech/RecognizeIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2279

fix: flaky tests in speech

---

.github/blunderbuss.yml

Reverts GoogleCloudPlatform/java-docs-samples#2140

Revert "chore: switch to built-in code review assignment"

---

automl/beta/src/test/java/com/example/automl/BatchPredictTest.java
automl/cloud-client/src/test/java/com/example/automl/BatchPredictTest.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2352

automl: update error check due to changes

---

video/beta/src/test/java/com/example/video/DetectFacesGcsIT.java
video/beta/src/test/java/com/example/video/DetectFacesIT.java
video/beta/src/test/java/com/example/video/DetectPersonGcsIT.java
video/beta/src/test/java/com/example/video/DetectPersonIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2334
Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2335

video: fix flaky tests

---

vision/product-search/cloud-client/src/main/java/com/example/vision/snippets/PurgeProducts.java
vision/product-search/cloud-client/src/main/java/com/example/vision/snippets/PurgeProductsInProductSet.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ImportProductSetsIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ProductInProductSetManagementIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ProductManagementIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ProductSearchIT.java
vision/product-search/cloud-client/src/test/java/com/example/vision/ReferenceImageManagementIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2392
For: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2170

vision: use uuid for product search tests

---

spanner/cloud-client/pom.xml

fix: Upgrade Spanner samples to OpenCensus 0.25.0

---

recommender/beta/cloud-client/pom.xml

Fix recommender dependency update.

---

appengine-java8/taskqueues-push/src/main/java/com/example/appengine/taskqueue/push/Enqueue.java

Close https://github.com/GoogleCloudPlatform/getting-started-java/issues/360

Correct path to task queues sample.

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java

Correct error message for unset GOOGLE_CLOUD_PROJECT.

---

vision/cloud-client/src/test/java/com/example/vision/DetectIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2424
Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2408

vision: makes tests more generic

---

translate/cloud-client/src/main/java/com/example/translate/BatchTranslateText.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithModel.java
vision/automl/src/test/java/com/google/cloud/vision/samples/automl/PredictionApiIT.java
vision/beta/cloud-client/src/test/java/com/example/vision/DetectIT.java

Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2493
Fix: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2496

docs: update tests that are failing or not cleaning up resources

---

SAMPLE_FORMAT.md

Fixes #<issue_number_goes_here>

Fix 2 URL's

---

spanner/cloud-client/src/main/java/com/example/spanner/SpannerSample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

Add samples for Spanner backups.

feat: add backups samples

---

functions/snippets/src/main/java/com/example/functions/GcsEvent.java
functions/snippets/src/main/java/com/example/functions/HelloError.java
functions/snippets/src/main/java/com/example/functions/HelloGcsGeneric.java
functions/snippets/src/main/java/com/example/functions/HelloMethod.java
functions/snippets/src/test/java/com/example/functions/SnippetsTests.java

✅Add `functions_helloworld_error`
✅Add `functions_helloworld_gcs_generic`
✅Delete excess logging code in `SnippetsTests.java`

Add missing helloworld samples + delete excess logging code

---

flexible/helloworld-springboot/pom.xml

Update springboot flexible app

---

dataproc/src/main/java/InstantiateInlineWorkflowTemplate.java

fixed template tag to be consistent with other samples

fix: changed template tag

---

endpoints/getting-started-grpc/api/build.gradle

Fixes #2533
Fixes #<issue_number_goes_here>

upgrade protobuf-gradle-plugin to 0.8.8

---

container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2507
The pubsub test was flaky due to race conditions. I simplified it to only check that some new occurrences were found in the topic, but not expect a specific number.
- [ Y ] Tests pass
- [ Y ] Appropriate changes to README are included in PR
- [ N ] API's need to be enabled to test (tell us)
- [ N ] Environment Variables need to be set (ask us to set them)

[Container Analysis] simplified pubsub test

---

.kokoro/tests/build_cloud_run.sh
functions/snippets/src/main/java/com/example/functions/BearerTokenHttp.java
run/authentication/README.md
run/authentication/pom.xml
run/authentication/src/main/java/com/example/cloudrun/Authentication.java
run/authentication/src/test/java/com/example/cloudrun/AuthenticationTest.java

Fixes #<issue_number_goes_here>

[Cloud Run] Auth Snippet

---

dlp/src/main/java/dlp/snippets/TriggersList.java
dlp/src/test/java/dlp/snippets/TemplatesTests.java
dlp/src/test/java/dlp/snippets/TriggersTests.java

Add AfterClass method to cleanup DLP Triggers and Templates

---

functions/snippets/src/main/java/com/example/functions/OcrProcessImage.java

Add missing functions_ocr_setup tag to sample

---

renovate.json

Jetty should update together

---

functions/snippets/ci_cd/cloudbuild.yaml

GCF CI/CD: add cloudbuild.yaml

---

jobs/v4/src/main/java/com/example/jobs/CommuteSearchJobs.java
jobs/v4/src/main/java/com/example/jobs/CustomRankingSearchJobs.java
jobs/v4/src/main/java/com/example/jobs/HistogramSearchJobs.java
jobs/v4/src/main/java/com/example/jobs/JobSearchAutoCompleteJobTitle.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateClientEvent.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateCompany.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJob.java
jobs/v4/src/main/java/com/example/jobs/JobSearchCreateJobCustomAttributes.java
jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteCompany.java
jobs/v4/src/main/java/com/example/jobs/JobSearchDeleteJob.java
jobs/v4/src/main/java/com/example/jobs/JobSearchGetCompany.java
jobs/v4/src/main/java/com/example/jobs/JobSearchGetJob.java
jobs/v4/src/main/java/com/example/jobs/JobSearchListCompanies.java
jobs/v4/src/main/java/com/example/jobs/JobSearchListJobs.java

…/java-docs-samples/issues/2549
Fixes #2549

jobs-v4: api update

---

SAMPLE_FORMAT.md

Memorialize our conversation about package names today.

Change how package names should be chosen.

---

healthcare/v1beta1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceConditionalPatch.java
healthcare/v1beta1/src/test/java/snippets/healthcare/FhirResourceTests.java

Remove ignore for 2 healthcare FHIR Resource tests.

---

healthcare/v1/pom.xml
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreCreate.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreDelete.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreExecuteBundle.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreExport.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreGet.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreGetIamPolicy.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreImport.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreList.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreSetIamPolicy.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceCreate.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDelete.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDeletePurge.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGet.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetHistory.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetMetadata.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceGetPatientEverything.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceListHistory.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourcePatch.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchPost.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java
healthcare/v1/src/test/java/snippets/healthcare/FhirStoreTests.java

NOTE: This PR is fundamentally a branch of https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/healthcare/v1beta1 to v1. The code has been previously reviewed in this repository.
After all healthcare/v1 samples are approved, I'll delete the existing v1beta1/ directory.

healthcare API: update fhir/ samples from v1beta1 to v1 

---

cloud-sql/mysql/servlet/pom.xml
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/Vote.java
cloud-sql/postgres/servlet/pom.xml
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/Vote.java
cloud-sql/postgres/servlet/src/main/webapp/WEB-INF/appengine-web.xml
cloud-sql/postgres/servlet/src/main/webapp/index.jsp

Update cloudsql/ samples to address spotbugs issues. 

---

iot/api-client/manager/pom.xml
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExampleOptions.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExampleOptions.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExampleOptions.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/RetryHttpInitializerWrapper.java
iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

Fixes some lint errors.

---

iot/api-client/manager/pom.xml
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExampleOptions.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/HttpExampleOptions.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExample.java
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/MqttExampleOptions.java
iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

Fixes #<issue_number_goes_here>

Fix integration test

---

functions/ocr/ocr-process-image/pom.xml
functions/ocr/ocr-process-image/src/main/java/functions/OcrProcessImage.java
functions/ocr/ocr-process-image/src/main/java/functions/OcrTranslateApiMessage.java
functions/ocr/ocr-process-image/src/main/java/functions/eventpojos/GcsEvent.java
functions/ocr/ocr-process-image/src/main/java/functions/eventpojos/PubSubMessage.java
functions/ocr/ocr-process-image/src/test/java/functions/OcrProcessImageTest.java
functions/ocr/ocr-save-result/pom.xml
functions/ocr/ocr-save-result/src/main/java/functions/OcrSaveResult.java
functions/ocr/ocr-save-result/src/main/java/functions/OcrTranslateApiMessage.java
functions/ocr/ocr-save-result/src/main/java/functions/eventpojos/PubSubMessage.java
functions/ocr/ocr-save-result/src/test/java/functions/OcrSaveResultTest.java
functions/ocr/ocr-translate-text/pom.xml
functions/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateApiMessage.java
functions/ocr/ocr-translate-text/src/main/java/functions/OcrTranslateText.java
functions/ocr/ocr-translate-text/src/main/java/functions/eventpojos/PubSubMessage.java
functions/ocr/ocr-translate-text/src/test/java/functions/OcrTranslateTextTest.java

(missed this during the previous file-splitting process)

GCF file split: OCR

---

jobs/v4/src/test/java/JobSearchGetJobTest.java

fix flaky tests of jobs v4

---

.kokoro/tests/run_tests.sh
jobs/v4/src/test/java/CommuteSearchJobsTest.java
jobs/v4/src/test/java/CustomRankingSearchJobsTest.java
jobs/v4/src/test/java/HistogramSearchJobsTest.java
jobs/v4/src/test/java/JobSearchAutoCompleteJobTitleTest.java
jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
jobs/v4/src/test/java/JobSearchCreateJobTest.java
jobs/v4/src/test/java/JobSearchCreateJobWithCustomAttrTest.java
jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
jobs/v4/src/test/java/JobSearchDeleteJobTest.java
jobs/v4/src/test/java/JobSearchGetCompanyTest.java
jobs/v4/src/test/java/JobSearchGetJobTest.java
jobs/v4/src/test/java/JobSearchGetTenantTest.java
jobs/v4/src/test/java/JobSearchListCompaniesTest.java
jobs/v4/src/test/java/JobSearchListJobsTest.java

CTS: [v4] converting hardcoded IDs into ENV vars

---

jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java
jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java
jobs/v3/src/main/java/com/google/samples/EmailAlertSearchSample.java
jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java
jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java
jobs/v3/src/main/java/com/google/samples/HistogramSample.java
jobs/v3/src/main/java/com/google/samples/LocationSearchSample.java

Wait for Jobs tasks execution before printing.

---

.github/PULL_REQUEST_TEMPLATE.md

Let users ask us to merge their PR's

---

container-registry/container-analysis/src/main/java/com/example/containeranalysis/HighVulnerabilitiesForImage.java
container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

[Container Analysis] effective severity

---

.kokoro/tests/run_tests.sh
functions/helloworld/hello-http/pom.xml
functions/helloworld/hello-http/src/test/java/functions/ExampleIntegrationTest.java
functions/helloworld/hello-http/src/test/java/functions/ExampleSystemTest.java

**N.B:** this uses the Node.js testing project for part of the tests

GCF: add http system/integration test sample

---

functions/spanner/pom.xml
functions/spanner/src/main/java/functions/HelloSpanner.java
functions/spanner/src/test/java/functions/HelloSpannerTest.java

Sample for querying a Cloud Spanner database through a Java Cloud Function.

sample: add Spanner sample for Cloud Functions

---

secretmanager/pom.xml
secretmanager/src/main/java/secretmanager/AccessSecretVersion.java
secretmanager/src/main/java/secretmanager/AddSecretVersion.java
secretmanager/src/main/java/secretmanager/CreateSecret.java
secretmanager/src/main/java/secretmanager/DeleteSecret.java
secretmanager/src/main/java/secretmanager/DestroySecretVersion.java
secretmanager/src/main/java/secretmanager/DisableSecretVersion.java
secretmanager/src/main/java/secretmanager/EnableSecretVersion.java
secretmanager/src/main/java/secretmanager/GetSecret.java
secretmanager/src/main/java/secretmanager/GetSecretVersion.java
secretmanager/src/main/java/secretmanager/IamGrantAccess.java
secretmanager/src/main/java/secretmanager/IamRevokeAccess.java
secretmanager/src/main/java/secretmanager/ListSecretVersions.java
secretmanager/src/main/java/secretmanager/ListSecrets.java
secretmanager/src/main/java/secretmanager/Quickstart.java
secretmanager/src/main/java/secretmanager/UpdateSecret.java
secretmanager/src/test/java/secretmanager/QuickstartIT.java
secretmanager/src/test/java/secretmanager/SnippetsIT.java

This updates Secret Manager to use the more canonical helpers and also updates the layout to use the new preferred layout.

Update Secret Manager samples to be canonical

---

automl/beta/src/main/java/com/example/automl/CancelOperation.java
automl/beta/src/main/java/com/example/automl/GetModel.java
automl/beta/src/main/java/com/example/automl/GetModelEvaluation.java
automl/beta/src/main/java/com/example/automl/GetOperationStatus.java
automl/beta/src/main/java/com/example/automl/ImportDataset.java
automl/beta/src/main/java/com/example/automl/ListDatasets.java
automl/beta/src/main/java/com/example/automl/ListModelEvaluations.java
automl/beta/src/main/java/com/example/automl/ListModels.java
automl/beta/src/main/java/com/example/automl/TablesCreateDataset.java
automl/beta/src/main/java/com/example/automl/TablesCreateModel.java
automl/beta/src/main/java/com/example/automl/TablesImportDataset.java
automl/beta/src/main/java/com/example/automl/TablesPredict.java
automl/beta/src/main/java/com/example/automl/VideoClassificationCreateDataset.java
automl/beta/src/main/java/com/example/automl/VideoClassificationCreateModel.java
automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateDataset.java
automl/beta/src/main/java/com/example/automl/VideoObjectTrackingCreateModel.java
automl/beta/src/test/java/com/example/automl/CancelOperationTest.java

Allows us to close and delete this PR/Branch: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2183

automl: move last sample on branch and do some spot bugs cleanup

---

speech/cloud-client/src/test/java/com/example/speech/RecognizeIT.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2820

speech: make flaky tests generic

---

healthcare/v1/src/main/java/snippets/healthcare/datasets/DatasetPatch.java

healthcare API: add DATASET_NAME variable to DatasetPatch.java

---

.github/CODEOWNERS

Adding SoDa teams for simpler repo triage and access

Adding SoDa teams

---

bigtable/beam/keyviz-art/pom.xml
dataflow/spanner-io/pom.xml

deps: upgrade beam version to 2.20.0 in bigtable and dataflow samples

---

.github/CODEOWNERS
functions/spanner/pom.xml
functions/spanner/src/test/java/functions/HelloSpannerTest.java

This is an example of the approach that I propose to follow for the 27 other samples that currently use PowerMockito.

Update functions/spanner to use plain Mockito rather than PowerMockito.

---

iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

Clear current registry between tests.

---

functions/helloworld/helloworld/pom.xml

functions: remove extra pom.xml line

---

healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStorePatch.java
healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebRetrieveRendered.java
healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebSearchForInstances.java
healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomWebSearchStudies.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java

Fixes:
b/155755377
b/155511623
b/155753369
b/155860928
b/155889861

healthcare API: add missing variables, fix incorrect var in fhir/

---

functions/concepts/scopes/src/main/java/functions/Scopes.java

Clarify comment in scopes sample

---

video/beta/src/main/java/com/example/video/StreamingAutoMlClassification.java
video/beta/src/test/java/com/example/video/StreamingAutoMlClassificationIT.java

samples: fix test

---

healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStoreGetIamPolicy.java

healthcare API: fix DICOM_NAME variable

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStoreExecuteBundle.java

healthcare API: fix input data for ExecuteBundle, fix path name

---

firestore/pom.xml
firestore/src/main/java/com/example/firestore/snippets/QueryDataSnippets.java
firestore/src/test/java/com/example/firestore/snippets/QueryDataSnippetsIT.java

feat: add snipped for firestore.query.limittolast()

---

functions/logging/log-helloworld/src/main/java/functions/LogHelloWorld.java

Fixes b/156655272
@saturnism FYI

functions: Java log severity is NOT broken :)

---

functions/helloworld/helloworld/pom.xml

As title. cc @saturnism as FYI

GCF example POM: fix mismatched region tag + add new one

---

SAMPLE_FORMAT.md

Update SAMPLE_FORMAT to use main.

---

.github/PULL_REQUEST_TEMPLATE.md

Let's ask folks to follow our guidelines.

---

.kokoro/java11/common.cfg
.kokoro/java8/common.cfg

Update build timeouts.

---

functions/helloworld/helloworld/pom.xml
functions/helloworld/helloworld/src/main/java/functions/HelloWorld.java

Region tag fixes for b/156959476

---

functions/ci_cd/cloudbuild.yaml

Functions: clarify cloudbuild.yaml

---

video/cloud-client/src/test/java/com/example/video/QuickstartIT.java

Change video test to not depend on specific inference

---

appengine-java11/appengine-simple-jetty-main/README.md
appengine-java11/cloudsql/app.yaml
appengine-java11/gaeinfo/src/main/appengine/app.yaml
appengine-java11/guestbook-cloud-firestore/src/main/appengine/app.yaml
appengine-java11/helloworld-servlet/README.md
appengine-java11/helloworld-servlet/src/main/appengine/app.yaml
appengine-java11/kotlin-ktor/app.yaml
appengine-java11/micronaut-helloworld/src/main/appengine/app.yaml
appengine-java11/oauth2/src/main/appengine/app.yaml
appengine-java11/quarkus-helloworld/src/main/appengine/app.yaml
appengine-java11/spanner/src/main/appengine/app.yaml
appengine-java11/sparkjava-helloworld/src/main/appengine/app.yaml
appengine-java11/springboot-helloworld/src/main/appengine/app.yaml

Update app.yaml for Java 11

---

dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156972853

 Create Java code sample for omit email address

---

appengine-java8/springboot-helloworld/src/main/resources/application.properties
appengine-java8/springboot-helloworld/src/main/resources/application.yaml

Fixes https://github.com/GoogleCloudPlatform/getting-started-java/issues/284

Fix memory error in springboot standard logging.

---

spanner/cloud-client/src/main/java/com/example/spanner/CreateInstanceExample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerSampleIT.java

feat: add sample for createInstance

---

dlp/src/main/java/dlp/snippets/JobsCreate.java
dlp/src/main/java/dlp/snippets/JobsGet.java
dlp/src/test/java/dlp/snippets/JobsTests.java

https://cloud.google.com/dlp/docs/creating-job-triggers
Fixes # Create Java code sample for get jobs
> [yes] I have followed Sample Format Guide
> [yes] pom.xml parent set to latest shared-configuration
> [yes] Appropriate changes to README are included in PR
> [nothing new] API's need to be enabled to test (tell us)
> [nothing new] Environment Variables need to be set (ask us to set them)
> [yes] Tests pass (mvn -P lint clean verify)
> (Note- Checkstyle passing is required; Spotbugs, ErrorProne, PMD, etc. ERROR's are advisory only)
> [yes] Please merge this PR for me once it is approved

 Create Java code sample for get jobs

---

automl/cloud-client/pom.xml

deps: bump libraries-bom version

---

firestore/README.md

Fix Firebase Console URL in README.

Fix Firebase Console URL in README

---

dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156967687

Create Java code sample for omit finding with substring using custom detector

---

dlp/src/main/java/dlp/snippets/InspectImageFile.java
dlp/src/main/java/dlp/snippets/InspectPhoneNumber.java
dlp/src/main/java/dlp/snippets/InspectString.java
dlp/src/main/java/dlp/snippets/InspectStringCustomExcludingSubstring.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDict.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionDictSubstring.java
dlp/src/main/java/dlp/snippets/InspectStringWithExclusionRegex.java
dlp/src/main/java/dlp/snippets/InspectTextFile.java
dlp/src/main/java/dlp/snippets/RedactImageFile.java
dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java
dlp/src/main/java/dlp/snippets/TriggersCreate.java
dlp/src/main/java/dlp/snippets/TriggersDelete.java
dlp/src/main/java/dlp/snippets/TriggersList.java
dlp/src/test/java/dlp/snippets/InspectTests.java
dlp/src/test/java/dlp/snippets/RedactTests.java

Fixes internal bug b/158239329
Also follows up on a comment from @lesv on https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3055

Make DLP Java samples exception handling consistent

---

dlp/src/main/java/dlp/snippets/InspectStringCustomOmitOverlap.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156971892

Create Java code sample for omit names that overlap with custom detector

---

appengine-java8/iap/pom.xml
compute/mailjet/pom.xml
endpoints/getting-started/clients/pom.xml
language/analysis/pom.xml

Remove error prone from individual pom files.

---

healthcare/v1/src/test/java/snippets/healthcare/DicomWebTests.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java

The following issues were already fixed but this PR is related to them:
* b/155786460
* b/155476854

healthcare API: remove unused imports

---

dlp/src/main/java/dlp/snippets/DeIdentifyWithReplacement.java
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java

Fixes #issue
- [yes] Tests pass (`mvn -P lint clean verify`)
- [yes] Please **merge** this PR for me once it is approved.

Add Java code sample for replacement

---

dlp/src/main/java/dlp/snippets/InspectStringCustomHotword.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/156971569

Inspect custom hotword b 156971569

---

.kokoro/tests/run_lint.sh
.kokoro/tests/run_static_analysis.sh

Fix lint / static analysis checks. 

---

.kokoro/tests/run_lint.sh
.kokoro/tests/run_static_analysis.sh

Make lint/static checks quieter.

---

healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java

healthcare API: remove message create from test_Hl7v2MessageList

---

iam/api-client/pom.xml

Warn us about possible RepoBot failures

---

dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
dlp/src/main/java/dlp/snippets/InspectBigQueryTableWithSampling.java
dlp/src/main/java/dlp/snippets/InspectGcsFileWithSampling.java
dlp/src/test/java/dlp/snippets/InspectTests.java

Fixes internal bug b/157051267

Create Java code sample for inspect BQ with sampling

---

functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java

Clarify infinite retries sample

---

dlp/src/main/java/dlp/snippets/InspectBigQueryTable.java
dlp/src/main/java/dlp/snippets/InspectBigQueryTableWithSampling.java
dlp/src/main/java/dlp/snippets/InspectDatastoreEntity.java
dlp/src/main/java/dlp/snippets/InspectGcsFile.java
dlp/src/main/java/dlp/snippets/InspectGcsFileWithSampling.java
dlp/src/main/java/dlp/snippets/RiskAnalysisCategoricalStats.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKAnonymity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisKMap.java
dlp/src/main/java/dlp/snippets/RiskAnalysisLDiversity.java
dlp/src/main/java/dlp/snippets/RiskAnalysisNumericalStats.java

Make pubsub handling consistent across inspect and risk DLP samples

---

functions/concepts/retry-pubsub/src/test/java/functions/RetryPubSubTest.java
functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java
functions/firebase/auth/src/test/java/functions/FirebaseAuthTest.java
functions/firebase/firestore-reactive/src/main/java/functions/FirebaseFirestoreReactive.java
functions/firebase/firestore-reactive/src/test/java/functions/FirebaseFirestoreReactiveTest.java
functions/firebase/firestore/src/test/java/functions/FirebaseFirestoreTest.java
functions/firebase/remote-config/src/test/java/functions/FirebaseRemoteConfigTest.java
functions/firebase/rtdb/src/test/java/functions/FirebaseRtdbTest.java
functions/helloworld/hello-http/src/test/java/functions/HelloHttpTest.java
functions/http/parse-content-type/src/test/java/functions/ParseContentTypeTest.java
functions/imagemagick/src/main/java/functions/ImageMagick.java
functions/logging/stackdriver-logging/src/test/java/functions/StackdriverLoggingTest.java
functions/slack/src/test/java/functions/SlackSlashCommandTest.java

Update GCF samples to Java 11 standards

---

dlp/pom.xml
dlp/src/test/java/dlp/snippets/DeIdentificationTests.java
dlp/src/test/java/dlp/snippets/InfoTypesTests.java
dlp/src/test/java/dlp/snippets/InspectTests.java
dlp/src/test/java/dlp/snippets/JobsTests.java
dlp/src/test/java/dlp/snippets/QuickstartTests.java
dlp/src/test/java/dlp/snippets/RedactTests.java
dlp/src/test/java/dlp/snippets/RiskAnalysisTests.java
dlp/src/test/java/dlp/snippets/TemplatesTests.java
dlp/src/test/java/dlp/snippets/TestBase.java
dlp/src/test/java/dlp/snippets/TriggersTests.java

Should help with #3191 and other test failures.
* Switch to using the Truth assertion library
* Cleaned up some poorly formed test assertions that gave no useful error output
* Refactor common test code into a base class

Clean up DLP tests

---

bigtable/snippets/src/main/java/com/example/bigtable/Reads.java

fix region tag

---

kms/pom.xml

feat(deps): add protobuf-java-util as a direct dep of kms

---

secretmanager/pom.xml

feat(deps): add protobuf-java-util as a direct dep of secretmanager

---

securitycenter/pom.xml

feat(deps): add protobuf-java-util as a direct dep of securitycenter

---

run/README.md
run/events-pubsub/README.md
run/events-pubsub/pom.xml
run/events-pubsub/src/main/java/com/example/cloudrun/Application.java
run/events-pubsub/src/main/java/com/example/cloudrun/EventController.java
run/events-pubsub/src/main/java/com/example/cloudrun/eventpojos/PubSubBody.java
run/events-pubsub/src/test/java/com/example/cloudrun/EventControllerTests.java
run/events-storage/README.md
run/events-storage/pom.xml
run/events-storage/src/main/java/com/example/cloudrun/Application.java
run/events-storage/src/main/java/com/example/cloudrun/EventController.java
run/events-storage/src/main/java/com/example/cloudrun/eventpojos/PubSubBody.java
run/events-storage/src/test/java/com/example/cloudrun/EventControllerTests.java

Add Cloud Run Events Samples

---

run/pubsub/README.md

Fix dependency in Cloud Run Readme

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourcePatch.java

healthcare API: add comment clarifying FHIR update resource

---

SAMPLE_FORMAT.md

FYI @GoogleCloudPlatform/java-samples-reviewers

Add a paragraph on specific exceptions.

---

.github/blunderbuss.yml

chore(blunderbuss): Remove kurtisvg@ from issues/prs while OOO

---

healthcare/v1/src/main/java/snippets/healthcare/hl7v2/messages/HL7v2MessageList.java
healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3308

healthcare API: fix flaky test

---

run/README.md
run/events-pubsub/anthos.md
run/events-storage/anthos.md

Added Events for Cloud Run for Anthos samples. Fixes #3330

---

appengine-java8/bigtable/pom.xml
appengine-java8/endpoints-v2-backend/pom.xml
appengine-java8/endpoints-v2-guice/pom.xml
appengine-java8/endpoints-v2-migration/pom.xml
appengine-java8/springboot-helloworld/pom.xml

Fix minimum Maven version errors

---

logging/cloud-client/pom.xml
logging/cloud-client/src/main/java/com/example/logging/ListLogs.java
logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java

remove unused parameter

---

functions/helloworld/hello-http-gradle/build.gradle

cc @labtopia
Fixes issue introduced in #3410 
**Please merge** once approved. Thanks!

chore(functions): fix gradle formatting issue

---

renovate.json

Update renovate.json for Apache Beam packages

---

spanner/cloud-client/pom.xml
spanner/cloud-client/src/main/java/com/example/spanner/AsyncDmlExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadOnlyTransactionExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadRowExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncReadUsingIndexExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncRunnerExample.java
spanner/cloud-client/src/main/java/com/example/spanner/AsyncTransactionManagerExample.java
spanner/cloud-client/src/test/java/com/example/spanner/AsyncExamplesIT.java

Adds examples for the newly added asynchronous API for Cloud Spanner.

docs: add samples for async api

---

dataflow/encryption-keys/pom.xml
dataflow/encryption-keys/src/main/java/com/example/dataflow/cmek/BigQueryKmsKey.java
dataflow/flex-templates/kafka_to_bigquery/pom.xml
dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
dataflow/templates/pom.xml
dataflow/templates/src/main/java/com/example/dataflow/templates/WordCount.java

Fix lint errors

---

pubsub/streaming-analytics/README.md
pubsub/streaming-analytics/pom.xml
pubsub/streaming-analytics/src/main/java/com/examples/pubsub/streaming/PubSubToGCS.java
pubsub/streaming-analytics/src/main/java/com/examples/pubsub/streaming/PubSubToGcs.java

Pub/Sub: add shared-config and fix lint

---

functions/helloworld/helloworld-gradle/build.gradle

Setting a default empty string for the function target when unused

---

jobs/v3/src/main/java/com/google/samples/AutoCompleteSample.java
jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java
jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java
jobs/v3/src/main/java/com/google/samples/EmailAlertSearchSample.java
jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java
jobs/v3/src/main/java/com/google/samples/GeneralSearchSample.java
jobs/v3/src/main/java/com/google/samples/HistogramSample.java
jobs/v3/src/main/java/com/google/samples/LocationSearchSample.java
jobs/v3/src/test/java/SampleTests.java
logging/cloud-client/src/test/java/com/example/logging/LoggingIT.java

Refactor tests jobs v3

---

monitoring/cloud-client/pom.xml
monitoring/v3/pom.xml

Fixes #3540 
I am not sure it is really good solution for this issue. I was able to make it pass adding the removed deps from previous PR.

deps: added temp fix for auth

---

cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java

Fixes internal bug b/165099138.

fix(cloud-sql): Updated sample to include full JDBC url in comments.

---

automl/beta/src/main/java/com/example/automl/ListModels.java

Fixes #3574 , #3550 
It is temporary fix, I think default timeout value should be increased to 10-15 sec on AutoMLClientSetting

samples: fixed flaky test automl

---

iam/api-client/src/main/java/iam/snippets/CreateServiceAccount.java
iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/DeleteServiceAccount.java
iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/DisableServiceAccount.java
iam/api-client/src/main/java/iam/snippets/EnableServiceAccount.java
iam/api-client/src/main/java/iam/snippets/ListServiceAccountKeys.java
iam/api-client/src/main/java/iam/snippets/RenameServiceAccount.java
iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java

Add UUID for IAM tests

---

healthcare/v1/src/test/java/snippets/healthcare/Hl7v2MessageTests.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3485

healthcare API: increase sleep time for hl7v2MessageList

---

vision/cloud-client/src/main/java/com/example/vision/snippets/DetectLandmarksUrl.java
vision/cloud-client/src/test/java/com/example/vision/DetectLandmarksGcsTest.java

Fixes #3557 
Looks like service is WAI. Added a retry when SERVICE is not available due to request throttling or DOS prevention
https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageRequest#ImageSource

samples (test): fixed the flaky test

---

automl/beta/src/test/java/com/example/automl/ImportDatasetTest.java

samples: refactor automl beta test for importDataset

---

SAMPLE_FORMAT.md

docs: clean up language

---

automl/beta/pom.xml

libraries-bom 10.0

---

translate/cloud-client/pom.xml

translate sample to use libraries-bom 10.0.0

---

automl/cloud-client/src/main/java/com/example/automl/GetOperationStatus.java
automl/cloud-client/src/test/java/com/example/automl/GetOperationStatusTest.java

samples: fixed flaky test on getOper sample

---

automl/cloud-client/README.md
automl/cloud-client/pom.xml

automl/cloud-client/pom.xml to use the GCP Libraries BOM 10.0.0

---

functions/slack/pom.xml

Hotfix for erroneous `pom.xml` change in #3689 
@lesv please merge **when tests pass** - thanks!

chore(functions/slack): add back missing package

---

monitoring/v3/README.md
monitoring/v3/src/main/java/com/example/AlertSample.java
monitoring/v3/src/test/java/com/example/AlertIT.java

Update Monitoring sample tests

---

pubsub/spring/pom.xml

Rearranging a region tag to show just the [Spring Cloud GCP Bill of Materials (BOM)](https://cloud.spring.io/spring-cloud-gcp/reference/html/#bill-of-materials). For internal cl/331028840.

Pub/Sub: rearrange region tag

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/AutocommitUpdateDataExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlUsingSqlStatementsExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BufferedWriteExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadOnlyTransactionExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadWriteTransactionExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyTimestampBoundExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/TransactionWithRetryLoopUsingOnlyJdbcExample.java
spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java

Adds samples for the `NUMERIC` data type to the existing JDBC samples.

feat: add samples for numeric

---

renovate.json

All Vertx packages should update together.

---

run/events-storage/Dockerfile
run/events-storage/pom.xml

This sample was not building with Cloud Build. The two changes I've made allow it to build. I have limited Docker and Maven expertise. Please don't assume I know what I'm doing.

Add Dockerfile and fix pom.xml so that the sample builds with Cloud Build

---

healthcare/v1/src/test/java/snippets/healthcare/DatasetTests.java

Fixes internal bug - 14,000 datasets created without being cleared out.

Delete dataset after each test in DatasetTests.

---

spanner/cloud-client/src/main/java/com/example/spanner/AddNumericColumnSample.java
spanner/cloud-client/src/main/java/com/example/spanner/InsertNumericDataSample.java
spanner/cloud-client/src/main/java/com/example/spanner/QueryWithNumericParameterSample.java
spanner/cloud-client/src/main/java/com/example/spanner/UpdateNumericDataSample.java
spanner/cloud-client/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java

Adds standalone samples for the new `NUMERIC` data type for Spanner.

samples: add standalone numeric samples for Spanner

---

renovate.json

We should always do this manually.
Fixes #issue

Never update servlet

---

functions/concepts/retry-timeout/src/main/java/functions/RetryTimeout.java
functions/concepts/retry-timeout/src/test/java/functions/RetryTimeoutTest.java

In the retry-timeout sample for GCF java11, we should determine
the event timestamp from the Context parameter, not from properties
of the passed-in PubSub object.
Fixes #3734.

Determine pubsub event timestamp correctly in retry-timeout.

---

automl/README.md

Added a small reminder for deleted autoML samples

samples: added small reminder for deleted samples

---

vision/beta/cloud-client/src/main/java/com/example/vision/AsyncBatchAnnotateImagesGcs.java
vision/cloud-client/src/main/java/com/example/vision/Detect.java

samples: vision async batch increase timeout len

---

translate/cloud-client/src/main/java/com/example/translate/BatchTranslateText.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossary.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithGlossaryAndModel.java
translate/cloud-client/src/main/java/com/example/translate/BatchTranslateTextWithModel.java

Fixes #3704 
It rarely happens but sometimes BatchTranslate samples may hit 4-5 min mark

samples: translate batch lro occasionally hits 4-5 min mark

---

appengine-java11/vertx-helloworld/src/main/appengine/app.yaml

Remove entrypoint from app.yaml

---

spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java

Fixes #3828 and the build error in #3823

fix: change return type to List

---

appengine-java11/appengine-simple-jetty-main/README.md

Fix minor typos

---

bigtable/spark/README.md
bigtable/spark/build.sbt
bigtable/spark/src/main/scala/example/Wordcount.scala

Fixes NPE when submitting Wordcount to Dataproc
/cc @kolea2 @igorbernstein2

Wordcount on Dataproc WORKS! (No more NPEs)

---

video/cloud-client/src/test/java/com/example/video/DetectIT.java
video/cloud-client/src/test/java/com/example/video/DetectTextTest.java
video/cloud-client/src/test/java/com/example/video/Retry.java

samples: added retry logic for flaky tests

---

video/beta/src/test/java/com/example/video/DetectFacesGcsIT.java
video/beta/src/test/java/com/example/video/DetectFacesIT.java

samples: tests refactored

---

.kokoro/tests/run_tests.sh
bigtable/memorystore/README.md
bigtable/memorystore/pom.xml
bigtable/memorystore/src/main/java/Memcached.java
bigtable/memorystore/src/test/java/MemcachedTest.java

Sample for Bigtable and Memcached

---

iot/api-client/end-to-end-example/src/main/java/com/example/cloud/iot/endtoend/CleanUpHelper.java
iot/api-client/end-to-end-example/src/test/java/com/example/cloud/iot/endtoend/CloudiotPubsubExampleServerTest.java

samples: added cleanup option

---

cloud-sql/r2dbc/README.md
cloud-sql/r2dbc/pom.xml
cloud-sql/r2dbc/src/main/appengine/app.yaml
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/CommanLineRunnerSchemaCreator.java
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/CommandLineRunnerSchemaCreator.java
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/MainController.java
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/R2dbcSampleApplication.java
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/Vote.java
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/VoteController.java
cloud-sql/r2dbc/src/main/java/com/example/cloudsql/r2dbcsample/VoteRepository.java
cloud-sql/r2dbc/src/main/resources/application.properties
cloud-sql/r2dbc/src/main/resources/templates/index.html

Add Cloud SQL R2DBC sample

---

bigtable/memorystore/README.md
bigtable/memorystore/src/main/java/Memcached.java
bigtable/memorystore/src/test/java/MemcachedTest.java

Update host IP to be discovery endpoint
Change cache to be 30 minutes instead of 10 seconds
Fixes #issue

Bigtable Memcached example fixes/cleanup

---

eventarc/pubsub/pom.xml

Remove region tag

---

appengine-java8/tasks/snippets/src/main/java/com/example/task/CreateQueue.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/CreateTask.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/CreateTaskWithName.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/DeleteQueue.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/DeleteTask.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/PauseQueue.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/PurgeQueue.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/RetryTask.java
appengine-java8/tasks/snippets/src/main/java/com/example/task/UpdateQueue.java

Update region tags with product name

---

translate/automl/src/main/java/com/google/cloud/translate/automl/PredictionApi.java

Fixed mistaken comment describing the function as image prediction instead of translation.

Fixed description of function

---

iot/api-client/end-to-end-example/src/test/java/com/example/cloud/iot/endtoend/CloudiotPubsubExampleServerTest.java

chore: added missing exception for iot test

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceUpdate.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java

Add FhirResourceUpdate sample.

---

iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

chore: added UIID to prevent concurrency error

---

bigtable/spark/README.md
bigtable/spark/build.sbt

note: this is still a WIP, opening this PR for the bigtable-spark-example branch

chore(bigtable): spark deps cleanup and readme updates

---

run/authentication/src/main/java/com/example/cloudrun/Authentication.java
run/hello-broken/pom.xml
run/hello-broken/src/main/java/com/example/cloudrun/App.java
run/helloworld/Dockerfile
run/helloworld/pom.xml
run/helloworld/src/main/java/com/example/helloworld/HelloworldApplication.java
run/helloworld/src/main/resources/application.properties
run/image-processing/Dockerfile
run/image-processing/pom.xml
run/image-processing/src/main/java/com/example/cloudrun/ImageMagick.java
run/image-processing/src/main/java/com/example/cloudrun/PubSubController.java
run/logging-manual/pom.xml
run/logging-manual/src/main/java/com/example/cloudrun/App.java
run/logging-manual/src/main/resources/logback.xml
run/markdown-preview/editor/src/main/java/com/example/cloudrun/RenderController.java
run/pubsub/pom.xml
run/pubsub/src/main/java/com/example/cloudrun/PubSubApplication.java
run/pubsub/src/main/java/com/example/cloudrun/PubSubController.java
run/system-package/Dockerfile
run/system-package/pom.xml
run/system-package/src/main/java/com/example/cloudrun/App.java

Will de-duplicate in the future.

New region tags for Cloud Run

---

functions/spanner/src/main/java/functions/HelloSpanner.java

The Spanner client library now includes a lazy initializer for Spanner instances that can be used with Google Cloud Functions and other libraries that want to create an instance the first time one is needed and reuse this instance for subsequent requests.
Fixes #2862

feat: use LazySpannerInitializer instead of DCL

---

cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java

In the mySQL example the comments mention PostgreSQL.

Example: Replace wrong PostgreSQL mention in comment

---

functions/concepts/lazy-fields/src/main/java/functions/LazyFields.java
functions/concepts/scopes/src/main/java/functions/Scopes.java
run/image-processing/pom.xml

update Cloud Run region tags

---

bigtable/spark/README.md
bigtable/spark/build.sbt
bigtable/spark/src/test/scala/example/IntegrationTest.scala

WIP targeting branch bigtable-spark-example

test(bigtable_spark): update integration test, update deps and readme

---

healthcare/v1/src/test/java/snippets/healthcare/DicomWebTests.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3845

healthcare API: add ascending order to DICOMweb tests

---

cloud-sql/sqlserver/servlet/README.md
cloud-sql/sqlserver/servlet/pom.xml
cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/IndexServlet.java
cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/Vote.java
cloud-sql/sqlserver/servlet/src/main/webapp/WEB-INF/appengine-web.xml
cloud-sql/sqlserver/servlet/src/main/webapp/index.jsp

Add sample for Cloud SQL for SQL Server

---

cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/IndexServlet.java

chore: fix region tag in Cloud SQL sample

---

bigtable/spark/README.md

WIP targeting bigtable-spark-example branch

chore(bigtable_spark): last round of readme updates

---

appengine-java8/firebase-backend/README.md
appengine-java8/firebase-backend/pom.xml
appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/backend/MessageProcessorServlet.java
appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/backend/MessagePurger.java
appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/common/LogEntry.java
appengine-java8/firebase-backend/src/main/java/com/google/cloud/solutions/flexenv/common/Message.java
appengine-java8/firebase-backend/src/main/webapp/WEB-INF/appengine-web.xml
appengine-java8/firebase-backend/src/main/webapp/WEB-INF/logging.properties
appengine-java8/firebase-backend/src/main/webapp/WEB-INF/web.xml

Move samples from firebase-appengine-backend to java-docs-samples.

---

bigtable/spark/build.sbt

chore(bigtable_spark): deps cleanup

---

pubsub/streaming-analytics/README.md

Pub/Sub: add --region to command to start dataflow job

---

dataflow/README.md

Many of the APIs are already enabled or are automatically added by the `dataflow` API.

dataflow: simplify enabled APIs list

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/Filters.java
bigtable/hbase/snippets/src/main/java/com/example/bigtable/Reads.java

fix: correcting region tags for Hbase filter and read snippets

---

.github/CODEOWNERS

Add iot team as code owner

---

iam/api-client/src/main/java/iam/snippets/AddBinding.java

This is step (1) of (3):
1. Wrap current region tag with the region tag used in other languages
2. Update DevSite Java sample to use newer/better region tag
3. Remove inner 'old' region tag once DevSite changes are proliferated
- [ x] Please **merge** this PR for me once it is approved.

standardize region tag to match other languages

---

pubsub/spring/pom.xml

Reverts GoogleCloudPlatform/java-docs-samples#4581
See #4579

Revert "chore(deps): update dependency org.springframework.boot:spring-boot-dependencies to v2.4.2"

---

code-of-conduct.md

Initial commit of standard c-o-c

---

cloud-sql/mysql/servlet/README.md
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/sqlserver/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java

- [x ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ x] Appropriate changes to README are included in PR
- [ x] **Tests** pass:   `mvn clean verify` **required**
- [ x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ x] Please **merge** this PR for me once it is approved.

docs: added comments clarifying use of JDBC Socket Factory

---

functions/helloworld/hello-http/src/test/java/functions/ExampleSystemIT.java

chore(functions): skip system test if env var not set

---

functions/http/parse-content-type/src/main/java/functions/ParseContentType.java
functions/http/parse-content-type/src/test/java/functions/ParseContentTypeTest.java

chore(functions): fix broken switch-case

---

bigtable/spark/build.sbt
renovate.json

fix renovate config and roll back deps

fix(deps): fix scalaVersion and pin jackson-module-scala

---

bigtable/spark/README.md

Update spark sample path

---

cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
cloud-sql/mysql/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java
cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/EncryptAndInsertData.java
cloud-sql/sqlserver/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java

Correct comments on associated data.

---

bigtable/spark/README.md

samples(bigtable): update second spark home

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java

Sample for configuring Bigtable connection pool

---

SAMPLE_FORMAT.md

@billyjacobson FYI
Fixes #issue

Save & Restore out / err

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java

docs: quick change of region tag for a Bigtable sample

---

eventarc/audit-storage/Dockerfile
eventarc/audit-storage/src/main/java/com/example/cloudrun/Application.java
eventarc/audit-storage/src/main/java/com/example/cloudrun/EventController.java

Updates region tags to use `audit_storage`, not `gcs`.
These aren't in the docs, please merge this when approved.

chore(eventarc): update region tags

---

healthcare/v1/pom.xml

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/4958

healthcare API: add missing com.google.http-client dependency

---

cloud-sql/postgres/client-side-encryption/src/main/java/cloudsql/tink/QueryAndDecryptData.java

Noticed a typo while looking at the docs.

chore: fix typo in Cloud SQL Sample

---

appengine-java8/guestbook-cloud-datastore/pom.xml

fix: update dependency

---

bigtable/beam/keyviz-art/pom.xml

fix:  Add additional dependency for Bigtable test

---

jobs/v3/src/main/java/com/google/samples/JobServiceQuickstart.java
jobs/v3/src/test/java/SampleTests.java

chore: refactor auth section of the jobs samples

---

trace/pom.xml

Fix Trace tests.

---

pubsublite/streaming-analytics/README.md
pubsublite/streaming-analytics/metadata.json

A nit in the Dataflow template file `metadata.json`.

fix: remove optional tag on input parameter

---

pubsublite/streaming-analytics/src/main/java/examples/PubsubliteToGcs.java

fix(pubsublite): move region tags to include imports

---

iot/api-client/manager/README.md
iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java

docs: Replace -Dproj to -Dproject_id in all example commands.

---

functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java

This should fix #5250 and #5257
(I wasn't able to reproduce them locally, but this makes the tests themselves more fault-tolerant.)

chore(functions): fix flaky tests + update dir property

---

.github/CODEOWNERS
.github/blunderbuss.yml

Updates the CODEOWNERs file and Blunderbuss config for new teamsync managed groups.

Update CODEOWNERS / Blunderbuss for SoDA

---

iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

test: Fixed registry cleanup.

---

functions/helloworld/hello-gcs/pom.xml
functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
functions/helloworld/hello-http/pom.xml
functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
functions/helloworld/hello-pubsub/pom.xml
functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java

chore(functions): increase retry counts for flaky tests

---

functions/helloworld/hello-gcs/src/test/java/functions/ExampleIT.java
functions/helloworld/hello-http/src/test/java/functions/ExampleIT.java
functions/helloworld/hello-pubsub/src/test/java/functions/ExampleIT.java

I wasn't able to isolate the cause of the flaky GCF tests. 🙁
This PR adds better debugging code, which should hopefully show us what the problem is.

chore(functions): improve emulator debugging code

---

run/helloworld/Dockerfile
run/image-processing/Dockerfile
run/system-package/Dockerfile

fix: update Dockerfile to use JRE

---

run/image-processing/src/main/java/com/example/cloudrun/PubSubController.java

fix: Update sample with best practices

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/ConfigureConnectionPool.java
bigtable/hbase/snippets/src/test/java/com/example/bigtable/ConfigureConnectionPoolTest.java

docs: fix connection pool size for samples

---

pubsub/spring/pom.xml

Fixes #4570 
Please only accept PRs that update the released version of springframework: 
- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies
- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-gcp-dependencies
Cc: @eaball35

fix(pubsub): update to the latest released version

---

compute/cmdline/src/main/java/ComputeEngineSample.java

Update compute java sample

---

pubsub/streaming-analytics/README.md

docs: fix command line args in Pub/Sub streaming sample

---

compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java

docs: updated comments in getUsageExportBucket

---

run/idp-sql/README.md
run/idp-sql/pom.xml
run/idp-sql/postcreate.sh
run/idp-sql/src/main/java/com/example/cloudrun/IdpSqlApplication.java
run/idp-sql/src/test/java/com/example/cloudrun/VoteControllerTests.java

feat: update sample to use Secret Manager integration

---

cloud-sql/mysql/servlet/README.md
cloud-sql/postgres/servlet/README.md
cloud-sql/r2dbc/README.md
cloud-sql/sqlserver/servlet/README.md

feat: update README with Secret Manager

---

unittests/src/test/java/com/google/appengine/samples/AuthenticationTest.java
unittests/src/test/java/com/google/appengine/samples/BaseTestConfiguration.java
unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java
unittests/src/test/java/com/google/appengine/samples/LocalCustomPolicyHighRepDatastoreTest.java
unittests/src/test/java/com/google/appengine/samples/LocalDatastoreTest.java
unittests/src/test/java/com/google/appengine/samples/LocalHighRepDatastoreTest.java
unittests/src/test/java/com/google/appengine/samples/LocalMemcacheTest.java
unittests/src/test/java/com/google/appengine/samples/LocalUrlFetchTest.java
unittests/src/test/java/com/google/appengine/samples/ShortTest.java
unittests/src/test/java/com/google/appengine/samples/TaskQueueConfigTest.java
unittests/src/test/java/com/google/appengine/samples/TaskQueueTest.java

May help fix #5575, or at least hopefully narrow down which test is causing the issue.

chore: Add junit timeout rule to unittests folder

---

spanner/opencensus/README.md
spanner/opencensus/src/main/java/com/example/spanner/opencensus/CaptureGfeMetric.java
spanner/opencensus/src/test/java/com/example/spanner/opencensus/CaptureGfeMetricIT.java

Continuation of https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5437 (This is the last PR in installment)

OpenCensus Cloud Spanner: capture GFE metric sample

---

compute/cloud-client/pom.xml
compute/cloud-client/src/main/java/compute/CreateInstance.java
compute/cloud-client/src/main/java/compute/DeleteInstance.java

fix: modified code to reflect 1.3.0-alpha changes

---

unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java

Debug flaky test

---

.github/CODEOWNERS
.github/auto-approve.yml

- [x ] Please **merge** this PR for me once it is approved.
@averikitsch FYI
@sofisl FYI
@kurtisvg FYI
@eaball35 FYI

chore: auto-approve.yml

---

unittests/src/test/java/com/google/appengine/samples/DeferredTaskTest.java

fix: extend timeout

---

compute/cloud-client/src/main/java/compute/CreateInstance.java
compute/cloud-client/src/main/java/compute/ListAllInstances.java
compute/cloud-client/src/main/java/compute/ListImages.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

Fixes #issue
> Adding samples to demonstrate pagination in GCE.

Compute pagination samples

---

cloud-sql/mysql/servlet/README.md
cloud-sql/postgres/servlet/README.md
cloud-sql/r2dbc/README.md
cloud-sql/sqlserver/servlet/README.md

Update Cloud Run mvn command in Cloud SQL  sample READMEs to address build error.

---

iam/api-client/pom.xml

docs: removed outdated comment

---

healthcare/v1/src/main/java/snippets/healthcare/dicom/DicomStorePatch.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java
healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceDeletePurge.java
healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StorePatch.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java

Fixes:
* b/174610018
* b/174755529

healthcare API: update Pub/Sub URI and fix FhirResourceDeletePurge formatting/test

---

appengine-java11/cloudsql/README.md
appengine-java11/cloudsql/pom.xml

Add test dependencies to pom.xml

---

compute/cloud-client/src/main/java/compute/CreateInstance.java
compute/cloud-client/src/main/java/compute/DeleteInstance.java
compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
compute/cloud-client/src/main/java/compute/WaitForOperation.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

1. Modified LRO wrappers to wait for the operation completion
2. Included wait for operation as a separate sample

fix(compute): modified LRO wrappers

---

media/transcoder/src/main/java/com/example/transcoder/CreateJobFromAdHoc.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobFromPreset.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobFromTemplate.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobTemplate.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobWithAnimatedOverlay.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobWithPeriodicImagesSpritesheet.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobWithSetNumberImagesSpritesheet.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobWithStaticOverlay.java
media/transcoder/src/main/java/com/example/transcoder/DeleteJob.java
media/transcoder/src/main/java/com/example/transcoder/DeleteJobTemplate.java
media/transcoder/src/main/java/com/example/transcoder/GetJob.java
media/transcoder/src/main/java/com/example/transcoder/GetJobState.java
media/transcoder/src/main/java/com/example/transcoder/GetJobTemplate.java
media/transcoder/src/main/java/com/example/transcoder/ListJobTemplates.java
media/transcoder/src/main/java/com/example/transcoder/ListJobs.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobFromTemplateTest.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobTemplateTest.java
media/transcoder/src/test/java/com/example/transcoder/DeleteJobTemplateTest.java
media/transcoder/src/test/java/com/example/transcoder/GetJobTemplateTest.java
media/transcoder/src/test/java/com/example/transcoder/ListJobTemplateTest.java

feat: update Transcoder API samples to v1

---

bigtable/beam/bulk-data-generator/pom.xml

docs: remove unused region tag

---

spanner/r2dbc/src/main/resources/application.properties

- [ x] **Tests** pass:   `mvn clean verify` **required**
- [ x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ x] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ x] Please **merge** this PR for me once it is approved.

Add documentation tags to R2DBC sample's connection string

---

.github/sync-repo-settings.yaml

Reverts GoogleCloudPlatform/java-docs-samples#5855

Revert "Update sync-repo-settings.yaml"

---

secretmanager/pom.xml
secretmanager/src/main/java/secretmanager/ListSecretVersionsWithFilter.java
secretmanager/src/main/java/secretmanager/ListSecretsWithFilter.java
secretmanager/src/test/java/secretmanager/SnippetsIT.java

Adds code samples for listSecrets and listSecretVersions with filter set.
- [ x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ x] `pom.xml` parent set to latest `shared-configuration`
- [ x] Appropriate changes to README are included in PR
- [ x] API's need to be enabled to test (tell us)

Added SecretManager filtered-listing samples

---

run/logging-manual/src/main/java/com/example/cloudrun/App.java

**Partial fix** for b/183751712

chore(functions/logging): exclude trace code from sample

---

functions/v2/helloworld/hello-gcs/src/main/java/functions/HelloGcs.java
functions/v2/helloworld/hello-gcs/src/test/java/functions/HelloGcsTest.java

Minor updates for GCF sample

---

compute/cloud-client/pom.xml
compute/cloud-client/src/main/java/compute/CreateInstance.java
compute/cloud-client/src/main/java/compute/DeleteInstance.java
compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
compute/cloud-client/src/main/java/compute/WaitForOperation.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

docs(samples): updating LRO wrappers and included operations wait blocking call

---

compute/cloud-client/src/main/java/compute/CreateFirewallRule.java
compute/cloud-client/src/main/java/compute/DeleteFirewallRule.java
compute/cloud-client/src/main/java/compute/GetFirewallRule.java
compute/cloud-client/src/main/java/compute/ListFirewallRules.java
compute/cloud-client/src/main/java/compute/ListImages.java
compute/cloud-client/src/main/java/compute/PatchFirewallRule.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

Gapic firewall samples

---

functions/v2/pubsub/subscribe-to-topic/pom.xml
functions/v2/pubsub/subscribe-to-topic/src/main/java/functions/SubscribeToTopic.java
functions/v2/pubsub/subscribe-to-topic/src/main/java/functions/eventpojos/PubSubBody.java
functions/v2/pubsub/subscribe-to-topic/src/test/java/functions/SubscribeToTopicTest.java

Update GCFv2 PubSub sample

---

spanner/jdbc/pom.xml
spanner/jdbc/src/main/java/com/example/spanner/jdbc/JsonCreateTableExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/JsonInsertDataExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/JsonQueryDataExample.java
spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java

Adds samples for the new JSON data type for Spanner JDBC.
Do not merge yet: Depends on changes in the Spanner JDBC driver that have not yet been included in the libraries bom.

feat: JSON samples for Spanner JDBC

---

run/image-processing/Dockerfile
run/system-package/Dockerfile

fix: update deprecated image

---

appengine-java11/springboot-helloworld/README.md

Fixes typo in the `README.md` file.

fix: correct typo in README.md

---

bigtable/memorystore/src/test/java/MemcachedTest.java

chore: add sleep to Bigtable MemcachedTest to fix flakiness

---

compute/cloud-client/src/main/java/compute/CreateEncryptedInstance.java
compute/cloud-client/src/main/java/compute/ResetInstance.java
compute/cloud-client/src/main/java/compute/StartEncryptedInstance.java
compute/cloud-client/src/main/java/compute/StartInstance.java
compute/cloud-client/src/main/java/compute/StopInstance.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

Contains samples and tests for:
1. Start/ Stop/ Reset Instance
2. Create Encrypted Instance

docs(compute): samples for instance operations

---

.kokoro/tests/run_tests.sh
run/filesystem/README.md
run/filesystem/gcsfuse.Dockerfile
run/filesystem/gcsfuse_run.sh
run/filesystem/pom.xml
run/filesystem/run.sh
run/filesystem/src/test/java/com/example/filesystem/FilesystemApplicationIT.java

feat: Add Fuse sample dockerfile

---

run/filesystem/gcsfuse.Dockerfile
run/filesystem/gcsfuse_run.sh

Add region tags to Cloud Run sample

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/AbortBatchExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/AutocommitUpdateDataExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDdlExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDdlUsingSqlStatementsExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/BatchDmlUsingSqlStatementsExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/ConnectionWithQueryOptionsExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithCredentialsExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithCustomHostExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithDataSourceExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithDefaultProjectIdExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithPropertiesExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateConnectionWithUrlPropertiesExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/CreateTableExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/GetCommitTimestampExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/GetReadTimestampExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/InsertDataExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/PartitionedDmlExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadOnlyTransactionExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/ReadWriteTransactionExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/SetQueryOptionsExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/SingleUseReadOnlyTimestampBoundExample.java

Suppressing warnings for OBL_UNSATISFIED_OBLIGATION is no longer needed after
https://github.com/GoogleCloudPlatform/java-repo-tools/issues/123 was merged.

chore: remove unnecessary warning suppressions

---

bigtable/memorystore/src/test/java/MemcachedTest.java

Fixes #4433
@meredithslota @billyjacobson trying out a different solution to fix this with some simple retry logic. WDYT?

fix(bigtable): add retry logic to MemecachedTest

---

compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

Samples compute create instances

---

cloud-sql/mysql/servlet/deployment.yaml
cloud-sql/mysql/servlet/service-account.yaml
cloud-sql/postgres/servlet/deployment.yaml
cloud-sql/postgres/servlet/service-account.yaml

Update Cloud SQL sample app yaml files with comments for Kubernetes service accounts.

---

functions/v2/cloudevent/log-cloudevent/pom.xml
functions/v2/cloudevent/log-cloudevent/src/main/java/functions/LogCloudEvent.java
functions/v2/cloudevent/log-cloudevent/src/test/java/functions/LogCloudEventTest.java

Adds first party Cloud Audit Logging sample for GCF v2.

feat: add GCFv2 CAL sample

---

functions/v2/cloudevent/log-cloudevent/src/main/java/functions/LogCloudEvent.java
functions/v2/cloudevent/log-cloudevent/src/test/java/functions/LogCloudEventTest.java

Update GCFv2 cloudevent

---

pubsub/spring/README.md
pubsub/spring/pom.xml
pubsub/spring/src/main/java/demo/PubSubApplication.java
pubsub/spring/src/test/java/demo/PubSubApplicationIT.java

- add test (suggestions welcome)
- update deprecated classes
@elefeint

Pub/Sub: update Spring tutorial with test + other nits

---

media/transcoder/src/main/java/com/example/transcoder/CreateJobWithConcatenatedInputs.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobWithConcatenatedInputsTest.java

fix(transcoder): use duration instead of float for args

---

dataflow/encryption-keys/pom.xml
dataflow/flex-templates/kafka_to_bigquery/pom.xml
dataflow/flex-templates/kafka_to_bigquery/src/main/java/org/apache/beam/samples/KafkaToBigQuery.java
dataflow/flex-templates/streaming_beam_sql/pom.xml
dataflow/flex-templates/streaming_beam_sql/src/main/java/org/apache/beam/samples/StreamingBeamSql.java
dataflow/spanner-io/pom.xml
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerGroupWriteIT.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerWriteIT.java
dataflow/templates/pom.xml

dataflow: update imports and upgrade log4j version

---

spanner/jdbc/pom.xml

Upgrades java-spanner to 6.17.3.
Upgrades java-spanner-jdbc to 2.5.6.

deps: bump spanner dependencies

---

bigtable/beam/workload-generator/README.md
bigtable/beam/workload-generator/metadata.json
bigtable/beam/workload-generator/pom.xml
bigtable/beam/workload-generator/src/main/java/bigtable/WorkloadGenerator.java
bigtable/beam/workload-generator/src/test/java/bigtable/WorkloadGeneratorTest.java

A dataflow template to put a heavy read load on a Bigtable table for demonstration purposes

docs: Bigtable Load generator tool

---

.kokoro/tests/run_tests.sh
compute/cloud-client/pom.xml
compute/cloud-client/src/main/java/compute/CreateEncryptedInstance.java
compute/cloud-client/src/main/java/compute/CreateFirewallRule.java
compute/cloud-client/src/main/java/compute/CreateInstance.java
compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
compute/cloud-client/src/main/java/compute/DeleteFirewallRule.java
compute/cloud-client/src/main/java/compute/DeleteInstance.java
compute/cloud-client/src/main/java/compute/ListAllInstances.java
compute/cloud-client/src/main/java/compute/ListImages.java
compute/cloud-client/src/main/java/compute/ListInstance.java
compute/cloud-client/src/main/java/compute/PatchFirewallRule.java
compute/cloud-client/src/main/java/compute/ResetInstance.java
compute/cloud-client/src/main/java/compute/SetUsageExportBucket.java
compute/cloud-client/src/main/java/compute/StartEncryptedInstance.java
compute/cloud-client/src/main/java/compute/StartInstance.java
compute/cloud-client/src/main/java/compute/StopInstance.java
compute/cloud-client/src/main/java/compute/WaitForOperation.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

docs(compute-samples): refactored samples and tests to adopt full-lro and enums as strings

---

run/filesystem/gcsfuse_run.sh
run/filesystem/run.sh

Make script copy and pasteable

---

run/pubsub/src/main/java/com/example/cloudrun/PubSubController.java

Add import statement to make sample clearer

---

functions/slack/src/test/java/functions/SlackSlashCommandTest.java

chore(functions/slack): fix flaky API call

---

compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java

Fixing a small issue with sample region tags

bug(compute): Fixing a small issue with sample region tags

---

compute/cloud-client/src/main/java/compute/StopInstance.java

chore: fix typo

---

functions/http/parse-xml/pom.xml
functions/http/parse-xml/src/main/java/functions/ParseXml.java
functions/http/parse-xml/src/test/java/functions/ParseXmlTest.java

feat(functions): add missing XML parsing sample

---

functions/helloworld/hello-http/src/test/java/functions/ExampleSystemIT.java

**Partial fix** for b/194128540

chore(functions): fix dep. on allow-unauthenticated

---

media/transcoder/src/main/java/com/example/transcoder/CreateJobWithEmbeddedCaptions.java
media/transcoder/src/main/java/com/example/transcoder/CreateJobWithStandaloneCaptions.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobWithEmbeddedCaptionsTest.java
media/transcoder/src/test/java/com/example/transcoder/CreateJobWithStandaloneCaptionsTest.java
media/transcoder/src/test/java/com/example/transcoder/testdata/caption.srt

feat(transcoder): add samples and tests for adding captions to videos

---

jobs/v3/src/test/java/SampleTests.java

test: fix job v3 autoCompleteSampleTest

---

iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java

docs(iam-samples): extract json_key_file from privatedata

---

cloud-sql/sqlserver/servlet/deployment.yaml
cloud-sql/sqlserver/servlet/service-account.yaml
cloud-sql/sqlserver/servlet/service.yaml

Update Cloud SQL for SQL Server sample app with Kubernetes Engine yaml files.

---

functions/v2/log-cloudevent/src/main/java/functions/LogCloudEvent.java
functions/v2/log-cloudevent/src/test/java/functions/LogCloudEventTest.java

fix(functions/v2): Fix typo

---

bigtable/beam/workload-generator/README.md
bigtable/beam/workload-generator/src/main/java/bigtable/WorkloadGenerator.java
bigtable/beam/workload-generator/src/test/java/bigtable/WorkloadGeneratorTest.java

samples: Update Bigtable workload generator to have a timer

---

bigtable/beam/workload-generator/README.md

updating dataflow delete functionality
Fixes the issue mentioned in #6612 by @kongweihan 

docs: fix Bigtable workload generator (df delete)

---

compute/cloud-client/src/main/java/compute/deleteprotection/CreateInstanceDeleteProtection.java
compute/cloud-client/src/main/java/compute/deleteprotection/GetDeleteProtection.java
compute/cloud-client/src/main/java/compute/deleteprotection/SetDeleteProtection.java
compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java
compute/cloud-client/src/test/java/compute/Util.java
compute/cloud-client/src/test/java/compute/deleteprotection/DeleteProtectionIT.java

docs(compute-samples): init samples and test for delete protection

---

compute/cloud-client/src/main/java/compute/ResetInstance.java

docs(compute-samples): fix comment

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/resources/FhirResourceSearchGet.java
healthcare/v1/src/test/java/snippets/healthcare/FhirResourceTests.java

Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/4848

healthcare API: update FhirResourceSearchGet to use CloudHealthcareClient

---

functions/v2/pubsub/src/main/java/functions/SubscribeToTopic.java
functions/v2/pubsub/src/test/java/functions/SubscribeToTopicTest.java

chore: update GCF v2 Sample

---

run/jobs/README.md
run/jobs/pom.xml
run/jobs/src/main/java/com/example/JobsExample.java
run/jobs/src/test/java/com/example/JobsIntegrationTests.java
run/jobs/src/test/java/com/example/resources/e2e_test_cleanup.yaml
run/jobs/src/test/java/com/example/resources/e2e_test_setup.yaml
run/jobs/src/test/java/com/example/resources/retry.sh

chore: add E2E tests for Cloud Run

---

dialogflow/basic-webhook/pom.xml
dialogflow/basic-webhook/src/main/java/com/example/dialogflow/cx/BasicWebhook.java
dialogflow/basic-webhook/src/test/java/com/example/dialogflow/cx/BasicWebhookIT.java

samples: added dialogflow webhook snippet

---

run/authentication/src/main/java/com/example/cloudrun/Authentication.java
run/authentication/src/test/java/com/example/cloudrun/AuthenticationTest.java

**NOTE:** Since this was a pretty minor change, I did _not_ test this on GCF or Cloud Run.
Please LMK if I should change that!
/cc @grayside

fix(serverless): clean up ID token example

---

functions/helloworld/hello-gcs/src/main/java/functions/HelloGcs.java

chore(functions/hello-gcs): clarify comments

---

functions/helloworld/hello-error/src/main/java/functions/HelloError.java

chore(functions/hello-error): update product name

---

compute/cloud-client/pom.xml
compute/cloud-client/src/main/java/compute/CreateInstance.java
compute/cloud-client/src/main/java/compute/ResumeInstance.java
compute/cloud-client/src/main/java/compute/SuspendInstance.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

Providing samples for the [Suspending and resuming an instance](https://cloud.google.com/compute/docs/instances/suspend-resume-instance)

docs(compute-samples): added snippets for suspend resume instance

---

.kokoro/java17/common.cfg
.kokoro/java17/continuous.cfg
.kokoro/java17/periodic.cfg
.kokoro/java17/presubmit.cfg
.kokoro/tests/run_test_java.sh

Fixes #6197 
Corresponding CL: [cl/445963302](https://critique.corp.google.com/cl/445963302)

chore: add Kokoro build configs for JDK 17

---

functions/logging/stackdriver-logging/pom.xml

Fixes #7090 
See:
- https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m
- https://openjdk.java.net/jeps/396

fix:  java.lang.reflect.InaccessibleObjectException in functions.StackdriverLogging sample

---

compute/cloud-client/src/main/java/compute/windows/osimage/CreateWindowsOsImage.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateFirewallRuleForWindowsActivationHost.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateRouteToWindowsActivationHost.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceExternalIp.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceInternalIp.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/GetInstanceSerialPort.java
compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java
compute/cloud-client/src/test/java/compute/windows/windowsinstances/CreatingManagingWindowsInstancesIT.java

for 1. Creating and managing instances
2. OS image
Fixes #issue

docs(compute-samples): added windows samples and tests

---

functions/concepts/env-vars/pom.xml

fix: java 17 test errors in functions.EnvVarsTest

---

functions/helloworld/hello-http-gradle/build.gradle

Fixes #7072
This confirms that the function is deployable and can run locally.

chore: update gradle function

---

media/livestream/pom.xml
media/livestream/src/main/java/com/example/livestream/CreateInput.java
media/livestream/src/main/java/com/example/livestream/DeleteInput.java
media/livestream/src/main/java/com/example/livestream/GetInput.java
media/livestream/src/main/java/com/example/livestream/ListInputs.java
media/livestream/src/main/java/com/example/livestream/UpdateInput.java
media/livestream/src/test/java/com/example/livestream/CreateInputTest.java
media/livestream/src/test/java/com/example/livestream/DeleteInputTest.java
media/livestream/src/test/java/com/example/livestream/GetInputTest.java
media/livestream/src/test/java/com/example/livestream/ListInputsTest.java
media/livestream/src/test/java/com/example/livestream/TestUtils.java
media/livestream/src/test/java/com/example/livestream/UpdateInputTest.java

feat:add Live Stream samples

---

media/livestream/src/main/java/com/example/livestream/CreateChannel.java
media/livestream/src/main/java/com/example/livestream/CreateChannelWithBackupInput.java
media/livestream/src/main/java/com/example/livestream/DeleteChannel.java
media/livestream/src/main/java/com/example/livestream/GetChannel.java
media/livestream/src/main/java/com/example/livestream/ListChannels.java
media/livestream/src/main/java/com/example/livestream/StartChannel.java
media/livestream/src/main/java/com/example/livestream/StopChannel.java
media/livestream/src/main/java/com/example/livestream/UpdateChannel.java
media/livestream/src/test/java/com/example/livestream/CreateChannelTest.java
media/livestream/src/test/java/com/example/livestream/CreateChannelWithBackupInputTest.java
media/livestream/src/test/java/com/example/livestream/DeleteChannelTest.java
media/livestream/src/test/java/com/example/livestream/GetChannelTest.java
media/livestream/src/test/java/com/example/livestream/ListChannelsTest.java
media/livestream/src/test/java/com/example/livestream/StartChannelTest.java
media/livestream/src/test/java/com/example/livestream/StopChannelTest.java
media/livestream/src/test/java/com/example/livestream/TestUtils.java
media/livestream/src/test/java/com/example/livestream/UpdateChannelTest.java

feat: add channel resource code samples and tests

---

media/livestream/src/main/java/com/example/livestream/CreateChannelEvent.java
media/livestream/src/main/java/com/example/livestream/DeleteChannelEvent.java
media/livestream/src/main/java/com/example/livestream/GetChannelEvent.java
media/livestream/src/main/java/com/example/livestream/ListChannelEvents.java
media/livestream/src/test/java/com/example/livestream/CreateChannelEventTest.java
media/livestream/src/test/java/com/example/livestream/DeleteChannelEventTest.java
media/livestream/src/test/java/com/example/livestream/GetChannelEventTest.java
media/livestream/src/test/java/com/example/livestream/ListChannelEventsTest.java
media/livestream/src/test/java/com/example/livestream/TestUtils.java

Fixes b:219762506
Final feature set

feat: add channel event resource code samples and tests

---

media/stitcher/pom.xml
media/stitcher/src/main/java/com/example/stitcher/CreateSlate.java
media/stitcher/src/main/java/com/example/stitcher/DeleteSlate.java
media/stitcher/src/main/java/com/example/stitcher/GetSlate.java
media/stitcher/src/main/java/com/example/stitcher/ListSlates.java
media/stitcher/src/main/java/com/example/stitcher/UpdateSlate.java
media/stitcher/src/test/java/com/example/stitcher/CreateSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/DeleteSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/GetSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/ListSlatesTest.java
media/stitcher/src/test/java/com/example/stitcher/UpdateSlateTest.java

feat: add Video Stitcher slate code samples and tests

---

functions/v2/label-compute-instance/src/main/java/functions/AutoLabelInstance.java

chore(functions/v2): Add region tag

---

media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/DeleteCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/GetCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/ListCdnKeys.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
media/stitcher/src/test/java/com/example/stitcher/CreateCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/DeleteCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/GetCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/ListCdnKeysTest.java
media/stitcher/src/test/java/com/example/stitcher/UpdateCdnKeyTest.java

feat: add Video Stitcher CDN key code samples and tests

---

media/stitcher/src/main/java/com/example/stitcher/CreateVodSession.java
media/stitcher/src/main/java/com/example/stitcher/GetVodAdTagDetail.java
media/stitcher/src/main/java/com/example/stitcher/GetVodSession.java
media/stitcher/src/main/java/com/example/stitcher/GetVodStitchDetail.java
media/stitcher/src/main/java/com/example/stitcher/ListVodAdTagDetails.java
media/stitcher/src/main/java/com/example/stitcher/ListVodStitchDetails.java
media/stitcher/src/test/java/com/example/stitcher/CreateVodSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/GetVodAdTagDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/GetVodSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/GetVodStitchDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/ListVodAdTagDetailsTest.java
media/stitcher/src/test/java/com/example/stitcher/ListVodStitchDetailsTest.java

feat: add Video Stitcher VOD session code samples and tests

---

media/stitcher/src/main/java/com/example/stitcher/CreateLiveSession.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveAdTagDetail.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveSession.java
media/stitcher/src/main/java/com/example/stitcher/ListLiveAdTagDetails.java
media/stitcher/src/test/java/com/example/stitcher/CreateLiveSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/GetLiveAdTagDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/GetLiveSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/ListLiveAdTagDetailsTest.java
media/stitcher/src/test/java/com/example/stitcher/TestUtils.java

feat: add Video Stitcher live session code samples and tests

---

.kokoro/tests/build_cloud_functions.sh
functions/helloworld/kotlin-hello-pubsub/src/main/kotlin/functions/KotlinHelloBackground.kt
functions/helloworld/kotlin-hello-pubsub/src/test/java/functions/KotlinHelloPubSubTest.java

Fixes issue encountered in #6876

fix: fix tests using wrong Pub/Sub func name

---

dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerGroupWrite.java
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadAll.java
dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerWrite.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerGroupWriteIT.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerWriteIT.java

Adds examples for Spanner PG dataflow.
Fixes b/232995390

feat: add sample for readAll for PG

---

media/livestream/src/main/java/com/example/livestream/CreateChannel.java
media/livestream/src/main/java/com/example/livestream/CreateChannelWithBackupInput.java

docs: align channel config with best practices

---

run/authentication/src/main/java/com/example/cloudrun/Authentication.java

chore(functions): clarify equality of endpoint and audience

---

container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

fix(issue-7198-7184): buffing up sleep timout to wait for more pubsub msgs

---

compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceExternalIp.java

Fix typo in CreateWindowsServerInstanceExternalIp.java

---

run/filesystem/gcsfuse.Dockerfile

Update ubuntu version for Dockerfile

---

media/livestream/src/main/java/com/example/livestream/CreateChannel.java
media/livestream/src/main/java/com/example/livestream/CreateChannelWithBackupInput.java
media/livestream/src/main/java/com/example/livestream/CreateInput.java
media/livestream/src/main/java/com/example/livestream/DeleteChannel.java
media/livestream/src/main/java/com/example/livestream/DeleteInput.java
media/livestream/src/main/java/com/example/livestream/StartChannel.java
media/livestream/src/main/java/com/example/livestream/StopChannel.java
media/livestream/src/main/java/com/example/livestream/UpdateChannel.java
media/livestream/src/main/java/com/example/livestream/UpdateInput.java
media/livestream/src/test/java/com/example/livestream/TestUtils.java

See also: https://chat.google.com/room/AAAAeSh7BFk/rTo-3gxrEnk

docs: fix timeout for LROs; first call can take up to 10 minutes

---

media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java

docs: clarify Google CDN is Cloud CDN

---

cloud-sql/postgres/servlet/src/main/java/com/example/cloudsql/ConnectorIamAuthnConnectionPoolFactory.java

Fix typo in Postgres Socket Factory class name

---

compute/cloud-client/src/main/java/compute/CreateInstanceWithExistingDisks.java
compute/cloud-client/src/main/java/compute/GetInstance.java
compute/cloud-client/src/main/java/compute/disks/CreateDiskFromImage.java
compute/cloud-client/src/main/java/compute/disks/CreateDiskFromSnapshot.java
compute/cloud-client/src/main/java/compute/disks/CreateEmptyDisk.java
compute/cloud-client/src/main/java/compute/disks/CreateSnapshot.java
compute/cloud-client/src/main/java/compute/disks/DeleteDisk.java
compute/cloud-client/src/main/java/compute/disks/DeleteSnapshot.java
compute/cloud-client/src/main/java/compute/disks/ListDisks.java
compute/cloud-client/src/main/java/compute/disks/ListSnapshots.java
compute/cloud-client/src/main/java/compute/disks/SetDiskAutodelete.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceExternalIp.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceInternalIp.java
compute/cloud-client/src/test/java/compute/InstancesAdvancedIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java
compute/cloud-client/src/test/java/compute/disks/DisksIT.java
compute/cloud-client/src/test/java/compute/disks/SnapshotsIT.java

Added samples to move instances across zones (https://cloud.google.com/compute/docs/instances/moving-instance-across-zones)
Apologies for the PR size.

docs(compute-samples): added samples for moving VM instances

---

compute/cloud-client/src/main/java/compute/custommachinetype/CreateCustomMachineType.java
compute/cloud-client/src/main/java/compute/custommachinetype/CreateInstanceWithCustomSharedCore.java
compute/cloud-client/src/main/java/compute/custommachinetype/CreateWithHelper.java
compute/cloud-client/src/main/java/compute/custommachinetype/CreateWithoutHelper.java
compute/cloud-client/src/main/java/compute/custommachinetype/ExtraMemoryWithoutHelper.java
compute/cloud-client/src/main/java/compute/custommachinetype/HelperClass.java
compute/cloud-client/src/main/java/compute/custommachinetype/UpdateMemory.java
compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java
compute/cloud-client/src/test/java/compute/custommachinetype/HelperIT.java
compute/cloud-client/src/test/java/compute/windows/windowsinstances/CreatingManagingWindowsInstancesIT.java

Added Compute Machine type samples and tests.
Docs: https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type

docs(compute-samples): added samples and tests for custom machine type

---

compute/cloud-client/src/main/java/compute/CreateWithLocalSSD.java
compute/cloud-client/src/main/java/compute/CreateWithLocalSsd.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

Sample to create disk with local SSD

docs(compute-samples): add sample and test for local SSD disk

---

container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java

fix: add retries to tests

---

jobs/v3/src/main/java/com/google/samples/BatchOperationSample.java

This fixes a collision with the region tags with the new Google Cloud Batch product. These code samples are not published on any documentation pages, so no documentation updates are needed.

fix(samples): Fix the region tags used on batch job search

---

storage-transfer/pom.xml
storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferFromS3CompatibleSource.java
storage-transfer/src/test/java/com/google/cloud/storage/storagetransfer/samples/test/ITStoragetransferSamplesTest.java

Add S3 compatible transfer sample, for this page:
https://cloud.google.com/storage-transfer/docs/s3-compatible#rest-api_1

Add S3 compatible transfer sample

---

media/stitcher/src/main/java/com/example/stitcher/CreateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/CreateLiveSession.java
media/stitcher/src/main/java/com/example/stitcher/CreateSlate.java
media/stitcher/src/main/java/com/example/stitcher/CreateVodSession.java
media/stitcher/src/main/java/com/example/stitcher/DeleteCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/DeleteSlate.java
media/stitcher/src/main/java/com/example/stitcher/GetCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveAdTagDetail.java
media/stitcher/src/main/java/com/example/stitcher/GetLiveSession.java
media/stitcher/src/main/java/com/example/stitcher/GetSlate.java
media/stitcher/src/main/java/com/example/stitcher/GetVodAdTagDetail.java
media/stitcher/src/main/java/com/example/stitcher/GetVodSession.java
media/stitcher/src/main/java/com/example/stitcher/GetVodStitchDetail.java
media/stitcher/src/main/java/com/example/stitcher/ListCdnKeys.java
media/stitcher/src/main/java/com/example/stitcher/ListLiveAdTagDetails.java
media/stitcher/src/main/java/com/example/stitcher/ListSlates.java
media/stitcher/src/main/java/com/example/stitcher/ListVodAdTagDetails.java
media/stitcher/src/main/java/com/example/stitcher/ListVodStitchDetails.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/UpdateSlate.java

fix(samples): Fix Video Stitcher region tag prefix

---

opencensus/pom.xml

fix(opencensus): add core dependency

---

appengine-java8/datastore/src/test/java/com/example/appengine/EntitiesTest.java

first step in fixing 253489606

fix: add gae region tag

---

.kokoro/tests/build_cloud_functions.sh
iot/api-client/codelab/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

test: address "functions in use" build failures

---

appengine-java11/oauth2/pom.xml
appengine-java11/oauth2/src/main/appengine/app.yaml
appengine-java11/oauth2/src/main/java/com/example/appengine/Utils.java

chore: update GAE Oauth2 sample

---

functions/slack/pom.xml

deps: update com.google.apis:google-api-services-kgsearch to v1-rev20200809-2.0.0

---

bigtable/use-cases/fraudDetection/pom.xml

fix(deps): update dependency add new line in pom file for CBT fraud-detection
Fixes #issue

fix(deps): update dependency add new line in pom file for CBT fraud-detection

---

bigtable/use-cases/fraudDetection/README.md
bigtable/use-cases/fraudDetection/src/main/java/bigtable/fraud/beam/FraudDetection.java

docs: Bigtable fraud example update readme and convert scan to get

---

webrisk/pom.xml

chore: updated pom for samples migration

---

storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/QuickstartSample.java

Adds a main method to the quickstart sample
This is required for a Neos tutorial to be possible (needs to be executable from the command line)

add main method to quickstart sample

---

kms/pom.xml
kms/src/main/java/kms/CheckStateImportJob.java
kms/src/main/java/kms/CheckStateImportedKey.java
kms/src/main/java/kms/CreateImportJob.java
kms/src/main/java/kms/CreateKeyForImport.java
kms/src/main/java/kms/ImportManuallyWrappedKey.java
kms/src/test/java/kms/SnippetsIT.java

Add Java docs samples for KMS key import.

---

asset/pom.xml
batch/snippets/pom.xml
mediatranslation/README.md
mediatranslation/pom.xml
recaptcha_enterprise/pom.xml
security-command-center/snippets/pom.xml
talent/snippets/pom.xml
tasks/snippets/pom.xml
vision/beta/README.md
vision/cloud-client/README.md
vision/product-search/README.md
workflows/cloud-client/README.md

chore: remove reference to googleapis

---

cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectionPoolContextListener.java
cloud-sql/mysql/servlet/src/main/java/com/example/cloudsql/ConnectorIamAuthnConnectionPoolFactory.java

feat: add iam authn example for mysql

---

dialogflow/snippets/src/test/java/com/example/dialogflow/CreateDocumentForArticleSuggestionTest.java

Temporary code for creating long-lived knowledge base and document resources needed for adding Article Suggestion sample code. It will be deleted by a followup PR once the resources are ready.
Reference:  https://cloud.google.com/agent-assist/docs/article-suggestion

samples: create long-lived resources for article suggestion feature

---

run/filesystem/README.md

Update readme: run/filesystem

---

dialogflow/snippets/src/main/java/com/example/dialogflow/AnswerRecordManagement.java
dialogflow/snippets/src/main/java/com/example/dialogflow/ParticipantManagement.java
dialogflow/snippets/src/test/java/com/example/dialogflow/UpdateAnswerRecordTest.java

Add sample code for updating answer record, which uses existing knowledge base created in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7486.

samples: add sample code for updating answer record

---

compute/cloud-client/src/test/java/compute/FirewallIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

test: add MultipleAttemptsRule to failing Compute tests

---

media/stitcher/pom.xml
media/stitcher/src/main/java/com/example/stitcher/CreateCdnKeyAkamai.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKey.java
media/stitcher/src/main/java/com/example/stitcher/UpdateCdnKeyAkamai.java
media/stitcher/src/test/java/com/example/stitcher/CreateCdnKeyAkamaiTest.java
media/stitcher/src/test/java/com/example/stitcher/CreateCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/DeleteCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/GetCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/ListCdnKeysTest.java
media/stitcher/src/test/java/com/example/stitcher/TestUtils.java
media/stitcher/src/test/java/com/example/stitcher/UpdateCdnKeyAkamaiTest.java
media/stitcher/src/test/java/com/example/stitcher/UpdateCdnKeyTest.java

feat: add Media CDN examples. Move Akamai samples to their own files.

---

functions/concepts/env-vars/pom.xml
functions/concepts/execution-count/pom.xml
functions/concepts/lazy-fields/pom.xml

Correct the names for a few cloud functions in POM.

fix function names in pom

---

iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/DeleteServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/DisableServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/EnableServiceAccountKey.java
iam/api-client/src/test/java/iam/snippets/ServiceAccountTests.java

Fixes #7521 #7522 #7523 #7524
The issue was due to an Assertion failure in key creation. It might be due to sysout being null. Hence, tried modifying it and also added an additional variable for key deletion to make sure the right key is being deleted.

docs(samples): fix service account key test issue

---

.github/CODEOWNERS

The Cloud Retail team is supporting the Retail samples. Updating CODEOWNERS to reflect that.
Fixes #issue

chore: Update ownership of Retail samples

---

media/livestream/src/test/java/com/example/livestream/CreateChannelEventTest.java
media/livestream/src/test/java/com/example/livestream/CreateChannelTest.java
media/livestream/src/test/java/com/example/livestream/CreateChannelWithBackupInputTest.java
media/livestream/src/test/java/com/example/livestream/CreateInputTest.java
media/livestream/src/test/java/com/example/livestream/DeleteChannelEventTest.java
media/livestream/src/test/java/com/example/livestream/DeleteChannelTest.java
media/livestream/src/test/java/com/example/livestream/DeleteInputTest.java
media/livestream/src/test/java/com/example/livestream/GetChannelEventTest.java
media/livestream/src/test/java/com/example/livestream/GetChannelTest.java
media/livestream/src/test/java/com/example/livestream/GetInputTest.java
media/livestream/src/test/java/com/example/livestream/ListChannelEventsTest.java
media/livestream/src/test/java/com/example/livestream/ListChannelsTest.java
media/livestream/src/test/java/com/example/livestream/ListInputsTest.java
media/livestream/src/test/java/com/example/livestream/StartChannelTest.java
media/livestream/src/test/java/com/example/livestream/StopChannelTest.java
media/livestream/src/test/java/com/example/livestream/UpdateChannelTest.java
media/livestream/src/test/java/com/example/livestream/UpdateInputTest.java

test: add retries to livestream tests

---

security-command-center/snippets/src/test/java/BigQueryExportIT.java

test: added uuid to bq dataset name for concurrency

---

spanner/changestreams/pom.xml
spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java

Add multiple attempts to Spanner ChangeStreams

---

aiplatform/src/test/java/aiplatform/CreateTrainingPipelineCustomJobSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineCustomTrainingManagedDatasetSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineImageClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineImageObjectDetectionSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTabularClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTabularRegressionSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextEntityExtractionSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextSentimentAnalysisSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineVideoActionRecognitionSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineVideoClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineVideoObjectTrackingSampleTest.java

test: add multiple attempts to aiplatform pipeline tests

---

run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java

Fix Cloud Run service cleanup for Filesystems

---

asset/src/test/java/com/example/asset/QuickStartIT.java

chore: increase timeout for flaky test

---

dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadApiWithIndex.java
dataflow/spanner-io/src/test/java/com/example/dataflow/SpannerReadIT.java

- [ N/A ] `pom.xml` parent set to latest `shared-configuration`
- [ N/A ] Appropriate changes to README are included in PR
- [ None ] API's need to be enabled to test (tell us)
- [ None ] Environment Variables need to be set (ask us to set them)
- [ X ] **Tests** pass:   `mvn clean verify` **required**
- [ X ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ X ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
-  ignoring USBR_UNNECESSARY_STORE_BEFORE_RETURN in new file for code sample.
- [ X ] Please **merge** this PR for me once it is approved.

Add sample code for Dataflow reading Spanner table with Index

---

document-ai/src/main/java/documentai/v1/BatchProcessDocument.java
document-ai/src/main/java/documentai/v1/ProcessDocument.java
document-ai/src/main/java/documentai/v1/QuickStart.java
document-ai/src/main/java/documentai/v1beta3/ProcessFormDocument.java
document-ai/src/main/java/documentai/v1beta3/ProcessOcrDocument.java
document-ai/src/main/java/documentai/v1beta3/ProcessQualityDocument.java
document-ai/src/main/java/documentai/v1beta3/ProcessSpecializedDocument.java
document-ai/src/main/java/documentai/v1beta3/ProcessSplitterDocument.java

Followup to https://stackoverflow.com/questions/70188610/google-documentai-java-example-fails-with-io-grpc-statusruntimeexception-invali

docs(samples): Added Endpoint to Document AI Samples

---

dataflow/spanner-io/src/main/java/com/example/dataflow/SpannerReadApiWithIndex.java

Comment was copy-pasted from Table read - corrected to refer to index read

Minor fix of comment text in SpannerReadApiWithIndex

---

spanner/changestreams/pom.xml
spanner/changestreams/src/test/java/com/example/spanner/changestreams/ChangeStreamSampleIT.java

Reverts GoogleCloudPlatform/java-docs-samples#7566

Revert "Add multiple attempts to Spanner ChangeStreams"

---

functions/v2/label-compute-instance/pom.xml
functions/v2/label-compute-instance/src/main/java/functions/AutoLabelInstance.java

chore: update compute API version for GCF sample

---

monitoring/v3/src/test/java/com/example/monitoring/AlertIT.java
monitoring/v3/src/test/java/com/example/monitoring/CreateAlertPolicyIT.java
monitoring/v3/src/test/java/com/example/monitoring/CreateMetricDescriptorIT.java
monitoring/v3/src/test/java/com/example/monitoring/DeleteAlertPolicyIT.java
monitoring/v3/src/test/java/com/example/monitoring/DeleteMetricDescriptorIT.java
monitoring/v3/src/test/java/com/example/monitoring/DeleteNotificationChannelIT.java
monitoring/v3/src/test/java/com/example/monitoring/EnableDisableAlertPolicyIT.java
monitoring/v3/src/test/java/com/example/monitoring/GetAlertPolicyIT.java
monitoring/v3/src/test/java/com/example/monitoring/GetMonitoredResourceIT.java
monitoring/v3/src/test/java/com/example/monitoring/ListAlertPolicyIT.java
monitoring/v3/src/test/java/com/example/monitoring/ListMetricDescriptorIT.java
monitoring/v3/src/test/java/com/example/monitoring/ListMonitoredResourcesIT.java
monitoring/v3/src/test/java/com/example/monitoring/QuickstartSampleIT.java
monitoring/v3/src/test/java/com/example/monitoring/TimeSeriesIT.java
monitoring/v3/src/test/java/com/example/monitoring/UpdateAlertPolicyIT.java
monitoring/v3/src/test/java/com/example/monitoring/UptimeIT.java

Fixes #7576
Fixes #7575
Fixes #7573

test: add retries to monitoring tests

---

auth/src/main/java/CreateApiKey.java
auth/src/main/java/DeleteApiKey.java
auth/src/main/java/LookupApiKey.java
auth/src/main/java/RestrictApiKeyAndroid.java
auth/src/main/java/RestrictApiKeyApi.java
auth/src/main/java/RestrictApiKeyHttp.java
auth/src/main/java/RestrictApiKeyIos.java
auth/src/main/java/RestrictApiKeyServer.java

Modifying the service part of the region tag to match the apikeys service.
Doc inclusions have been identified and will be updated post the PR merge.

docs(samples): modified region tag to match apikey service

---

.github/auto-label.yaml

chore: add dataflow to auto-label configuration

---

privateca/snippets/src/test/java/privateca/SnippetsIT.java

docs(privateca-samples): add MultipleAttemptsRule to retry service issue

---

appengine-java11/vertx-helloworld/pom.xml

chore: update vertx deps

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/BatchWriteStorage.java
dataflow/snippets/src/test/java/com/example/dataflow/BatchWriteStorageIT.java

Adds a snippet for a Dataflow doc in progress
Also adds a snippets dataflow/snippets subdirectory with POM file

docs(samples): Add Dataflow TextIO snippet

---

recaptcha_enterprise/demosite/docker-compose.yaml

This can be helpful such that files get created by the same user that is running docker.

Add an optional DOCKER_COMPOSE_USER environment variable. 

---

privateca/snippets/src/test/java/privateca/SnippetsIT.java
privateca/snippets/src/test/java/privateca/Util.java

Adding util to delete stale resource in JDST project.

docs(ca-samples): delete stale ca pool in test project

---

run/jobs/src/test/java/com/example/JobsIntegrationTests.java

fix: wait for service to be deleted

---

compute/cloud-client/src/main/java/compute/ChangeInstanceMachineType.java
compute/cloud-client/src/main/java/compute/disks/AttachDisk.java
compute/cloud-client/src/main/java/compute/disks/RegionalCreateFromSource.java
compute/cloud-client/src/main/java/compute/disks/ResizeDisk.java
compute/cloud-client/src/main/java/compute/disks/ResizeRegionalDisk.java
compute/cloud-client/src/test/java/compute/InstanceOperationsIT.java
compute/cloud-client/src/test/java/compute/Util.java
compute/cloud-client/src/test/java/compute/disks/DisksFromSourceIT.java
compute/cloud-client/src/test/java/compute/disks/DisksIT.java

Adding samples needed for [this page](https://cloud.google.com/compute/docs/disks/regional-persistent-disk).

docs(compute-samples): adding machine type update and regional disk samples

---

batch/snippets/src/test/java/BatchTemplateIT.java

fix: add MultipleAttemptsRule for Batch template creation

---

.github/CODEOWNERS

Add @GoogleCloudPlatform/recaptcha-customer-obsession-reviewers team as codeowners to reCAPTCHA demosite folder.

chore: update CODEOWNERS for recaptcha demosite

---

cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java

Description: Old region tags are replaced with product specific region tags. Please check b/272509882 for more details.
New Region tags were added using Pull Request: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7732/files
Fixes #issue

chore: cleanup un-wanted region tags

---

dlp/snippets/src/test/java/dlp/snippets/TestBase.java

test: add retries to dlp tests

---

jobs/v3/src/test/java/SampleTests.java
jobs/v4/src/test/java/CommuteSearchJobsTest.java
jobs/v4/src/test/java/CustomRankingSearchJobsTest.java
jobs/v4/src/test/java/HistogramSearchJobsTest.java
jobs/v4/src/test/java/JobSearchAutoCompleteJobTitleTest.java
jobs/v4/src/test/java/JobSearchCreateCompanyTest.java
jobs/v4/src/test/java/JobSearchCreateJobTest.java
jobs/v4/src/test/java/JobSearchCreateJobWithCustomAttrTest.java
jobs/v4/src/test/java/JobSearchCreateTenantTest.java
jobs/v4/src/test/java/JobSearchDeleteCompanyTest.java
jobs/v4/src/test/java/JobSearchDeleteJobTest.java
jobs/v4/src/test/java/JobSearchDeleteTenantTest.java
jobs/v4/src/test/java/JobSearchGetCompanyTest.java
jobs/v4/src/test/java/JobSearchGetJobTest.java
jobs/v4/src/test/java/JobSearchGetTenantTest.java
jobs/v4/src/test/java/JobSearchListCompaniesTest.java
jobs/v4/src/test/java/JobSearchListJobsTest.java
jobs/v4/src/test/java/JobSearchListTenantsTest.java

test: add retries to jobs tests

---

container-registry/container-analysis/src/test/java/com/example/containeranalysis/SamplesTest.java
container-registry/vulnerability-notification-function/src/test/java/com/example/containeranalysis/VulnerabilityFunctionTest.java

test: add retries to container-registry tests

---

recaptcha_enterprise/demosite/src/main/java/app/MainController.java
recaptcha_enterprise/demosite/src/main/java/recaptcha/CreateAssessment.java
recaptcha_enterprise/demosite/src/main/resources/config.properties
recaptcha_enterprise/demosite/src/main/resources/static/scripts/component.js
recaptcha_enterprise/demosite/src/main/resources/static/scripts/global.js
recaptcha_enterprise/demosite/src/main/resources/templates/comment.html
recaptcha_enterprise/demosite/src/main/resources/templates/home.html
recaptcha_enterprise/demosite/src/main/resources/templates/login.html
recaptcha_enterprise/demosite/src/main/resources/templates/signup.html
recaptcha_enterprise/demosite/src/main/resources/templates/store.html

Update control flow from the client to create_assessment call.
New flow: Client calls the respective post action method which inturn calls the create assessment.
Example: client -> on_signup -> create_assessment
Respective Python PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/9279

docs(demosite-recaptcha): update control flow from client

---

batch/snippets/src/test/java/BatchBucketIT.java

Unblocks PR: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7752

fix: Batch bucket issue fix

---

batch/snippets/src/test/java/BatchBasicIT.java
batch/snippets/src/test/java/BatchBucketIT.java
batch/snippets/src/test/java/BatchTemplateIT.java
batch/snippets/src/test/java/Util.java

Unblocks PR: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/7752
Fixes timeout issue with "MultipleAttemptsRule".
Fixes Job exists issue by moving the Job creation to setup, so that the job is created only once when the MultipleAttemptsRule runs.

fix: Batch issue fix

---

asset/src/main/java/com/example/asset/ExportAssetsExample.java

fix: add timeout to async request

---

bigtable/use-cases/fraudDetection/src/test/java/FraudDetectionTestUtil.java

docs: Fix bigtable fraud detection test output to be more comprehensive

---

appengine-java11/tasks/src/main/java/com/example/task/CreateTask.java
appengine-java11/tasks/src/test/java/com/example/task/CreateTaskIT.java

fix: make task arguments clear

---

media/stitcher/src/test/java/com/example/stitcher/CreateCdnKeyAkamaiTest.java
media/stitcher/src/test/java/com/example/stitcher/CreateCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/CreateLiveSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/CreateSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/CreateVodSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/DeleteCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/DeleteSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/GetCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/GetLiveAdTagDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/GetLiveSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/GetSlateTest.java
media/stitcher/src/test/java/com/example/stitcher/GetVodAdTagDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/GetVodSessionTest.java
media/stitcher/src/test/java/com/example/stitcher/GetVodStitchDetailTest.java
media/stitcher/src/test/java/com/example/stitcher/ListCdnKeysTest.java
media/stitcher/src/test/java/com/example/stitcher/ListLiveAdTagDetailsTest.java
media/stitcher/src/test/java/com/example/stitcher/ListSlatesTest.java
media/stitcher/src/test/java/com/example/stitcher/ListVodAdTagDetailsTest.java
media/stitcher/src/test/java/com/example/stitcher/ListVodStitchDetailsTest.java
media/stitcher/src/test/java/com/example/stitcher/UpdateCdnKeyAkamaiTest.java
media/stitcher/src/test/java/com/example/stitcher/UpdateCdnKeyTest.java
media/stitcher/src/test/java/com/example/stitcher/UpdateSlateTest.java

Ignore stitcher tests

---

dataflow/snippets/pom.xml
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadAvro.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadFromQuery.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadOptions.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadWithProjectionAndFiltering.java
dataflow/snippets/src/main/java/com/example/dataflow/BiqQueryReadTableRows.java
dataflow/snippets/src/test/java/com/example/dataflow/BiqQueryReadIT.java

Adds BigQuery I/O snippets for a Dataflow doc in progress

docs(samples): Add Dataflow BigQueryIO read snippets

---

speech/src/main/java/com/example/speech/QuickstartSampleV2.java
speech/src/main/java/com/example/speech/TranscribeFileV2.java

fix: update speech sample to check list count

---

.github/PULL_REQUEST_TEMPLATE.md

Updates to the PR Template before upcoming Fix-It based on python-docs-samples best practices.
Fixes b/275440694

chore: PR Template updates

---

.github/header-checker-lint.yml

chore: add linter for license header

---

.kokoro/tests/run_lint.sh
dlp/snippets/src/main/java/dlp/snippets/DeIdenitfyWithDeterministicEncryption.java

chore: debug lint

---

flexible/java-11/cloudstorage/src/main/appengine/app.yaml
flexible/java-11/static-files/src/main/webapp/index.html

Add region tags for two files.

Add region tags

---

.github/CODEOWNERS

@Shabirmean After starting CODEOWNERs audit I believe that your file is more applicable here. I won't be able to sort things out in such detailed way as you did in Java for all repos, so I suggest going back to using your doc for Java. Sorry for the confusion.

docs: update internal doc link

---

bigtable/hbase/snippets/src/main/java/com/example/bigtable/Filters.java
bigtable/hbase/snippets/src/test/java/com/example/bigtable/FiltersTest.java
bigtable/hbase/snippets/src/test/java/com/example/bigtable/ReadsTest.java

HBase layer tests should only use HBase surface and not the implementation details

test: avoid referencing veneer in HBase tests

---

.github/CODEOWNERS

Fixes [b/275440264](http://b/275440264)
Updates after a cross-repo audit in preparations for the upcoming FixIt.

chore: CODEOWNERS audit

---

run/jobs/README.md
run/jobs/src/test/java/com/example/JobsIntegrationTests.java
run/jobs/src/test/java/com/example/resources/e2e_test_cleanup.yaml
run/jobs/src/test/java/com/example/resources/e2e_test_setup.yaml

fix: delete Cloud Run Job resource after test

---

iot/api-client/manager/src/test/java/com/example/cloud/iot/examples/ManagerIT.java

The IOT samples are marked as deprecated. One of these samples failed the nightly build test. Recommend ignoring these and not investing any time into resolving this.

chore: skip iot/manager tests

---

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTextWithFpe.java

Updating the example to contain InfoType PHONE_NUMBER.
Fixes #7952

Updating example

---

.github/CODEOWNERS

chore: fix the teams for spanner and memorystore

---

workflows/cloud-client/pom.xml
workflows/cloud-client/src/main/java/com/example/workflows/WorkflowsQuickstart.java
workflows/cloud-client/src/test/java/com/example/workflows/WorkflowsQuickstartTest.java
workflows/cloud-client/src/test/java/com/example/workflows/resources/source.yaml

fix: update workflows quickstart

---

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableBucketing.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableConditionInfoTypes.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableConditionMasking.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableInfoTypes.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableRowSuppress.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyWithMasking.java

Adding main method to DeIdentifyTableBucketing.java, DeIdentifyTableConditionInfoTypes.java, DeIdentifyTableConditionMasking.java, DeIdentifyTableInfoTypes.java and DeIdentifyTableRowSuppress. 
Fixes #7936

Adding main method

---

pubsub/spring/README.md
pubsub/spring/build.gradle
pubsub/streaming-analytics/README.md
pubsub/streaming-analytics/build.gradle
pubsub/streaming-analytics/pom.xml
pubsub/streaming-analytics/src/main/java/com/examples/pubsub/streaming/PubSubToGcs.java

Minor cleanup:
* Removed unused dependencies
* Removed unused imports
* Updated dependencies
* Linted READMEs

chore: pubsub sample cleanup

---

.github/CODEOWNERS
.github/blunderbuss.yml

Update CODEOWNERs and Blunderbuss configuration for the asset team.

chore: update ownership for asset team

---

kms/src/main/java/kms/ConvertPublicKeyToJwk.java

Update the region tag.

---

appengine-java11/appengine-simple-jetty-main/README.md
appengine-java11/appengine-simple-jetty-main/pom.xml
appengine-java11/appengine-simple-jetty-main/src/main/java/com/example/appengine/jetty/Main.java
appengine-java11/cloudsql/app.yaml
appengine-java11/gaeinfo/src/main/appengine/app.yaml
appengine-java11/guestbook-cloud-firestore/pom.xml
appengine-java11/guestbook-cloud-firestore/src/main/appengine/app.yaml
appengine-java11/helloworld-servlet/README.md
appengine-java11/helloworld-servlet/pom.xml
appengine-java11/helloworld-servlet/src/main/appengine/app.yaml
appengine-java11/oauth2/pom.xml
appengine-java11/oauth2/src/main/appengine/app.yaml
appengine-java11/spanner/pom.xml
appengine-java11/spanner/src/main/appengine/app.yaml

fix: update package path for simple jetty server

---

aiplatform/src/main/java/aiplatform/ListModelEvaluationSliceSample.java

b/281693388 : Update region tag to match other languages.

chore: update region tag - listModelEvaluationSliceSample - aiplatform

---

iam/snippets/pom.xml
iam/snippets/src/main/java/CreateDenyPolicy.java
iam/snippets/src/main/java/CreateRole.java
iam/snippets/src/main/java/DeleteRole.java
iam/snippets/src/main/java/EditRole.java
iam/snippets/src/main/java/GetRole.java
iam/snippets/src/main/java/ListRoles.java
iam/snippets/src/main/java/QueryTestablePermissions.java
iam/snippets/src/main/java/UndeleteRole.java
iam/snippets/src/main/java/UpdateDenyPolicy.java
iam/snippets/src/test/java/DenyIT.java
iam/snippets/src/test/java/RoleIT.java

add 7 missing samples for https://cloud.google.com/iam/docs/creating-custom-roles
running `mvn com.coveo:fmt-maven-plugin:format` touched files in the `iam/` directory without me intending to change them

fixit: add 7 iam samples

---

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyWithExceptionList.java

Correction in DeIdentifyWithExceptionList class to follow exception rule in InspectConfig.
Fixes #7954

chore: correction in DeIdentifyWithExceptionList

---

monitoring/prometheus/README.md
monitoring/prometheus/pom.xml
monitoring/prometheus/src/main/java/com/example/prometheus/PrometheusApplication.java
monitoring/prometheus/src/main/resources/application.properties
monitoring/prometheus/src/test/java/com/example/prometheus/PrometheusApplicationTests.java

Region tags:
* `monitoring_sli_metrics_prometheus_setup`
* `monitoring_sli_metrics_prometheus_latency`
* `monitoring_sli_metrics_prometheus_counts`
* `monitoring_sli_metrics_prometheus_metrics_endpoint`
* `monitoring_sli_metrics_prometheus_create_metrics`
Doc page: https://cloud.google.com/stackdriver/docs/solutions/slo-monitoring/sli-metrics/prometheus

fixit: create new sample for Prometheus SLI

---

functions/v2/response-streaming/pom.xml
functions/v2/response-streaming/src/main/java/com/google/StreamBigQuery.java
functions/v2/response-streaming/src/test/java/com/google/StreamBigQueryTest.java

New sample for streaming responses in v2 functions in Java.

fixit: new sample for response streaming

---

appengine-java11/quarkus-helloworld/pom.xml
appengine-java11/quarkus-helloworld/src/main/java/com/example/appengine/quarkus/HelloResource.java

Updated javax.* packages to jakarta.* to migrate to v3.

fix(deps): update dependency io.quarkus:quarkus-bom to v3

---

renovate.json

Slow dependency updates to monthly for 2 frequently updated, but noncritical dependencies:
* com.amazonaws:*
* io.ktor:*

chore: slow down frequently updated dependencies

---

appengine-java8/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java
pubsublite/streaming-analytics/src/test/java/examples/PubsubliteToGcsIT.java

fix: update nightly failures

---

asset/src/main/java/com/example/asset/BatchGetEffectiveIamPolicyExample.java
asset/src/test/java/com/example/asset/BatchGetEffectiveIamPolicy.java
asset/src/test/java/com/example/asset/BatchGetEffectiveIamPolicyTest.java

BatchGetEffectiveIamPolicy was not moved from [googleapis/java-asset](https://github.com/googleapis/java-asset) to this repo, move to here manually. Here is the original PR - https://github.com/googleapis/java-asset/pull/1325

Add BatchGetEffectiveIamPolicy sample code

---

dialogflow/snippets/src/main/dialogflow/Example.java

related: b/281695703
identified that there are 2 samples in this repository with the same region tag 
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/4eccabd9f0dc1f783edf5caa1841fc3066650f16/dialogflow/basic-webhook/src/main/java/com/example/dialogflow/cx/BasicWebhook.java#L21-L75
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/234aa56b1398a24584234a619e1ac51fe7f2d29f/dialogflow/snippets/src/main/dialogflow/Example.java#L19-L72
Adding the _es_ for the one that works with diagflow es

fix: update to remove region tag conflict

---

asset/src/test/java/com/example/asset/AnalyzeIT.java
asset/src/test/java/com/example/asset/ListAssetsIT.java
asset/src/test/java/com/example/asset/RealTimeFeedIT.java
asset/src/test/java/com/example/asset/SearchIT.java

fix: update asset test filenames

---

appengine-java8/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java

fix: flaky GAE test

---

aiplatform/pom.xml
aiplatform/src/main/java/aiplatform/PredictChatPromptSample.java
aiplatform/src/test/java/aiplatform/PredictChatPromptSampleTest.java

Fixes b/281562687
Added chat prompt sample for Vertex Gen AI

feat: chat prompt sample for Vertex Gen AI

---

aiplatform/src/main/java/aiplatform/PredictTextClassificationSample.java
aiplatform/src/test/java/aiplatform/PredictTextClassificationSampleTest.java

Fixes # b/281562687
Added a text classification sample with large language models.

feat: text classification sample with large language models

---

.github/CODEOWNERS
content-warehouse/pom.xml
content-warehouse/src/main/java/contentwarehouse/v1/CreateRuleSet.java
content-warehouse/src/test/java/contentwarehouse/v1/CreateRuleSetTest.java

feat(content-warehouse): create ruleset sample

---

aiplatform/src/main/java/aiplatform/PredictTextExtractionSample.java
aiplatform/src/test/java/aiplatform/PredictTextExtractionSampleTest.java

Fixes #b/281562687
Added text extraction sample with large language models

feat: text extraction sample with large language models

---

.github/CODEOWNERS
.github/auto-label.yaml
.github/blunderbuss.yml
.github/header-checker-lint.yml

see b/285615555 for details
fixes #8015 
cc: @chasinandrew

chore: add contentwarehouse to self-service program

---

bigtable/beam/change-streams/README.md
bigtable/beam/change-streams/quickstart-data.csv

Add example dataset for bigtable cdc quickstart and fixed readme command to run

docs: bigtable cdc quickstart 

---

aiplatform/src/test/java/aiplatform/PredictChatPromptSampleTest.java
aiplatform/src/test/java/aiplatform/PredictCustomTrainedModelSampleTest.java
aiplatform/src/test/java/aiplatform/PredictImageClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/PredictImageObjectDetectionSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTabularClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTabularRegressionSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextClassificationSingleLabelSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextEntityExtractionSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextExtractionSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextSentimentAnalysisSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextSentimentSampleTest.java
aiplatform/src/test/java/aiplatform/PredictTextSummarizationSampleTest.java

chore: add retries to aiplatform prediction tests

---

bigtable/beam/change-streams/pom.xml
bigtable/beam/change-streams/src/main/java/ChangeStreamsHelloWorld.java

docs: add region tags for Bigtable cdc hello world

---

aiplatform/src/main/java/aiplatform/PredictCodeChatSample.java
aiplatform/src/main/java/aiplatform/PredictCodeCompletionCommentSample.java
aiplatform/src/main/java/aiplatform/PredictCodeCompletionTestFunctionSample.java
aiplatform/src/main/java/aiplatform/PredictCodeGenerationFunctionSample.java
aiplatform/src/main/java/aiplatform/PredictCodeGenerationUnitTestSample.java
aiplatform/src/test/java/aiplatform/PredictCodeChatSampleTest.java
aiplatform/src/test/java/aiplatform/PredictCodeCompletionCommentSampleTest.java
aiplatform/src/test/java/aiplatform/PredictCodeCompletionTestFunctionSampleTest.java
aiplatform/src/test/java/aiplatform/PredictCodeGenerationFunctionSampleTest.java
aiplatform/src/test/java/aiplatform/PredictCodeGenerationUnitTestSampleTest.java

Fixes b279595025
Add code samples for Vertex LLMs code models.

feat(aiplatform): experimental code samples for Codey API (draft)

---

appengine-java8/firebase-tictactoe/src/test/java/com/example/appengine/firetactoe/TicTacToeServletTest.java

chore: add more guards to flaky tictactoe test

---

dlp/snippets/src/main/java/dlp/snippets/DeIdentifyWithInfoType.java
dlp/snippets/src/main/java/dlp/snippets/InspectDataToHybridJobTrigger.java

chore(dlp): modified region tag for samples

---

dlp/snippets/src/main/java/dlp/snippets/DeIdenitfyWithDeterministicEncryption.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyDataReplaceWithDictionary.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyTableWithBucketingConfig.java
dlp/snippets/src/main/java/dlp/snippets/DeIdentifyWithTimeExtraction.java
dlp/snippets/src/main/java/dlp/snippets/DeidentifyFreeTextWithFpeUsingSurrogate.java
dlp/snippets/src/main/java/dlp/snippets/ReidentifyFreeTextWithFpeUsingSurrogate.java
dlp/snippets/src/main/java/dlp/snippets/ReidentifyWithDeterministicEncryption.java
dlp/snippets/src/test/java/dlp/snippets/DeIdentificationTests.java

[DLP] Cosmetic Changes

---

dlp/snippets/src/test/java/dlp/snippets/InspectTests.java
dlp/snippets/src/test/java/dlp/snippets/JobsTests.java
dlp/snippets/src/test/java/dlp/snippets/RiskAnalysisTests.java

[DLP] Implemented mock mechanism

---

discoveryengine/src/test/java/discoveryengine/v1beta/SearchTest.java

test: Add multiple attempts to Gen App Builder `SearchTest`

---

dialogflow-cx/pom.xml
dialogflow-cx/src/main/java/dialogflow/cx/DetectIntentStream.java

Fixes #8336 
Fixes #8337 
Also updates dependencies, and addresses warnings.

fix: dialogflow-cx speech parameter

---

cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java

No code changes. Updated the algorithm name in the comments.
Fixes [b/288979726](http://b/288979726)

docs: Update comments

---

functions/v2/typed/greeting/pom.xml
functions/v2/typed/greeting/src/main/java/functions/Greeting.java
functions/v2/typed/greeting/src/main/java/functions/GreetingRequest.java
functions/v2/typed/greeting/src/main/java/functions/GreetingResponse.java
functions/v2/typed/greeting/src/test/java/functions/GreetingTest.java

Creates new samples for GCF Java strongly typed function signature.
Do not merge this PR once approved, waiting on a release of functions framework java to publish.

feat(functions): create new sample for typed function signature

---

dlp/snippets/src/test/java/dlp/snippets/InspectTests.java

Taken care of the comment provided in the issue #8342

Remove Unused code

---

run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java

fix: delete container image after test

---

pubsublite/streaming-analytics/src/test/java/examples/PubsubliteToGcsIT.java

fix: add retries to pubsublite test

---

iam/api-client/src/main/java/iam/snippets/CreateServiceAccountKey.java
iam/api-client/src/main/java/iam/snippets/Quickstart.java
iam/api-client/src/main/java/iam/snippets/RemoveMember.java
iam/api-client/src/test/java/iam/snippets/QuickstartTests.java

chore: add null checks to IAM snippets

---

bigtable/beam/change-streams/README.md
bigtable/beam/change-streams/src/main/java/SongRank.java

docs: Bigtable cdc example cleanup

---

run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java

fix: update Cloud Run filesystem sample

---

dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadAvro.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryReadWithProjectionAndFiltering.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryStreamExactlyOnce.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryWrite.java
dataflow/snippets/src/main/java/com/example/dataflow/BigQueryWriteWithSchema.java
dataflow/snippets/src/main/java/com/example/dataflow/BiqQueryReadTableRows.java
dataflow/snippets/src/main/java/com/example/dataflow/ExamplePipelineOptions.java
dataflow/snippets/src/test/java/com/example/dataflow/BigQueryWriteIT.java

Adds BigQuery I/O snippets for a Dataflow doc in progress
@reuvenlax @johnjcasey  FYI

docs(samples): Add Dataflow BigQueryIO write snippets

---

.kokoro/tests/run_tests.sh
run/filesystem/src/test/java/com/example/filesystem/ApplicationTests.java

fix: don't throw error for test

---

dlp/snippets/src/test/java/dlp/snippets/InspectTests.java
dlp/snippets/src/test/java/dlp/snippets/RiskAnalysisTests.java

- Resolved flaky test cases with mock mechanism

[DLP] Mock flaky unit test cases

---

dlp/snippets/src/main/java/dlp/snippets/InspectDataToHybridJobTrigger.java

[DLP] Fixed the error of job activation

---

aiplatform/src/main/java/aiplatform/DeployModelSample.java
aiplatform/src/test/java/aiplatform/DeployModelSampleTest.java

Fixes b/281672516
Demonstrate how to set LRO timeout explicitly for model deployment operation.

fix(aiplatform): add LRO timeout explicitly for model deployment operations

---

aiplatform/src/main/java/aiplatform/CreatePipelineJobModelTuningSample.java
aiplatform/src/test/java/aiplatform/CreatePipelineJobModelTuningSampleTest.java

Fixes b/292073664
Update the Gen AI code samples to support the recent product changes:
- Pipeline version
- Default train step
- Supported regions

chore(aiplatform); Gen AI code samples update to support the recent product changes

---

speech/src/main/java/com/example/speech/AdaptationInlineCustomClassV2.java

fix: update speech class name

---

renovate.json

validation was moved into `io.micronaut.validation`
See https://micronaut-projects.github.io/micronaut-validation/snapshot/guide/index.html

Update renovate.json for micronaut breaking changes

---

compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceExternalIp.java
compute/cloud-client/src/main/java/compute/windows/windowsinstances/CreateWindowsServerInstanceInternalIp.java

chore(update): Windows version update to 2022

---

.github/blunderbuss.yml

chore: Add storage to blunderbuss.yml

---

functions/v2/hello-gcs/src/test/java/functions/HelloGcsTest.java

chore: adding in region tag for cloud storage v2 unit test docs

---

aiplatform/src/main/java/aiplatform/CreatePipelineJobCodeModelTuningSample.java
aiplatform/src/test/java/aiplatform/CreatePipelineJobCodeModelTuningSampleTest.java

Fixes b/293603470
Add a code sample to demonstrate how to create a code model tuning job.
Docs: https://cloud.google.com/vertex-ai/docs/generative-ai/models/tune-models#create_a_model_tuning_job

feat(aiplatform): add sample for Gen AI code model tuning

---

appengine-java11-bundled-services/datastore/pom.xml
appengine-java8/iap/pom.xml
appengine-java8/pubsub/pom.xml
cloud-sql/mysql/servlet/pom.xml
renovate.json
session-handling/pom.xml
unittests/pom.xml
vision/face-detection/pom.xml

chore: update renovate

---

document-ai/src/main/java/documentai/v1/BatchProcessDocument.java

- Reported in internal issue 297235066

docs(samples): Remove timeout seconds from Document AI Batch Sample

---

healthcare/v1/src/main/java/snippets/healthcare/hl7v2/Hl7v2StoreCreate.java

fix(healthcare): specify V3 parser version when creating HL7v2 store

---

.github/CODEOWNERS
.github/blunderbuss.yml

Update sample repo code owners to infra-db-sdk

chore: update code owners to infra-db-sdk

---

spanner/jdbc/src/main/java/com/example/spanner/jdbc/AutoPartitionModeExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/DataBoostExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/PartitionQueryExample.java
spanner/jdbc/src/main/java/com/example/spanner/jdbc/RunPartitionedQueryExample.java
spanner/jdbc/src/test/java/com/example/spanner/jdbc/JdbcExamplesIT.java

docs: sample for running Partitioned Queries using Spanner JDBC

---

document-ai/src/test/java/documentai/v1beta3/ProcessOcrDocumentTest.java

Fix flaky issue #8593

---

errorreporting/src/main/java/com/example/errorreporting/QuickStart.java

align code sample for error reporting with code in other languages (b/275730159):
- demonstrate the use of Error Reporting for reporting exceptions
- use the "fixed" error message
- delegate error context processing to Error Reporting backend

fix: refactor error reporting code sample

---

asset/src/test/java/com/example/asset/SearchIT.java

Increasing wait time to 120 seconds, to allow resources to be created.

chore(asset): increase wait time in tests

---

aiplatform/src/main/java/aiplatform/PredictCodeCompletionCommentSample.java
aiplatform/src/main/java/aiplatform/PredictCodeCompletionTestFunctionSample.java
aiplatform/src/main/java/aiplatform/PredictCodeGenerationFunctionSample.java
aiplatform/src/main/java/aiplatform/PredictCodeGenerationUnitTestSample.java

Vertex AI product name changes:
Code Generation > Codey for Code Generation
Code Completion > Codey for Code Completion

chore(aiplatform): Vertex AI product name changes

---

content-warehouse/src/main/java/contentwarehouse/v1/UpdateDocument.java

adding region tag for update document

---

.github/header-checker-lint.yml
.github/sync-repo-settings.yaml

remove Java8 from the list of required checks (related to #8935)
remove yoshi-admin from admins

chore(proc): update repo's settings

---

vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

Use gemini-pro instead of gemini-pro-vision in chat

---

.github/sync-repo-settings.yaml

Modify the repo settings to enforce header-check on every submitted change.

chore(proc): make header check required

---

.github/flakybot.yaml

Per agreement in DEE Leads couple months back.

Set default priority of flaky bot issues to P2

---

opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/MultiController.java
opentelemetry/spring-boot-instrumentation/src/main/java/com/example/demo/SingleController.java

fix(opentelemetry): update method names of sprring controllers to match the javadoc

---

Makefile

a variable can be defined, and still have an empty string value.

fix(Makefile): use string value checks instead of ifndef

---

.kokoro/java11/periodic.cfg
.kokoro/java17/periodic.cfg

Restoring periodic runs of Java 11 and 17.

chore: restore periodic configs in Java 11 and 17

---

vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
vertexai/snippets/src/main/java/vertexai/gemini/FunctionCalling.java
vertexai/snippets/src/main/java/vertexai/gemini/GetTokenCount.java
vertexai/snippets/src/main/java/vertexai/gemini/MultiTurnMultimodal.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalMultiImage.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalQuery.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalVideoInput.java
vertexai/snippets/src/main/java/vertexai/gemini/QuestionAnswer.java
vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
vertexai/snippets/src/main/java/vertexai/gemini/StreamingQuestionAnswer.java
vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

Update Gemini model names to the GA version:
gemini-pro > gemini-1.0-pro
gemini-pro-vision > gemini-1.0-pro-vision

fix(vertexai): update Gemini model names

---

appengine-java8/datastore/src/test/java/com/example/appengine/EntitiesTest.java

chore: remove old region tag that causes sample to show up for batch

---

security-command-center/snippets/src/main/java/vtwo/iam/GetIamPolicies.java
security-command-center/snippets/src/main/java/vtwo/iam/SetIamPolices.java
security-command-center/snippets/src/main/java/vtwo/iam/TestIamPermissions.java
security-command-center/snippets/src/test/java/vtwo/IamIT.java

Fixes # https://buganizer.corp.google.com/issues/333914958

feat: Adding API v2 IAM samples

---

asset/src/test/java/com/example/asset/RealTimeFeedIT.java

unignore test class, added try with resources
Fixes #8963

assets.RealTimeFeedIT tests are failing

---

vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
vertexai/snippets/src/main/java/vertexai/gemini/FunctionCalling.java
vertexai/snippets/src/main/java/vertexai/gemini/GetTokenCount.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalMultiImage.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalQuery.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalVideoInput.java
vertexai/snippets/src/main/java/vertexai/gemini/QuestionAnswer.java
vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
vertexai/snippets/src/main/java/vertexai/gemini/StreamingQuestionAnswer.java
vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

Update Gemini code samples to stable model versions:
gemini-1.0-pro -> gemini-1.0-pro-002
gemini-1.0-pro-vision -> gemini-1.0-pro-vision-001

Update Gemini model versions

---

security-command-center/snippets/src/main/java/vtwo/marks/AddMarkToFinding.java
security-command-center/snippets/src/main/java/vtwo/marks/DeleteAndUpdateMarks.java
security-command-center/snippets/src/main/java/vtwo/marks/DeleteMarks.java
security-command-center/snippets/src/main/java/vtwo/marks/ListFindingMarksWithFilter.java
security-command-center/snippets/src/test/java/vtwo/SecurityMarkIT.java

feat: Adding API v2 Marks samples

---

vertexai/snippets/src/main/java/vertexai/gemini/TextInput.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

feat: update text-only input sample to use a generic review

---

vertexai/snippets/src/main/java/vertexai/gemini/TextInput.java

Joint String output variable declaration and use in Vertex AI TextInput.java Snippet

---

vertexai/snippets/src/main/java/vertexai/gemini/QuestionAnswer.java

add region tag for QuestionAnswer.java

---

compute/cloud-client/src/main/java/compute/routes/CreateRoute.java
compute/cloud-client/src/main/java/compute/routes/DeleteRoute.java
compute/cloud-client/src/main/java/compute/routes/ListRoute.java
compute/cloud-client/src/test/java/compute/routes/RoutesIT.java

refactor(compute): create Route samples

---

compute/cloud-client/src/main/java/compute/CreateInstanceBulkInsert.java
compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java

implemented sample : compute_instances_bulk_insert

refactor(compute): create Instance bulk insert sample

---

.kokoro/tests/run_prptst_tests.sh

add debug info about operational locations to troubleshoot script failure. remove enclosing quotes from 'dir' parameter for call to 'make'.

chore(proc): add debug info

---

.kokoro/tests/run_prptst_tests.sh

Remove validation instructions that cause to Kokoro job to fail.

chore(proc): clean up test prptst script

---

.kokoro/tests/run_prptst_tests.sh

Set up GOOGLE_CLOUD_UNIVERSE_DOMAIN variable to declare prptst universe domain.
Remove debug output from script.

chore(proc): add universe domain envar

---

managedkafka/examples/pom.xml
managedkafka/examples/src/main/java/examples/CreateCluster.java
managedkafka/examples/src/main/java/examples/CreateTopic.java
managedkafka/examples/src/main/java/examples/DeleteCluster.java
managedkafka/examples/src/main/java/examples/DeleteConsumerGroup.java
managedkafka/examples/src/main/java/examples/DeleteTopic.java
managedkafka/examples/src/main/java/examples/GetCluster.java
managedkafka/examples/src/main/java/examples/GetConsumerGroup.java
managedkafka/examples/src/main/java/examples/GetTopic.java
managedkafka/examples/src/main/java/examples/ListClusters.java
managedkafka/examples/src/main/java/examples/ListConsumerGroups.java
managedkafka/examples/src/main/java/examples/ListTopics.java
managedkafka/examples/src/main/java/examples/UpdateCluster.java
managedkafka/examples/src/main/java/examples/UpdateConsumerGroup.java
managedkafka/examples/src/main/java/examples/UpdateTopic.java
managedkafka/examples/src/test/java/examples/ClustersTest.java
managedkafka/examples/src/test/java/examples/ConsumerGroupsTest.java
managedkafka/examples/src/test/java/examples/MockDeleteOperationFuture.java
managedkafka/examples/src/test/java/examples/MockOperationFuture.java
managedkafka/examples/src/test/java/examples/TopicsTest.java

feat(managedkafka): code samples

---

security-command-center/snippets/pom.xml
security-command-center/snippets/src/main/java/vtwo/bigquery/CreateBigQueryExport.java
security-command-center/snippets/src/main/java/vtwo/bigquery/DeleteBigQueryExport.java
security-command-center/snippets/src/main/java/vtwo/bigquery/GetBigQueryExport.java
security-command-center/snippets/src/main/java/vtwo/bigquery/ListBigQueryExports.java
security-command-center/snippets/src/main/java/vtwo/bigquery/UpdateBigQueryExport.java
security-command-center/snippets/src/test/java/vtwo/BigQueryExportIT.java

feat: Adding API v2 Bigquery export samples

---

compute/cloud-client/pom.xml
compute/cloud-client/src/test/java/compute/InstanceOperationsIT.java
compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
compute/cloud-client/src/test/java/compute/InstancesAdvancedIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java
compute/cloud-client/src/test/java/compute/customhostname/CustomHostnameInstanceIT.java
compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java
compute/cloud-client/src/test/java/compute/deleteprotection/DeleteProtectionIT.java
compute/cloud-client/src/test/java/compute/disks/DisksIT.java
compute/cloud-client/src/test/java/compute/preemptible/PreemptibleIT.java
compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java

Upgrade libraries-bom to the latest version in order to have universe domain support in Cloud SDK.

chore: upgrade bom to latest

---

vertexai/snippets/src/main/java/vertexai/gemini/ChatDiscussion.java
vertexai/snippets/src/main/java/vertexai/gemini/FunctionCalling.java
vertexai/snippets/src/main/java/vertexai/gemini/GetTokenCount.java
vertexai/snippets/src/main/java/vertexai/gemini/MultiTurnMultimodal.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalMultiImage.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalQuery.java
vertexai/snippets/src/main/java/vertexai/gemini/MultimodalVideoInput.java
vertexai/snippets/src/main/java/vertexai/gemini/Quickstart.java
vertexai/snippets/src/main/java/vertexai/gemini/SingleTurnMultimodal.java
vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

feat: update samples to Gemini Flash; add updated region tags

---

.kokoro/tests/run_prptst_tests.sh

refactor setup instructions to hide tpc configuration details and remove debug lines.

chore(proc): refactor running tests in tpc

---

jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java

fix(jobs): migrate to valid region tag job_discovery_commute_search

---

jobs/v3/src/main/java/com/google/samples/BasicJobSample.java

add job_get_job region tag

---

iap/pom.xml

fix(iap): delete invalid and unused region_tags

---

dataflow/templates/src/main/java/com/example/dataflow/templates/WordCount.java

Internal:
- b/347352003
- b/347352001
- b/347352332
- b/347351982

fixit: remove unused dataflow region tags

---

batch/snippets/src/main/java/com/example/batch/CreateBatchCustomEvent.java
batch/snippets/src/test/java/com/example/batch/CreateResourcesIT.java

refactor(batch): create Batch Custom Event sample

---

jobs/v3/src/main/java/com/google/samples/JobServiceQuickstart.java

Add new region tag as part of migration (quickstart -> job_search_quick_start_python)
Internal: b/347826158

Chore: Update region tag for JobServiceQuickstart.java

---

jobs/v3/src/main/java/com/google/samples/CommuteSearchSample.java

fix: removed old region tag

---

jobs/v3/src/main/java/com/google/samples/BasicJobSample.java

chore: remove get_job region tag from BasicJobSample.java

---

spanner/opentelemetry_traces/Readme.md
spanner/opentelemetry_traces/pom.xml
spanner/opentelemetry_traces/src/main/java/com/example/spanner/OpenTelemetryUsage.java

Adds a sample to configure client traces with OpenTelemetry and OTLP

feat(spanner): New Sample for OpenTelemetry Traces

---

compute/cloud-client/src/main/java/compute/ipaddress/GetStaticIpAddress.java

docs(compute): Renaming a region tag to match other langs

---

batch/snippets/src/main/java/com/example/batch/CreateBatchCustomNetwork.java
batch/snippets/src/test/java/com/example/batch/CreateResourcesIT.java

feat(batch): add Batch create custom network sample

---

batch/snippets/src/main/java/com/example/batch/CreateGpuJobN1.java
batch/snippets/src/main/java/com/example/batch/CreateLocalSsdJob.java
batch/snippets/src/test/java/com/example/batch/CreateResourcesIT.java

Fixes b/352408456
Making the code samples match the ones in Python repo.

feat(batch): Adding new Batch GPU sample

---

batch/snippets/src/main/java/com/example/batch/CreateBatchRunnableLabel.java
batch/snippets/src/main/java/com/example/batch/CreateBatchRunnableLable.java
batch/snippets/src/test/java/com/example/batch/CreateResourcesIT.java

feat(batch): add Batch labels runnable sample

---

secretmanager/pom.xml
secretmanager/src/main/java/secretmanager/CreateSecretWithLabels.java
secretmanager/src/main/java/secretmanager/CreateUpdateSecretLabel.java
secretmanager/src/main/java/secretmanager/DeleteSecretLabel.java
secretmanager/src/main/java/secretmanager/ViewSecretLabels.java
secretmanager/src/test/java/secretmanager/SnippetsIT.java

feat: added labels samples for secret manager

---

compute/cloud-client/src/main/java/compute/CreateInstanceFromTemplateWithOverrides.java
compute/cloud-client/src/main/java/compute/CreateInstanceTemplate.java
compute/cloud-client/src/main/java/compute/CreateInstancesAdvanced.java
compute/cloud-client/src/main/java/compute/CreateWithLocalSsd.java
compute/cloud-client/src/test/java/compute/InstanceOperationsIT.java
compute/cloud-client/src/test/java/compute/InstanceTemplatesIT.java
compute/cloud-client/src/test/java/compute/SnippetsIT.java
compute/cloud-client/src/test/java/compute/customhostname/CustomHostnameInstanceIT.java
compute/cloud-client/src/test/java/compute/custommachinetype/CustomMachineTypeIT.java
compute/cloud-client/src/test/java/compute/deleteprotection/DeleteProtectionIT.java
compute/cloud-client/src/test/java/compute/disks/DisksFromSourceIT.java
compute/cloud-client/src/test/java/compute/disks/DisksIT.java
compute/cloud-client/src/test/java/compute/preemptible/PreemptibleIT.java
compute/cloud-client/src/test/java/compute/windows/osimage/WindowsOsImageIT.java

fix: Multiple tests in compute/cloud client fail

---

vertexai/snippets/src/main/java/vertexai/gemini/StreamingQuestionAnswer.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

fix: generativeaionvertexai_stream_text_basic

---

aiplatform/src/main/java/aiplatform/imagen/GenerateImageSample.java
aiplatform/src/test/java/aiplatform/imagen/GenerateImageSampleTest.java

feat(aiplatform): add initial Imagen code sample and test

---

jobs/v3/src/main/java/com/google/samples/CustomAttributeSample.java

fix(jobs): updating region_tag with product prefix

---

dlp/snippets/src/main/java/dlp/snippets/InspectStringRep.java
dlp/snippets/src/test/java/dlp/snippets/InspectTests.java

Add regional endpoints code samples

---

vertexai/snippets/src/main/java/vertexai/gemini/WithSafetySettings.java

fix: generativeaionvertexai_gemini_safety_settings

---

aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSamplePreview.java
aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java

fix: Elastic Text-Embedding demo.

---

recaptcha_enterprise/snippets/src/main/java/recaptcha/CreateAssessment.java

Updating docs around sending user_ip_address, useragent, and Ja3 via createAssessment request.

refactor(recaptcha): update CreateAssessment sample

---

healthcare/v1/src/main/java/snippets/healthcare/fhir/FhirStorePatch.java
healthcare/v1/src/test/java/snippets/healthcare/FhirStoreTests.java

fix: update deprecated notificationconfig for healthcare api

---

vertexai/snippets/src/main/java/vertexai/gemini/GeminiTranslate.java
vertexai/snippets/src/test/java/vertexai/gemini/SnippetsIT.java

Recommended tag for using Gemini to translate - aiplatform_gemini_translate  

feat(vertexai): add aiplatform gemini translate sample

---

aiplatform/src/main/java/aiplatform/imagen/EditImageMaskFreeSample.java
aiplatform/src/test/java/aiplatform/imagen/EditImageMaskFreeSampleTest.java

Sample and test originally added in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9442

fix(aiplatform): add back accidentally removed Imagen sample and test

---

.kokoro/tests/build_cloud_functions.sh
.kokoro/tests/build_cloud_run.sh
.kokoro/tests/teardown_cloud_functions.sh
appengine-java8/firebase-backend/README.md
appengine-java8/firebase-backend/src/main/webapp/WEB-INF/appengine-web.xml
bigtable/scheduled-backups/scripts/scheduled_backups.sh
datacatalog/quickstart/pom.xml
dataflow/snippets/pom.xml
endpoints/getting-started/k8s/esp_echo_http.yaml
monitoring/v3/pom.xml
retail/interactive-tutorials/user_environment_setup.sh
retail/interactive-tutorials/user_import_data_to_catalog.sh
spanner/changestreams/pom.xml
texttospeech/beta/pom.xml

chore(oss): correct apache license headers

---

CONTRIBUTING.md

Update to the readme that removes old reference to community. fixes #9540

fix: remove archived repository

---

secretmanager/src/main/java/secretmanager/CreateSecretWithAnnotations.java
secretmanager/src/main/java/secretmanager/EditSecretAnnotations.java
secretmanager/src/main/java/secretmanager/ViewSecretAnnotations.java
secretmanager/src/test/java/secretmanager/SnippetsIT.java

feat(secretmanager): added samples for annotations

---

aiplatform/src/main/java/aiplatform/EmbeddingBatchSample.java
aiplatform/src/test/java/aiplatform/CreateTrainingPipelineTextClassificationSampleTest.java
aiplatform/src/test/java/aiplatform/EmbeddingBatchSampleTest.java

Python sample - https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/generative_ai/embeddings/batch_example.py

feat(aiplatform): add generativeaionvertexai embedding batch sample

---

dataplex/snippets/src/main/java/dataplex/CreateAspectType.java
dataplex/snippets/src/main/java/dataplex/DeleteAspectType.java
dataplex/snippets/src/main/java/dataplex/GetAspectType.java
dataplex/snippets/src/main/java/dataplex/ListAspectTypes.java
dataplex/snippets/src/main/java/dataplex/UpdateAspectType.java
dataplex/snippets/src/test/java/dataplex/AspectTypeIT.java

feat(dataplex): adjust code samples for Aspect Type

---

compute/cloud-client/src/main/java/compute/reservation/CreateReservation.java
compute/cloud-client/src/main/java/compute/reservation/DeleteReservation.java
compute/cloud-client/src/test/java/compute/Util.java
compute/cloud-client/src/test/java/compute/disks/HyperdisksIT.java
compute/cloud-client/src/test/java/compute/reservation/CrudOperationsReservationIT.java
compute/cloud-client/src/test/java/compute/reservation/ReservationIT.java

Fixing pipeline tests new

---

appengine-java21/helloworld/README.md
appengine-java21/helloworld/src/main/java/com/example/appengine/java21/HelloAppEngine.java
appengine-java21/helloworld/src/test/java/com/example/appengine/java21/HelloAppEngineTest.java

Follow up to https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9432

fix: remove unused method from testing (appengine jdk 21 sample)

---

security-command-center/snippets/src/main/java/vtwo/notifications/DeleteNotification.java
security-command-center/snippets/src/main/java/vtwo/notifications/ListNotification.java
security-command-center/snippets/src/test/java/vtwo/NotificationIT.java

Fixes #9542
- [] **Tests** pass:   `mvn clean verify` **required**

[SCC] Fix list notification configs test.

---

secretmanager/src/main/java/secretmanager/regionalsamples/CreateRegionalSecretWithAnnotations.java
secretmanager/src/main/java/secretmanager/regionalsamples/EditRegionalSecretAnnotations.java
secretmanager/src/main/java/secretmanager/regionalsamples/ViewRegionalSecretAnnotations.java
secretmanager/src/test/java/secretmanager/regionalsamples/SnippetsIT.java

feat: add samples for annotations, regional SM

---

dataplex/snippets/src/main/java/dataplex/CreateEntry.java
dataplex/snippets/src/main/java/dataplex/DeleteEntry.java
dataplex/snippets/src/main/java/dataplex/GetEntry.java
dataplex/snippets/src/main/java/dataplex/ListEntries.java
dataplex/snippets/src/main/java/dataplex/LookupEntry.java
dataplex/snippets/src/main/java/dataplex/UpdateEntry.java
dataplex/snippets/src/test/java/dataplex/EntryIT.java

feat(dataplex): add code samples for Entry

---

cdn/signed-urls/src/main/java/com/google/cdn/SignedUrls.java

Move region tag to clarify that static methods are called from the same class

---

dataplex/snippets/src/main/java/dataplex/CreateAspectType.java
dataplex/snippets/src/main/java/dataplex/CreateEntryGroup.java
dataplex/snippets/src/main/java/dataplex/CreateEntryType.java
dataplex/snippets/src/main/java/dataplex/DeleteAspectType.java
dataplex/snippets/src/main/java/dataplex/DeleteEntryGroup.java
dataplex/snippets/src/main/java/dataplex/DeleteEntryType.java
dataplex/snippets/src/main/java/dataplex/GetAspectType.java
dataplex/snippets/src/main/java/dataplex/GetEntryGroup.java
dataplex/snippets/src/main/java/dataplex/GetEntryType.java
dataplex/snippets/src/main/java/dataplex/ListAspectTypes.java
dataplex/snippets/src/main/java/dataplex/ListEntryGroups.java
dataplex/snippets/src/main/java/dataplex/ListEntryTypes.java
dataplex/snippets/src/main/java/dataplex/UpdateAspectType.java
dataplex/snippets/src/main/java/dataplex/UpdateEntryGroup.java
dataplex/snippets/src/main/java/dataplex/UpdateEntryType.java
dataplex/snippets/src/test/java/dataplex/AspectTypeIT.java
dataplex/snippets/src/test/java/dataplex/EntryGroupIT.java
dataplex/snippets/src/test/java/dataplex/EntryTypeIT.java

feat(dataplex): adjust code snippets

---

dataplex/snippets/src/main/java/dataplex/CreateEntry.java
dataplex/snippets/src/main/java/dataplex/DeleteEntry.java
dataplex/snippets/src/main/java/dataplex/GetEntry.java
dataplex/snippets/src/main/java/dataplex/ListEntries.java
dataplex/snippets/src/main/java/dataplex/LookupEntry.java
dataplex/snippets/src/main/java/dataplex/UpdateEntry.java

feat(dataplex): link documentation for available locations

---

functions/README.md

Update README.md to reflect CRf rebrand

---

bigtable/bigtable-proxy/.gitignore
bigtable/bigtable-proxy/pom.xml
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/Main.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/package-info.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/package-info.java
bigtable/bigtable-proxy/src/main/resources/logback.xml

Stacked PRs:
* #9695
* #9692
* #9691
* #9690
* #9689
* __->__#9688
--- --- ---

chore: add basic foundation: logging, testing, cli parsing

---

bigtable/bigtable-proxy/pom.xml
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/Main.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Endpoint.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Serve.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/ByteMarshaller.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallProxy.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/ProxyHandler.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/Registry.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/EndpointTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeParsingTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/utils/ContextSubject.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/utils/MetadataSubject.java

Stacked PRs:
* #9695
* #9692
* #9691
* #9690
* __->__#9689
* #9688
--- --- ---

feat: add basic proxy

---

bigtable/bigtable-proxy/pom.xml
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Serve.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/ProxyHandler.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/utils/MetadataSubject.java

Stacked PRs:
* #9695
* #9692
* #9691
* __->__#9690
* #9689
* #9688
--- --- ---

feat: move credential handling responsibility to the proxy

---

bigtable/bigtable-proxy/pom.xml
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Serve.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallProxy.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/ProxyHandler.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/CallLabels.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/InstrumentedCallCredentials.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Metrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/NoopMetrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Tracer.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeMetricsTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeParsingTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/metrics/CallLabelsTest.java

Stacked PRs:
* #9695
* #9692
* __->__#9691
* #9690
* #9689
* #9688
--- --- ---

feat: add metrics

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/ChannelFactory.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/ChannelPool.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/ChannelPoolSettings.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/ResourceCollector.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Serve.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/CallLabels.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Metrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/NoopMetrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Tracer.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/channelpool/ChannelPoolTest.java

Stacked PRs:
* #9695
* __->__#9692
* #9691
* #9690
* #9689
* #9688
--- --- ---

feat: add channel pooling

---

bigtable/bigtable-proxy/README.md
bigtable/bigtable-proxy/pom.xml
bigtable/bigtable-proxy/src/main/assembly/assembly.xml
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/Main.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Serve.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/main/scripts/bigtable-proxy.sh

Stacked PRs:
* __->__#9695
* #9692
* #9691
* #9690
* #9689
* #9688
--- --- ---
Also:
* fix metric name

docs: packaging & docs

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java

fix: fix channel priming by adding missing halfClose()

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java

fix PingAndWarm request params

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/commands/Verify.java

fix: bigtable-proxy verify command metric checks

---

dataplex/quickstart/src/main/java/dataplex/Quickstart.java
dataplex/quickstart/src/test/java/dataplex/QuickstartIT.java

feat(dataplex): Fix dataplex quickstart flaky execution

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallLabels.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/commands/ServeMetricsTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/core/CallLabelsTest.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImplTest.java

NOTE: this depends on and includes #9748

chore: support the rest of RLS headers for priming

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java

NOTE: this depends on and includes https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9752

feat: bigtable-proxy add gfe debug headers

---

bigtable/bigtable-proxy/README.md
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/channelpool/DataChannel.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Metrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/metrics/NoopMetrics.java

NOTE: this depends on and includes https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9754

feat: add channel state transition counter

---

bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java

NOTE: this depends on and includes https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9755

chore: record sub-ms latency measurements

---

bigtable/bigtable-proxy/README.md
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/core/CallProxy.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Metrics.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/MetricsImpl.java
bigtable/bigtable-proxy/src/main/java/com/google/cloud/bigtable/examples/proxy/metrics/Tracer.java
bigtable/bigtable-proxy/src/test/java/com/google/cloud/bigtable/examples/proxy/metrics/NoopMetrics.java

NOTE: this depends on and includes https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9789

feat: add downstream write latency to bigtableproxy

---

language/snippets/pom.xml

chore(language): delete sample language_install_with_bom

---

appengine-java8/datastore/src/test/java/com/example/appengine/QueriesTest.java

chore(gae): delete sample gae_java8_datastore_interface_2

---

jobs/v3/src/main/java/com/google/samples/LocationSearchSample.java

Fixes 
[b/347826159](b/347826159)
basic_location_search -> job_basic_location_search 
[b/347826166](b/347826166)
keyword_location_search -> job_keyword_location_search
[b/347826161](b/347826161)
city_location_search -> job_city_location_search
[b/347826174](b/347826174)
multi_locations_search -> job_multi_locations_search
[b/347826316](b/347826316)
broadening_location_search -> job_broadening_location_search

chore(job): migrate regions by associating them with an official product with a job_ prefix

---

endpoints/multiple-versions/openapi-v1.yaml
endpoints/multiple-versions/openapi-v2.yaml

Fixes Internal:
b/347825690
b/347826156

chore(endpoints): delete region 'swagger' in endpoints/multiple-versions

---

jobs/v3/src/main/java/com/google/samples/AutoCompleteSample.java

Fixes
Internal 
b/389974338
b/390012704

chore(job): migrate region tag to include product prefix

---

compute/mailjet/src/main/java/com/example/compute/mailjet/MailjetSender.java

Add product prefix and a more descriptive name
Internal
b/390238528
b/390245420

chore(job): migrate region tag

---

compute/sendgrid/pom.xml
compute/sendgrid/src/main/java/com/example/compute/sendgrid/SendEmailServlet.java

Delete old region tag "dependencies"
Fixes [b/386956670](https://b.corp.google.com/issues/386956670)

fix(compute): delete old region tag

---

compute/cloud-client/src/test/java/compute/reservation/CrudOperationsReservationIT.java

fix(compute): ignore reservation ITs

---

compute/mailjet/src/main/java/com/example/compute/mailjet/MailjetSender.java

chore(compute): remove old region tag

---

compute/error-reporting/pom.xml
compute/error-reporting/src/main/java/com/example/compute/errorreporting/ExceptionUtil.java

Internal
b/347825209
b/347825167

chore(compute): add new region tags for migration

---

jobs/v3/src/main/java/com/google/samples/HistogramSample.java

chore(job): delete old unused region tag after migration

---

endpoints/getting-started/openapi-appengine.yaml

chore(endpoints): step 1 add new region tag

---

compute/cmdline/src/main/java/ComputeEngineSample.java

Internal
b/347824910
b/347825073

chore(compute): add new region tags

---

functions/pubsub/publish-message/src/main/java/functions/PublishMessage.java
functions/pubsub/publish-message/src/test/java/functions/PublishMessageTest.java

fix(functions): add code to shutdown publisher to free up resources

---

.github/CODEOWNERS
.github/blunderbuss.yml

feat(parametermanager): created folder to add samples

---

.github/CODEOWNERS
.github/blunderbuss.yml

Replace outdated cloud-storage-dpe group

chore: set gcs-sdk-team as CODEOWNERS

---

parametermanager/pom.xml
parametermanager/src/main/java/parametermanager/CreateParam.java
parametermanager/src/main/java/parametermanager/CreateParamVersion.java
parametermanager/src/main/java/parametermanager/CreateParamVersionWithSecret.java
parametermanager/src/main/java/parametermanager/CreateStructuredParam.java
parametermanager/src/main/java/parametermanager/CreateStructuredParamVersion.java
parametermanager/src/test/java/parametermanager/SnippetsIT.java

Created samples for creating parameter and parameter version using Parameter Manager SDK
**Sample List (global):**
1. [parameter-structured-data](https://cloud.google.com/secret-manager/parameter-manager/docs/create-parameter#parameter-structured-data)
2. [parameter-unstructured-data](https://cloud.google.com/secret-manager/parameter-manager/docs/create-parameter#parameter-unstructured-data)
3. [add-parameter-version](https://cloud.google.com/secret-manager/parameter-manager/docs/add-parameter-version#add-parameter-version) (structured, unstructured)
4. [create-parameter-secret-reference](https://cloud.google.com/secret-manager/parameter-manager/docs/reference-secrets-in-parameter#create-parameter-secret-reference)
Added required Tests for the same.

feat(parametermanager): Added samples for creating parameter and versions

---

parametermanager/pom.xml
parametermanager/src/main/java/parametermanager/regionalsamples/DeleteRegionalParam.java
parametermanager/src/main/java/parametermanager/regionalsamples/DeleteRegionalParamVersion.java
parametermanager/src/main/java/parametermanager/regionalsamples/DisableRegionalParamVersion.java
parametermanager/src/main/java/parametermanager/regionalsamples/EnableRegionalParamVersion.java
parametermanager/src/test/java/parametermanager/regionalsamples/SnippetsIT.java

Added samples for deleting parameter, enabling, disabling and deleting parameter version using Parameter manager SDK
**Sample List (regional):**
[delete-parameter](https://cloud.google.com/secret-manager/parameter-manager/docs/delete-parameters#list-all-parameters)
[disable-parameters-version](https://cloud.google.com/secret-manager/parameter-manager/docs/disable-parameter-versions#disable-parameters-version)
[enable-disabled-parameters-version](https://cloud.google.com/secret-manager/parameter-manager/docs/enable-disabled-versions#enable-disabled-parameters-version)
[delete-parameter-version](https://cloud.google.com/secret-manager/parameter-manager/docs/delete-parameter-version#list-all-parameters)
Added required tests for it.

feat(parametermanager): Added samples for delete, enable or disable parameter or parameter version in specified region 

---

parametermanager/pom.xml
parametermanager/src/main/java/parametermanager/regionalsamples/CreateRegionalParam.java
parametermanager/src/main/java/parametermanager/regionalsamples/CreateRegionalParamVersion.java
parametermanager/src/main/java/parametermanager/regionalsamples/CreateRegionalParamVersionWithSecret.java
parametermanager/src/main/java/parametermanager/regionalsamples/CreateStructuredRegionalParam.java
parametermanager/src/main/java/parametermanager/regionalsamples/CreateStructuredRegionalParamVersion.java
parametermanager/src/test/java/parametermanager/regionalsamples/SnippetsIT.java

Created samples for creating parameter and parameter version using Parameter Manager SDK
**Sample List (regional):**
1. [parameter-structured-data](https://cloud.google.com/secret-manager/parameter-manager/docs/create-parameter#parameter-structured-data)
2. [parameter-unstructured-data](https://cloud.google.com/secret-manager/parameter-manager/docs/create-parameter#parameter-unstructured-data)
3. [add-parameter-version](https://cloud.google.com/secret-manager/parameter-manager/docs/add-parameter-version#add-parameter-version) (structured, unstructured)
4. [create-parameter-secret-reference](https://cloud.google.com/secret-manager/parameter-manager/docs/reference-secrets-in-parameter#create-parameter-secret-reference)
Added required Tests for the same.

feat(parametermanager): Added samples for creating parameter and versions in specified region

---

parametermanager/pom.xml
parametermanager/src/main/java/parametermanager/GetParam.java
parametermanager/src/main/java/parametermanager/GetParamVersion.java
parametermanager/src/main/java/parametermanager/ListParamVersions.java
parametermanager/src/main/java/parametermanager/ListParams.java
parametermanager/src/main/java/parametermanager/RenderParamVersion.java
parametermanager/src/test/java/parametermanager/SnippetsIT.java

Added samples for viewing, listing and rendering parameter and parameter versions using Parameter Manager SDK
**Sample List (global):**
1. [list-all-parameters](https://cloud.google.com/secret-manager/parameter-manager/docs/list-parameter#list-all-parameters)
2. [view-parameter-details](https://cloud.google.com/secret-manager/parameter-manager/docs/view-parameter-details#view-parameter-details)
3. [list-all-parameters-versions](https://cloud.google.com/secret-manager/parameter-manager/docs/list-parameter-versions#list-all-parameters-versions)
4. [view-parameter-version-details](https://cloud.google.com/secret-manager/parameter-manager/docs/view-parameter-version-details#view-parameter-version-details)
5. [render-secret-parameter-version](https://cloud.google.com/secret-manager/parameter-ma …

feat(parametermanager): Added samples to view, list and render parameter

---

endpoints/getting-started/openapi-appengine.yaml
endpoints/getting-started/openapi.yaml

Fixes internal
b/394866317
b/347825552

chore(endpoints): delete old region tag swagger

---

flexible/repacking-legacy-applications/custom-runtime/src/main/java/com/example/HelloServlet.java

chore(appengine): add start and end region for code block

---

jobs/v3/src/main/java/com/google/samples/FeaturedJobsSearchSample.java

chore(job): migrate region tags

---

endpoints/getting-started/deployment.yaml

chore(job): add new region tag to start migration

---

endpoints/getting-started/deployment.yaml

chore(endpoints): remove unused region tag

---

endpoints/multiple-versions/container-engine.yaml

Delete unused region tag "esp" at endpoints/multiple-versions/container-engine.yaml
Fixes Internal b/347825689

fix(endpoints): delete unused region tag esp

---

aiplatform/src/main/java/aiplatform/PredictTextEmbeddingsSample.java
aiplatform/src/test/java/aiplatform/PredictTextEmbeddingsSampleTest.java

feat: Update model name to gemini-embedding-001

---

retail/interactive-tutorials/src/main/java/search/SearchSimpleQuery.java

Added region tag.
Fixes #415382524

fix(retail): add region tag for Java - Update SearchSimpleQuery.java

---

retail/interactive-tutorials/src/main/java/product/DeleteProduct.java
retail/interactive-tutorials/src/main/java/product/GetProduct.java
retail/interactive-tutorials/src/test/java/search/SearchWithBoostSpecTest.java
retail/interactive-tutorials/src/test/java/search/SearchWithFacetSpecTest.java
retail/interactive-tutorials/src/test/java/search/SearchWithFilteringTest.java

Addresses https://github.com/GoogleCloudPlatform/java-docs-samples/issues/10133

ci: skip failing retail tests

---

dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergCdcRead.java
dataflow/snippets/src/main/java/com/example/dataflow/ApacheIcebergRestCatalogStreamingWrite.java

Minor Documentation corrections. A follow up bug fix PR for #10149

Fixing Iceberg documentation code comments

---

genai/snippets/pom.xml

Update GenAI to the latest SDK

chore(deps): update GenAI SDK to v1.15.0
